### ISSUE TITLE
Nagstatmon 3.12.0 not working with Centreon 23.10

### ISSUE THREAD

**Issue by LittleBog** [HenriWahl/Nagstamon#1000]
Hello,
I'm facing an issue with the latest version of Centreon (23.10.5). Nagastamon can't detect the version, same result with the latest release. So, as you can imagine, nothing appears.
Is there anything I can do ? 

Many Thanks !

**Comment by BenoitPoulet** [comment]
Hello,

Which version of Nagstamon are you using ?

**Comment by LittleBog** [comment]
Hi Benoit,
We're using the 3.12.

Thanks for your help !

**Comment by LittleBog** [comment]
{"web":{"version":"23.10.5","major":"23","minor":"10","fix":"5"},"modules":{"centreon-license-manager":{"version":"22.04.0","major":"22","minor":"04","fix":"0"},"centreon-pp-manager":{"version":"22.04.0","major":"22","minor":"04","fix":"0"},"centreon-autodiscovery-server":{"version":"22.04.1","major":"22","minor":"04","fix":"1"}},"widgets":{"Service Monitoring":{"version":"22.04.1","major":"22","minor":"04","fix":"1"},"Engine-status":{"version":"22.04.0","major":"22","minor":"04","fix":"0"},"Hostgroup Monitoring":{"version":"22.04.0","major":"22","minor":"04","fix":"0"},"Grid-map":{"version":"22.04.0","major":"22","minor":"04","fix":"0"},"Live Top 10 Memory Usage":{"version":"22.04.0","major":"22","minor":"04","fix":"0"},"Tactical Overview":{"version":"22.04.0","major":"22","minor":"04","fix":"0"},"HTTP Loader":{"version":"22.04.0","major":"22","minor":"04","fix":"0"},"Host Monitoring":{"version":"22.04.0","major":"22","minor":"04","fix":"0"},"Global Health":{"version":"22.04.0","major":"22","minor":"04","fix":"0"},"Single Metric":{"version":"22.04.0","major":"22","minor":"04","fix":"0"},"Servicegroup Monitoring":{"version":"22.04.0","major":"22","minor":"04","fix":"0"},"Live Top 10 CPU Usage":{"version":"22.04.0","major":"22","minor":"04","fix":"0"},"Graph Monitoring":{"version":"22.04.0","major":"22","minor":"04","fix":"0"},"centreon-widget-generictext":{"version":"23.10.5","major":"23","minor":"10","fix":"5"},"centreon-widget-singlemetric":{"version":"23.10.5","major":"23","minor":"10","fix":"5"},"centreon-widget-graph":{"version":"23.10.5","major":"23","minor":"10","fix":"5"},"centreon-widget-topbottom":{"version":"23.10.5","major":"23","minor":"10","fix":"5"},"centreon-widget-statusgrid":{"version":"23.10.5","major":"23","minor":"10","fix":"5"}}}

Is it what you need ?

**Comment by BenoitPoulet** [comment]
The output is OK for me.
Can you try to enable the debug mode (Setting > Servers) and post the output ?

🧨**Don't forget to remove sensitive information, like hostname of Centreon, credentials, ....**

**Comment by LittleBog** [comment]
Thanks for guiding me through this :)

**Comment by HenriWahl** [comment]
Congrats for getting issue #1000! 
So this is fixed now?

**Comment by LittleBog** [comment]
1000 ! I'm so proud !
As I said before, problem solved. 

By the way, thanks guys for the soft. I really appreciate to work with it, and also thanks for being so reactive (kudos to Benoit).

Have a good day !
