### ISSUE TITLE
Nagstamon crashes while rechecking an icinga2 service if the servicename contains a % sign

### ISSUE THREAD

**Issue by coolburner1337** [HenriWahl/Nagstamon#1001]
If i hit "recheck" on an icinga2 service where the servicename contains a % or if i hit "recheck all" and there is one or more 
service(s) with a % sign in the servicename Nagstamon will crash for sure.

OS: Windows 10
Nagstamon version: 3.12.0

**Comment by coolburner1337** [comment]
Hi, the issue still persists even with the latest version "Nagstamon-3.13-20240108-win64_setup.exe" :-(

**Comment by coolburner1337** [comment]
The console output is:

`Traceback (most recent call last):
  File "Nagstamon\QUI\__init__.py", line 4301, in recheck
  File "Nagstamon\Servers\Generic.py", line 413, in set_recheck
  File "Nagstamon\Servers\IcingaWeb2.py", line 372, in _set_recheck
AttributeError: 'NoneType' object has no attribute 'findNext'`

**Comment by coolburner1337** [comment]
@HenriWahl:
Do you have any idea on fixing that?
That would be nice! :-)

Thank you!

**Comment by HenriWahl** [comment]
Can you send me the whole console output please?

**Comment by coolburner1337** [comment]
@HenriWahl : Or do you mean something else?

Kind regards

**Comment by HenriWahl** [comment]
@coolburner1337 no, thanks, I just hoped there would be more info but well, so this must be enough. 👍

**Comment by HenriWahl** [comment]
Does it actually work if there is no % in the service name? The fn part is, that the form name `IcingaModuleMonitoringFormsCommandObjectCheckNowCommandForm` which is lookded for and not found only exists in the Nagstamon codebase - I did not found any other trace of it.

**Comment by HenriWahl** [comment]
Maybe it works with one of the other Icinga plugins in Nagstamon?

**Comment by coolburner1337** [comment]
> Does it actually work if there is no % in the service name?

Yes, it does. We have over 1000 services in incinga and only the ones with a % in the service name make Nagstamon crash on recheck.

**Comment by coolburner1337** [comment]
> Maybe it works with one of the other Icinga plugins in Nagstamon?

I'll give it a try.

**Comment by coolburner1337** [comment]
Sadly I'm not able to use the other Icinga plugins in Nagstamon. So the issue persists for me.

**Comment by HenriWahl** [comment]
Just in case: you are allowed to recheck services on the monitoring Incinga2 Server?

**Comment by HenriWahl** [comment]
And: What version of IcingaWeb2 do you use?

**Comment by coolburner1337** [comment]
> Just in case: you are allowed to recheck services on the monitoring Incinga2 Server?

Of cource we are! We are using the tool since years and everthing works fine, except then the icinga service name includes an %-sign ;-)

Actually we are using Icinga Version 2.14.1 with Icingaweb2 Version 2.12.1 -- so newer then icinga.com himself :-P -- and the connection works in Nagstamon.

**Comment by HenriWahl** [comment]
Strange, really strange. I will try to reproduce this.

**Comment by HenriWahl** [comment]
@coolburner1337 kind of good news... the problem does not only occur on % services... at least with the demo server https://livedemos.mjs.de/icingaweb2.
Other findings are:

- the line 371 in IcingaWeb2.py, the one before the crash, tries to find the ID `IcingaModuleMonitoringFormsCommandObjectCheckNowCommandForm` in the Icinga output but this one is not existent. Looks like someone changed something at the Icinga side.
- even worse from a Nagstamon perspective - all IDs have some random suffix which makes it harder to find them.

So investigations go further...

**Comment by HenriWahl** [comment]
Maybe you could send me the plain HTML of a Service status page or wherever in Icinga webinterface it is possible to trigger a recheck?

**Comment by coolburner1337** [comment]
@HenriWahl : Hi, thanks for your investigation! 
To your question... This one works for us:
![image](https://github.com/HenriWahl/Nagstamon/assets/156332514/80fa3990-123f-42ae-af98-c1f17e34e85a)

**Comment by HenriWahl** [comment]
Please check latest release 3.13-20240221.
