### ISSUE TITLE
Nagstamon 3.12 not working with Centreon User with ACL

### ISSUE THREAD

**Issue by tmss999** [HenriWahl/Nagstamon#1004]
Hi,

Version 3.12 don't work with Centeron User with ACLs acive. Full Admin works. Centreon Version: 22.10.16

Error Message: see file

thanks for help,

tmss999
![error](https://github.com/HenriWahl/Nagstamon/assets/1415486/8298cf23-87b3-457a-8f62-b815d5a5ce2e)

**Comment by tmss999** [comment]
Hi, thanks for qour quick answer. New Version 22.10.17 is on Test environment :-). same issue with new nagstamon version. i have only Ressources Access configured. Menu and Action, default by centreon.

![image](https://github.com/HenriWahl/Nagstamon/assets/1415486/128337cf-2061-403e-bb15-6bcd3dc24148)

tmss999

**Comment by BenoitPoulet** [comment]
Can you try to enable the debug mode (Setting > Servers) and post the output ?

🧨Don't forget to remove sensitive information, like hostname of Centreon, credentials, ....

**Comment by tmss999** [comment]
hi,

i have found my error in the debug log. by user API Realtime was disabeld. now it works

thanks for help,

tmss999
