### ISSUE TITLE
show alias

### ISSUE THREAD

**Issue by sadden3194** [HenriWahl/Nagstamon#1009]
Hi all

is it possible to show the alias from checkmk in nagstamon?
![image](https://github.com/HenriWahl/Nagstamon/assets/17011498/f499b2ed-1916-4659-8e37-ac03a2e90252)

At the moment I see only the hostname.

**Comment by sadden3194** [comment]
no response here? :(

**Comment by HenriWahl** [comment]
Hi @sadden3194, sorry, this issue somehow got lost. Well, I need to look into the server response to see if the alias gets transmitted at all.

**Comment by sadden3194** [comment]
that would be perfect! :)

**Comment by clanfreak1988** [comment]
@HenriWahl do you have any update for this issue? We would also like to see the alias name.

**Comment by Hazer31** [comment]
Hi, +1 :)
Thanks a lot!

**Comment by clanfreak1988** [comment]
@HenriWahl can i help to reach this feature?

**Comment by HenriWahl** [comment]
Sorry folks, I (finally :facepalm:) looked into this and found no alias information in the Checkmk output.
