### ISSUE TITLE
nagstamon v3.14.0 on Win11 23H2 - icinga KeyError host_name

### ISSUE THREAD

**Issue by hknet** [HenriWahl/Nagstamon#1020]
Hi,
the current nagstamon (and previous releases) report this "KeyError: 'host_name'" when trying to monitor an icinga v1 host.
Switching the monitor type to Nagios solves the problem.
the very same release on Win10 clients works fine though.

**Comment by HenriWahl** [comment]
Which one of the many Icinga types did you try?

**Comment by HenriWahl** [comment]
No response
