### ISSUE TITLE
Nagstamon 3.14.0 and Zabbix 6.2.9 - All information copy not complate

### ISSUE THREAD

**Issue by ZoltanLang** [HenriWahl/Nagstamon#1024]
I'm using Nagstamon 3.14.0 and Zabbix 6.2.9, and when I right click on an alert, Copy to clipboard / All information, I get an output like this: 

Host: proper_hostname (it is good) 
Status: UP
Last check: n/a
Duration: 
Attempt: N/A
Status information: 

So as you can see the last check, duration, attempt and Status information fields are empty. If I copy the service, host, status information  from the same menu, they work properly. 

Could you please check and advise? Thanks!

**Comment by HenriWahl** [comment]
Hi @ZoltanLang,
sorry for the late reply. Did you try a later testing release if you problem still exists?

**Comment by ZoltanLang** [comment]
Hi, 
no worries :) 
Now I tried it with version 3.15-20240902, and the behavior is still the same.

**Comment by ZoltanLang** [comment]
Hi, do you happen to have any update on this topic?
Issue is still present in Nagstamon 3.17
Thanks for checking!

**Comment by HenriWahl** [comment]
Please check latest 3.17-20241018 from https://github.com/HenriWahl/Nagstamon/releases/tag/latest

**Comment by ZoltanLang** [comment]
Thank you, it works now perfectly!

**Comment by HenriWahl** [comment]
BTW - do you have any idea regarding https://github.com/HenriWahl/Nagstamon/issues/1067 ?

**Comment by ZoltanLang** [comment]
No idea, we've never had such an issue. Would be nice to know their zabbix and nagstamon version, and some error message or something
