### ISSUE TITLE
Regex duration issue

### ISSUE THREAD

**Issue by squidly** [HenriWahl/Nagstamon#1025]
Hi,

I had a duration filter with a regex to filter out everything more than 5 days old : 

``
^([6-9]|[1-9][0-9]|[1-9][0-9][0-9])d
``

it used to work with nagstamon 3.8.0 but with the last one ( 3.14 ) it goes to the 9th day.

Am I missing something ?

thanks in advance.

**Comment by HenriWahl** [comment]
Hi @squidly,
sorry for the late reply. Does the problem still persist?

**Comment by squidly** [comment]
Hi !
no worries, I just figured out by looking at another issue that I can use `[6-9]d|[1-9][0-9]d|[1-9][0-9][0-9]d` to produce the effect I used to have.

Thanks for the work :) Awesome tool !
