### ISSUE TITLE
ValueError when parsing QT_VERSION_STR

### ISSUE THREAD

**Issue by fermino** [HenriWahl/Nagstamon#1026]
I encountered the following error today:
```
Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 45, in <module>
    from Nagstamon.QUI import (APP,
  File "/usr/lib/python3.11/site-packages/Nagstamon/QUI/__init__.py", line 35, in <module>
    from .qt import *
  File "/usr/lib/python3.11/site-packages/Nagstamon/QUI/qt.py", line 31, in <module>
    QT_VERSION_MAJOR, QT_VERSION_MINOR, QT_VERSION_BUGFIX = [int(x) for x in QT_VERSION_STR.split('.')]
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Nagstamon/QUI/qt.py", line 31, in <listcomp>
    QT_VERSION_MAJOR, QT_VERSION_MINOR, QT_VERSION_BUGFIX = [int(x) for x in QT_VERSION_STR.split('.')]
                                                             ^^^^^^
ValueError: invalid literal for int() with base 10: 'dev2404081550'
```

This is caused by the library being compiled with a different version string: 
```
$ pacman -Q | grep 'python-pyqt6 '
python-pyqt6 6.7.0dev2404081550-1
```

I can make a patch for it but @HenriWahl what do you think would be better? I was thinking it would be useful to add an environment var to force QT5 over QT6 if necessary, and maybe falling back to QT5 if the version can be parsed (I don't know if the version would be available from a more reliable source instead of that string. The quick and dirty fix would be to get only the first numbers from QT_VERSION_BUGFIX and ignore the rest of the string.

**Comment by HenriWahl** [comment]
@fermino well, Nagstamon here is only interested in the major version. The minor and bugfix versions are only catched there from the standard QT version string.

So it would be enough to grab just the major version, via something like

```
QT_VERSION_MAJOR = int(QT_VERSION_STR.split('.')[0])
```

Regarding a version selection variable I thing we should go the Qt6 way. The used variable already comes with Qt and it would make things more complex to use such a switch.

**Comment by WoutResseler** [comment]
Had the exact same issue, @HenriWahl 's solution does the trick for me for now.

**Comment by jr-timme** [comment]
I also ran into this Problem and am currently running Nagstamon with the change mentioned by @HenriWahl :
```diff
diff --git a/Nagstamon/QUI/qt.py b/Nagstamon/QUI/qt.py
index 3bc50c5b..50fb0886 100644
--- a/Nagstamon/QUI/qt.py
+++ b/Nagstamon/QUI/qt.py
@@ -28,7 +28,7 @@ try:
     from PyQt6.QtCore import PYQT_VERSION_STR as QT_VERSION_STR
 
     # get int-ed version parts
-    QT_VERSION_MAJOR, QT_VERSION_MINOR, QT_VERSION_BUGFIX = [int(x) for x in QT_VERSION_STR.split('.')]
+    QT_VERSION_MAJOR = int(QT_VERSION_STR.split('.')[0])
     # for later decision which differences have to be considered
     QT_FLAVOR = 'PyQt6'
 except ImportError:
```

I haven't found any problems yet.

So if there is no reason to include the Minor and Bugfix versions this could be merged?

**Comment by HenriWahl** [comment]
I fixed it in latest testing release 3.15-240417 - can you please try it?

**Comment by jr-timme** [comment]
I think one of the square brackets should be moved further back as we want to limit the output of the split function to the first two elements and not the output of the list comprehension?
```python
>>> from PyQt6.QtCore import PYQT_VERSION_STR as QT_VERSION_STR

>>> [int(x) for x in QT_VERSION_STR.split('.')][0:2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
ValueError: invalid literal for int() with base 10: 'dev2404081550'

>>> [int(x) for x in QT_VERSION_STR.split('.')[0:2]]
[6, 7]
```

or did I misunderstand the intent of the change?


I'm not sure if the Version Number always is the way it is now but if it is, we could also keep the Patch version if we limit the array to the first 3 elements:
```python
>>> QT_VERSION_STR.split('.')
['6', '7', '0', 'dev2404081550']
>>> [int(x) for x in QT_VERSION_STR.split('.')[0:3]]
[6, 7, 0]
```

**Comment by HenriWahl** [comment]
@jr-timme Nagstamon only needs the major and the minor version part, so it is ok to ignore the bugfix level.

**Comment by jr-timme** [comment]
Ok, so then only the square bracket should be moved further back to prevent the list comprehension from still trying to cast `dev2404081550` into an integer

**Comment by liberodark** [comment]
Hi,

@HenriWahl Can you release a little version for example 3.14.1 with this fix ?
Is better than use a workaround.

Best Regards

**Comment by HenriWahl** [comment]
@liberodark sorry for the delay but I am really short on time and the next weeks won't get better, so I do not like to publish a new stable version while not being available. The fix is already in the testing release.
