### ISSUE TITLE
AttributeError with Icinga DB 1.2.0 / Icinga DB Web 1.1.2

### ISSUE THREAD

**Issue by xeiss** [HenriWahl/Nagstamon#1028]
Since the Update to Icinga DB 1.2.0 / Icinga DB Web 1.1.2 nagstamon only show ERROR - https://icinga.com/blog/2024/04/11/releasing-icinga-db-1-2-0-and-icinga-db-web-1-1-2
Nagstamon Error: `AttributeError: 'bool' object has no attribute 'replace'`

Monitor type: IcingaDBWeb
Authentication: Kerberos
Nagstamon: 3.14, but I also testet 3.15-20240326 - on Windows
Icinga2: r2.14.2-1
Icinga DB: 1.2.0
Icinga DB Web: 1.1.2

**Comment by Dymo-dcc** [comment]
is there anyway to apply this fix locally, while we wait for the release?  I am really missing my Nagstamon sind the icingadb update

**Comment by HenriWahl** [comment]
Please check latest testing release 3.15-20240503.
