### ISSUE TITLE
[Feature][Integration] Opsgenie

### ISSUE THREAD

**Issue by danir-de** [HenriWahl/Nagstamon#1036]
Hi ✌️,

Nagstamon with Nagios/Icinga is a very helpful tool and also allows integrating the new world of clouds, thanks to the Prometheus integration provided in #623. 

Having multiple monitoring environments (Nagios, Prometheus, Icinga,...) and the need for tracking and handling SLAs in one place makes [Opsgenie](https://www.atlassian.com/en/software/opsgenie) a perfect solution for centrally collecting and handling issues.

The only thing missing would be a Nagstamon integration for [Opsgenie](https://www.atlassian.com/en/software/opsgenie), so that it's possible to continuing to use Nagstamon to keep everything at a glance while at the desk.

Would it be possible to write a Nagstamon integration/plugin for handling [Opsgenie](https://www.atlassian.com/en/software/opsgenie) alerts?

**Comment by HenriWahl** [comment]
Hi @danir-de,
I myself won't find the time to do it but if someone else offers a merge request it is very welcome.

**Comment by HenriWahl** [comment]
Closing due to non-existent merge request.
