### ISSUE TITLE
Display own columns from check_MK view in nagstamon

### ISSUE THREAD

**Issue by fanaticsurf** [HenriWahl/Nagstamon#1037]
I created an own column at first position for my hosts und svc view, which is visible in 
https://mon.mydomain.org/mysite/check_mk/view.py?view_name=nagstamon_hosts_my_view
and
https://mon.mydomain.org/mysite/check_mk/view.py?view_name=nagstamon_svc_my_view

but nagstamon is only showing the "standard" columns when using my view with the extra column on first position.

Is it not possible to display own columns?
Did I miss something?
I'm using nagstamon 3.4.1

**Comment by HenriWahl** [comment]
Hi @fanaticsurf,
sorry for the late reply. Nagstamon has it sets of columns which get filled by Checkmk's special Nagstamon views. So it is not intended to add extra columns being defined in web view.
