### ISSUE TITLE
Sorting by duration not saved when restarting nagstamon (minor cosmetic problem)

### ISSUE THREAD

**Issue by BDevGW** [HenriWahl/Nagstamon#1038]
I use the current dev build 3.15-20240506 with one checkmk site connected.
I usually sort by duration, newest on top but when Nagstamon restarts the order is always displayed oldest top.
When I left with oldest at top I have to click once to get newest up but when I left with newest on top it still loads the oldest first but needs two clicks to fix as if it knows that it should display newest first.
The issue persists for a few versions.
I haven't noticed sorting issues with other filters then duration.
As mentioned this is mostly cosmetic so low priority.

**Comment by HenriWahl** [comment]
You should be able to set this in tab "Display" in settings dialog?

**Comment by BDevGW** [comment]
Seems right after changing it to ascending.
Think it can be closed.
