### ISSUE TITLE
Nagstamon 3.15-20240506, Fedora 40, Couldn't load VAAPI library

### ISSUE THREAD

**Issue by Fonant** [HenriWahl/Nagstamon#1039]
Just a note: Nagstamon is great, thank you!

Although Nagstamon latest works OK on Fedora 40, there is a problem with sounds.

Starting from the command line I get:

```
$ nagstamon .nagstamon/

(python3:779996): Gtk-WARNING **: 09:43:19.734: Theme parsing error: gtk.css:3:14: 'max-height' is not a valid property name

(python3:779996): Gtk-WARNING **: 09:43:20.045: Theme file for Future-cursors has no directories
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
qt.multimedia.ffmpeg.libsymbolsresolver: Couldn't load VAAPI library
Failed to open VDPAU backend libvdpau_radeonsi.so: cannot open shared object file: No such file or directory
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
```

I can't find any suitable packages to install to fix the problem...

**Comment by HenriWahl** [comment]
Might be related to https://github.com/HenriWahl/Nagstamon/issues/1015

**Comment by balykin95** [comment]
> I can't find any suitable packages to install to fix the problem...

Hello! 
I have same issue On Fedora 40.
Temporarily solved problem by cleaning all .nagstamon folders (under my user, under root), and launching nagstamon from shell in screen like this:
[mbalykin@mb-office ~]$ sudo nagstamon

**Comment by HenriWahl** [comment]
@balykin95 so it finally worked?

**Comment by balykin95** [comment]
> @balykin95 so it finally worked?

yeah, but only from root.
From user level still "Couldn't load VAAPI library

**Comment by HenriWahl** [comment]
Looks like same issue in https://github.com/HenriWahl/Nagstamon/issues/1015

Googling for `qt.multimedia.ffmpeg.libsymbolsresolver: Couldn't load VAAPI library` shows that it seems to be a pretty young problem.

**Comment by balykin95** [comment]
@HenriWahl after today (2024-07-09) "all system update" ( dnf update -y ) I found, that all works fine.
As i see qt6-* and python-pyqt6-* was updated

**Comment by balykin95** [comment]
> @HenriWahl after today (2024-07-09) "all system update" ( dnf update -y ) I found, that all works fine. As i see qt6-* and python-pyqt6-* was updated

Oh. When i added server - nagstamon closed. i already had same issue in about year ago with floating icon widget...

**Comment by HenriWahl** [comment]
So this problem is gone now?

**Comment by Fonant** [comment]
Yes, this seems to be fixed :)

The only warnings I see from starting nagstamon from the command line are now:

```
(python3:1940839): Gtk-WARNING **: 09:54:29.502: Theme parsing error: gtk.css:3:14: 'max-height' is not a valid property name

(python3:1940839): Gtk-WARNING **: 09:54:29.684: Theme file for Future-cursors has no directories
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
```

but they don't seem to cause any problems.
