### ISSUE TITLE
After Update Icingadb to 1.2.0 / IcingaDB-Web to 1.1.2: Error 'AttributeError: 'bool object has not attribute 'replace'

### ISSUE THREAD

**Issue by winter1967** [HenriWahl/Nagstamon#1051]
After updating icingadb (Icinga-Version 2.14.1) to Version 1.2.0 (=schema-upgrade) and icingaDB-Web to 1.1.2 i get this error, when i open Nagstam
<img width="932" alt="nagstamon-error" src="https://github.com/user-attachments/assets/5847b1aa-eeee-4d29-8cdd-1f003e07e053">
on:

`AttributeError: 'bool object has not attribute 'replace'`

Nagstamon-Version: 3.14.0

**Comment by winter1967** [comment]
Okay.. i tried it, it's  true - the newest Git-Version work with the new icingaDB, so the Issue could be closed.

**Comment by robert-scheck** [comment]
Commit 224e2d8a35331a326ef796f25f71af9ac106c8ca is the fix for the `AttributeError`.

@HenriWahl, any chance for a 3.14.1 patch release containing this commit?

**Comment by HenriWahl** [comment]
@robert-scheck please check prerelease https://github.com/HenriWahl/Nagstamon/releases/tag/v3.16.0

**Comment by robert-scheck** [comment]
@HenriWahl, the pre-release works here – thank you.
