### ISSUE TITLE
Nagstamon 3.14 does not work with Centreon 24.04

### ISSUE THREAD

**Issue by pgarat02** [HenriWahl/Nagstamon#1053]
Hi,
nagstamon 3.14 on windows does not work with the latest version of centreon 24.04. 
I have a statusbar which only tells me OK without showing the details of the services.
![image](https://github.com/user-attachments/assets/b72eeccf-3909-4753-958d-3338ae76ae2c)

![image](https://github.com/user-attachments/assets/4b7dc0f4-1539-4a72-9519-3a143e51bd77)

With debug mode : 
pip_system_certs\wrapt_requests.py:71: UserWarning: Failed to patch SSL settings for unverified requests (unsupported version of urllib3?)
This may lead to errors when urllib3 tries to modify verify_mode.
Please report an issue at https://gitlab.com/alelec/pip-system-certs with your
python version included in the description

QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
DEBUG: 2024-08-29 18:55:52.328375 Saving configuration to file c:\users\pgarat2\.nagstamon\nagstamon.conf
DEBUG: 2024-08-29 18:55:53.760937 Centreon FetchURL: http://xxxxxxxxxxxxxxxxxxx.fr/centreon/api/latest/platform/versions CGI Data: None
DEBUG: 2024-08-29 18:55:54.106152 [Centreon] Status code 200
DEBUG: 2024-08-29 18:55:54.106152 [Centreon] Loading class API, Centreon version : 24.4
DEBUG: 2024-08-29 18:55:54.106152 Centreon Created server.
DEBUG: Initializing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000015CA20313F0> for state "OK"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000015CA20312D0> for state "INFORMATION"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000015CA2031480> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000015CA2031510> for state "WARNING"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000015CA20315A0> for state "AVERAGE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000015CA2031630> for state "HIGH"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000015CA20316C0> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000015CA2031750> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000015CA20317E0> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000015CA2031870> for state "DOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000015CA2031900> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt6.QtGui.QIcon object at 0x0000015CA2031120>
DEBUG: 2024-08-29 18:55:57.291231 Centreon FetchURL: http://xxxxxxxxxxxxxxxxxxx.fr/centreon/api/latest/platform/versions CGI Data: None
DEBUG: 2024-08-29 18:55:57.622117 [Centreon] Centreon version detected : 24.4
DEBUG: 2024-08-29 18:55:57.622117 [Centreon] Centreon API version used : v23.10
DEBUG: 2024-08-29 18:55:58.943878 Centreon FetchURL: https://nagstamon.de/version/stable CGI Data: None
DEBUG: 2024-08-29 18:55:58.943878 [Centreon] Checking session status
DEBUG: 2024-08-29 18:55:58.943878 [Centreon] Check-session, the token expire if not been used for more than one hour. Current Token = None
DEBUG: 2024-08-29 18:55:58.943878 Centreon FetchURL: http://xxxxxxxxxxxxxxxxxxx.fr/centreon/api/v23.10/monitoring/resources?limit=0 CGI Data: None
DEBUG: 2024-08-29 18:55:59.235183 Centreon FetchURL: http://xxxxxxxxxxxxxxxxxxx.fr/centreon/api/v23.10/login CGI Data: {"security": {"credentials": {"login": "Nagstamon", "password": "xxxxxxxxxxxxxxxxxxx"}}}
DEBUG: 2024-08-29 18:55:59.501656 Centreon Fetched JSON: {'contact': {'alias': 'Nagstamon',
             'email': 'noreply@ac-********',
             'id': 19,
             'is_admin': True,
             'name': 'Nagstamon'},
 'security': {'token': '9tQYm/2f4NUG01py3Yr6xXBRoEon/dAvCoxbKwSP+aP6ECxbjftrh6H/yHexcaif'}}
DEBUG: 2024-08-29 18:55:59.501656 [Centreon] API login : Nagstamon / xxxxxxxxxxxxxx > Token : 9tQYm/2f4NUG01py3Yr6xXBRoEon/dAvCoxbKwSP+aP6ECxbjftrh6H/yHexcaif > User ID : 19
DEBUG: 2024-08-29 18:55:59.501656 [Centreon] Check-session, session renewed
DEBUG: 2024-08-29 18:55:59.501656 Centreon FetchURL: http://xxxxxxxxxxxxxxxxxxx.fr/centreon/api/v23.10/monitoring/resources?limit=0 CGI Data: None
DEBUG: 2024-08-29 18:55:59.725934 Centreon Check-session, Fetched JSON: {'meta': {'limit': 0, 'page': 1, 'search': {}, 'sort_by': {}, 'total': 1817},
 'result': []}
DEBUG: 2024-08-29 18:55:59.725934 Centreon Check-session, Error : , Status code : 200
DEBUG: 2024-08-29 18:55:59.725934 Centreon FetchURL: http://xxxxxxxxxxxxxxxxxxx.fr/centreon/api/v23.10/monitoring/resources?types=["host"]&statuses=["WARNING","DOWN","CRITICAL","UNKNOWN"]&limit=9999 CGI Data: None
DEBUG: 2024-08-29 18:55:59.928624 [Centreon] No host down
DEBUG: 2024-08-29 18:55:59.928624 Centreon FetchURL: http://xxxxxxxxxxxxxxxxxxx.fr/centreon/api/v23.10/monitoring/resources?types=["metaservice","service"]&statuses=["WARNING","DOWN","CRITICAL","UNKNOWN"]&limit=9999 CGI Data: None
DEBUG: 2024-08-29 18:56:00.205946 [Centreon] Service indexed : STORE8-9 / ALL_DISKS
DEBUG: 2024-08-29 18:56:00.205946 [Centreon] Service indexed : STORE8-8 / ALL_DISKS
DEBUG: 2024-08-29 18:56:00.205946 [Centreon] Service indexed : STORE8-7 / ALL_DISKS
DEBUG: 2024-08-29 18:56:00.205946 [Centreon] Service indexed : STORE8-1 / ALL_DISKS
DEBUG: 2024-08-29 18:56:00.205946 [Centreon] Service indexed : ORME / ALL_DISKS
...

Thank you in advance for your help.
Pascal

**Comment by HenriWahl** [comment]
Please try the latest development release which contains fixes for newer Centreon.

**Comment by pgarat02** [comment]
I have the same problem :
![image](https://github.com/user-attachments/assets/30c87242-3eaf-4942-bf3b-bd35096fab24)

pip_system_certs\wrapt_requests.py:71: UserWarning: Failed to patch SSL settings for unverified requests (unsupported version of urllib3?)
This may lead to errors when urllib3 tries to modify verify_mode.
Please report an issue at https://gitlab.com/alelec/pip-system-certs with your
python version included in the description

QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
DEBUG: 2024-08-30 11:15:17.843783 Saving configuration to file c:\users\pgarat2\.nagstamon\nagstamon.conf
DEBUG: 2024-08-30 11:15:19.527873 Centreon FetchURL: http://xxxxxxxxxxxxxxxxxxxxxxxxx.fr/centreon/api/latest/platform/versions CGI Data: None
DEBUG: 2024-08-30 11:15:19.906601 [Centreon] Status code 200
DEBUG: 2024-08-30 11:15:19.906601 [Centreon] Loading class API, Centreon version : 24.4
DEBUG: 2024-08-30 11:15:19.906601 Centreon Created server.
DEBUG: Initializing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000219ADA3A5F0> for state "OK"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000219ADA3A4D0> for state "INFORMATION"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000219ADA3A680> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000219ADA3A710> for state "WARNING"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000219ADA3A7A0> for state "AVERAGE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000219ADA3A830> for state "HIGH"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000219ADA3A8C0> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000219ADA3A950> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000219ADA3A9E0> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000219ADA3AA70> for state "DOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x00000219ADA3AB00> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt6.QtGui.QIcon object at 0x00000219ADA3A320>
DEBUG: 2024-08-30 11:15:21.417523 Centreon FetchURL: http://xxxxxxxxxxxxxxxxxxxxxxxxx.fr/centreon/api/latest/platform/versions CGI Data: None
DEBUG: 2024-08-30 11:15:21.764060 [Centreon] Centreon version detected : 24.4
DEBUG: 2024-08-30 11:15:21.764060 [Centreon] Centreon API version used : v24.04
DEBUG: 2024-08-30 11:15:22.988683 Centreon FetchURL: https://nagstamon.de/version/unstable CGI Data: None
DEBUG: 2024-08-30 11:15:22.988683 [Centreon] Checking session status
DEBUG: 2024-08-30 11:15:22.988683 [Centreon] Check-session, the token expire if not been used for more than one hour. Current Token = None
DEBUG: 2024-08-30 11:15:22.988683 Centreon FetchURL: http://xxxxxxxxxxxxxxxxxxxxxxxxx.fr/centreon/api/v24.04/monitoring/resources?limit=0 CGI Data: None
DEBUG: 2024-08-30 11:15:23.280739 Centreon FetchURL: http://xxxxxxxxxxxxxxxxxxxxxxxxx.fr/centreon/api/v24.04/login CGI Data: {"security": {"credentials": {"login": "Nagstamon", "password": "xxxxxxxxxxxx"}}}
DEBUG: 2024-08-30 11:15:23.539508 Centreon Fetched JSON: {'contact': {'alias': 'Nagstamon',
             'email': 'noreply@ac-bordeaux.fr',
             'id': 19,
             'is_admin': True,
             'name': 'Nagstamon'},
 'security': {'token': '6BhxkINOVJR58I5l0cC16gcAderTqMfFfNkVBjwAOspEg3sm5g+COB0ANTnGGiQ+'}}
DEBUG: 2024-08-30 11:15:23.539508 [Centreon] API login : Nagstamon / B&45uG0o&9i0 > Token : 6BhxkINOVJR58I5l0cC16gcAderTqMfFfNkVBjwAOspEg3sm5g+COB0ANTnGGiQ+ > User ID : 19
DEBUG: 2024-08-30 11:15:23.539508 [Centreon] Check-session, session renewed
DEBUG: 2024-08-30 11:15:23.539508 Centreon FetchURL: http://xxxxxxxxxxxxxxxxxxxxxxxxx.fr/centreon/api/v24.04/monitoring/resources?limit=0 CGI Data: None
DEBUG: 2024-08-30 11:15:23.760225 Centreon Check-session, Fetched JSON: {'meta': {'limit': 0, 'page': 1, 'search': {}, 'sort_by': {}, 'total': 1817},
 'result': []}
DEBUG: 2024-08-30 11:15:23.760225 Centreon Check-session, Error : , Status code : 200
DEBUG: 2024-08-30 11:15:23.760225 Centreon FetchURL: http://xxxxxxxxxxxxxxxxxxxxxxxxx.fr/centreon/api/v24.04/monitoring/resources?types=["host"]&statuses=["WARNING","DOWN","CRITICAL","UNKNOWN"]&limit=9999 CGI Data: None
DEBUG: 2024-08-30 11:15:23.954901 [Centreon] No host down
DEBUG: 2024-08-30 11:15:23.954901 Centreon FetchURL: http://xxxxxxxxxxxxxxxxxxxxxxxxx.fr/centreon/api/v24.04/monitoring/resources?types=["metaservice","service"]&statuses=["WARNING","DOWN","CRITICAL","UNKNOWN"]&limit=9999 CGI Data: None
DEBUG: 2024-08-30 11:15:24.239058 [Centreon] Service indexed : STORE8-9 / ALL_DISKS
DEBUG: 2024-08-30 11:15:24.239058 [Centreon] Service indexed : STORE8-8 / ALL_DISKS
DEBUG: 2024-08-30 11:15:24.239058 [Centreon] Service indexed : STORE8-7 / ALL_DISKS
….
DEBUG: 2024-08-30 11:15:24.241573 Centreon Filter: NOTIFICATIONS CORUM;Cpu
DEBUG: 2024-08-30 11:16:24.276678 [Centreon] Checking session status
DEBUG: 2024-08-30 11:16:24.276678 [Centreon] Check-session, the token expire if not been used for more than one hour. Current Token = 6BhxkINOVJR58I5l0cC16gcAderTqMfFfNkVBjwAOspEg3sm5g+COB0ANTnGGiQ+
DEBUG: 2024-08-30 11:16:24.276678 Centreon FetchURL: http://xxxxxxxxxxxxxxxxxxxxxxxxx.fr/centreon/api/v24.04/monitoring/resources?limit=0 CGI Data: None
DEBUG: 2024-08-30 11:16:24.567260 Centreon Check-session, Fetched JSON: {'meta': {'limit': 0, 'page': 1, 'search': {}, 'sort_by': {}, 'total': 1817},
 'result': []}
DEBUG: 2024-08-30 11:16:24.567260 Centreon Check-session, Error : , Status code : 200
DEBUG: 2024-08-30 11:16:24.567260 Centreon FetchURL: http://xxxxxxxxxxxxxxxxxxxxxxxxx.fr/centreon/api/v24.04/monitoring/resources?types=["host"]&statuses=["WARNING","DOWN","CRITICAL","UNKNOWN"]&limit=9999 CGI Data: None
DEBUG: 2024-08-30 11:16:24.761659 [Centreon] No host down
DEBUG: 2024-08-30 11:16:24.761659 Centreon FetchURL: http://xxxxxxxxxxxxxxxxxxxxxxxxx.fr/centreon/api/v24.04/monitoring/resources?types=["metaservice","service"]&statuses=["WARNING","DOWN","CRITICAL","UNKNOWN"]&limit=9999 CGI Data: None
DEBUG: 2024-08-30 11:16:25.044439 [Centreon] Service indexed : STORE8-9 / ALL_DISKS
….

**Comment by pgarat02** [comment]
Hi,
to complete here is another screen print:
![image](https://github.com/user-attachments/assets/c58849da-8d3a-4456-8027-f551626d49d2)

**Comment by BenoitPoulet** [comment]
Hello,

Can you check that the access to the Reatime API is enable on your account ?
Please look at this screenshot : 
https://github.com/HenriWahl/Nagstamon/issues/1002#issuecomment-1891913743

PS : your debug still contain a password.

**Comment by pgarat02** [comment]
Hi,
THANKS. It's fixed for the password.
I was correctly configured for the Nagstamon account:
![image](https://github.com/user-attachments/assets/db5412e7-1a43-44c1-b2f9-82ee983822f1)

**Comment by BenoitPoulet** [comment]
Can you try : to only enable the server in 24.04, enable debug, then exit Nagstamon, and restart it.

And post the debug here.

I just tried with a Centreon 24.04.6 with success.

**Comment by pgarat02** [comment]
Hi Benoit, Henri,

thank you for your feedback. Here is the solution to make it work:
 - 1 Uninstall nagstamon
 - 2 Delete the .Nagstamon folder from the user folder.
 - 3 Install Nagstamon version (3.14)
 - 4 Recreate the centreon servers in the Nagstamon interface

Everything works fine now with version 3.14 !
:)

**Comment by BenoitPoulet** [comment]
@HenriWahl 
You can close this issue.

**Comment by pgarat02** [comment]
OK.
