### ISSUE TITLE
Trojan detection much significant than before compared to previous version

### ISSUE THREAD

**Issue by Tontonitch** [HenriWahl/Nagstamon#1056]
Hello Henri,

Due to the incompatibility of the last release 3.14 with the latest version of icingaweb2/icingadb, I tried the latest 3.15 pre-release version.
However, it has been reported by our antivirus solution as containing a Trojan.
I know that it is an old problem that you are facing and that you are dependent to some third party resources, however for the lastest build it rings a lot of bells.

Comparing the VirusTotal report of 3.14 (which was fine, 5/69 security vendors flagged the file as malicious, but no consensus):
https://www.virustotal.com/gui/file/a3775b4489e9764f94683a82e1854ecb82d2ed0a8ec12bc23a84c2e79c77eea8
and the latest 3.15.20240903 (28/73 security vendors flagged the file as malicious)
https://www.virustotal.com/gui/file/2001e4bd54369487fc0e04c66fc4712cde55ff0b29e3c1466a037614aa763d68

So the latest build could not be considered as safe on my side. Would a rebuild with more recent dependencies produce a more reliable version?

**Comment by HenriWahl** [comment]
@Tontonitch sorry for the late reply. Yes, I will do a rebuild.

**Comment by HenriWahl** [comment]
Please check https://github.com/HenriWahl/Nagstamon/releases/tag/v3.16.0

**Comment by Tontonitch** [comment]
Hello Henri,
I've checked the pre-release 3.16 on virustotal, and this version is almost completely reported as clean. Much better than before. In the meantime I had built a temporary version that passed McAfee Scan, but your latest version is reported much better so I will switch asap :-)
I'm closing the issue.

**Comment by Tontonitch** [comment]
Fixed with 3.16 pre-release

**Comment by Tontonitch** [comment]
Fixed with 3.16 pre-release
