### ISSUE TITLE
cannot move the window on Mac

### ISSUE THREAD

**Issue by marc-guenther** [HenriWahl/Nagstamon#106]
Nagstamon opens it's small status window behind the dock (which I have on the left side of the screen). This means that it is not possible to move the window around, as the only draggable area is the small N, and that is hidden behind the dock.

**Comment by HenriWahl** [comment]
Please check out https://nagstamon.ifw-dresden.de/files-nagstamon/unstable/Nagstamon-2.0-alpha.dmg which is a first alpha release of a more future-proof MacOSX-version.

**Comment by HenriWahl** [comment]
Please check latest BETA from https://nagstamon.ifw-dresden.de/nagstamon-20/
