### ISSUE TITLE
 Nagstamon-3.15-20240902-win64.zip rated as trojan / virus

### ISSUE THREAD

**Issue by LordCrush** [HenriWahl/Nagstamon#1062]
Brave Browser and Firefox rate the file as Malicious, Brave Browser blocks it completely.
Virus Total: 
18/69 security vendors flagged this file as malicious

![grafik](https://github.com/user-attachments/assets/24ea3a1d-1d86-4aa1-a61c-71b9ee79c74f)

Best regards
Wolfram

**Comment by HenriWahl** [comment]
Thanks for the hint - I will check this.

**Comment by HenriWahl** [comment]
Please check https://github.com/HenriWahl/Nagstamon/releases/tag/v3.16.0

**Comment by LordCrush** [comment]
Hello, 
the download with Firefox and Brave Browser, current version, runs without problems
Virus Total finds a general problem:

![grafik](https://github.com/user-attachments/assets/a74fbe02-2e7a-4fad-a770-9db984f67287)

Fine for me 

Regards
Wolfram

**Comment by HenriWahl** [comment]
Great. Yesterday Avast still cried but looks like they processed my false positive report already. 👍
