### ISSUE TITLE
3.16.0 - Display issue when highlighting more than one check

### ISSUE THREAD

**Issue by q2uantum** [HenriWahl/Nagstamon#1066]
When highlighting more than one result (to acknowledge them all for example) - the text and background go light grey so are unreadable (Top 3 are highlighted just above a Critical).

Cant see an option in Colors for when selected like this

![image](https://github.com/user-attachments/assets/e65ff524-70af-4bc8-936e-edf6092054e6)

**Comment by HenriWahl** [comment]
@q2uantum what the... I assume this happens in Windows? Which version of Windows?

**Comment by q2uantum** [comment]
@HenriWahl  Yes this is the Windows Install of Nagstamon - I am running Windows 11 (Version 23H2 - OS Build 22631.4169)

The highlight is light grey, so the white text on the default critical colouring can not be seen when it has been highlighted.

If you highlight a warning alert then it can be seen, due to the default color of text being black - see below:

![image](https://github.com/user-attachments/assets/f83b3d30-46ca-4513-8fad-2ef26596c734)

**Comment by HenriWahl** [comment]
At least I can confirm this. Never seen this as not using Windows 11... until now all OSes just used their highlight color. I added a fixed color now which will be available in testing release soon.

**Comment by HenriWahl** [comment]
Please try one of https://github.com/HenriWahl/Nagstamon/releases/tag/latest

**Comment by fmonts** [comment]
I write here even if it's not strictly the same issue, but still about the graphic changes, I find this new black margin between lines quite disturbing to the eyes (dark theme on Window 11): 
![image](https://github.com/user-attachments/assets/e02d59a5-a53e-43e0-90b0-bc26044df56c)

**Comment by HenriWahl** [comment]
@fmonts I use Linux as my production system so I never saw Nagstamon in Windows 11. This makes the somehow oldfashioned look of Nagstamon pretty weird, thanks to the general widgets of Windows 11. I will have a look if this is somehow fixable.

**Comment by HenriWahl** [comment]
@fmonts @q2uantum please check latest testing release https://github.com/HenriWahl/Nagstamon/releases/tag/latest

**Comment by xinnak** [comment]
Thanks for the quick response. The testing release fixes the issue for me.

**Comment by fmonts** [comment]
Latest is perfect, thank you!

![image](https://github.com/user-attachments/assets/aed764eb-1373-439d-9c76-d49ade6c5348)

**Comment by q2uantum** [comment]
> @fmonts @q2uantum please check latest testing release https://github.com/HenriWahl/Nagstamon/releases/tag/latest

That is absolutely perfect now mate

![image](https://github.com/user-attachments/assets/d9f81f1e-4073-4859-ab7b-0c57a205a4d5)
