### ISSUE TITLE
Support for kerberos authentification

### ISSUE THREAD

**Issue by arthurlogilab** [HenriWahl/Nagstamon#107]
Hi,

I'm an avid user of nagstamon, but recently we integrated kerberos for authentification on our shinken/check_mk install and now I can  only use the web interface, nagstamon doesn't seem to support kerberos. Any chance of getting this on nagstamon ?

**Comment by sim0nx** [comment]
Hi,

To add kerberos support, it should suffice to (strictly connection-wise speaking) include sth. like:
``from requests_kerberos import HTTPKerberosAuth``
``r = requests.get("http://example.org", auth=HTTPKerberosAuth())``


Ref: https://pypi.python.org/pypi/requests-kerberos

**Comment by winter1967** [comment]
This would be very interesting  for me, too. We've icingaweb2 authentification with kerberos (single sign on), an option to do this with nagstamon would be very nice.

**Comment by HenriWahl** [comment]
I polished the UI a little to get rid of unused auth dialog in commit 4807db9a9bafa8b71deca645659ade37a41676e7. Are you able to test this?

**Comment by winter1967** [comment]
Hello,
i try to test it, but after I fill the informations about my icingaweb2 Server in the field, it crashs. So I can’t do more tests.

Kind regards


Wolfgang Winter

Stadt Köln
Amt für Informationsverarbeitung
-Management Tools-
Enggasse 2
50668  Köln
Tel.: +49 221 221-30115

E-Mail: wolfgang.winter@stadt-koeln.de<mailto:wolfgang.winter@stadt-koeln.de>



[cid:image001.png@01D306CD.044CCA00]
[cid:image002.png@01D306CD.044CCA00]

[cid:image003.png@01D306CD.044CCA00]

Von: Henri Wahl [mailto:notifications@github.com]
Gesendet: Dienstag, 25. Juli 2017 12:06
An: HenriWahl/Nagstamon
Cc: Winter, Wolfgang; Comment
Betreff: Re: [HenriWahl/Nagstamon] Support for kerberos authentification (#107)


I polished the UI a little to get rid of unused auth dialog in commit 4807db9<https://github.com/HenriWahl/Nagstamon/commit/4807db9a9bafa8b71deca645659ade37a41676e7>. Are you able to test this?

**Comment by HenriWahl** [comment]
Any debug output in console available?
