### ISSUE TITLE
Zabbix - filter out suppressed problems from Nagstamon

### ISSUE THREAD

**Issue by ZoltanLang** [HenriWahl/Nagstamon#1076]
Dear Henri, 

we use Zabbix 6.4.14 and Nagstamon 3.17 (although I think this is the same for all combination of versions) , and we want to hide 'suppressed' Zabbix problems (like 'acknowledged' is hidden from Nagstamon, we want to have it the same way with 'suppressed')

Could you please check if it is possible to configure it this way? 
Thanks!

**Comment by ZoltanLang** [comment]
we don't need it anymore

**Comment by nnuxx** [comment]
using 
zabbix 7.0.10 
nagstamon 3.14
I'm also looking for this feature.
