### ISSUE TITLE
Acknowledge doesn't work

### ISSUE THREAD

**Issue by ndias** [HenriWahl/Nagstamon#108]
If I acknowledge a machine that is down nothing happens, the acknowlege works fine in the webinterface of nagios 
I'm using  nagstamon-1.0-1.nagstamon.fc20.noarch

Nuno

**Comment by nona00** [comment]
same issue with 1.0.1 on Windows

**Comment by HenriWahl** [comment]
Please check latest BETA from https://nagstamon.ifw-dresden.de/2
