### ISSUE TITLE
Nagstamon-3.16.2-win64_setup.exe Virus

### ISSUE THREAD

**Issue by RalfOlaf** [HenriWahl/Nagstamon#1086]
Webroot Secure Anywhere detects malware in the installation file
Malware Group: W32.Malware.Gen
MD5: 2b60bbb1814589c6d0ef53b368d5830c

**Comment by HenriWahl** [comment]
Can you report this as false positive?

**Comment by RalfOlaf** [comment]
They have confirmed this detection was a false positive and have whitelisted the detected file.
