### ISSUE TITLE
Filtering out "Host & services with disabled notifications" in Naemon

### ISSUE THREAD

**Issue by simpatia** [HenriWahl/Nagstamon#113]
Hi,
first of all, congratulations for the excellent work, I've been using nagstamon for several years with nagios and it really worked perfectly.
Last month I migrated to Naemon, that unlike other monitoring solutions, requires minimal reconfiguration of the old nagios cfg files.
Naemon uses Thruk as web interface and I noticed that nagstamon doesn't filter out "Host & services with disabled notifications" anymore.
The same hosts with disabled notification were successfuly filtered out with the combination nagios+nagstamon.
Do you think that it could be a bug in nagstamon?
The only way I found to filter them out was enabling a regular expression for every single host, but this is not so comfortable.
Thank you again,
Giuseppe

**Comment by kassandra42** [comment]
Hi,
I agree that Nagstamon is a brilliant tool!
However, it is true that it has an issue filtering out services with notifications disabled, if the monitoring frontend is Check_MK (URL .../check_mk, Check_MK version 1.2.4p5) - accessing the same Nagios system (version 3.2.1) via the normal Nagios URL (.../nagios) works.

**Comment by HenriWahl** [comment]
Please check latest commit https://github.com/HenriWahl/Nagstamon/commit/176475d2a5e6fb6acb383dd6ca982c131ef574bd - there notifications information simply was not evaluated.
