### ISSUE TITLE
Server info not saved on Windows

### ISSUE THREAD

**Issue by wrossmann** [HenriWahl/Nagstamon#114]
I've found that every time Nagstamon restarts I need to re-enter the server info. Originally noticed in 1.0.0 and persists in 1.0.1

OS Name:                   Microsoft Windows 7 Professional
OS Version:                6.1.7601 Service Pack 1 Build 7601

Please let me know any other useful info I could provide or diagnostics I could perform.

**Comment by ashleshrahul55** [comment]
Hi @HenriWahl, 
I have the same problem, every time I restart my system/laptop the nagstamon asks to set up the server details again.
I have a .nagstamon directory containing a nagstamon.conf and an actions/ and servers/ in users home directory but still facing this problem. 
Can you please check and advise?
Thank you

**Comment by HenriWahl** [comment]
What version do you use?
What special conditions apply to your setup?

**Comment by ashleshrahul55** [comment]
Hi @HenriWahl, 
Sorry was on long leave. 
My version is Nagstamon 3.8.0. 
No special conditions apply to the setup, just using the Monitor type: Nagios, Monitor URL and Monitor CGI URL. 
The problem still persists, every time I restart my system/laptop the nagstamon asks to set up the server details again.
Can you please check and advise?
Thank you

**Comment by HenriWahl** [comment]
Please use latest release 3.10.1.
