### ISSUE TITLE
Floating status bar window exceeds display size on UbuntU 14.04

### ISSUE THREAD

**Issue by syshackmin** [HenriWahl/Nagstamon#115]
When using the floating status bar on UbuntU 14.04 the window displayed when hovering over it exceeds the display size. This makes the scroll bar impossible to reach. When using the appindicator mode the window draws the correct size when opened.

It appears it is not be taking into account the unity launcher on the left. If I set the unity launcher to auto hide the window will draw the correct size.

**Comment by HenriWahl** [comment]
Please check the latest 2.0 beta.
