### ISSUE TITLE
Zabbix integration

### ISSUE THREAD

**Issue by Randy2009** [HenriWahl/Nagstamon#119]
Hello, the Zabbix integration worked very well, but since update from Zabbix 2.2 to 2.4 this integration doesn't work anymore.

Is it possible to look into this?

**Comment by Gibzon** [comment]
i sent an email to nono-gdv, hope this feature can work again :)

**Comment by nono-gdv** [comment]
Hello,

For the record, I just backported an old fork (I think it was called zagstamon) in the current versions of Nagstamon, I didn't write the main code myself.

I'm afraid I can't help you here as I still run Zabbix 2.2.

**Comment by Harrie-O** [comment]
I think a found the fix, but I do not succeed in building the installer myself. Is there any extended instruction in how to build it? I get an installer size of 2,74MB and missing the executable for example.

**Comment by HenriWahl** [comment]
Did you check http://nagstamon.ifw-dresden.de/docs/requirements/ ? The current executable has around 8 MB.

**Comment by Harrie-O** [comment]
I did, I get the following output:
..\Nagstamon\Nagstamon\resources\acknowledge_dialog.ui
..\Nagstamon\Nagstamon\resources\authentication_dialog.ui
..\Nagstamon\Nagstamon\resources\close.png
..\Nagstamon\Nagstamon\resources\close.svg
..\Nagstamon\Nagstamon\resources\critical.wav
..\Nagstamon\Nagstamon\resources\downtime_dialog.ui
..\Nagstamon\Nagstamon\resources\history.png
..\Nagstamon\Nagstamon\resources\history.svg
..\Nagstamon\Nagstamon\resources\hostdown.wav
..\Nagstamon\Nagstamon\resources\hosts.png
..\Nagstamon\Nagstamon\resources\hosts.svg
..\Nagstamon\Nagstamon\resources\LICENSE
..\Nagstamon\Nagstamon\resources\menu.png
..\Nagstamon\Nagstamon\resources\menu.svg
..\Nagstamon\Nagstamon\resources\nagios.png
..\Nagstamon\Nagstamon\resources\nagios.svg
..\Nagstamon\Nagstamon\resources\nagstamon.1
..\Nagstamon\Nagstamon\resources\nagstamon.appdata.xml
..\Nagstamon\Nagstamon\resources\nagstamon.desktop
..\Nagstamon\Nagstamon\resources\nagstamon.icns
..\Nagstamon\Nagstamon\resources\nagstamon.ico
..\Nagstamon\Nagstamon\resources\nagstamon.png
..\Nagstamon\Nagstamon\resources\nagstamon.svg
..\Nagstamon\Nagstamon\resources\nagstamon_acknowledged.png
..\Nagstamon\Nagstamon\resources\nagstamon_acknowledged.svg
..\Nagstamon\Nagstamon\resources\nagstamon_appindicator.png
..\Nagstamon\Nagstamon\resources\nagstamon_appindicator.svg
..\Nagstamon\Nagstamon\resources\nagstamon_black.png
..\Nagstamon\Nagstamon\resources\nagstamon_black.svg
..\Nagstamon\Nagstamon\resources\nagstamon_darkred.png
..\Nagstamon\Nagstamon\resources\nagstamon_darkred.svg
..\Nagstamon\Nagstamon\resources\nagstamon_downtime.png
..\Nagstamon\Nagstamon\resources\nagstamon_downtime.svg
..\Nagstamon\Nagstamon\resources\nagstamon_error.png
..\Nagstamon\Nagstamon\resources\nagstamon_error.svg
..\Nagstamon\Nagstamon\resources\nagstamon_flapping.png
..\Nagstamon\Nagstamon\resources\nagstamon_flapping.svg
..\Nagstamon\Nagstamon\resources\nagstamon_fresh.png
..\Nagstamon\Nagstamon\resources\nagstamon_fresh.svg
..\Nagstamon\Nagstamon\resources\nagstamon_green.png
..\Nagstamon\Nagstamon\resources\nagstamon_green.svg
..\Nagstamon\Nagstamon\resources\nagstamon_label.png
..\Nagstamon\Nagstamon\resources\nagstamon_label.svg
..\Nagstamon\Nagstamon\resources\nagstamon_orange.png
..\Nagstamon\Nagstamon\resources\nagstamon_orange.svg
..\Nagstamon\Nagstamon\resources\nagstamon_passive.png
..\Nagstamon\Nagstamon\resources\nagstamon_passive.svg
..\Nagstamon\Nagstamon\resources\nagstamon_red.png
..\Nagstamon\Nagstamon\resources\nagstamon_red.svg
..\Nagstamon\Nagstamon\resources\nagstamon_small.png
..\Nagstamon\Nagstamon\resources\nagstamon_small.svg
..\Nagstamon\Nagstamon\resources\nagstamon_yellow.png
..\Nagstamon\Nagstamon\resources\nagstamon_yellow.svg
..\Nagstamon\Nagstamon\resources\recheckall.png
..\Nagstamon\Nagstamon\resources\recheckall.svg
..\Nagstamon\Nagstamon\resources\refresh.png
..\Nagstamon\Nagstamon\resources\refresh.svg
..\Nagstamon\Nagstamon\resources\services.png
..\Nagstamon\Nagstamon\resources\services.svg
..\Nagstamon\Nagstamon\resources\settings.png
..\Nagstamon\Nagstamon\resources\settings.svg
..\Nagstamon\Nagstamon\resources\settings_action_dialog.ui
..\Nagstamon\Nagstamon\resources\settings_dialog.ui
..\Nagstamon\Nagstamon\resources\settings_server_dialog.ui
..\Nagstamon\Nagstamon\resources\submit_check_result_dialog.ui
..\Nagstamon\Nagstamon\resources\warning.wav
66 bestand(en) gekopieerd
installer\windows\msvcm90.dll
installer\windows\msvcp90.dll
installer\windows\msvcr90.dll
3 bestand(en) gekopieerd
installer\windows\Microsoft.VC90.CRT.manifest
1 bestand(en) gekopieerd
helpers\gtk-windows-theme\etc\gtk-2.0\gdk-pixbuf.loaders
helpers\gtk-windows-theme\etc\gtk-2.0\gtk.immodules
helpers\gtk-windows-theme\etc\gtk-2.0\gtkrc
helpers\gtk-windows-theme\etc\gtk-2.0\im-multipress.conf
helpers\gtk-windows-theme\lib\gtk-2.0\2.10.0\engines\libpixmap.dll
helpers\gtk-windows-theme\lib\gtk-2.0\2.10.0\engines\libsvg.dll
helpers\gtk-windows-theme\lib\gtk-2.0\2.10.0\engines\libwimp.dll
helpers\gtk-windows-theme\share\themes\MS-Windows\gtk-2.0\gtkrc
8 bestand(en) gekopieerd
Inno Setup 5 Command-Line Compiler
Copyright (C) 1997-2014 Jordan Russell. All rights reserved.
Portions Copyright (C) 2000-2014 Martijn Laan
Inno Setup Preprocessor
Copyright (C) 2001-2004 Alex Yackimoff. All rights reserved.

Compiler engine version: Inno Setup 5.5.5 (a)

[ISPP] Preprocessing.
[ISPP] Preprocessed.

Parsing [Setup] section, line 2
Parsing [Setup] section, line 3
Parsing [Setup] section, line 4
Parsing [Setup] section, line 5
Parsing [Setup] section, line 6
Parsing [Setup] section, line 7
Parsing [Setup] section, line 8
Parsing [Setup] section, line 9
Parsing [Setup] section, line 10
Parsing [Setup] section, line 11
Parsing [Setup] section, line 12
Parsing [Setup] section, line 13
Parsing [Setup] section, line 14
Parsing [Setup] section, line 15
Parsing [Setup] section, line 16
Parsing [Setup] section, line 17
Parsing [Setup] section, line 18
Parsing [Setup] section, line 19
Parsing [Setup] section, line 20
Parsing [Setup] section, line 21
Reading file (WizardImageFile)
   File: C:\Program Files (x86)\Inno Setup 5\WIZMODERNIMAGE.BMP
Reading file (WizardSmallImageFile)
   File: C:\Program Files (x86)\Inno Setup 5\WIZMODERNSMALLIMAGE.BMP
Preparing Setup program executable
   Updating icons (SETUP.E32)
Reading default messages from Default.isl
Parsing [LangOptions], [Messages], and [CustomMessages] sections
   File: C:\Program Files (x86)\Inno Setup 5\Default.isl
   Messages in script file
Reading [Code] section
Parsing [Icons] section, line 23
Parsing [Icons] section, line 24
Parsing [Files] section, line 26
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\Microsoft.VC90.CRT.manifest
Parsing [Files] section, line 27
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\msvcm90.dll
Parsing [Files] section, line 28
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\msvcp90.dll
Parsing [Files] section, line 29
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\msvcr90.dll
Parsing [Files] section, line 30
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libatk-1.0-0.dll
Parsing [Files] section, line 31
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libcairo-2.dll
Parsing [Files] section, line 32
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libfontconfig-1.dll
Parsing [Files] section, line 33
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libgdk_pixbuf-2.0-0.dll
Parsing [Files] section, line 34
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libgio-2.0-0.dll
Parsing [Files] section, line 35
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libglib-2.0-0.dll
Parsing [Files] section, line 36
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libgmodule-2.0-0.dll
Parsing [Files] section, line 37
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libgobject-2.0-0.dll
Parsing [Files] section, line 38
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libgthread-2.0-0.dll
Parsing [Files] section, line 39
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libpango-1.0-0.dll
Parsing [Files] section, line 40
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libpangocairo-1.0-0.dll
Parsing [Files] section, line 41
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libpangoft2-1.0-0.dll
Parsing [Files] section, line 42
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libpangowin32-1.0-0.dll
Parsing [Files] section, line 43
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libxml2-2.dll
Parsing [Files] section, line 44
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\bin\zlib1.dll
Parsing [Files] section, line 45
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\etc\gtk-2.0\gdk-pixbuf.loaders
Parsing [Files] section, line 46
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\etc\gtk-2.0\gtk.immodules
Parsing [Files] section, line 47
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\etc\gtk-2.0\gtkrc
Parsing [Files] section, line 48
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\etc\gtk-2.0\im-multipress.conf
Parsing [Files] section, line 49
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\lib\gtk-2.0\2.10.0\engines\libpixmap.dll
Parsing [Files] section, line 50
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\lib\gtk-2.0\2.10.0\engines\libsvg.dll
Parsing [Files] section, line 51
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\lib\gtk-2.0\2.10.0\engines\libwimp.dll
Parsing [Files] section, line 52
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\acknowledge_dialog.ui
Parsing [Files] section, line 53
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\authentication_dialog.ui
Parsing [Files] section, line 54
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\close.png
Parsing [Files] section, line 55
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\close.svg
Parsing [Files] section, line 56
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\critical.wav
Parsing [Files] section, line 57
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\downtime_dialog.ui
Parsing [Files] section, line 58
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\history.png
Parsing [Files] section, line 59
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\history.svg
Parsing [Files] section, line 60
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\hostdown.wav
Parsing [Files] section, line 61
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\hosts.png
Parsing [Files] section, line 62
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\hosts.svg
Parsing [Files] section, line 63
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\LICENSE
Parsing [Files] section, line 64
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\menu.png
Parsing [Files] section, line 65
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\menu.svg
Parsing [Files] section, line 66
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagios.png
Parsing [Files] section, line 67
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagios.svg
Parsing [Files] section, line 68
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon.1
Parsing [Files] section, line 69
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon.appdata.xml
Parsing [Files] section, line 70
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon.desktop
Parsing [Files] section, line 71
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon.icns
Parsing [Files] section, line 72
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon.ico
Parsing [Files] section, line 73
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon.png
Parsing [Files] section, line 74
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon.svg
Parsing [Files] section, line 75
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_acknowledged.png
Parsing [Files] section, line 76
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_acknowledged.svg
Parsing [Files] section, line 77
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_appindicator.png
Parsing [Files] section, line 78
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_appindicator.svg
Parsing [Files] section, line 79
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_black.png
Parsing [Files] section, line 80
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_black.svg
Parsing [Files] section, line 81
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_darkred.png
Parsing [Files] section, line 82
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_darkred.svg
Parsing [Files] section, line 83
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_downtime.png
Parsing [Files] section, line 84
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_downtime.svg
Parsing [Files] section, line 85
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_error.png
Parsing [Files] section, line 86
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_error.svg
Parsing [Files] section, line 87
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_flapping.png
Parsing [Files] section, line 88
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_flapping.svg
Parsing [Files] section, line 89
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_fresh.png
Parsing [Files] section, line 90
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_fresh.svg
Parsing [Files] section, line 91
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_green.png
Parsing [Files] section, line 92
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_green.svg
Parsing [Files] section, line 93
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_label.png
Parsing [Files] section, line 94
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_label.svg
Parsing [Files] section, line 95
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_orange.png
Parsing [Files] section, line 96
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_orange.svg
Parsing [Files] section, line 97
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_passive.png
Parsing [Files] section, line 98
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_passive.svg
Parsing [Files] section, line 99
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_red.png
Parsing [Files] section, line 100
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_red.svg
Parsing [Files] section, line 101
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_small.png
Parsing [Files] section, line 102
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_small.svg
Parsing [Files] section, line 103
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_yellow.png
Parsing [Files] section, line 104
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_yellow.svg
Parsing [Files] section, line 105
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\recheckall.png
Parsing [Files] section, line 106
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\recheckall.svg
Parsing [Files] section, line 107
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\refresh.png
Parsing [Files] section, line 108
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\refresh.svg
Parsing [Files] section, line 109
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\services.png
Parsing [Files] section, line 110
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\services.svg
Parsing [Files] section, line 111
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\settings.png
Parsing [Files] section, line 112
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\settings.svg
Parsing [Files] section, line 113
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\settings_action_dialog.ui
Parsing [Files] section, line 114
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\settings_dialog.ui
Parsing [Files] section, line 115
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\settings_server_dialog.ui
Parsing [Files] section, line 116
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\submit_check_result_dialog.ui
Parsing [Files] section, line 117
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\resources\warning.wav
Parsing [Files] section, line 118
   Reading version info: D:\GIT\Nagstamon\build\dist\nagstamon\share\themes\MS-Windows\gtk-2.0\gtkrc
Deleting Nagstamon_1.0.1_setup.exe from output directory
Creating setup files
   Updating icons (SETUP.EXE)
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\Microsoft.VC90.CRT.manifest
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\msvcm90.dll   (9.0.30729.1)
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\msvcp90.dll   (9.0.30729.1)
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\msvcr90.dll   (9.0.30729.1)
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libatk-1.0-0.dll   (2.6.0.0)
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libcairo-2.dll
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libfontconfig-1.dll
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libgdk_pixbuf-2.0-0.dll   (2.26.5.0)
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libgio-2.0-0.dll   (2.34.3.0)
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libglib-2.0-0.dll   (2.34.3.0)
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libgmodule-2.0-0.dll   (2.34.3.0)
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libgobject-2.0-0.dll   (2.34.3.0)
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libgthread-2.0-0.dll   (2.34.3.0)
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libpango-1.0-0.dll   (1.30.1.0)
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libpangocairo-1.0-0.dll   (1.30.1.0)
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libpangoft2-1.0-0.dll   (1.30.1.0)
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libpangowin32-1.0-0.dll   (1.30.1.0)
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\bin\libxml2-2.dll
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\bin\zlib1.dll   (1.2.7.0)
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\etc\gtk-2.0\gdk-pixbuf.loaders
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\etc\gtk-2.0\gtk.immodules
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\etc\gtk-2.0\gtkrc
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\etc\gtk-2.0\im-multipress.conf
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\lib\gtk-2.0\2.10.0\engines\libpixmap.dll
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\lib\gtk-2.0\2.10.0\engines\libsvg.dll
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\lib\gtk-2.0\2.10.0\engines\libwimp.dll
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\acknowledge_dialog.ui
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\authentication_dialog.ui
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\close.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\close.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\critical.wav
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\downtime_dialog.ui
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\history.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\history.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\hostdown.wav
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\hosts.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\hosts.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\LICENSE
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\menu.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\menu.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagios.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagios.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon.1
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon.appdata.xml
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon.desktop
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon.icns
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon.ico
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_acknowledged.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_acknowledged.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_appindicator.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_appindicator.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_black.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_black.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_darkred.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_darkred.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_downtime.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_downtime.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_error.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_error.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_flapping.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_flapping.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_fresh.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_fresh.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_green.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_green.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_label.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_label.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_orange.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_orange.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_passive.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_passive.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_red.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_red.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_small.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_small.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_yellow.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\nagstamon_yellow.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\recheckall.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\recheckall.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\refresh.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\refresh.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\services.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\services.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\settings.png
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\settings.svg
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\settings_action_dialog.ui
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\settings_dialog.ui
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\settings_server_dialog.ui
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\submit_check_result_dialog.ui
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\resources\warning.wav
   Compressing: D:\GIT\Nagstamon\build\dist\nagstamon\share\themes\MS-Windows\gtk-2.0\gtkrc
   Compressing Setup program executable
   Updating version info


Successful compile (5,179 sec). Resulting Setup program filename is:
D:\GIT\Nagstamon\build\Output\Nagstamon_1.0.1_setup.exe
Running: helpers\pyinstaller-2.1\pyinstaller.py --noconfirm nagstamon.spec
Running: xcopy "..\Nagstamon\Nagstamon\resources" dist\nagstamon\resources /y /e /i /h /EXCLUDE:helpers\excludelist.txt
Running: xcopy "installer\windows\*.dll" dist\nagstamon /y /i /h 
Running: xcopy "installer\windows\*.manifest" dist\nagstamon /y /i /h 
Running: cd dist\nagstamon & del /q /f USP10.DLL & cd ..
Running: "C:\Program Files (x86)\Inno Setup 5\ISCC" nagstamon.iss

**Comment by HenriWahl** [comment]
Did you use the git repository? It comes with pyinstaller included which does a good job melting all binary stuff together.

**Comment by HenriWahl** [comment]
Should be fixed with https://github.com/HenriWahl/Nagstamon/pull/130

**Comment by HenriWahl** [comment]
Should be repaired too with https://github.com/gescheit/scripts/tree/master/zabbix
