### ISSUE TITLE
Noobie Can't connect to Nagios

### ISSUE THREAD

**Issue by stratfordv** [HenriWahl/Nagstamon#120]
I have a nagios 4 server running on CentOS.  I haven't been able to get the E-mail notifications working so i thought tNagstamon would be a big help.  I installed it into windows, set my server details http://192.168.204.110/nagios.  Not sure what the cgi is.  Set my username and password but keep getting  HTTP error 404 not found yet I can login fine using any web browser with the same credentials.  Any idea what I'm missing?

**Comment by berndwaibel** [comment]
I am using Nagios3.
The URL is:
http://myhost.mydomain.de/nagios3
The CGI URL is:
http://myhost.mydomain.de/cgi-bin/nagios3

Maybe you must have enabled "external commans", not sure.
http://nagios.sourceforge.net/docs/3_0/extcommands.html
