### ISSUE TITLE
Notifications for WARNING sound while WARNING option is unchecked.

### ISSUE THREAD

**Issue by guerini** [HenriWahl/Nagstamon#121]
In settings tab "Notifications", when ticking option "Repeat sound until notification has been noticed", Nagstamon sounds for WARNING notifications (and repeats alert) even if option "WARNING" is unchecked. It seems it happens only for Linux version of Nagstamon.

**Comment by HenriWahl** [comment]
Does this happen with the latest 2.0 beta binaries too?

**Comment by HenriWahl** [comment]
Cannot confirm for 2.0 - seems fixed.
