### ISSUE TITLE
[Feature Request] Provide Nagstamon version in User-Agent

### ISSUE THREAD

**Issue by dasmarci** [HenriWahl/Nagstamon#124]
First: congratulations on this great tool, we're very happy with it!

We ran in an issue having high load caused by webserver on monitoring host. Solution were an upgrade of some older nagstamon versions used.
Nagstamon is not provided by automatic software distribution here so it may be possible that users install older versions in future...

Would it be possible to include the nagstamon version in User-Agent? This way we'd be able to identify not-up-to-date versions in webserver logs :-)
Current User-Agent (v1.0.1) is "Python-urllib/2.7", maybe it could be expanded to something like "Python-urllib/2.7, Nagstamon/1.0.2".

Many thanks in advance!

**Comment by dasmarci** [comment]
Great, I'll wait for it.

**Comment by HenriWahl** [comment]
Done with Requests library. Not yet available but done.
