### ISSUE TITLE
About dialog URL not working

### ISSUE THREAD

**Issue by DoGauss** [HenriWahl/Nagstamon#125]
Hello Henry, I found a minor issue in the about dialog of Nagstamon 1.0.1 on Windows 8.1.

When clicking on the link to "https://nagstamon.ifw-dresten.de/" I get an error "Could not show link, no application is registered as handling this file"
![nagstamon_about_error](https://cloud.githubusercontent.com/assets/3746442/5501772/a6b13ed2-8760-11e4-87ef-b79d968054bd.png)

**Comment by HenriWahl** [comment]
Does in 2.0 now.
