### ISSUE TITLE
Nagstamon closes if you right click on it twice (or more)

### ISSUE THREAD

**Issue by kirrus** [HenriWahl/Nagstamon#131]
I suspect this may be triggering the 'exit' menu item

**Comment by HenriWahl** [comment]
Yes, then you simply got the 'Exit' menu entry. Shouldn't it be the expected behaviour?

**Comment by kirrus** [comment]
No? If I twitch, or have a muscle glitch, I don't expect right clicking an extra time to close the program entirely. Right click shouldn't act on menu items, especially on a right-click accessed menu? 

If I were clicking right click, and then left clicking on 'Exit', I'd expect this...

**Comment by HenriWahl** [comment]
OK, I get it. Well, at the moment I am porting Nagstamon to Qt which might be a good chance to investigate this too.

**Comment by HenriWahl** [comment]
Please check latest BETA from https://nagstamon.ifw-dresden.de/nagstamon-20/

**Comment by kirrus** [comment]
On 29/04/16 14:32, Henri Wahl wrote:
>
> Please check latest BETA from 
> https://nagstamon.ifw-dresden.de/nagstamon-20/
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/HenriWahl/Nagstamon/issues/131#issuecomment-215712101>
>
Confirmed fixed, thanks!
