### ISSUE TITLE
Display hosts using display_name param

### ISSUE THREAD

**Issue by plista-ld** [HenriWahl/Nagstamon#133]
Hi,

First of all thanks for this cool tool ! 

I'd like to display my hostnames in Nagstamon using the Nagios display_name field. The reason is that my display_name is a concatenation of server role + short hostname, which is much more convenient than a fqdn.

Is there a setting that allows this ?
If not would it be possible to add this feature ? 
Meanwhile, is there a way to manually overwrite some code in the nagstamon confib/bin to allow this ?

Thanks !

**Comment by HenriWahl** [comment]
As of now there is now setting like this, but if you want to look deeper into this just grab the Python source from Github.

**Comment by plista-ld** [comment]
Thanks. Using the Icinga "host_display_name" field for the Nagstamon "$host_name" variable solves my problem.
