### ISSUE TITLE
Issue when us "display name as host name"

### ISSUE THREAD

**Issue by czarnetz** [HenriWahl/Nagstamon#136]
I will use "Display_name" in icinga like this:

define host {
  use           generic-host
  host_name     host1
  alias         Alias1
  display_name  displayname1
  address       x.x.x.x
}

If i check "use Display Name as host Name", the Display Name will show correctly in the app.
But if a click e.g. "Monitor", nagstamon will open a browser-window with the following URL:

http://.../icinga/cgi-bin/extinfo.cgi?host=displayname1&type=2&service=FTP

The URL will be wrong, because there must be used the "host_name", instead of the "display_name".

**Comment by HenriWahl** [comment]
Thank you for that hint.

**Comment by HenriWahl** [comment]
Please check latest BETA from https://nagstamon.ifw-dresden.de/nagstamon-20/
