### ISSUE TITLE
Nagstamon on OS X Yosemite crashes on click

### ISSUE THREAD

**Issue by ashleydrees** [HenriWahl/Nagstamon#137]
Just noticed there is a bug request list and my Nagstamon is still crashing on click - Previously raised by email.

I updated to Yosemite on my OSX workstation and now if i try and click on any "issue" python exits...  I can restart nagstamon but it will crash as often as i click... mouseover works - but if i click - either button - left instant crash - right, twice then crash.  it worked fine in Mavericks, but i had to upgrade to Yosemite.

Henri (in email) said:-
"Yes, I noticed the crash on Yosemite too but found no time already to check this. :-("

**Comment by HenriWahl** [comment]
At the moment I work on porting Nagstamon to Qt5 instead of especially under OSX always clumsy GTK2. First results look promising but there is still a lot to do. So I can't tell you a release date.

**Comment by ashleydrees** [comment]
Hi Henri, any good news on your port to Qt5?

**Comment by HenriWahl** [comment]
I am steadily on it but progress is really kind of slowly achieved... because of the other daily admin stuff to do. If your are brave you might use the qt tree at https://github.com/HenriWahl/Nagstamon/tree/qt but it does not more than display host/server problems. Runs best with fink python and qt5 from http://www.finkproject.org/ but does not allow interaction at the moment. I almost finished the settings dialogs and hope to get the same features as in Nagstamon 1.0.1 soon.

**Comment by ashleydrees** [comment]
Thanks for the info Henri.. yes, i know about the other daily admin stuff.. the list never seems to get any smaller.. when you think it is ready to test, then i will give it a go, i have macports on everything rather than fink so that might be a show stopper, i'll keep an eye on this and when you feel you have feature parity with 1.0.1 and need  an alpha/beta tester i will be available.

**Comment by HenriWahl** [comment]
Actually yesterday I found fink being a better option than macports because it already comes with Qt 5.4 instead of macports sticking on 5.3. At once all crashes are gone... but it runs with macports too, only that it seems to freeze after a while at least on my testing machine. No freeze and faster at all with fink.

**Comment by ashleydrees** [comment]
I used to use fink, can easily do it again, it transpires that nagstamon window is very much part of my daily workflow, so it working nicely is fairly important.

**Comment by HenriWahl** [comment]
Please check out https://nagstamon.ifw-dresden.de/files-nagstamon/unstable/Nagstamon-2.0-alpha.dmg which is a first alpha release of a more future-proof MacOSX-version.

**Comment by mattiasr** [comment]
Is it suppose to start? ;-)

No luck for me under OSX 10.9.5

**Comment by mattiasr** [comment]
Had to delete my old .nagstamon folder since i got
"AttributeError: 'Op5MonitorServer' object has no attribute 'debug_queue'"

**Comment by mattiasr** [comment]
I got it to work with op5MonitorServer but when first starting and adding
server it doesn't refresh so i get no info about it, when i quit and then
start app again it shows me the numbers.

**Comment by ashleydrees** [comment]
Worked fine for me… selecting individual error messages is a bit random, need to click on the window header/background before being able to select individual errors, seems to be something to do with focus.. but is GREAT to have it working again.

**Comment by HenriWahl** [comment]
Nice to hear... the focus thing was the same as far as I remember with GTK2 but maybe there will be an solution.
There is no notification yet, no sounds and stuff but when I now got it kind of running I hope the missing parts will soon be implemented.

**Comment by ashleydrees** [comment]
Henri.

Thanks again for Nagstamon (on osx).

A little thing that has actually been causing me some head scratching - and it really is a little thing… the latest version is getting very smooth.

Volume - i tend to have Nagstamon running on my workstation, and i like music, the default sounds come out at the same level as my music - yes, i know i should know when things are going wrong, but i like loud music - so SOMETIMES the alerts are very loud indeed… i was going to modify the sound files to reduce output (i like the default sounds) - but perhaps an alert volume could be included as well as the bespoke sound files…

---

A B D
t:+447968726775
e:ash@trellick.net

**Comment by HenriWahl** [comment]
Yes, I had the same problem... :-) I already have it on my todo list.

**Comment by ashleydrees** [comment]
OK, i’ll keep “quiet” till then then…

Thanks again.

A

**Comment by HenriWahl** [comment]
Please check latest BETA from https://nagstamon.ifw-dresden.de/nagstamon-20/

**Comment by ashleydrees** [comment]
Thanks - i have it now - getting better each version.
---

A B D
t:+447968726775
e:ash@trellick.net
