### ISSUE TITLE
Switch to Python3 need lowercase package and module names 

### ISSUE THREAD

**Issue by berndwaibel** [HenriWahl/Nagstamon#138]
I tried to switch to the "qt" branch. Failed in first step.
I did load Python 3.4 and  PyQt5-5.4.1-gpl-Py3.4-Qt5.4.1-x32, as current available versions.
I am running Eclipse on Windows, currently using 32bit on 64bit machine.

Due to the redesign of Python3, Python decided to rename all packages and modules to "lowercase".
See:
https://www.python.org/dev/peps/pep-0008/#package-and-module-names
So the ConfigParser.ConfigParser is now configparser.ConfigParser.

My question: which Python and PyQt versions are used for current development of the Qt branch?

New issue: When switching to v3, you have to rename all modules used.

**Comment by HenriWahl** [comment]
At the moment I develop with PyQt 5.4 and Python 2.7 on Linux, but I am aware that the switch to Python 3 will make sense too, especially for Windows, where there is no PyQt 5.4 for older Python available. So after the GUI port I think the switch to Python 3 is way easier - possible in general only with something non-GTK2.
