### ISSUE TITLE
warnig of parsing error in markup

### ISSUE THREAD

**Issue by berndwaibel** [HenriWahl/Nagstamon#139]
We monitor a smtp server, and do look inside the logfiles.
In the logfiles are error messages, which will be shown by nagios.
If the error message itself contains illegal characters, the Gtk will show a warning:

```
nagstamon.py:164 GtkWarning: Failed to set text from markup due to error parsing markup: 
Fehler in Zeile 2, Zeichen 160: ******** ist kein gültiger Name
gtk.main()
```
(I masked the message with ***).

This is a warning. Should not be critical. 
Currently this does not make problems.
I do not know if this could lead to problems, security or crash. But I do not think so, because the warning is shown, and the view keeps running.

Maybe the "Status Information" message should be parsed, and critial chars replaced before viewed.
If I will find free time, I will try to patch that.

**Comment by berndwaibel** [comment]
Hm, may be a nagios problem, should be fixed there. But oh, I am not expecting that.
May be this issue should be closed with "wont fix".

**Comment by simonfiddaman** [comment]
Henri is porting the code to Qt5, which *may* alleviate this (perhaps, hopefully, depends on the Qt5 language libraries).

**Comment by berndwaibel** [comment]
Thanks. So this should be retestet when Qt is released.
I will test this issue when Qt is running in my environment (Windows, Nagios).

**Comment by berndwaibel** [comment]
I moved this issue to my own fork, cause I will follow this issue.
