### ISSUE TITLE
custom actions - $IP$

### ISSUE THREAD

**Issue by flammy** [HenriWahl/Nagstamon#14]
Hi,

It would be nice to implement an $IP$ placeholder because many scripts work only with the ip-address of the host.

greets 

flam

**Comment by KirbyDE** [comment]
I've got address `1.2.3.4` in Nagios config.

How can I use exactly this IP address in an action? I've tried `$ADDRESS$` but this does not seem to be the value.

**Comment by HenriWahl** [comment]
What connection method is configured down in the actions tab of settings?
