### ISSUE TITLE
Feature request: Option to have all events in GUI until clicked/acknowledged

### ISSUE THREAD

**Issue by simpusconi** [HenriWahl/Nagstamon#142]
Option to have all events in to stay as "posts" in GUI until clicked/acknowledged.

**Comment by HenriWahl** [comment]
Can you explain in more detail by example what exactly do you mean?

**Comment by simpusconi** [comment]
Ok. I'll try. It would be nice to have a possibility as an option to have all warning/critical alarms that Nagstamon notifies/beeps about, stick in window until a actual person clicks or acknowledged them. 

SO lets say, specific user in monitor environment has nagstamon installed. But leaves his desk. During person is afk, a couple of criticals is happening. But then is back to normal. THe wish is to have these visible to the user when he returns. Clicking or acknowledge them just removes them from the list. 

So like even if a check is setup as volatile. All and every notification that backend notifies about and the goes back to normal. Stays in a gui. 

Get it? =)

**Comment by HenriWahl** [comment]
Hm, at the moment the model is to show all current events as Nagstamon gets them from monitor. Implementing your request would mean a greater change I assume. As I try at the moment to port Nagstamon to Qt5 I cannot implement other features. Anyway this idea sounds interesting so I would leave it open here.

**Comment by HenriWahl** [comment]
Well, if all is OK if the user comes back why bother him further? If he has interest in the history he might look there in the web interface. Nagstamon only shows realtime data.
