### ISSUE TITLE
Nagstamon overwrites .nagstamon data on exit with the running configuration. It shouldn't.

### ISSUE THREAD

**Issue by oernii** [HenriWahl/Nagstamon#143]
Basicaly I can edit the config files only when nagstamon is not running, or else it overwrites the files on exit. 

This creates a lot of issues with my synced configuration, I need to stop all running nagstamon instances to make a change. If I forget even one, it will save it's old config on exit and what old config will get synced to all nodes :(.

**Comment by HenriWahl** [comment]
This cannot be changed, sorry. How should Nagstamon know that it has no sovereignity over its config file?
Maybe you can simply exclude the .nagstamon directory from syncing or give Nagstamon as commandline parameter some arbitrary config directory which is not synchronized?

**Comment by oernii** [comment]
Well, I have 3 computers and have synced .dotfiles . My goal was to have the same configuration of nagstamon on all 3. All other programs (kde apps, pidgin, cinnamon applets, sqldeveloper, teamviewer, ...) work this way without a problem. But nagstamon even deletes files on exit. I create a new action on computer1, sync the file to computer2 and after nagstamon  deletes the file on exit.

**Comment by HenriWahl** [comment]
OK, let's see what I can do. At the moment I care more about porting Nagstamon to Qt5 but if this will ever be finished I could investigate this further.

**Comment by HenriWahl** [comment]
I accidently crossed the lines where the config files are removed - please see https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/Nagstamon/Config.py#L616 and the following lines.

Apparently you run Linux so maybe try to comment out these lines and let's see what happens...

**Comment by oernii** [comment]
thank you, will try

**Comment by neufeind** [comment]
@oernii What's the status here?

**Comment by oernii** [comment]
Well I commented out a bunch of os.unlink lines and it's working for me.

**Comment by Karmeni** [comment]
Same problem here in windows version, any sugestion? Thanks anyway

**Comment by HenriWahl** [comment]
@oernii what exactly were your changes?

**Comment by oernii** [comment]
I uncommented the "os.unlink" lines. No patch :(

**Comment by HenriWahl** [comment]
Ok. When doing so then deleted servers and action will not vanish and stay there after a restart.
So I will add a function to delete those files explicitely when the according settings will be deleted.

**Comment by HenriWahl** [comment]
Please chack latest commit https://github.com/HenriWahl/Nagstamon/commit/5c188bc679372fdf314b05efc117b2b7656127de - appears to work here.

**Comment by HenriWahl** [comment]
Latest BETA 20160513 binaries available now: https://nagstamon.ifw-dresden.de/nagstamon-20/
