### ISSUE TITLE
Settings' cancel button behaves as OK

### ISSUE THREAD

**Issue by Unode** [HenriWahl/Nagstamon#144]
Steps to reproduce:

1. Open settings (by right-clicking the nagstamon icon and clicking "Settings...")
2. Selected the "Filters" tab
3. Tick or Untick any of the listed filters
4. Press the "Cancel" button
5. Repeat 1. and 2. to confirm that actions taken in 3. were saved (when they shouldn't have).

**Comment by HenriWahl** [comment]
Thanks for the hint. This is a bug no feature... will vanish I hope with the upcoming Qt5 port when all GUI is reworked.

**Comment by HenriWahl** [comment]
Please check latest BETA from https://nagstamon.ifw-dresden.de/nagstamon-20/
