### ISSUE TITLE
[feature request] show OS type in overview

### ISSUE THREAD

**Issue by sjas** [HenriWahl/Nagstamon#145]
How much work is this to implement? Which part of the code to I have to work on, besides the GUI?

Is this even possible with all monitoring solutions? (Nagios/Icinga/...)

**Comment by HenriWahl** [comment]
Hi,
I assume you mean the OS type of the hosts/services in trouble? Well, I do not know any monitoring server that shows that information, sorry.
If you want to inspect the evaluated information have a look at all the .py files in the Server directory.
Regards
