### ISSUE TITLE
nagstamon not working with zabbix 2.4

### ISSUE THREAD

**Issue by The-spiki** [HenriWahl/Nagstamon#146]
Hi,

I realize that zabbix support is experimental.
And only version 2.2 is mentioned in the feature list.

2.2 works/worked fine for me.

Just got some servers updated and noticed it doesn't work with 2.4 version (of the server).

**Comment by HenriWahl** [comment]
Please check latest devel version. Windows binaries are available at https://seafile.ifw-dresden.de/d/c49b34412f/

**Comment by The-spiki** [comment]
Don't have windows.
Couldn't find newer than 1.0.1 on sourceforge.
Found qt tree here in github. Cloned the 1.1 dev... but don't have PyQt5 on my pc.
I'll get this sorted out one of these days.

**Comment by HenriWahl** [comment]
No it's the master tree. 1.0.1 + the latest Zabbix patches.
The 1.1 is still less than alpha.

**Comment by The-spiki** [comment]
OK.
Tried it now with the version from git master.
And I can confirm it works with zabbix 2.4

**Comment by alexei-znamensky-movile** [comment]
Same here. The git master version works fine with zabbix 2.4.3

**Comment by The-spiki** [comment]
Just FYI, with the git code Henri pointed me to use, I had it working on all 2.4 branch versions so far, up to and including the latest version 2.4.6

**Comment by HenriWahl** [comment]
Seems to work now.
