### ISSUE TITLE
[feature request] pause communication to certain server

### ISSUE THREAD

**Issue by The-spiki** [HenriWahl/Nagstamon#147]
Hi,

I believe it would be very nice if there was pause (or enable/disable) option for server.
For example inside Settings | server | edit

Otherwise I have to occasionally delete and recreate the server in settings.

**Comment by HenriWahl** [comment]
There is this option already. Check setting of the desired server, at the top of settings dialog.

**Comment by The-spiki** [comment]
Correct. It was even at the exact place where I wanted it.

It was just hidden from plain sight because of the color.
It may be because of dark themes I use, though it may be also reproducible for others.
If the server is already "enabled" in settings, after clicking on edit, there is checkbox visible in the new window. But font for the text is black... Until the checkbox is unticked.
Nothing important.

I apologize for wasting your time.
