### ISSUE TITLE
[feature request] support for multiple instances

### ISSUE THREAD

**Issue by The-spiki** [HenriWahl/Nagstamon#148]
I wonder if you could make out of the box support for running multiple instances of nagstamon.
Each with own settings, servers etc..

**Comment by HenriWahl** [comment]
Just run it with different config directories on command line. Like "nagstamon /home/user/config1" and "nagstamon /home/user/config2".

**Comment by The-spiki** [comment]
OK. Thanks.
It was easy enough to get this work the way I wanted/needed it.
And this is relatively uncommon usage.
So, consider this resolved.
