### ISSUE TITLE
kubuntu nagstamon 0.9.11 and 1.0.1 issue

### ISSUE THREAD

**Issue by div-one** [HenriWahl/Nagstamon#149]
writev(4, [{"\213\nP\1\3\f\0\4\300\10\0\4e\f\0\4w\2\0\0\35\0\213\1\0\331\213\1\0'\215\1"..., 16200}, {"\0\331g\1\0'i\1\0\276\35\0\0\331g\1\0\276\27\0\0\331n\1\0\276\35\0\0\331g\1"..., 1320}, {"", 0}], 3) = 17520
poll([{fd=4, events=POLLIN|POLLOUT}], 1, 4294967295) = 1 ([{fd=4, revents=POLLOUT}])
writev(4, [{"\213\27\22\0\3\f\0\4\300\10\0\4e\f\0\4\0\0\0\0H\1\0\4(\0n\1$\0\0\0"..., 1972}, {NULL, 0}, {"", 0}], 3) = 1972
poll([{fd=4, events=POLLIN}], 1, 4294967295) = 1 ([{fd=4, revents=POLLIN}])
recvmsg(4, {msg_name(0)=NULL, msg_iov(1)=[{"\0\10\3268\264\1\0\4\0\0>\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
poll([{fd=4, events=POLLIN}], 1, 4294967295) = 1 ([{fd=4, revents=POLLIN}])
recvmsg(4, {msg_name(0)=NULL, msg_iov(1)=[{"A\0\3468\300\f\0\4\3\0\202\0\v\0\0\4\0\0\5\0\0\0\0\0\0\0\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
poll([{fd=4, events=POLLIN}], 1, 4294967295) = 1 ([{fd=4, revents=POLLIN}])
recvmsg(4, {msg_name(0)=NULL, msg_iov(1)=[{"\0\10\3638\264\1\0\4\0\0>\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
poll([{fd=4, events=POLLIN}], 1, 4294967295) = 1 ([{fd=4, revents=POLLIN}])
recvmsg(4, {msg_name(0)=NULL, msg_iov(1)=[{"A\0\0039\304\f\0\4\3\0\202\0\v\0\0\4\0@\5\0\0\0\0\0\0\0\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
poll([{fd=4, events=POLLIN}], 1, 4294967295) = 1 ([{fd=4, revents=POLLIN}])
recvmsg(4, {msg_name(0)=NULL, msg_iov(1)=[{"\1 J9\1\0\0\0\4\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 36
open("/usr/share/X11/XErrorDB", O_RDONLY) = 13
fstat(13, {st_mode=S_IFREG|0644, st_size=41532, ...}) = 0
read(13, "!\n! Copyright 1993, 1995, 1998  "..., 41532) = 41532
close(13)                               = 0
write(2, "The program 'nagstamon' received"..., 570The program 'nagstamon' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 14550 error_code 8 request_code 62 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
) = 570
write(9, "DEBUG: 2015-06-10 17:01:00.24838"..., 1265) = 1265
exit_group(1)                           = ?
+++ exited with 1 +++

Traceback (most recent call last):
  File "/usr/share/nagstamon/Nagstamon/Config.py", line 673, in KeyringAvailable
    import keyring, secretstorage
ImportError: No module named keyring
DEBUG: 2015-06-10 15:37:45.943568 its   Created server.
DEBUG: 2015-06-10 15:37:46.295941 its   FetchURL: http://IP/monitoring/check_mk/view.py?view_name=nagstamon_hosts&output_format=python&lang=&limit=hard&is_host_acknowledged=-1&is_service_acknowledged=-1&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1&host_scheduled_downtime_depth=-1&is_in_downtime=-1 CGI Data: None
DEBUG: 2015-06-10 15:37:46.781498 its   FetchURL: http://IP/monitoring/check_mk/view.py?view_name=nagstamon_svc&output_format=python&lang=&limit=hard&is_host_acknowledged=-1&is_service_acknowledged=-1&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1&host_scheduled_downtime_depth=-1&is_in_downtime=-1 CGI Data: None
DEBUG: 2015-06-10 15:37:46.930325 its   server return values:  
DEBUG: 2015-06-10 15:37:46.930456 its   Refreshing output - server is already checking: False
DEBUG: 2015-06-10 15:37:46.947239    Notification on.
DEBUG: 2015-06-10 15:37:46.947748    Playing sound: /usr/share/nagstamon/Nagstamon/resources/critical.wav
DEBUG: 2015-06-10 15:37:59.028947    Notification off.
Traceback (most recent call last):
  File "/usr/share/nagstamon/Nagstamon/Config.py", line 673, in KeyringAvailable
    import keyring, secretstorage
ImportError: No module named keyring
The program 'nagstamon' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 34878 error_code 8 request_code 62 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty

**Comment by HenriWahl** [comment]
Please check https://github.com/HenriWahl/Nagstamon/issues/104 - sounds like pretty much the same problem. If not there is only hope that it will be working better with the upcoming Qt5 port of Nagstamon.

**Comment by div-one** [comment]
more stable but when you try to get Display menu the program closes

**Comment by HenriWahl** [comment]
Yes this is the same behaviour as in mentioned issue #104. Please check the measures taken at the end of that issue - it was a long journey to the working solution.
Otherwise stay tuned until the Qt5 port is ready, sorry.
