### ISSUE TITLE
Status: ERROR IndexError: list index out of range

### ISSUE THREAD

**Issue by ilyasparamban** [HenriWahl/Nagstamon#150]
Hi, 
I am trying to setup nagstamon on ubuntu 15.04 desktop for groundwork nagios, but I am getting the following error after configuring nagstamon. Please help me to resolve this issue. 
Status: ERROR IndexError: list index out of range
Following the errors I can see when I run it in debug mode: 

DEBUG: 2015-07-22 19:51:36.805445 server return values: ERROR IndexError: list index out of range 
DEBUG: 2015-07-22 19:51:56.821107 Vinam   FetchURL: http://*******/portal/auth/portal/groundwork-monitor/nagios/cgi-bin/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
ERROR: 2015-07-22 19:51:57.450398 Traceback (most recent call last):
  File "/usr/share/nagstamon/Nagstamon/Server/Generic.py", line 503, in _get_status
    table = htobj('table', {'class': 'status'})[0]
IndexError: list index out of range

**Comment by HenriWahl** [comment]
Looks like failed authorisation?

**Comment by ilyasparamban** [comment]
I am not sure. Using the same user-name and password which I use for login to groundwork panel.

**Comment by HenriWahl** [comment]
Did it ever work? Or is this a first attempt? I never had to do with Groundwork so I cannot say much about it.

**Comment by ilyasparamban** [comment]
This is the first attempt and its a new groundwork installation.

**Comment by HenriWahl** [comment]
OK so it is quite likely that it does not work with Groundwork. :-(
