### ISSUE TITLE
Does not show up in systray on KDE (Plasma)

### ISSUE THREAD

**Issue by neufeind** [HenriWahl/Nagstamon#152]
When the systray-option is active it doesn't show up in systray. This happens on KDE (Plasma). Afaik other applications had that as well and needed to adjust since the "old" systray-functionality isn't available anymore or so.

**Comment by HenriWahl** [comment]
Does it appear when using the 2.0 alpha?

**Comment by Brettdah** [comment]
Hi got the same problem on my brand new ubuntu 16.04...
I had to install indicator-systemtray-unity
but the last 2.0 alpha is OK (didn't test the others)

**Comment by Brettdah** [comment]
yes of course.. (even in floating I disable the hover thing it with wide screen it's not really a good option, for me) when I clicked on it I just had the right click menu, with a right click the menu, But this is not the subject here ;)

**Comment by HenriWahl** [comment]
Systray was never easy in Ubuntu Unity but now things are getting worse. Now they mixed systray with their appindicator stuff and so the systray icon appears but never talks back to Nagstamon. There is no signal that the icon was clicked and so Nagstamon can't react to a click. At the moment the only solution I see is adding a menu entry like "Show status window" to get the popup,

**Comment by HenriWahl** [comment]
Solution at #228
