### ISSUE TITLE
Add "Use Expire Time" for an acknowledgement

### ISSUE THREAD

**Issue by neufeind** [HenriWahl/Nagstamon#154]
In Icinga an acknowledgement has the option "Use Expire Time". With that you can accept an alarm for a given time.

If it returns to okay-state before, then the monitoring takes effect immediately again (in contrast to if you specify a downtime of some hours). But if the alarm doesn't go away after the given time the alarm will return.
Example usecase: When sending out a large newsletter you can ack that for a certain time a high load on the mailqueue is okay.

**Comment by HenriWahl** [comment]
Sounds interesting.

**Comment by idl0r** [comment]
I'd like to see that option too. Would be really handy.

**Comment by Mahagon** [comment]
This would be really usefull

**Comment by Dreamfire78** [comment]
+1 for this feature from me. Now I have to open the WebInterface everytime I have to add an expiration time.

**Comment by HenriWahl** [comment]
Just 4 years later this feature arrived - thanks @Massl123 

Check at https://nagstamon.ifw-dresden.de/download/#testing
