### ISSUE TITLE
not display chinese correctly on OS X Yosemite

### ISSUE THREAD

**Issue by johncanlam** [HenriWahl/Nagstamon#155]
We have some alerts written in chinese,nagstamon does not display it correctly .Today,we fix this problem.
Here is the tips
1. install font:"Microsoft YaHei",other fonts not work
2. open GUI.py
change
    gtk.rc_parse_string('style "font" {font_name = "Lucida Grande"} widget_class "*" style "font"')
to
    gtk.rc_parse_string('style "font" {font_name = "Microsoft YaHei"} widget_class "*" style "font"')
3. restart nagstamon
Hope it is helpful.At last, Nagstamon is great job.Thanks.

**Comment by HenriWahl** [comment]
Thanks!
Let's see what will happen with the Qt5 port - maybe already works there.

**Comment by HenriWahl** [comment]
Please check out https://nagstamon.ifw-dresden.de/files-nagstamon/unstable/Nagstamon-2.0-alpha.dmg which is a first alpha release of a more future-proof MacOSX-version.

**Comment by HenriWahl** [comment]
Please check with latest BETA from https://nagstamon.ifw-dresden.de/nagstamon-20/ .
