### ISSUE TITLE
Nagsta+icinga2+icingaweb2

### ISSUE THREAD

**Issue by MarcusCaepio** [HenriWahl/Nagstamon#158]
Hi,

is this supported and if yes, can you please tell me, how to config nagstamon?

**Comment by HenriWahl** [comment]
No, Nagstamon currently takes its information via JSON from Icinga1 CGI URLs. Doesn't Icinga2 support the legacy URLs?

**Comment by marcinn** [comment]
Please review  #159. It adds possibility to register custom `Server`. Anyone can provide external `egg` package with support for newer versions or uncommon monitoring tools.

**Comment by HenriWahl** [comment]
Hi,
sounds interesting. Please give me some time to check this because I am still lagging with that Qt5 port.
Thanks!

**Comment by marcinn** [comment]
Thanks. I saw Qt5 branch after making PR #159.  I've tried to cherry-pick changes, but without success - there are some major differences. And Nagstamon-qt does not work with Py2.7 (because of `configparser`).

**Comment by HenriWahl** [comment]
Yes, I used the chance to port to Python 3 too - mainly forced by Qt5 for Python only being available as binary for Python 3 for Window. It was not that hard as expected, maybe check commit 9ccb9e4d02a797eee90f9d710d3b62d90d6fbfd9 which was the major breakthrough as far as I remember. Changes were more cosmetic than very deep, like the ConfigParser -> configparser thing.

**Comment by marcinn** [comment]
So I'll try again :)

**Comment by marcinn** [comment]
I ran QT version with Py3, but after playing a while I see several problems:
 
  * `setup develop` does not work (can't find `Nagstamon/Server` pkg); I've installed deps by hand
  * QT interface (or just new interface) does not work well with Linux/tiled WM (I'm using AwesomeWM)
  * Nagstamon crashes at exit (core dump)

It looks that there is a lot work behind you with QT branch.

**Comment by HenriWahl** [comment]
Yes... behind and before. But It seems the only chance to keep Nagstamon fit for the future. The combo Python2 + GTK2 is a dead end and Qt5's portability way better. I tried with GTK3 but support for it for any platform other than Linux is worse than for good old GTK2.

What is `setup develop` for?

Any WM problems can be investigated if at least an alpha version can be made available for a broader public.

**Comment by MarcusCaepio** [comment]
Hi All,
So will Icinga2 be implemented into Nagstamon? Icinga2 uses a REST API and no more cgi bins

**Comment by HenriWahl** [comment]
I have no concrete plans but it should not be that hard, just the correct requests and evaluation of returned values.

**Comment by MarcusCaepio** [comment]
Since I am no programmer, I can't help implement this feature. But I would gratefully test your implementations.

**Comment by mymz** [comment]
As you say the implemention of icinga2 REST API will not be that hard I would kindly ask to put that on your roadmap as the icinga2 community grows and there is no alternative to nagstamon yet.

**Comment by HenriWahl** [comment]
After finishing the Qt5 port new features can be added. An Icinga2 interface sounds useful.

**Comment by MarcusCaepio** [comment]
Hi all,
anything new about this?
If you followed the last Open Source Monitoring Conference, the Icinga developer told, that Icinga2 is the main project for the comming developements. Icinga1 will only be supported incidentally. So Icinga2 will be the future product for open source monitoring. 
To use Nagstamon again, would be very nice.

**Comment by HenriWahl** [comment]
Nothing new but still on the todo list.

**Comment by minibbjd** [comment]
I've started to work on a IcingaWeb2Server class for Nagstamon 2. This will be limited to "view only" as long as the icingaweb2 REST API is not available.

**Comment by HenriWahl** [comment]
Great news!
As far as I know there is an API to trigger certain actions.

**Comment by minibbjd** [comment]
There's no documentation and I can't figure out the php code. I've asked in https://monitoring-portal.org/index.php?thread/34559-using-nagastamon-with-icinga-web-2/ already.

**Comment by HenriWahl** [comment]
Fixed with https://github.com/HenriWahl/Nagstamon/pull/202
