### ISSUE TITLE
Sound Notifications not working

### ISSUE THREAD

**Issue by Ringerl** [HenriWahl/Nagstamon#162]
Can't get sound notifcations with Nagstamon-2.0-alpha-20151001-win32 to work.
Also the play-button in settings does not produce any sound.

**Comment by HenriWahl** [comment]
Yes, like all the other notifications sound is not yet implemented.
At https://nagstamon.ifw-dresden.de/nagstamon-20/ there is a todo list of stuff still waiting to be finished. I hope to get it done soon.

**Comment by HenriWahl** [comment]
Last commit 6e9282165c34d1fce80b5e19c7a74990dc2fe999 is a workaround to let play button actually play sound on Windows and OSX - it is moving forward!

**Comment by HenriWahl** [comment]
Meanwhile working since months...
