### ISSUE TITLE
Nagstamon not showing status windows with 3 or more screens

### ISSUE THREAD

**Issue by Mycosis** [HenriWahl/Nagstamon#164]
I have a setup of 3 screens on my computer, and now nagstamon does not show the status window if i left click it. If I go back to two screens and then switch to 3 screens it still works, but has an awkward position and caanot be moved. It also works if I use remote desktop with two screens or less.

My screen resolutions are:
1. 1920x1200
2. 2560x1440
3. 1440x3440

**Comment by HenriWahl** [comment]
Which version are you referring to? Which OS? If not already, can you test with the latest Nagstamon 2.0 test releases from https://nagstamon.ifw-dresden.de/nagstamon-20 ?

**Comment by Mycosis** [comment]
If I use the Nagstamon-2.0-alpha-20151013-win32 i only get a right click menu on the tray icon showing "Dummy" and "Exit".

On version 1.0.1 i get the first described scenario.

I'm running Windows 8.1 Enterprise.

**Comment by HenriWahl** [comment]
Can you make sure that not somewhere on your vast screen space some tiny statusbar is floating around? At the moment this is the only mode that works so I am astonished that it should stay nowhere.

**Comment by Mycosis** [comment]
Would you look at that! It was hiding in the top corner of my main screen with a "OK" text. Just had to re-enter my password and now it works :) Thumbs up!, Can't wait for the finished version.

**Comment by HenriWahl** [comment]
Ok, good to hear. Thus I close this issue.
