### ISSUE TITLE
v2.0 Feature Req -- Server contact failure should indicate

### ISSUE THREAD

**Issue by pbrunnen** [HenriWahl/Nagstamon#167]
Hi.  Love Nagstamon!
I have been testing v2 and it has been working well.  One request would be to indicate if it can no longer contact the Nagios server.  The old v1 edition would start to indicate in grey "ERROR" when it could not contact the Nagios server.  The new v2 edition doesn't indicate this.  So looking at the icon, it keeps the last know state.  The user is thus unaware if the link to the Nagios server is lost or other problems and may be occurring.

**Comment by HenriWahl** [comment]
Yes, this is still on the todo list. Just being happy that the alpha runs at all... :-)

**Comment by pbrunnen** [comment]
Hi HenriWahl,
  Oh, I am very happy about it!  :-)
My apologies as I had not seen that in the todo list.

Thanks again!  -With kind regards, Peter.

**Comment by HenriWahl** [comment]
Should work now.
