### ISSUE TITLE
nagstamon centreon 2.6.6 compatibilty

### ISSUE THREAD

**Issue by cbijon** [HenriWahl/Nagstamon#168]
Hello,

Since the last update from centreon (2.6.6), nagstamon can't get the real status about the server.
It's indicate a green OK status with the error "AttributeError: 'NoneType' Object has not attribute 'parent'" and my centreon is RED.

Can you check this please ?

Regards,

**Comment by HenriWahl** [comment]
Hard to say when I will find the time...

**Comment by cbijon** [comment]
Can i help you to patch it ? Where are defined protocols ?

**Comment by HenriWahl** [comment]
It might help you if you enable debugging in Nagstamon and have a look at what the used URLs really spit out.

**Comment by lorenzo8769** [comment]
The same at #165

**Comment by lorrainezo** [comment]
Until the bug is resolved, solution is to use autologin feature, see my explainations here :
https://github.com/HenriWahl/Nagstamon/issues/165#issuecomment-161019857

**Comment by HenriWahl** [comment]
Please check the latest 20160519 binaires from https://nagstamon.ifw-dresden.de/nagstamon-20/

**Comment by lorrainezo** [comment]
Hello,

Version 20160519  works with Centreon 2.7.3 with autologin.
But like precedents versions, if you put a bad autologin key nagstamon return only a OK in green.

Thanks for your job

**Comment by HenriWahl** [comment]
Please check latest 20160527 binaries from https://nagstamon.ifw-dresden.de/nagstamon-20/ which address the not-noticing-any-auth-problems problem.
