### ISSUE TITLE
Offer compression-support (gzip/deflate) with http-requests

### ISSUE THREAD

**Issue by neufeind** [HenriWahl/Nagstamon#170]
With a client that supports compression (offers it in the http-request) replies can get dramatically smaller. One such example is:
95283bytes json uncompressed
vs. 7563bytes gzipped

It works fine when requesting the status with a browser. However nagstamon doesn't offer compression-support in the request.

**Comment by neufeind** [comment]
How do add the needed Accept-Encoding and handle the reply:
http://united-coders.com/christian-harms/use-compressed-data-directly-from-zip-files-or-gzip-http-response/

**Comment by HenriWahl** [comment]
Apparently already in Nagstamon 2.0 and the Requests module it uses instead of urllib.

**Comment by neufeind** [comment]
This made me pull my first copy of Nagstamon 2.0-alpha from Github. Indeed, gzip works fine there.

**Comment by HenriWahl** [comment]
Nice to know! Any speed improvements?
