### ISSUE TITLE
Few problems with 2.0.0

### ISSUE THREAD

**Issue by didier13150** [HenriWahl/Nagstamon#171]
Hi there,

I've encoured few problems with 2.0.0 alpha 1 on Linux (Fedora 23): see [attached patch nagstamon-enable-qt.patch](https://github.com/HenriWahl/Nagstamon/files/62250/nagstamon-enable-qt.patch.txt)
* byte compile fail because syntax is not python 3.x compliant on file Nagstamon/GUI.py
* Wrong name for lib: It's seem Server lib renamed to Servers
* setup is not recursive for third party modules

I give you [RPM spec file nagstamon.spec](https://github.com/HenriWahl/Nagstamon/files/62252/nagstamon.spec.txt) too

Best Regards

Didier.

**Comment by HenriWahl** [comment]
Hi,
GUI.py is just remaining and needed for reference for development - not needed for execution anymore. You can safely ingore it.
Setup is not finished yet anyway... but thanks for the patch!
