### ISSUE TITLE
Filter for soft state are ignored by v1.0.1

### ISSUE THREAD

**Issue by sk16tor7** [HenriWahl/Nagstamon#173]
Hi,

i'm using Nagstamon 1.0.1 on Windows 10 Enterprise 64 bit. I set up these filters
- acknowledged hosts & services
- hosts & services down for maintenance
- services on down hosts
- services on hosts in maintenance
- hosts in soft state
- services in soft state

but at the moment that a service get's in a soft state i'm getting the notification with sound. I pretty sure that a large number of notifications are filtered but not all of them. Is there any limit in the filter function?

thankx, Stefano
![nagstamon filters](https://cloud.githubusercontent.com/assets/16474233/12032021/d8026134-ae13-11e5-994f-a7773688f607.PNG)
![nagstamon soft state](https://cloud.githubusercontent.com/assets/16474233/12032048/2129dfd6-ae14-11e5-9554-c1b58f454aa8.PNG)

**Comment by HenriWahl** [comment]
This seems to be a known bug. I assume it will be fixed in 2016.

**Comment by HenriWahl** [comment]
Can you please test with latest Nagstamon 2.0 BETA from https://nagstamon.ifw-dresden.de/nagstamon-20/ ? Anyway there is no further development in the 1.0 branch.

**Comment by HenriWahl** [comment]
Seemes to wirk in the 2.0 BETA.
