### ISSUE TITLE
[Feature] New Action Variable for access to documentation url

### ISSUE THREAD

**Issue by e-hubert** [HenriWahl/Nagstamon#176]
We are using Nagstamon with Nagios, Icinga and Zabbix and would like to configure custom browser actions to access the alert documentation stored in notes_url of host and service (for Nagios and Icinga) as well as trigger.url (for Zabbix), see:
http://docs.icinga.org/latest/en/objectdefinitions.html#host
http://docs.icinga.org/latest/en/objectdefinitions.html#service
https://www.zabbix.com/documentation/2.4/manual/api/reference/trigger/object

Regarding variable names I think of something like $HOST-NOTESURL$, $SERVICE-NOTESURL$ - for Zabbix one could assign the trigger.url to both of them.

This would really improve the usability a lot as one currently has to jump to the actual web ui of the monitoring servers and click in those web frontends on the documentation link in order to jump to the appropriate documentation sites.

I did not yet look at the inner workings of nagstamon (source code) in order to figure out whether it would be possible to support the implementation of this feature request.

**Comment by HenriWahl** [comment]
If these URLs come with every host from the monitoring server this could be possible, otherwise there where no data to use.
If you look into the source please look at the qt branch as it is becoming the new master if I get from alpha to beta which I hope will happen soon.

**Comment by e-hubert** [comment]
Thanks for your very quick response. 
I know Zabbix's API quite well so I'm confident for this part. 
Regarding Icinga I was not sure, so I activated Nagstamon's debug output and let it run. Manually firing logged urls like: 
http://<my_icinga_inst>/cgi-bin/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&jsonoutput 
and inspecting the json response you can find the original notes_url (but without makro substition), e.g. they can look like this example:
http://<myhost>/<mydynamic_script>.php?host=$HOSTNAME$&ip=$HOSTADDRESS$&service=$SERVICEDESC$&serdisp=$SERVICEDISPLAYNAME$&sout=$SERVICEOUTPUT$&custom_param=-YAJKg
So this will require some further substition...

Against my expectation requests to Zabbix do not seem to be logged in the same way as for Nagios/Icinga. 
I guess next I really have to grab the sources and look into at least the following for the server part:
https://github.com/HenriWahl/Nagstamon/blob/qt/Nagstamon/Nagstamon/Objects.py
https://github.com/HenriWahl/Nagstamon/blob/qt/Nagstamon/Nagstamon/Servers/Generic.py
https://github.com/HenriWahl/Nagstamon/blob/qt/Nagstamon/Nagstamon/Servers/Icinga.py
https://github.com/HenriWahl/Nagstamon/blob/qt/Nagstamon/Nagstamon/Servers/Zabbix.py
and setting up test system running directly from source of the qt branch.

**Comment by e-hubert** [comment]
Quickly setup everything required to run the project from source and modified the Icinga server implementation as a starting point. I have never been involved in Python development before.
Server part did not look too complicated after all, but I may need some advice regarding QUI with its close to 5000 lines. ;-)
I'm currently looking at line [line 2430] (https://github.com/HenriWahl/Nagstamon/blob/621898cfedde37829da18daf935bcff353813d06/Nagstamon/Nagstamon/QUI/__init__.py#L2430) and it looks like the place where the second parameter is used to populate the info array later used in the mapping at [line 2932] (https://github.com/HenriWahl/Nagstamon/blob/621898cfedde37829da18daf935bcff353813d06/Nagstamon/Nagstamon/QUI/__init__.py#L2932). If I get it right most alert specific values are taken right from the selected row of the table in the UI, not some kind of data model. So right now I'm quite unsure how to best access the data which I placed for the Icinga server into `self.new_hosts[host_name].services[service_name].service_docurl`

**Comment by HenriWahl** [comment]
The table code definitifely keeps room for improvement.... yes, at the moment the relevant data comes from GUI at https://github.com/HenriWahl/Nagstamon/blob/qt/Nagstamon/Nagstamon/QUI/__init__.py#L2305.
As far as I see could access the info in the execute_action method by `self.server.nagitems_filtered[info['host'][info['service'].service_docurl`

**Comment by e-hubert** [comment]
Thanks for your quick feedback!

Hmm, I guess I will have to read a bit more about Python first and further study the source code, as unfortunately I do not yet understand your proposed code line. I have even difficulties to parse it in terms of number of brackets.

To me it looked like server.nagitems_filtered would be a map (dict) with two keys "services" and "hosts" each storing another map (dict) where the service/host state represents the key and the value a list of those objects (hosts, services) according to the relevant state.
Within the method execute_action I understand info['host'] will give me the hostname and info['service'] the service name of the selected row. What I don't understand is how to use those two values as keys for the data structure nagitems_filtered?
After looking at the code what I think should work in execute_action is something like this:
`self.server.hosts[info['host']].services[info['service']].service_docurl`

I will likely test this out tomorrow. By the way, I noticed another small bug. When configuring actions and selecting "All monitor servers" from the dropdown "Monitor type" the action is not shown on any of the monitors I have configured, limiting to a certain type works correctly though.
Looks like this
`if action.enabled == True and action.monitor_type in ['', self.server.TYPE]:`
is meant to be
`if action.enabled == True and action.monitor_type in ["All monitor servers", self.server.TYPE]:`
but it would certainly be better to either add this to the type enumeration or at least define a constant at a single place instead.

**Comment by HenriWahl** [comment]
You are right, nagitems_filtered is a dictionary holding hostnames as keys and GenericHost objects as values. These have the dictionary .services with the servicenames as keys.

If an action applies to all monitor types its monitor_type property is simply '' so this is supposed to work. Can you send me the action config file from $HOME/.nagstamon/actions/ACTION.conf to check this?

**Comment by HenriWahl** [comment]
There seems to be a bug when saving edited action to file - one thing more to check... :-)

**Comment by e-hubert** [comment]
Ah, understood. Looks like somehow resource values are written to the action.conf instead of resource keys. You are right, in my action.conf there is 
`monitor_type = All monitor servers` 
instead of an empty string and there is also 
`type = Browser`
(with capital first letter) which explains, why suddenly I did not reach the code block to open my url in the browser. If I changed the source to compare with "All monitor servers" or "Browser" all was working fine, but felt wrong. Now I understand the reason. If you already have an idea where to fix this it would be very welcome. Otherwise I can have a look when I find some time.

**Comment by HenriWahl** [comment]
As I am doing still GUI stuff right now I will look there later.

**Comment by e-hubert** [comment]
I think after all the reported problem with action and monitor types is a GUI issue. I can't see any model view separation here. Am I right that QUI is the replacement of GUI?

In GUI I noticed code like this for combobox data population:
```
# as default setting - would be "" in config file
self.monitor_types.insert(0, "All monitor servers")
# transform monitor types list to a dictionary with numbered values to handle combobox index later
self.monitor_types = dict(zip(self.monitor_types, range(len(self.monitor_types))))
for monitor_type in sorted(self.monitor_types.keys()):
    self.combomodel_monitor_type.append((monitor_type,))
    self.combobox_monitor_type.set_model(self.combomodel_monitor_type)
```
and access to combo box values
```
# set monitor type combobox which cannot be set by above hazard method
self.combobox_monitor_type = self.builder.get_object("input_combo_monitor_type")
active = self.combobox_monitor_type.get_active_iter()
self.combomodel_monitor_type = self.combobox_monitor_type.get_model()
new_action.monitor_type = self.combomodel_monitor_type.get_value(active, 0)

# if action applies to all monitor types its monitor_type should be ""
# because it is "All monitor servers" in Combobox
if not new_action.monitor_type in Actions.get_registered_server_type_list():
       new_action.monitor_type = ""
```

It doesn't look like separation between model values and text representations, but rather transforming text values back and forth - which is now just missing in QUI code:

In QUI code I only find
```
# fill action types into combobox
self.ui.input_combobox_type.addItems(["Browser", "Command", "URL"])

# fill default order fields combobox with monitor server types
self.ui.input_combobox_monitor_type.addItem("All monitor servers")
```

The code in Config.py looks quite generic to me as all options (key, value pairs) are stored in Config.\__dict\__ and data from UI widgets is promoted in Dialog_Action.ok.
For all comboboxes this looks like this:
```
elif widget.startswith('input_combobox_'):
    setting = widget.split('input_combobox_')[1]
    self.action_conf.__dict__[setting] = self.ui.__dict__[widget].currentText()
```
This explains why the text from all comboboxes is written as is to the action config files.

**Comment by HenriWahl** [comment]
Thank you for your investigations - looks like there is still something missing :-(
I will check this as soon as possible.

**Comment by HenriWahl** [comment]
The 2.0 BETA now uses a way more functional model + view. If you like to dig into again - now it at least theoretically would make sense at all.
