### ISSUE TITLE
[Bug] Hosts, Services and History button not working (current qt branch)

### ISSUE THREAD

**Issue by e-hubert** [HenriWahl/Nagstamon#177]
I noticed the app is currently crashing in debug mode when using the buttons of the main menu `QUI\__init__.py", line 442, in open_url self.Debug(server=self.server.get_name(), debug='Open {0} web page {1}'.format(self.url_type, url))
AttributeError: 'PushButton_BrowserURL' object has no attribute 'Debug'`
In non-debug mode the action variable $monitor-cgi$ used in the url was not replaced for my test with icinga and a proper configuration of this server setting "MONITOR CGI URL".
According to Generic Server browser url can either use a placeholder $MONITOR$ or $MONITOR-CGI$, but replacements seems to be done ALWAYS only for $MONITOR$, see [line 439] (https://github.com/HenriWahl/Nagstamon/blob/621898cfedde37829da18daf935bcff353813d06/Nagstamon/Nagstamon/QUI/__init__.py#L439)
So Monitor button is working, and Hosts, Services and History are broken.

**Comment by HenriWahl** [comment]
Thanks for some alpha-feedback! :-)

Which version do you use?

**Comment by e-hubert** [comment]
Hi Henri! As written in my description I'm talking about Icinga and I'm running nagstamon 2.0 alpha directly from source of qt branch:
`git status
On branch qt
Your branch is up-to-date with 'origin/qt'.`

As I'm willing to contribute to improvements regarding access to documentation urls as defined in the monitoring systems (see issue #176), I will indirectly test nagstamon 2.0 alpha a little bit at least against Icinga 1.13.2 with cgi_json_version 1.11.0. as well as Zabbix 2.4.7. So I can report any issues I find and ask for further improvements. Hope this feedback will help.

**Comment by HenriWahl** [comment]
Closed with last commit.

**Comment by e-hubert** [comment]
Fix confirmed - successfully tested with Icinga after fetching latest. Many thanks for such a fast resolution!
