### ISSUE TITLE
Nagstamon 2.0 can't open status

### ISSUE THREAD

**Issue by gtozzi** [HenriWahl/Nagstamon#184]
Hi there,

I'm testing the current GIT snapshot on KDE5.
After installing the required python modules it runs, sets up the tray icon, and connects to server.
But when I click the icon, the status window only "flashes" for a brief moment, then closes again.

**Comment by HenriWahl** [comment]
Is there any output in a terminal?

**Comment by gtozzi** [comment]
Apparently nothing relevant. I am using lastest Kubuntu with KDE 5.15.

This is the output at startup, but I get no extra output when i try to click the icon.
>$ env LANG=C ./nagstamon-qt.py
>QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
>QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
>QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
>GStreamer; Unable to pause - "file:///mnt/secfs/Nagstamon/Nagstamon/Nagstamon/resources/down.wav"
>Warning: "No decoder available for type 'audio/x-wav'."
>Error: "Your GStreamer installation is missing a plug-in."

If you can tell me where to start looking for, I can try to debug the source.

**Comment by HenriWahl** [comment]
There is a debugging mode, available at first tab of settings.
Anyway I think I will try myself if I can reproduce this.
When I see the error message you got - maybe you could make sure that

> Warning:  "No decoder available for type 'audio/x-wav'."
> Error: "Your GStreamer installation is missing a plug-in.

wouldn't happen?

**Comment by gtozzi** [comment]
I have disabled sound and enabled debug log.
The gstreamer error is gone, the debug log is empty.
I have debug messages straight into the terminal, but they only refer to:
> DEBUG: 2016-02-07 08:02:52.732645 servername FetchURL: ...

**Comment by HenriWahl** [comment]
You use Kubuntu 15.10, right? Just to make sure to reproduce it correctly.

**Comment by gtozzi** [comment]
Affirmative.

**Comment by HenriWahl** [comment]
I have it running now in a VirtualBox VM:
- Kubuntu 15.10 64 bit
- displayed as systray icon

When I click it the first time after starting it I see a short flashing status window, every next click works flawlessly. You have the short flash every time?

**Comment by gtozzi** [comment]
Yes.

**Comment by HenriWahl** [comment]
Please check latest commit bd2a20cbdfbbeb9c55f4df6fb44f763b31a9f75a - I lost at least the first flashing.

**Comment by gtozzi** [comment]
You solved it :)

Thank you!

**Comment by phaoost** [comment]
My nagstamon recent 2.0-beta is still affected with this bug:
~$ nagstamon 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Config.py", line 599, in KeyringAvailable
    import secretstorage
ImportError: No module named 'secretstorage'
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
GStreamer; Unable to play - "file:///usr/lib/python3/dist-packages/Nagstamon/resources/critical.wav"
GStreamer; Unable to play - "file:///usr/lib/python3/dist-packages/Nagstamon/resources/critical.wav"
Warning: "No decoder available for type 'audio/x-wav'."
Error: "Your GStreamer installation is missing a plug-in."
