### ISSUE TITLE
Status: ERROR URLError: urlopen error EOF occurred in violation of protocol (_ssl.c:590) error

### ISSUE THREAD

**Issue by thomasjamesgoin** [HenriWahl/Nagstamon#185]
Using the master branch of the git repo, appears that this occurred with a very recent commit.  This used to work as early as last week.
![image](https://cloud.githubusercontent.com/assets/2332670/12868122/e56105dc-cccd-11e5-81fd-a58c1b49c77d.png)

**Comment by HenriWahl** [comment]
Must be some local change as all development happens at the qt branch https://github.com/HenriWahl/Nagstamon/tree/qt. Please recheck again with this branch. Quite possible that the error vanishes as the qt branch uses the Requests module for connections, with is configured to be more tolerant to TLS problems.

**Comment by thomasjamesgoin** [comment]
Confirmed.  Also switched to 2.0 alpha and having much better success.  Thank you.
