### ISSUE TITLE
URLError: urlopen error [SSL:CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by scrubby** [HenriWahl/Nagstamon#186]
Hi,

I'm running Nagstamon 1.0.1 on Ubuntu Gnome 15.10 and I'm getting the following error.

URLError: urlopen error [SSL:CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

Everything was running fine when I was still running Ubuntu Gnome 14.04 LTS
When I open the nagios website in my browsers, then everything works fine. The nagios server is however and older server, so maybe some compatibility issues?

**Comment by HenriWahl** [comment]
You are victim of https://github.com/HenriWahl/Nagstamon/issues/126. There is also a fix described.

This is fixed permanently in Nagstamon 2.0 which is at the moment only available as source for your platform - see https://github.com/HenriWahl/Nagstamon/tree/qt.
