### ISSUE TITLE
v2.0 Blurred font

### ISSUE THREAD

**Issue by sronline** [HenriWahl/Nagstamon#187]
With Nagstamon-2.0-alpha-20160128-amd64 the font is blurred with Windows 7 (classic theme):

![nagstamon_2 0](https://cloud.githubusercontent.com/assets/17158346/12945351/30496202-cfed-11e5-83a9-8c60b5069578.PNG)

![nagstamon_1 0](https://cloud.githubusercontent.com/assets/17158346/12945344/29c2697e-cfed-11e5-9e77-6d8ae8c8bbd9.png)

**Comment by HenriWahl** [comment]
In the Nagstamon directory you got from zip file there is a file
qt.conf. Can you please check how the look is when you delete the last 2
lines in that file regarding the used font engine in Windows?

**Comment by sronline** [comment]
when I delete the lines the font rendering is ok!
