### ISSUE TITLE
2.0 - Feb 6 Zenoss and general issues.

### ISSUE THREAD

**Issue by mdiorio** [HenriWahl/Nagstamon#188]
Hi,

Love this and love that you're adding Zenoss support.  

Not sure if it's because the code was ported for Zenoss 4 or not, but I can't get it to work for Zenoss 5.  
urllib.error.URLError: <Open URL Error [Errno 110001 Getaddrinfo failed]>

With just the Nagios monitor running, 2.0 is very slow when there are a lot of alerts.

Also, the Filters button doesn't bring up the filters menu.  I can only access it through settings.

Thanks!

Max

**Comment by HenriWahl** [comment]
Let's see what can be done regarding Zenoss 5.

What do you mean by getting slow? Is the UI less responsive? Which monitor type are you using? How many alerts do you have?

The filters button is still dysfunctional - to be changed soon.

Regards
Henri

**Comment by mdiorio** [comment]
Hi Henri,

Thanks for the reply.  Yes, the UI is significantly less responsive.  Without filters in place, we had 500 or so alerts (I know, we need some cleanup) in our Nagios monitor.  Doing anything like opening NagstaMon or closing it, took 30 seconds to 2 minutes.  I'm sure most people won't have that many alerts, but in large environments I can definitely see it.

Thanks.  Max

**Comment by HenriWahl** [comment]
What the... well, 30 secs to 2 minutes is much. Very much... is this the same disaster with Nagstamon 1.0.1?

**Comment by HenriWahl** [comment]
What platform do you run Nagstamon on?

**Comment by HenriWahl** [comment]
This issue brought me to rework the whole table display to use now a more standard treeview. In my tests this consumes enormously less memory and displays especially large amounts of hosts/services way better. It is not feature complete yet (speaking of context menus), but could you check the latest commit of the "treeview" branch https://github.com/HenriWahl/Nagstamon/tree/treeview if there is any improvement noticeable in your environment?

**Comment by mdiorio** [comment]
Much better!  It's down to about 1-1.5 seconds to open when there are over 700 items to display!  Thank you.

**Comment by HenriWahl** [comment]
Yes, opening the window with so many items is a bit laggy but this is the best we can get here (or someone has another idea how to improve?). Compared to the situation before I think this is some progress.
