### ISSUE TITLE
v2.0 Feature Request: custom http read timeout values

### ISSUE THREAD

**Issue by thomasjamesgoin** [HenriWahl/Nagstamon#191]
The check_mk box I have is very slow and I need to be able to have a read timeout value that is longer than the default 10 seconds.  Making it a changeable max value in individual server profiles would be very helpful.

**Comment by ricardoamaro** [comment]
I'm sure that everyone will benefit from having the http timeout configurable.

**Comment by ricardoamaro** [comment]
Propose to make this line into a configurable variable via settings:

https://github.com/HenriWahl/Nagstamon/search?utf8=%E2%9C%93&q=%22socket.setdefaulttimeout%22&type=Code
```
import socket

# fix/patch for https://bugs.launchpad.net/ubuntu/+source/nagstamon/+bug/732544
socket.setdefaulttimeout(30)
```

**Comment by HenriWahl** [comment]
Might be some parameter in Requests module has this line sets a socket timeout of 30 and not 10.

**Comment by ricardoamaro** [comment]
Thanks for the reply @HenriWahl 
Is there any way we can tweak this?

**Comment by HenriWahl** [comment]
http://docs.python-requests.org/en/master/user/advanced/?highlight=timeout shows there is that option. Should be no rocket science to implement this - main obstacle is time. Any contribution is welcome :-)

**Comment by HenriWahl** [comment]
Added in 1f3713cf52f1dabcdac6db132732956730f2bd88 - can you test from GitHub master or do you need a binary? If so, for which OS?

**Comment by HenriWahl** [comment]
Please check latest 20160601 binaries from https://nagstamon.ifw-dresden.de/nagstamon-20/
