### ISSUE TITLE
v2.0 Actions not shown 

### ISSUE THREAD

**Issue by sronline** [HenriWahl/Nagstamon#193]
Custom actions are not shown in the context menu:

![nagstamon_actions_1](https://cloud.githubusercontent.com/assets/17158346/13044928/ff6a8386-d3d0-11e5-98a0-c998809df8e8.png)

![nagstamon_actions_2](https://cloud.githubusercontent.com/assets/17158346/13044936/056a48d4-d3d1-11e5-9898-239386e5436e.png)

Config files in folder "actions":
[actions.zip](https://github.com/HenriWahl/Nagstamon/files/130404/actions.zip)

**Comment by HenriWahl** [comment]
Never or after changes?

**Comment by sronline** [comment]
Never

**Comment by HenriWahl** [comment]
Sorry for the delay.... i could reproduce this now with your actions.zip. I do not have an idea yet but you are not alone :-)

**Comment by HenriWahl** [comment]
How did you create the actions? By actions editor or externally?

**Comment by HenriWahl** [comment]
Please check if it works now for you - I had success with your actions.zip.
