### ISSUE TITLE
Thruk - downtime problems

### ISSUE THREAD

**Issue by exodus1984** [HenriWahl/Nagstamon#194]
Does not work turning downtime, acknowledge etc
Filtering does not work "notification disable" for the host
Filtering does not work "notification disable" services (when set to host disable notifications)

Forgive me for the level of English.

ps.
The same problem in version 1.0.1

**Comment by HenriWahl** [comment]
Which version do you refer to? Fixes and features only will go into 2.0.
Are you sure you have the access rights to set acknowledge etc.?

**Comment by exodus1984** [comment]
a have 2.0 alpha - i install this version to test this issue.

from thruk web page I can do everything

Description 1.0.1 I gave information only

What can I give you, so that you can better debug?

**Comment by exodus1984** [comment]
thruk 2.04

**Comment by HenriWahl** [comment]
I checked Thruk's downtime code at a Thruk monitor. Apparently they have changed the web formular to trigger such events. I do not know when I will find time to dig deeper there.

**Comment by HenriWahl** [comment]
Please see https://www.thruk.org/documentation/faq.html#possible-csrf-no-or-invalid-token - as suspected they added a csrf-token. Should be the same to fix like with Check_MK. In the meantime follow their recipe.

**Comment by Lord-of-Kerry** [comment]
we're using the icinga webgui now. That works fine for us. Thanks for the advice and all the nagstamon-work you did!
