### ISSUE TITLE
Incorrect behavior on two monitors, ubuntu, unity

### ISSUE THREAD

**Issue by Yakoot** [HenriWahl/Nagstamon#195]
If nagstamon always opened on one monitor, after refresh he blocks my actions on second monitor, so I should collapse it. After collapsing I can work on second monitor.
My english is bad, sorry.

**Comment by HenriWahl** [comment]
Which version of Nagstamon do you use?

**Comment by Yakoot** [comment]
Latest

**Comment by HenriWahl** [comment]
LTS or not? 14.04 or 15.10?

**Comment by Yakoot** [comment]
15.10, unity
in kde all works correctly

**Comment by HenriWahl** [comment]
By "monitor" you mean different monitoring servers? Or do you mean physical screens?

**Comment by Yakoot** [comment]
physical scsreens

**Comment by HenriWahl** [comment]
I will try to reproduce this. Might take a while...

**Comment by Yakoot** [comment]
tomorrow I can make a skreenshot of my nagstamon settings

**Comment by HenriWahl** [comment]
Good idea

**Comment by Yakoot** [comment]
https://drive.google.com/file/d/0B6XQHCQPupskajVnZ0pfd20tWjQ/view?usp=sharing
https://drive.google.com/file/d/0B6XQHCQPupskdi1EWnN5ZVdTdW8/view?usp=sharing
https://drive.google.com/file/d/0B6XQHCQPupskNmVRVXFiSk5xN1U/view?usp=sharing

**Comment by HenriWahl** [comment]
OK, 'latest' means '1.0.1'... please check with latest 2.0 alpha, because only there further development happens. There is no .deb file yet but I hope it will be coming soon,

**Comment by HenriWahl** [comment]
Yep there it is: https://nagstamon.ifw-dresden.de/files-nagstamon/unstable/nagstamon_2.0-alpha-20160216_all.deb
Please let me know if it runs and if your problem gets solved.

**Comment by Yakoot** [comment]
Works fine! Thank you!
