### ISSUE TITLE
Nagstamon-qt opening the window in the wrong desktop

### ISSUE THREAD

**Issue by gtozzi** [HenriWahl/Nagstamon#197]
Hi again,

I am using nagstamon-qt in systray mode.

When I click the icon, sometimes it does not open any window. If I then start cycling all the virtual desktops, I find the window opened in a different one.

Couldn't still determine which criteria it uses to choose the desktop, but often it does not chose the right one.

**Comment by HenriWahl** [comment]
Which desktop environment on which OS do you use?

**Comment by gtozzi** [comment]
I am using XFCE on Ubuntu GNU/Linux

**Comment by HenriWahl** [comment]
Which versions exactly? Xubuntu?

**Comment by gtozzi** [comment]
Ubuntu 15.10, you can call it XUbuntu if you prefer, doesn't make much difference :)

**Comment by gtozzi** [comment]
If you can please point me to the right file/line where the window displaying is handled, I can try to fix it myself.

**Comment by HenriWahl** [comment]
In case of systray usage it should be here: https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/QUI/__init__.py#L1118

**Comment by gtozzi** [comment]
Thank you.

After investigating further. It looks like the window is always opened on the same desktop it has been opened the first time.

I have made some progress by making the window manager switch to that desktop, but I am trying to accomplish exactly the opposite: https://github.com/gtozzi/Nagstamon/commit/63854c19b604df82333f87092daf88be28f4a7dd

**Comment by gtozzi** [comment]
Ok, I've found a fix, but i do not like it: https://github.com/gtozzi/Nagstamon/commit/24feaf635fe3beb0823c1c362b40105677a59111

In short, this is done via a different protocol, called EWMH, that apparently is not implemented in the Qt libraries itself, so it requires an extra library. That is bad.
Also, it looks like PyQt does not allow to customize the window's WM_NAME, that is required to uniquely identify the window under that protocol. That is bad.

The other way would probably be to destroy and recreate the window instead of hiding and showing it, so that every time it gets recreated it will hopefully be shown on the right desktop.

@HenriWahl What do you think?

**Comment by HenriWahl** [comment]
Strange at all as it does not occur with GNOME or KDE.
I already use ewmh.py for staying on all desktops as floating statusbar.
I think I have to test with XFCE then.
Recreating window with every popup seems really nasty...
