### ISSUE TITLE
Nagstamon-qt displaying two weird rectangles

### ISSUE THREAD

**Issue by gtozzi** [HenriWahl/Nagstamon#198]
I am not sure if this is a bug or a wanted feature.
If this is a feature, I didn't find a way to disable it and couldn't understand what it means, so there probably is still a minor bug behind.

I have just noticed nagstamon paces two small green rectangles on top-left of my desktop. They are always on top. They are movable: when they are created: they look like one, because they are on top of each-other. They are always on the current desktop (or in every desktop). If I click them nothing happens.

Here is a screen-shoot:
![istantanea_2016-02-19_21-49-40](https://cloud.githubusercontent.com/assets/386394/13188609/b57dfd18-d752-11e5-92df-37272658c37e.png)

**Comment by gtozzi** [comment]
Update: right click opens the tray menu, but the "Servers" tab content is empty.

**Comment by HenriWahl** [comment]
I wonder why there are two of them... and what is your display setting? Showing a statusbar or a systray icon? In the first case there should be only one and in the latter none... strange.
Do you have any servers configured?
Did you run it twice accidently?

**Comment by gtozzi** [comment]
Thank you for your answer.
I have realized they were linked to two different processes. I killed them, and they vanished.

For some reason, they didn't read my configuration file (with 3 servers and systray mode) and went to default settings: no servers and statusbar.

Probably these processes were started by some sort of automated session-restoring in my desktop environment.

So in the end, no bug, just my fault. But I'm wondering... shouldn't the nagstamon process check if it is already running when started? Maybe the answer is no, for some reason I can't get, or this could be an option.

**Comment by HenriWahl** [comment]
Some people use different instances of Nagstamon with different config files, so I do not think it might be a good idea to check if it is already running. In the worst case such a behavior would not have solved your problem if only running one instance with empty defaults.
Would be interesting if your both extra instances got a yet config argument by accident or session management which they may have considered as config directory to use.

**Comment by gtozzi** [comment]
You are right: there was a --session argument that were misunderstood.
Here is a fix for this: https://github.com/gtozzi/Nagstamon/commit/9d8820fe3f44f31a2fb3513523cbc89859e0f036
