### ISSUE TITLE
v2.0 Digest auth

### ISSUE THREAD

**Issue by mortzu** [HenriWahl/Nagstamon#203]
It seems like digest auth is broken in v2

**Comment by sammcj** [comment]
+1 to this, I can't login to any Nagios / Check_MK instances with digest auth.

@HenriWahl any idea how hard this would be to fix?

**Comment by HenriWahl** [comment]
Maybe a stupid question, bu I do not use digest auth myself, so I wonder: did it ever work, even in v1?

**Comment by HenriWahl** [comment]
Added in commit 263821c68103785cf14b10f678baf0b4b02ad680.
I can not test this - do you? Or do you need binaries?

**Comment by sammcj** [comment]
Hey, thanks for doing that - would you be able to build me an OSX binary?
I've given building it a go but got a bit lost.

**Comment by HenriWahl** [comment]
Please get it at https://seafile.ifw-dresden.de/f/02ec579606/

For OSX builds I install all dependencies via fink.

**Comment by sammcj** [comment]
Works perfectly both with Nagios 4 and Check_MK both on Digest!

**Comment by HenriWahl** [comment]
Good news. Thus I close this issue now. Thanks for testing!

**Comment by sammcj** [comment]
Legend, thank you!
