### ISSUE TITLE
Grouping and sorting in v.2

### ISSUE THREAD

**Issue by presianbg** [HenriWahl/Nagstamon#204]
Hi, 

First of all I want to thank you for the great work! Is there a way to group items by status and sort them by duration? In v.1 clicking on duration and then on status seems to do the trick, but this is not the case in V.2.

Thank you in advance.

**Comment by HenriWahl** [comment]
Nagstamon 1.0 is based on GTK2, Nagstamon 2.0 uses Qt5 - quite possible that tables behave differently then. Might need some investigation.

**Comment by presianbg** [comment]
Thank you. Looking forward for your solution :)

**Comment by presianbg** [comment]
In the latest git version it's fixed for hosts in DOWN state. Can you do the same for CRITICAL AND WARNING (Services and Hosts) ?

**Comment by HenriWahl** [comment]
What exactly do you mean? I am sorry but do not really understand... :-(

**Comment by presianbg** [comment]
![nagstamon-grouping-sorting](https://cloud.githubusercontent.com/assets/2163486/14957604/cfbc5ca4-108e-11e6-9c7a-4d71e0c631fa.png)
Check this screenshot. By clicking on Duration and then on Status makes it grouped by status and sorted by Duration. It was not working at all but now It's working only for HOST in Down state. Back in the old cliend (v1) it was working for all of them.

**Comment by HenriWahl** [comment]
Please check latest commit https://github.com/HenriWahl/Nagstamon/commit/4e4dec6ad77925d27d245ce13a19bed363bbc75c which hopefully kind of fixes this problem.

I will supply binaries as soon as possible.

**Comment by HenriWahl** [comment]
Now available as binary BETA 20160511 from https://nagstamon.ifw-dresden.de/nagstamon-20/

**Comment by HenriWahl** [comment]
Seems to be fixed,

**Comment by presianbg** [comment]
Sorry for my late response. It is fixed. Thanks.
