### ISSUE TITLE
Icinga2 Failure

### ISSUE THREAD

**Issue by MarcusCaepio** [HenriWahl/Nagstamon#205]
Tested the new GIT, seems Icinga2 is not working properly yet. 

![image](https://cloud.githubusercontent.com/assets/7324088/13419394/0ba98cce-df7e-11e5-8cda-3b98750313aa.png)

**Comment by HenriWahl** [comment]
Looks like some error coming from GUI.

**Comment by MarcusCaepio** [comment]
Seems it looks for any hosts with the "parent" parameter. But I don't have any parents defined yet. It's not compelling necessary

**Comment by HenriWahl** [comment]
'parent' is only used in GUI widgets, thus this is somehow misleading.

**Comment by MarcusCaepio** [comment]
Have this issue also with another Icinga2 Server.

**Comment by HenriWahl** [comment]
I found some problem in getting server version - .parent here is not GUI related, rather some parsing problem.

**Comment by HenriWahl** [comment]
Please check latest binaries from https://nagstamon.ifw-dresden.de/nagstamon-20/

**Comment by MarcusCaepio** [comment]
Still got this parent issue :(

**Comment by HenriWahl** [comment]
With the latest version? And no problems displayed? Which Icinga2 version do you use?

**Comment by MarcusCaepio** [comment]
Yes, with the latest Git Master. Just downloaded it.
I am using the latest versions:
`ii  icinga2                              2.4.3-1~ppa1~trusty1                amd64        host and network monitoring system
ii  icinga2-bin                          2.4.3-1~ppa1~trusty1                amd64        host and network monitoring system - daemon
ii  icinga2-common                       2.4.3-1~ppa1~trusty1                all          host and network monitoring system - common files
ii  icinga2-doc                          2.4.3-1~ppa1~trusty1                all          host and network monitoring system - documentation
ii  icinga2-ido-mysql                    2.4.3-1~ppa1~trusty1                amd64        host and network monitoring system - MySQL support
ii  libicinga2                           2.4.3-1~ppa1~trusty1                amd64        host and network monitoring system - internal libraries
ii  icingaweb2                           2.2.0-1~ppa1                        all          simple and responsive web interface for Icinga
ii  icingaweb2-common                    2.2.0-1~ppa1                        all          simple and responsive web interface for Icinga - common files
ii  icingaweb2-module-doc                2.2.0-1~ppa1                        all          simple and responsive web interface for Icinga - documentation module
ii  icingaweb2-module-monitoring         2.2.0-1~ppa1                        all          simple and responsive web interface for Icinga - monitoring module
`

**Comment by HenriWahl** [comment]
Please compare your local copy with https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/Servers/Icinga2.py - the lines 99 and 110 in your error dump seem to be different to the current master.

**Comment by MarcusCaepio** [comment]
I already downloaded the current master again and build it. Still appears....

**Comment by HenriWahl** [comment]
But the line numbers do not match - from which URL exactly did you get the master?

**Comment by MarcusCaepio** [comment]
https://github.com/HenriWahl/Nagstamon/archive/master.zip

**Comment by HenriWahl** [comment]
Sorry, cannot reproduce. I am sorry to ask but are you sure you do not accidently run an older version? Can you please check a binary version of the latest release?

**Comment by MarcusCaepio** [comment]
Henry, serious, how can I use an older version, when I click on "Download ZIP" in Master Branch? :D I tried the latest Version via build an via the .py file which opens the cmd. Do you have any parent Parameter in your icinga config?

**Comment by HenriWahl** [comment]
Of course this should be the master version but If I see the line numbers the error screenshot they do not match. Maybe some caching/proxy in between?
The parent crying comes from Beatifulsoup.
The Icinga2.py now became a IcingaWeb2.py because there might one day be a Icinga2API. See https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/Servers/IcingaWeb2.py. Do you get errors from IcingaWeb2.py?

**Comment by MarcusCaepio** [comment]
Hi Henry,
sorry for late response, I was ill a while.
I downloaded the latest 2.0-alpha-20160307 and still have trouble with the parent problem. :(

**Comment by HenriWahl** [comment]
What is the current error output on command line?

**Comment by MarcusCaepio** [comment]
I just realise, it's has been to long, that I workged with nagstamon....how do I run Nagstamon in Concsole, when I downloaded the alpha exe? I just have a Problem with psautils, so I cannot use the sources right now.... :(

**Comment by HenriWahl** [comment]
If you worked with sources before just install psutils via pi as described on https://nagstamon.ifw-dresden.de/nagstamon-20/

**Comment by MarcusCaepio** [comment]
Had to install visual studio again,.....now it works again....
![image](https://cloud.githubusercontent.com/assets/7324088/14247672/19bd85ba-fa70-11e5-8251-5ecdb9e156bb.png)

**Comment by MarcusCaepio** [comment]
OMG, I got it. The Icinga URL was wrong. Instead of  http://"Server"/authentication/login it has to be "Server"/icingaweb2/authentication/login So in my Nagsta Settings I have to type in http://"Server"/icingaweb2 to land on the correct Login Screen.

**Comment by HenriWahl** [comment]
Congratulation! This explains all the misunderstood error messages.

In general Nagstamon should catch and display such errors better.

**Comment by MarcusCaepio** [comment]
Thank you :dancer: 
But I noticed, that Nagstamon shows a wrong timestamp. It says on a fresh warning, that the last check was 2 hours ago.
![image](https://cloud.githubusercontent.com/assets/7324088/14271837/39ca4ce8-fafd-11e5-9a18-cbfd22e2c700.png)
Seems, that Nagsta is Using UTC timezone instead of CET

**Comment by HenriWahl** [comment]
This is issue https://github.com/HenriWahl/Nagstamon/issues/218 - not clear yet where the problem comes from. I assume IcingaWeb2 gives wrong information.

**Comment by MarcusCaepio** [comment]
The never ending Story with timestamps in icinga2 :(
Would you open an issue on dev.icinga.org for this?

**Comment by HenriWahl** [comment]
@simplexify already contacts the Icinga2 devs.

**Comment by MarcusCaepio** [comment]
:+1:

**Comment by lippser** [comment]
Hi all,

We deliver UTC timestamps and you call `datetime.datetime.utcfromtimestamp(...)`.

@MarcusCaepio Which never ending story are you referring to? ;)

Best regards,
Eric

**Comment by MarcusCaepio** [comment]
@lippser Meant it in a kindly way, because I had trouble with the timeperiods in the past releases for a long time, where also the timestamps had sth to do with it, if I remember right. :)  But that seemed to be fixed in the current release, so I was a little embittered, because there is sth. with the time, again :) :) :)
