### ISSUE TITLE
Icingaweb2 and JSON?

### ISSUE THREAD

**Issue by mzac** [HenriWahl/Nagstamon#209]
I was looking at the Icingaweb2 module and you say you use the HTML pages and parse them until API comes out (Rest I guess?)  Can't you use the json output that icingaweb2 produces?

For example:
https://icinga2/monitoring/list/hosts?host_problem=1&sort=host_severity&format=json

https://icinga2/monitoring/list/servicesservice_problem=1&sort=service_severity&dir=desc&format=json

**Comment by HenriWahl** [comment]
JSON is of course used for passive data retrieval. Only actions like Acknowledge cannot be done yet with Icinga2 API, only with IcingaWeb2. Even there Nagstamon only fires up a formular submit - just needs to parse the formular HTML to get a CSRF_Token.
