### ISSUE TITLE
v2.0-a20160302 Overtaking window focus

### ISSUE THREAD

**Issue by simisimis** [HenriWahl/Nagstamon#210]
If using other programs like terminal or browser while nagstamon window is open, it grabs window focus every few seconds. This only started after I installed v2.0-a20160302. Previous versions did not behave like that.

**Comment by HenriWahl** [comment]
There were some changes to support XFCE. Maybe they cause this behaviour. What is your desktop environment?

**Comment by simisimis** [comment]
oh sorry, initially I wrote it, but I accidentally left it out when moved sentences around.

I'm on OSX El Capitan.
I reverted back to 20160216 version for now and the problem did not reappear.

**Comment by HenriWahl** [comment]
This is good news as then the solution will be just apply those changes to Linux, not to OSX. I will inform you if there is anything ready to be tested.

**Comment by HenriWahl** [comment]
Please check latest binary https://nagstamon.ifw-dresden.de/files-nagstamon/unstable/Nagstamon-2.0a20160307.dmg

**Comment by simisimis** [comment]
Thanks for such a fast response. I do not have access from home to our
nagios servers, but will try it first thing tomorrow.
Thanks

**Comment by simisimis** [comment]
It did solve the problem. with 0307 windows do not lose focus to nagstamon anymore
