### ISSUE TITLE
Feature Req: Locally ignore/acknoledge problem hosts/services

### ISSUE THREAD

**Issue by varac** [HenriWahl/Nagstamon#211]
When working in a team, it is annoying to see problems on hosts that you cannot solve/do not want to solve, and wait for someone else to fix it. 
In this case, it would be great to have the option to ignore this problem, like an acknowledgement, but only locally so other ppl will still see it.

**Comment by HenriWahl** [comment]
This is what the filters are made for - not really convinced that this may be a good idea.

**Comment by varac** [comment]
Filters are too static. Also, when i have a certain service on a certain host, i cannot create a filter for this. The way filters work right now is that i can only make host or service filters, not combined (correct me if i'm wrong).

Because of this, a right click -> "Filter/Ignore this problem" would help immensely when working with a larger team that has different and dynamic responsbilities.
