### ISSUE TITLE
IcingaWeb2

### ISSUE THREAD

**Issue by TheUntouchable** [HenriWahl/Nagstamon#212]
First thanks a lot for this nice tool, there is no competitor out there!

In version 2.0 ALPHA-20160302 you added support for Icinga2 (icingaweb2). Using the version 2.0 ALPHA-20160307, I am not able to configure nagstamon to work with icingaweb2.

If I use "https://icinga.domain.de/" as proposed, I got a connection error.
If I use "https://icinga.domain.de/icingaweb2/", nagstamon quits itself and I am not able to start it anymore. It only shows an ok for a second and then quits itself again.

How can I provide you more information?

Thanks and best wishes,

Michael.

**Comment by HenriWahl** [comment]
You can enable debugging into a file in settings and/or run Nagstamon in a console window from sources to see any output.

Which OS do you run Nagstamon on?

**Comment by TheUntouchable** [comment]
From source is sadly no option as I am running it on windows.

But here is the logoutput after restarting nagstamon with "https://icinga.domain.de/":

DEBUG: 2016-03-14 10:29:12.845835 Icinga Produktiv Created server.
DEBUG: 2016-03-14 10:29:12.845835 Nagios Produktiv Created server.
DEBUG: 2016-03-14 10:29:13.092852 Icinga Produktiv FetchURL: https://icinga.domain.de/authentication/login CGI Data: None
DEBUG: 2016-03-14 10:29:13.121854 Nagios Produktiv FetchURL: http://nagios/nagios/cgi-bin/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2016-03-14 10:29:13.351868 Icinga Produktiv FetchURL: https://nagstamon.ifw-dresden.de/version/unstable CGI Data: None
DEBUG: 2016-03-14 10:29:14.255939 Icinga Produktiv FetchURL: https://icinga.domain.de/about CGI Data: None
ERROR: 2016-03-14 10:29:14.260938 Icinga Produktiv Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\IcingaWeb2.py", line 124, in _get_status
  File "C:\Nagstamon\Nagstamon\Servers\IcingaWeb2.py", line 114, in get_server_version
AttributeError: 'NoneType' object has no attribute 'parent'

**Comment by HenriWahl** [comment]
C:\Nagstamon comes from my binary creation machine.

Which Icinga server version do you run?

**Comment by TheUntouchable** [comment]
Icinga: r2.4.1-1
IcingaWeb2: 2.1.2

**Comment by TheUntouchable** [comment]
After an update to the following versions, the problem between icinga web and nagstamon seems to be fixed:
Icinga: r2.4.3-1
IcingaWeb2: 2.2.0

BUT, now nagstamon is unusable when opening and causing high cpu load. GUI is not responding and also it seems that it doesn't use the filters I configured because its showing all servers that are in maintenance.

**Comment by minibbjd** [comment]
https://icinga.domain.de/icingaweb2/ is the correct URL.

Seems like aboutsoup.find('dt', text='Version') in get_server_version returns None.

Could you post the HTML code for the URL https://icinga.domain.de/icingaweb2/about ?

Also, what is your default language setting in the IcingaWeb2 interface?

**Comment by TheUntouchable** [comment]
Here is the HTML code for the about page:
http://pastebin.com/S2ta1aGz

Default language is german.

If you need more information just tell me! :)

**Comment by minibbjd** [comment]
Seems like you have additonal CR/LFs in the HTML code. I'll trim that away.

**Comment by minibbjd** [comment]
If you have the source code version installed, please try the update IcingaWeb2.py file:

https://github.com/HenriWahl/Nagstamon/pull/214

If not, please test after the next binary release is available that includes this change.
