### ISSUE TITLE
Authetication problem Nagstamon 2.0

### ISSUE THREAD

**Issue by renraw** [HenriWahl/Nagstamon#213]
Hi, Im using and enjoying Nagstamon 1.0.1, but when I try to upgrade to v 2.0 I got the Authetication problem with the same configuration server. I got Nagios 3.5 with a URL like: https://nagios.nagios.com:30001/nagios/cgi-bin

**Comment by HenriWahl** [comment]
Can you provide some debug output? You can enable debugging in settings dialog.

**Comment by HenriWahl** [comment]
No reponse - maybe resolved?
