### ISSUE TITLE
Tray icon is not displayed if started too early

### ISSUE THREAD

**Issue by gtozzi** [HenriWahl/Nagstamon#215]
Hi again,

I think I have found one more issue.
I am auto-starting NagStaMon at login, in systray mode.
Sometimes, the tray icon does not appear, even if the process is regularly started and running in the background. When the icon should change/refresh (eg. when a service goes down), then the icon appears.

My hypothesis is that sometimes NagStaMon gets started before the system panel/tray so, when it starts, it tries to register the icon but it fails because there is yet no panel to register in.

I would like to try to troubleshoot/fix this, but I was unable to find the source file/line where NagStaMon is creating the system tray icon for the first time. Could you please give me an hint?

**Comment by HenriWahl** [comment]
Strange thing. What was your environment again?

systrayicon is created at https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/QUI/__init__.py#L5367

**Comment by gtozzi** [comment]
Thank you. I have some debug lines, let's see if i can hunt it down.
Environment is Linux/XFCE 4.12.

**Comment by HenriWahl** [comment]
Any news?

**Comment by gtozzi** [comment]
Not really, after b314fd1a12ec8e2b20160058521a6dc7df30fa21 it never happened again... but that code should not have changed any behavior

**Comment by HenriWahl** [comment]
Sounds pretty much like voodoo...
