### ISSUE TITLE
Issues using nagstamon under Wayland

### ISSUE THREAD

**Issue by bkurt78** [HenriWahl/Nagstamon#216]
I'm using the nagstamon that is packaged with Fedora 23 which is version 0.9.11-3.  Running with a standard X windows evironment in  Gnome 3 is no problem.  When I switch to Wayland I run into some issues.  When I click on the tray icon when there is an alert the pop up window that would normally pop up at the bottom pops up at the top and there isn't a good way to then close it or interact with it in general.  See screen shot for an example.
![screenshot from 2016-03-23 10-09-50](https://cloud.githubusercontent.com/assets/17072318/13987929/32fa1898-f0e0-11e5-93f7-f5db8cf44b3b.png)

**Comment by HenriWahl** [comment]
0.9.11 will receive no further development as the whole 1.0 branch which is considered legacy. Current work is going on on the 2.0 branch. Please get the master from GitHub or check the RPM file from https://nagstamon.ifw-dresden.de/nagstamon-20/

**Comment by bkurt78** [comment]
I just installed nagstamon 2.0a20160307-1 via the rpm package and it behaves the exact same way as reported with the 0.9.11 version in a Wayland session.

**Comment by HenriWahl** [comment]
OK so Wayland support will be another item at the never shrinking todo list... In theory the now used Qt5 should have native Wayland support, but I did not get deeper into this.

**Comment by bkurt78** [comment]
Understandable.  I will just continue to test out new builds as they come out.

**Comment by HenriWahl** [comment]
Latest experiments setting os.environ['QT_QPA_PLATFORM']='wayland' in nagstamon.py were more than discouraging... looked worse in Fedora 26 than even in 25. I fear there is still some way to go.

In general the different (safer) architecture of Wayland will make some features of Nagstamon unusable.

**Comment by varac** [comment]
Does this mean nagstamon won't support wayland ?

**Comment by HenriWahl** [comment]
@varac let's see it the other way: Wayland does not really support Nagstamon. As far as I understand the architecture of Wayland there is no support for self-positioning applications which makes parts of Nagstamon useless.

Maybe things got better meanwhile but when I looked at it the last time it was really unusable.

Running Nagstamon as X11-application on Wayland via XWayland kind of works - despite some quirks.

**Comment by varac** [comment]
> the architecture of Wayland there is no support for self-positioning applications which makes parts of Nagstamon useless.

What's meant by self-positioning here ? What makes nagstamon different from other tray icons ?

**Comment by HenriWahl** [comment]
Nagstamon uses a window for the status information. Size and position of the window have to be calculated depending on the amount of information. After calculation the window has to be displayed. As far as I found out Wayland won't allow an application to manipulate windows due to security reasons.
