### ISSUE TITLE
Nagstamon 2.0 floating bar just in one virtual desktop

### ISSUE THREAD

**Issue by Pelrauns** [HenriWahl/Nagstamon#217]
I'm in Ubuntu 10.15 and had to move to alpha release due to the problem with self signed certificates. Now the nagstamon floating bar (Qt based) shows in just one virtual desktop and not in the remaining three.

**Comment by HenriWahl** [comment]
Which alpha version are you running exactly? Which is your desktop environment? Unity? GNOME?

**Comment by Pelrauns** [comment]
Alpha version is 2.0-alpha-20160307 on Unity

**Comment by HenriWahl** [comment]
Ho many physical monitors (displays) do you use?

**Comment by Pelrauns** [comment]
I'm currently using two monitors. They are setup so that 2 monitors = 1 virtual screen.

**Comment by HenriWahl** [comment]
Can you check the latest commit https://github.com/HenriWahl/Nagstamon/commit/0b32e69c4a14db1a71950ec9ee8cbc060354237d from Github?

**Comment by Pelrauns** [comment]
Sure. I'll find a time slot this evening for that and will report here.

**Comment by Pelrauns** [comment]
I checked and still getting the same behavior. Floating bar is show in just one virtual desktop.

**Comment by HenriWahl** [comment]
Bad. I will test on Ubuntu as soon as possible.

**Comment by HenriWahl** [comment]
This is straight classical X or maybe some experimental Wayland?

**Comment by Pelrauns** [comment]
I'd bet on classical X. It's the default Ubuntu 15.10 installation and I didn't found any trace of Wayland or Mir on my system.

**Comment by HenriWahl** [comment]
Bad news: my Ubuntu in VirtualBox does not recognize multiple display.
Good news: I have the same problem like you on virutal desktops.

Did you have this problem with Nagstamon 1.0 too or is this somehting new?

**Comment by Pelrauns** [comment]
No It didn't. It's something entirely new. Actually I reverted to 1.0 and
modified some files with a temporary solution someone posted in a forum and
that fixed it for me. Of course I'm still willing to test the new version
for you providing you need it.

**Comment by HenriWahl** [comment]
The move to Qt5 might have caused this problem. It apparently only occurs with Unity - I even tested with the shiny new 16.04 release - still the same. Well, I myself do not see much room to fix this as Nagstamon already tells the window manager that it wants to stay on every desktop - which works in almost every other environment.

**Comment by Pelrauns** [comment]
That's curious. The feature is definitely there as I've got Thunderbird on
all desktops in one of my monitors. I think is the window manager who makes
the trick as it is a control you get right-clicking on the top bar of an
application window. Unfortunately I'm not a Linux development expert to
help you past that.

**Comment by HenriWahl** [comment]
Really strange because as already mentioned Nagstamon only uses the window manager to stick statusbar at all virtual desktops.
Maybe the used compiz has an option to keep a window at all workspaces? There is a tweak tool only for compiz - can you check if this would be a workaround?

**Comment by Pelrauns** [comment]
I'm away from home this weekend but I'll check on Monday and let you know.
Hopefully there's something like that.

**Comment by HenriWahl** [comment]
I see nothing I can do here anymore.
