### ISSUE TITLE
icingaweb2 events not converted to local time zone

### ISSUE THREAD

**Issue by simplexify** [HenriWahl/Nagstamon#218]
Hi

I've been test driving nagstamon in combination with the new icingaweb2 integration for about a week now and the experience so far is really good. Especially from a performance point of view, icingaweb2 scores much better than the legacy icinga status.cfg file approach.

Whilst we were running 2 instances of nagstamon in parallel: pulling data from icinga through the legacy status.cgi file vs. icingaweb2, we discovered that icingaweb2 reports the last state change in GMT, whilst icinga's legacy interface reports in local time.

**Icinga legacy status.cgi:**
`"last_state_change": "2016-03-30 16:57:13",`

**Icingaweb2:**
`"host_last_state_change":"1459349833"`
which translates to: Wed, 30 Mar 2016 14:57:13 GMT

I am in GMT+2, so both report the same time stamp, but in different time zones.

The effect of this is that the nagstamon instance that talks to the icingaweb2 interface incorrectly reports WARNING or CRITICAL events with an incorrect additional 2h of 'age'.

**Comment by HenriWahl** [comment]
Just a guess - isn't this to be configured at the Icinga2 server?

**Comment by simplexify** [comment]
For the avoidance of confusion: I'm talking about icinga**web**2, not icinga2

I've not been able to find any reference to setting the timezone for the json view specifically in icingaweb2. The only references I find are the php TZ setting, which is correctly set to Europe/Brussels.

Also, in the icingaweb2 regular html view, the time indications are reported in the correct TZ.

I'll double check with the icingaweb2 developers, but afaict,  the json view reporting in GMT (even with explicit mention of the GMT TZ) is deliberate.

**Comment by simplexify** [comment]
Question forwarded to the icinga developers:

https://dev.icinga.org/issues/11527

**Comment by lippser** [comment]
Hi all,

Please see #205 for my answer.

Best regards,
Eric

**Comment by simplexify** [comment]
Thank you for the quick answer @lippser

**Comment by simplexify** [comment]
@HenriWahl - do you have enough information to progress this or is there anything else we can do to assist in progressing this?

**Comment by HenriWahl** [comment]
Being occupied by work and GUI transformation I did not follow this further... but well, the proposed solution sounds interesting. I just wonder if there is anything to consider if time is converted locally. How will this behave in larger setups spanning over several timezones?

**Comment by HenriWahl** [comment]
The solution was already applied for a while, but the calculation of duration seems to brake time again - see https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/Servers/IcingaWeb2.py#L195

**Comment by simplexify** [comment]
No we are still seeing the duration in UTC, even with alpha-20160415

The functionality offered by datetime.utcfromtimestamp() also seems to be consistent with the observed behaviour that we reported: the UNIX time in the json output of icingaweb2 gets translated to a human readable UTC time:

> "host_last_state_change":"1459349833"
> which translates to: Wed, 30 Mar 2016 14:57:13 GMT

From looking at the python documentation, datetime.fromtimestamp() looks like what would be needed to show the time in the local TZ? See [1]

[1] - https://docs.python.org/2/library/datetime.html#datetime.datetime.fromtimestamp

**Comment by HenriWahl** [comment]
Sorry, i missed the small 'utc' there. Your are right, without it it should work as expected.

**Comment by simplexify** [comment]
I've just upgraded to 20160419, but I'm still getting the wrong time:

See screenshot:

<img width="314" alt="screen shot 2016-04-20 at 08 11 49" src="https://cloud.githubusercontent.com/assets/8797304/14664955/cd7a680a-06cf-11e6-8081-3816b4a5472b.png">

**Comment by HenriWahl** [comment]
It is not yet available as binary. If you need a binary - which platform do you run Nagstamon on?

**Comment by simplexify** [comment]
Ah sorry, I saw the update and falsely assumed it would contain this fix. My bad.

I run nagstamon on MacOS X.

**Comment by HenriWahl** [comment]
Please check if https://seafile.ifw-dresden.de/f/64a1ea7c5e/?raw=1 is of any help.

**Comment by simplexify** [comment]
solved! :+1: 

<img width="263" alt="screen shot 2016-04-20 at 14 27 55" src="https://cloud.githubusercontent.com/assets/8797304/14674359/3dba1dfc-0704-11e6-9f00-75f64265267e.png">

**Comment by HenriWahl** [comment]
OK. Great. My objection there might be a problem with timezones is not valid neither, as the duration calculation only is made with 2 values from the same zone so any difference is leveled.
