### ISSUE TITLE
tray icon: no menu

### ISSUE THREAD

**Issue by lr1980** [HenriWahl/Nagstamon#220]
after i switched to tray icon mode i cannot change it back because i see no way to access the (settings) menu!?

**Comment by HenriWahl** [comment]
Which OS and maybe desktop environment are you using?

**Comment by lr1980** [comment]
sorry.... MacOS 10.11.4

**Comment by lr1980** [comment]
it is only when the status is green. when it's yellow or red then i can click on the tray icon and i see the list and i can use the menu. without the status list i see no way to get a menu (left or right mouse click on the tray icon)

**Comment by HenriWahl** [comment]
Any relation to issue #215?

**Comment by HenriWahl** [comment]
Sorry... now I understand. The icon exists but no menu. Yes, this is apperently still missing in MacOSX. Short solution is to provoke some state of failing host/service... :-)

**Comment by HenriWahl** [comment]
Fixed in https://github.com/HenriWahl/Nagstamon/commit/da927d59d553ce457afe1b5f47d4506021163a6e

**Comment by HenriWahl** [comment]
Try https://seafile.ifw-dresden.de/f/64a1ea7c5e/?raw=1 to check if it is better now. When OK click on the tray icon will raise the menu.

**Comment by lr1980** [comment]
it works! thx!
