### ISSUE TITLE
[feature ]windows size 

### ISSUE THREAD

**Issue by golimer** [HenriWahl/Nagstamon#224]
Please make possibility to change windows size, cause at this moment in full screen

**Comment by HenriWahl** [comment]
Do you mean whole screen width or real fullscreen?

**Comment by golimer** [comment]
"Status information" taking too much space in screen (preview attached)
http://postimg.org/image/uelbykh5j/

**Comment by HenriWahl** [comment]
Ok. This automaitc-shrinking-feature is on the todo list.

**Comment by golimer** [comment]
Great Thanks!!!

**Comment by HenriWahl** [comment]
Done. Please check https://nagstamon.ifw-dresden.de/nagstamon-20/.
