### ISSUE TITLE
[bug] - strings passwd to browser aren't quoted

### ISSUE THREAD

**Issue by theundefined** [HenriWahl/Nagstamon#225]
passing string as parameter for url should be quoted.

**Comment by theundefined** [comment]
`index 0c43c30..492629d 100644
--- a/Nagstamon/Nagstamon/Actions.py
+++ b/Nagstamon/Nagstamon/Actions.py
@@ -657,7 +657,7 @@ class Action(threading.Thread):
                         }
             # mapping mapping
             for i in mapping:
-                string = string.replace(i, mapping[i])
+                string = string.replace(i, urllib.quote_plus(mapping[i]))
 
             # see what action to take
             if action_type == "browser":
`

**Comment by HenriWahl** [comment]
Your browser should treat the URL correctly - when testing .quote_plus I only got errors due to two times quoted URLs.

**Comment by theundefined** [comment]
i'm using chromium. i don't think that it's problem of browser. Problem is with $STATUS-INFO$ data when from nagios is passed for example % character. If you have error due to two times quoting - what quote it second time? I don't see any mechanism which do it.

**Comment by HenriWahl** [comment]
OK then it might be enough to quote $STATUS-INFO$ but leave the others as they are because event the http:// got quoted which lead to a complete mess. I will check this.

**Comment by HenriWahl** [comment]
Please test it with master and look at https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/QUI/__init__.py#L3504 and the following lines where the string already gets quoted.
