### ISSUE TITLE
no hover if displayed as tray icon

### ISSUE THREAD

**Issue by origpumu** [HenriWahl/Nagstamon#228]
If I use the option to display nagstamon as tray icon, I'm not able to get the status list. 

Description: Ubuntu 16.04 LTS
Release: 16.04
Codename: xenial
Nagstamon 2.0-alpha-20160419

**Comment by HenriWahl** [comment]
Due to Ubuntu's great Unity.... things are complicated. Do you see some systray icon? How do you try to get the status overview?

**Comment by HenriWahl** [comment]
Please check https://github.com/HenriWahl/Nagstamon/issues/152 there is some systray indicator plugin mentioned.

**Comment by Brettdah** [comment]
As said in the #152 for the systray it's only for needed for stable version
For the V2 the right click and left click are the same :'( can't get the status bar details popup; just the right click menu :'(

**Comment by origpumu** [comment]
@HenriWahl , 
- settings to systray icon
- tried to change the statusbar setting from click to hover
Trayicon is visible but only the contextmenu will open on click.
@Brettdah ,
Is there a way to use a double click? behavior: open the overview after double clicking the tray icon, closing by the "x"-button is okay. no hover-out-close needed (by me). :)

**Comment by HenriWahl** [comment]
Ok thanks I will look into this.

**Comment by HenriWahl** [comment]
Please see https://github.com/HenriWahl/Nagstamon/issues/152#issuecomment-214968220

**Comment by HenriWahl** [comment]
I now added a "Show status window" menu entry to systray menu - I think this is the best we can get here.

**Comment by HenriWahl** [comment]
Please check latest 20160427 binary from https://nagstamon.ifw-dresden.de/nagstamon-20/

**Comment by origpumu** [comment]
Smart solution. Thank You!
