### ISSUE TITLE
Statusbar only on fixed VirtualDesktop

### ISSUE THREAD

**Issue by shadowhaze** [HenriWahl/Nagstamon#229]
Hi,

I have the problem that the status bar, the program was only open on the Virtual Desktop opens on and not on my current virtual desktop.

Nagstamon Version: 2.0a-20160427

Settings:
    Statusbar display size: Long
    Appearance: Icon in Systray
    Statusbar details popup: Popup / close on click

OS:
   System Version: OS X 10.11.4 (15E65)
   Kernel Version: Darwin 15.4.0

BR, J

**Comment by HenriWahl** [comment]
Did it work as expected before or is this a new bug? You mean 1 physical screen with several virtual desktops?

**Comment by shadowhaze** [comment]
Hi, 

yes i mean 1 physical screen with several virtual desktops. 
I this and last Nagstamon 2.0a exist this problem/bug in other version i didn't try, sorry.

**Comment by HenriWahl** [comment]
I fear there is no real solution. Other apps allow to have their windows by rightclicking on their dock icon, but this menu does not exist in this case.
A workaround is to use Nagstamon as system tray icon on top - to be configured in Settings/Display.

**Comment by HenriWahl** [comment]
If no Apple Genius has an idea there is no other fix than using systray icon.

**Comment by soxwellfb** [comment]
I've figured how to get to Nagstamon assign to different spaces in OS X by right clicking on the doc icon.

In the info.plist, add value to the CFBundleIdentifier key.

ie:
```
        <key>CFBundleIdentifier</key>
        <string>Nagstamon</string>
```

Seems to work.

**Comment by soxwellfb** [comment]
Upon inspection of all the other apps on my system, the string should probably be:
```
        <key>CFBundleIdentifier</key>
        <string>de.ifw-dresden.nagstamon</string>
```
And here's the developer doc: https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102070
