### ISSUE TITLE
Downtime on Centreon

### ISSUE THREAD

**Issue by RymRabehi** [HenriWahl/Nagstamon#230]
Hello,

I'm testing Nagstamon 2 with Centreon and I figured out that when you try to set a downtime on a service or a host, you can't choose the time for the start and the end of the downtime. This functionnality was available on Nagstamon 1. Is it an oversight or did you choose to remove it?

Thanks.
Best regards.

**Comment by HenriWahl** [comment]
I did not touch anything there willingly - still has to be reviewed, especially the Centron 2.7 compatibility (or whatever new version it is).

**Comment by benoiteolas** [comment]
Ok, we just saw, it was already broken in Nagstamon 1.0 ^.^ (that's why we disabled the downtime entry in our version).

We will fix it for Nagstamon 2.

**Comment by HenriWahl** [comment]
Great news. I and even more the Centreon users out there await your pull request. :-)

**Comment by benoiteolas** [comment]
This bug can be closed as it's fixed push https://github.com/HenriWahl/Nagstamon/pull/251
