### ISSUE TITLE
CheckMK: KeyError 'host_notifications_enabled'

### ISSUE THREAD

**Issue by tyhawk** [HenriWahl/Nagstamon#231]
As of version 2.0-alpha-20160527, all CheckMK hosts I have in my Nagstamon return the error

> KeyError 'host_notifications_enabled'

This could possibly be caused by the fix for issue #132 (which was for a CheckMK issue).
OS: OS X El Capitan 10.11.4

**Comment by HenriWahl** [comment]
Thanks for reporting! Apparently this value is not sent in every version of Check_MK - should be fixable. What version of Check_MK do you run?

**Comment by ootada** [comment]
same for 2.0-alpha-20160527-win64
check_mk version 1.2.4p5

**Comment by golimer** [comment]
Hello 

same problem

**Comment by golimer** [comment]
solution how to fix?

**Comment by HenriWahl** [comment]
Fixed right now in latest commit - I did not expect the notifications_enabled flag not being used by older Check_MK installations.

**Comment by golimer** [comment]
hmm can you add in website compiled version? :)

**Comment by HenriWahl** [comment]
Planned for today - stay tuned.

**Comment by HenriWahl** [comment]
Check https://nagstamon.ifw-dresden.de/nagstamon-20/ - it's there now.
