### ISSUE TITLE
Crashing periodically on Ubuntu Mate (14.10)

### ISSUE THREAD

**Issue by jpptinsley** [HenriWahl/Nagstamon#233]
How do I put in into debug mode / where can I find debug reports?

**Comment by HenriWahl** [comment]
Please check settings dialog, at the first tab there is a debug option.

**Comment by jpptinsley** [comment]
Found it. I'll post a new issue if I find any useful bug reports. Thanks!

**Comment by HenriWahl** [comment]
Otherwise consider an update? Isn't there Ubuntu 16.04 already?
