### ISSUE TITLE
Nagstamon2: tray icon not updated when switching servers

### ISSUE THREAD

**Issue by cverbiest** [HenriWahl/Nagstamon#234]
I have 2 servers configured in settings. 
When I deactivate server 1 and activate server 2 the Nagstamon tray icon remains green .

Server 1 is on a different unreachable network 
There are critical alerts on server 2.

Exiting and restarting Nagstaomn solved the issue

alpha-20160415

**Comment by HenriWahl** [comment]
I will investigate this issue.

**Comment by HenriWahl** [comment]
What OS are you using Nagstamon at?

**Comment by cverbiest** [comment]
Using windows 8.1
