### ISSUE TITLE
Enhancement request: enable/disable servers based on current network connection

### ISSUE THREAD

**Issue by cverbiest** [HenriWahl/Nagstamon#235]
I have Nagstamon running on my windows laptop.
When I go on site to a customers office I have to enable the server for that customer and disable the previous one.

It would be nice of servers could be enabled/disabled based on current network settings like dns server, domain name, ... 
I don't know what is feasible but I'm thinking about regex matching with some of the parameters below 

   Connection-specific DNS Suffix  .
   Link-local IPv6 Address . . . . .
   IPv4 Address. . . . . . . . . . .
   Subnet Mask . . . . . . . . . . .
   Default Gateway . . . . . . . . .

**Comment by HenriWahl** [comment]
Sounds like a pretty special requirement. Why not simple enable/disable the servers?

**Comment by cverbiest** [comment]
I currently enable/disable the servers. It would be nice if there was an easier, or even an automatic, way to do it. I agree automatic may be too farfetched

A button to enable/disabled a server without having to open the server settings dialog and check/uncheck the enabled box would be nice though.

An alternative way could be an option to specify a configuration on the command line. I could use that to load different configurations depending on the network I'm on.

**Comment by HenriWahl** [comment]
This option already exists - just give the desired configuration directory. If it does not exist yet it will be created.
