### ISSUE TITLE
OP5 and Nagstamon schedule downtime not correct

### ISSUE THREAD

**Issue by AukeH1984** [HenriWahl/Nagstamon#237]
When scheduling a host in OP5 in downtime the services also are being put in downtime.
Unfortunally Nagstamon doest reconize this, so when the host goes down Nagstamon keeps notifying that the services are down. (All filters are set correctly) This issue is present in all versions of Nagstamon (also the stable release).

http://oi68.tinypic.com/msioty.jpg
http://oi68.tinypic.com/wvoevm.jpg

Running Nagstamon on Windows 10 against OP5 v7.2.0

**Comment by chelmertz** [comment]
Some more information on this:

op5 Monitor's native GUI presents a service as being in downtime if itself or its host is in downtime. op5 Monitor's HTTP API exposes both of these values but the Nagstamon implementation does not take the downtime of a service's host into account, see here: https://github.com/HenriWahl/Nagstamon/blob/794fca6/Nagstamon/Servers/op5Monitor.py#L213

I would think this could fix it:

    #current:
    n["scheduled_downtime"] = 1 if api['scheduled_downtime_depth'] else 0
    #wanted:
    n["scheduled_downtime"] = 1 if api['scheduled_downtime_depth'] or api['host']['scheduled_downtime_depth'] else 0

Note that I haven't tested this.

// Calle from op5 (who submitted some patches for Nagstamon some time ago, but is not actively involved)

**Comment by TestingUser1432** [comment]
Some additional comment: In previous versions of OP5 it worked fine. But from the update of begin April 2016 something went broken.

**Comment by AukeH1984** [comment]
In my environment it never worked properly..

**Comment by chelmertz** [comment]
I just installed Nagstamon 1.0.1 and the following diff fixes the issue:

```
@@ -93,6 +93,7 @@
     api_svc_col.append('host.name')
     api_svc_col.append('host.state')
     api_svc_col.append('host.active_checks_enabled')
+    api_svc_col.append('host.scheduled_downtime_depth')
     api_svc_col.append('is_flapping')
     api_svc_col.append('last_check')
     api_svc_col.append('last_state_change')
@@ -217,7 +218,7 @@
                     n["flapping"] = api['is_flapping']
                     n["notifications_disabled"] = 0 if api['notifications_enabled'] else 1
                     n["passiveonly"] = 0 if api['active_checks_enabled'] else 1
-                    n["scheduled_downtime"] = 1 if api['scheduled_downtime_depth'] else 0
+                    n["scheduled_downtime"] = 1 if api['scheduled_downtime_depth'] or api['host']['scheduled_downtime_depth'] else 0
                     n['attempt'] = "%s/%s" % (str(api['current_attempt']), str(api['max_check_attempts']))
                     n['duration'] = human_duration(api['last_state_change'])
                     n['last_check'] = datetime.fromtimestamp(int(api['last_check'])).strftime('%Y-%m-%d %H:%M:%S')
```

@HenriWahl do you accept PR to any specific branches? The current master (4e4dec6) looks very much like WIP. I'm not sure if you are planning on doing any backport releases or such, but anyways, there's the fix for you.

@AukeH1984 and @TestingUser1432: you should be able to confirm that the patch works (on my Fedora system, the file to patch is /usr/lib/python2.7/site-packages/Nagstamon/Server/op5Monitor.py for Nagstamon 1.0.1).

**Comment by HenriWahl** [comment]
I only work on the 2.0 master branch. Still a moving target but pretty much progress achieved already. I do not want to touch the 1.0 legacy branch anymore as the whole Python2/GTK2 thing is a dead end. So if you do a pull request I will merge it soon into master.

**Comment by AukeH1984** [comment]
@HenriWahl cant wait to see this issue fixed! :+1:

**Comment by TestingUser1432** [comment]
@chelmertz thanks for the fix, but I am unable to test it. I am running it on Windows clients.

**Comment by HenriWahl** [comment]
Binaries might come tomorrow,

**Comment by HenriWahl** [comment]
Latest BETA 20160513 binaries available now: https://nagstamon.ifw-dresden.de/nagstamon-20/

**Comment by TestingUser1432** [comment]
@HenriWahl : Thanks. I installed it and will test it.

**Comment by TestingUser1432** [comment]
Yes. Issue fixed.
Thanks Henri!

**Comment by HenriWahl** [comment]
Thanks to @chelmertz! :-)

**Comment by AukeH1984** [comment]
Awesome!!!!!!

**Comment by HenriWahl** [comment]
Please contact @chelmertz

**Comment by AukeH1984** [comment]
@chelmertz please help? @HenriWahl can you reopen this issue?

**Comment by chelmertz** [comment]
I can test the newly built binaries but I am in the middle of a scrum sprint at work so ... give me a week? :)

**Comment by AukeH1984** [comment]
@chelmertz any news?

**Comment by HenriWahl** [comment]
@chelmertz any news?

**Comment by HenriWahl** [comment]
Again: @chelmertz @AukeH1984 any news? Or summer vacation? :-)

**Comment by AukeH1984** [comment]
@HenriWahl Unfortunately no... Still no response from @chelmertz

**Comment by HenriWahl** [comment]
@AukeH1984 does this mean the situation is still the same none-working one?

**Comment by AukeH1984** [comment]
@HenriWahl Yes :-1:

**Comment by chelmertz** [comment]
@HenriWahl, @AukeH1984 

Hi again, sorry for being so AFK.

So, I tried to reproduce this with your latest binary for Fedora 24. Let me see if I got the steps to reproduce correctly:
- register a server in Nagstamon, make sure it connects correctly etc etc
- create a host & a service, disable active checking on both of them, just to make sure their statuses are static
- set host to down, service to critical (I later tested with host = up + scheduled downtime, see second screenshot)
- mark host as in scheduled downtime, make sure it ends far in the future
- filter for the host or service name to find it easier in Nagstamon's service listing
- make sure the statuses are refreshed

I put some debug code around the code which was patched the last time, and the service is getting "in_scheduled_downtime" = 1 from the host, even if the service is not itself in downtime. So far so good. I'm afraid I'm not too used with the Nagstamon GUI to determine the result of my research, so could you do it for me? :)

Here are two screenshots: https://imgur.com/a/Fwqkf

**Comment by HenriWahl** [comment]
Hi @chelmertz @AukeH1984,
as far as I understand the images, the setting and the displayed result is as expected - service in downtime if host is too. As required in the original post here.
@AukeH1984: which version of Nagstamon did you test last?

**Comment by AukeH1984** [comment]
Hmm, just installed the latest OP5 release (7.2.8) and the Nagstamon-2.0-beta-20160825 build, now the problem is gone! :+1:
