### ISSUE TITLE
App indicator option is gone

### ISSUE THREAD

**Issue by jwhipp** [HenriWahl/Nagstamon#238]
Just downloaded the 20160429 2.0 DEB and installed on 16.04 LTS and I am not seeing the app indicator option for display as I have in previous releases under display in settings.   

I tested this using a fresh install of Nagstamon, no existing cache/config data present.

**Comment by HenriWahl** [comment]
It was a dirty thing in 1.0 already but now seemed inpossible to be implemented. But the systray icon behaves like the former AppIndicator thingy now.

**Comment by jwhipp** [comment]
Ok that worked, I turned on Systray and it's an app indicator now.
