### ISSUE TITLE
Popup: Allow for sizing adjustments

### ISSUE THREAD

**Issue by jwhipp** [HenriWahl/Nagstamon#239]
This is a request to allow the popup to be re-sized based on a grabber in the window or re-size cursor.  In 1.0, the window would resize based on how much stuff was being displayed, in 2.0, it appears to be fixed with a scroll bar.   Could we get an option to make this window adjustable or have an auto re-size with a maximum?

**Comment by HenriWahl** [comment]
Please check latest BETA which resizes like the 1.0 version.

**Comment by jwhipp** [comment]
I'm on 2.0-beta-20160429 and it is not auto resizing nor is there a grabber/cursor to expand it

Is there a different build you'd like me to try?

**Comment by HenriWahl** [comment]
No there is no grabber but same behaviour as in 1.0 to use only needed space.

**Comment by jwhipp** [comment]
Yeah it's definitely not resizing in 2.0-beta-20160429.

**Comment by HenriWahl** [comment]
Can you provide me a screenshot?

**Comment by jwhipp** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/556332/15127833/a3a49200-15f5-11e6-85a6-59e40d1b00b6.png)

You can see the bottom one is cut off, I can mouse scroll down to see it all the way which cuts off the top entry completely. 

Not a huge deal, I just noticed it because I am used to the behavior of 1.0.1.

**Comment by HenriWahl** [comment]
This is not intended... What OS or desktop environment is this?

**Comment by jwhipp** [comment]
Ubuntu 16.04 with Unity.  I noticed that 2.0 handles the GTK theme better, could there be something with the GTK3 theme I am using?

**Comment by HenriWahl** [comment]
Looks like non-default... I do not know of such a problem but you might try with the default. Which one are you currently using?

**Comment by jwhipp** [comment]
https://github.com/xyl0n/iris

Looks like that was it, here is the same data with Ambiance which is the default theme:
![selection_004](https://cloud.githubusercontent.com/assets/556332/15128237/e217fffc-15f7-11e6-967f-97259c45ff01.png)

**Comment by jwhipp** [comment]
Also just tried with Arc (https://github.com/horst3180/arc-theme), same thing, works fine.  So it was theme specific. :+1:

**Comment by HenriWahl** [comment]
Good to know but I have no idea of an explanation of this.
