### ISSUE TITLE
Systray icon in Ubuntu 14.04 Unity in upper left corner of screen

### ISSUE THREAD

**Issue by madaxel** [HenriWahl/Nagstamon#245]
Using Nagstamon 2.0beta 20160511 and earlier on Ubuntu 14.04 displays the systray icon in the upper left corner of the screen.
I would expect it in the upper right corner near the other AppIndicators.

Python 3.4.3

**Comment by HenriWahl** [comment]
Surely one would expect the systray icons with the others but this is nothing I can reproduce. I tested with Ubuntu versions from 14.04 to 16.04 and this never happened - might be a local problem.
Anyway why not upgrade to 16.04?

**Comment by madaxel** [comment]
FYI: this is a QT5 Ubuntu problem.
See https://bugs.launchpad.net/sni-qt/+bug/1209106

I installed a fresh VirtualBox with latest Ubuntu 14.04 images and the problem exists there. Anyway I'll check upgrading to 16.04 next days. 

Thanks for your fast answer, and keep up the good work.

**Comment by valterhenrique** [comment]
I'm also having the same problem. I just installed the latest version 2.0, and my icon is on the left side. 
![screenshot from 2016-09-06 10 31 10](https://cloud.githubusercontent.com/assets/3298422/18266936/31e1b072-741d-11e6-8758-e6d5f1261827.png)
](url)

**Comment by HenriWahl** [comment]
@valterhenrique which verson of Ubuntu do you use? I only tested with 16.04 (which should be used anyway as being the latest) and I am not able to support older versions.

**Comment by valterhenrique** [comment]
@HenriWahl I'm using 14.10.

**Comment by madaxel** [comment]
@valterhenrique might be the same problem as in 14.04. See Comment on May 16

**Comment by valterhenrique** [comment]
@madaxel Oh, I see. Thanks a lot for the feedback! Unfortunately, I can't upgrade my OS version at the office :( . But soon, soon! o/
