### ISSUE TITLE
Feature request: ack/downtime multiple issues at once

### ISSUE THREAD

**Issue by oernii** [HenriWahl/Nagstamon#247]
It would be great if nagstamon allowed multiselection and action on the selected issues.

**Comment by HenriWahl** [comment]
Already somewhere at the todo list...

**Comment by oernii** [comment]
I've thought so too, as we talked about this few years back, but haven't seen it on the todo :(

**Comment by HenriWahl** [comment]
Please check latest testing version from https://nagstamon.ifw-dresden.de/download/#testing.
