### ISSUE TITLE
Feature request: keyboard only operation

### ISSUE THREAD

**Issue by oernii** [HenriWahl/Nagstamon#248]
It would be great if the nagstamon main window could be opened with a keyboard shortcut and if issues could be ackd/downtimed with keyboard

**Comment by HenriWahl** [comment]
Nagstamon does not always have keyboard focus when being hovered by mouse. A shortcut for opening it would need deeper OS integretion - needs investigation.

**Comment by oernii** [comment]
I think this could be done in 2 steps:
1) os global shortcut could be done via any display manger just by running nagstamon again or with a command line attribute. The main window would open. I unsuccessfuly tried this approach via multiprocessing.connection, but failed on on threads.
2) the in-app shortcuts shouldn't be difficult, the cursor movement might though.

**Comment by HenriWahl** [comment]
Nagstamon uses QThreads for any thready/multiprocessy stuff to avoid trouble with Qt5.
