### ISSUE TITLE
Nagstamon tray icon not getting green

### ISSUE THREAD

**Issue by AukeH1984** [HenriWahl/Nagstamon#250]
When there are no problems the trayicon wont turn green. Also it is not left clickable when there are no problems. Using OP5 7.2.1 monitoring

**Comment by HenriWahl** [comment]
Which version do you refer to? And which OS?

**Comment by AukeH1984** [comment]
Windows 10 and on Windows 2008 as OS where nagstamon is running on

**Comment by HenriWahl** [comment]
What color does it have in case there are no problems?

**Comment by AukeH1984** [comment]
Red! All settings are correct! So it stays non-blinking red!

**Comment by HenriWahl** [comment]
Sorry... couldn not reproduce... becomes nicely green here if no alarm exists. The left-clickability makes less sense as there is nothing to show in case of green - but maybe just show context menu instead as already the case in OSX.

**Comment by HenriWahl** [comment]
Commit https://github.com/HenriWahl/Nagstamon/commit/415057d3e3aa3667960c7029f0bcb728ee040a11 has showing menu when left click on OK systray.

**Comment by HenriWahl** [comment]
Can you provide a screenshot for comparison of monitor server and nagstamon state?

**Comment by AukeH1984** [comment]
http://i66.tinypic.com/jk9c2g.png
http://i63.tinypic.com/2qx9coo.png

As you can see, no unhandeld problems on hosts and services, still icon is red. With the 1.0.1 all works fine. Left clicking when the icon is in this state (with nog problems in OP5) is not possible, only right click

**Comment by HenriWahl** [comment]
I am really sorry but the icon i see in your second screenshot is GREEN.

**Comment by MaikL** [comment]
Hello AukeH1984,
in the second screenshot I can only see a green nagstamon symbol, so where exactly is your problem?

**Comment by AukeH1984** [comment]
Ok please close and delete, i need to be ashamed right now... :-)
