### ISSUE TITLE
green icon flashing on latest beta (2016-05-13) 

### ISSUE THREAD

**Issue by danypd69** [HenriWahl/Nagstamon#252]
I am using nagstamon on windows with zabbix 3, this morning I found the status icon green and flashing.
There are currently no alerts and there is no way to stop the flashing.
Checking the triggers history on zabbix server I see that tonight there has been a temporary event (too many processes running)

**Comment by HenriWahl** [comment]
This sounds funny - I will check this.

**Comment by HenriWahl** [comment]
I tried to reproduce this but had no luck - can you reproduce this?

**Comment by danypd69** [comment]
I am using nagstamon on windows 10.
Yes I can try to reproduce the problem, is there a way to create a debug log that I can send to you?

**Comment by HenriWahl** [comment]
You can enable debugging in settings' first tab but I fear this is not covered by debugging.

**Comment by danypd69** [comment]
Ok so what should I do if I'm able to reproduce the problem?

**Comment by HenriWahl** [comment]
Tell me how to achieve it :-)

**Comment by danypd69** [comment]
Ok I reproduced it:
1) connected to one of the monitored server
2) swapoff -a to trigger the lack of swap condition
3) wait yellow icon flashing on nagstamon
4) swapon -a
5) icon turns green again but continues to flash

between 3 and 5 I did not click the icon on nagstamon

**Comment by HenriWahl** [comment]
Do you have any filters applied? Even in Windows 10 I only get a green non-blinking icon after the trouble condition is gone,

**Comment by danypd69** [comment]
no, I don't have any filter set.
I will try to reset all the settings.

**Comment by danypd69** [comment]
Ok tried, I still have the same problem after removing nagstamon.conf

**Comment by HenriWahl** [comment]
Now I at least achieved it. Zabbix is the key. No ideay why yet but one step closer...

**Comment by HenriWahl** [comment]
OK... one reason for this effect is the fact,. that Zabbix shows even the OK hosts/services, which confuses Nagstamon's tracking of new/known problems. This is easy to fix - just ignore the OK ones. But I also have a "Zabbix server" "UNKNOWN" problem on the list... but not shown any UNKNOWN problem. So my question is: does Nagstamon display any UNKNOWN Zabbix problems at all?

**Comment by HenriWahl** [comment]
I think I got it. If you are able to run Nagstamon from Python source you can test it now - otherwise expect binaries soon.

**Comment by danypd69** [comment]
Great! I will wait for the binaries.
Thanks

**Comment by HenriWahl** [comment]
Out now.

**Comment by danypd69** [comment]
Tested, works well :+1:
