### ISSUE TITLE
Update interval field too short

### ISSUE THREAD

**Issue by benoiteolas** [HenriWahl/Nagstamon#254]
Hello,

Is it possible to set the update interval field on 3 digits ? (in the Servers config page)

Because i would like to use a 120 seconds interval and it's currently not possible.

Regards.

**Comment by HenriWahl** [comment]
Done in commit dc678ba5401057f7daa436a32bf4d6c716de4c4a. Will be in next binary.

**Comment by HenriWahl** [comment]
Sorry, forgot some - now in 0654d7f92ca75b4ba3155b811b30dfb940bca92c

**Comment by benoiteolas** [comment]
already tested, working fine.
thanks !
