### ISSUE TITLE
Fix Opsview 5.x Compatibility

### ISSUE THREAD

**Issue by pauldsmyth** [HenriWahl/Nagstamon#256]
Hi Believe that the Opsview people have been in touch with you and I keep hearing rumours that REST api for Opsview 5 will be in the "next release". I've tried the latest code from git for version 1 and the latest version 2 beta and it's clearly not there. Any news when this will be added?

**Comment by HenriWahl** [comment]
Most probably you refer to https://github.com/HenriWahl/Nagstamon/pull/166 - yes, just needs to be put into Python3. If it works it will go into the final stable 2.0. Any volunteers? :-)

**Comment by duncs** [comment]
FYI I compiled an EXE from the patch I did and make it available via https://www.opsview.com/comment/15556#comment-15556.  FYI the Rest API has been in Opsview for a very long time - I just amended Nagstamon to work with it.

  Duncs

**Comment by HenriWahl** [comment]
Thanks! I will port this as soon as possible.

**Comment by pauldsmyth** [comment]
@HenriWahl  yes that's the issue. 

@duncs The exe would be great but I'm an Ubuntu Desktop toting sysadmin :-(

**Comment by duncs** [comment]
In which case you should be able to just check it out from the repo and build/use it from there :)  That is how I did the dev/testing anyhow.

**Comment by duncs** [comment]
Until Henri has the time to get the changes in, anyhow...

**Comment by pauldsmyth** [comment]
I've done so and can confirm it's working, thanks

**Comment by HenriWahl** [comment]
Right now I added a temporary Opsview5.py in commit cde3e4ccc5740d19b113d5a379b2efd1cb71c4c1, where I made all changes necessary to work with Python3 and some things I changed meanwhile. I am not able to test if it works - still no Opsview VM. @duncs, can you take it and check if it can replace Opsview.py? If you need help to set up a working Python3+Qt5 environment - there are some infos at https://nagstamon.ifw-dresden.de/nagstamon-20/.

**Comment by HenriWahl** [comment]
Commit a87a577f0e42b0a84e394c6ed262ebe837199bb7 contains the full port of Opsview.py to Python3. Expect binaries soon or check form source meanwhile.

**Comment by HenriWahl** [comment]
Binaries are out now at https://nagstamon.ifw-dresden.de/nagstamon-20/

**Comment by pauldsmyth** [comment]
Tested Ubuntu 64bit working perfectly
