### ISSUE TITLE
crash on acknowledge

### ISSUE THREAD

**Issue by simplexify** [HenriWahl/Nagstamon#257]
I've just upgraded to beta 20160527 and now nagstamon crashes when I acknowledge a critical service check.

I'm on mac os x and am using nagstamon in combination with icingaweb2.

On 20160524 I did not have this issue.

Let me know how I can provide more detailed debug information if needed.

**Comment by HenriWahl** [comment]
Thanks for the hint. I found the solution and will provide binaries soon.

**Comment by varac** [comment]
same here with 2.0-beta-20160527:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 5388, in ok
    'author': self.server.username,
AttributeError: 'NoneType' object has no attribute 'username'
[1]    8091 abort      nagstamon

```

**Comment by HenriWahl** [comment]
Please check the 20160530 binaries available now.

**Comment by simplexify** [comment]
fixed!

many thanks
