### ISSUE TITLE
Nagstamon 2.0 is silent

### ISSUE THREAD

**Issue by phaoost** [HenriWahl/Nagstamon#262]
Hello,

I am not getting any sounds in recent version of nagstamon:

~$ nagstamon 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Config.py", line 599, in KeyringAvailable
    import secretstorage
ImportError: No module named 'secretstorage'
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
GStreamer; Unable to play - "file:///usr/lib/python3/dist-packages/Nagstamon/resources/critical.wav"
GStreamer; Unable to play - "file:///usr/lib/python3/dist-packages/Nagstamon/resources/critical.wav"
Warning: "No decoder available for type 'audio/x-wav'."
Error: "Your GStreamer installation is missing a plug-in."

**Comment by HenriWahl** [comment]
Error: "Your GStreamer installation is missing a plug-in." - please check which plugins your gstreamer has.

**Comment by phaoost** [comment]
~# gst-inspect-1.0 |grep wav
wavpack:  wavpackdec: Wavpack audio decoder
wavpack:  wavpackenc: Wavpack audio encoder
wavenc:  wavenc: WAV audio muxer
wavparse:  wavparse: WAV audio demuxer
audiovisualizers:  wavescope: Waveform oscilloscope
audioparsers:  wavpackparse: Wavpack audio stream parser
typefindfunctions: application/x-shockwave-flash: swf, swfl
typefindfunctions: audio/x-wav: wav
typefindfunctions: audio/x-wavpack: wv, wvp
typefindfunctions: audio/x-wavpack-correction: wvc
libav:  avenc_adpcm_ima_wav: libav ADPCM IMA WAV encoder
libav:  avenc_adpcm_swf: libav ADPCM Shockwave Flash encoder
libav:  avdec_adpcm_ima_wav: libav ADPCM IMA WAV decoder
libav:  avdec_adpcm_swf: libav ADPCM Shockwave Flash decoder
libav:  avmux_wav: libav WAV / WAVE (Waveform Audio) muxer (not recommended, use wavenc instead)

**Comment by phaoost** [comment]
Here is the full list, I don't know which one I am missing: http://pastebin.com/n0Cp3JbQ

**Comment by HenriWahl** [comment]
What distro do you use?

**Comment by phaoost** [comment]
It's Debian, the latest possible stable version

**Comment by phaoost** [comment]
I have also added packages from debian-multimedia but this did not affect nagstamon in the bug reported here

**Comment by HenriWahl** [comment]
I have this packages installed on a Debian 8 GNOME:
$ dpkg-query -l | grep gst | grep plug
ii  gir1.2-gst-plugins-base-1.0           1.4.4-2                              i386         Description: GObject introspection data for the GStreamer Plugins Base library
ii  gstreamer0.10-gconf:i386              0.10.31-3+nmu4+b1                    i386         GStreamer plugin for getting the sink/source information from GConf
ii  gstreamer0.10-nice:i386               0.1.7-1                              i386         ICE library (GStreamer 0.10 plugin)
ii  gstreamer0.10-plugins-bad:i386        0.10.23-7.4                          i386         GStreamer plugins from the "bad" set
ii  gstreamer0.10-plugins-base:i386       0.10.36-2                            i386         GStreamer plugins from the "base" set
ii  gstreamer0.10-plugins-good:i386       0.10.31-3+nmu4+b1                    i386         GStreamer plugins from the "good" set
ii  gstreamer0.10-pulseaudio:i386         0.10.31-3+nmu4+b1                    i386         GStreamer plugin for PulseAudio
ii  gstreamer0.10-x:i386                  0.10.36-2                            i386         GStreamer plugins for X11 and Pango
ii  gstreamer1.0-libav:i386               1.4.4-2                              i386         libav plugin for GStreamer
ii  gstreamer1.0-nice:i386                0.1.7-1                              i386         ICE library (GStreamer plugin)
ii  gstreamer1.0-plugins-bad:i386         1.4.4-2.1+b1                         i386         GStreamer plugins from the "bad" set
ii  gstreamer1.0-plugins-base:i386        1.4.4-2                              i386         GStreamer plugins from the "base" set
ii  gstreamer1.0-plugins-good:i386        1.4.4-2                              i386         GStreamer plugins from the "good" set
ii  gstreamer1.0-plugins-ugly:i386        1.4.4-2+b1                           i386         GStreamer plugins from the "ugly" set
ii  gstreamer1.0-pulseaudio:i386          1.4.4-2                              i386         GStreamer plugin for PulseAudio
ii  gstreamer1.0-vaapi:i386               0.5.9-2                              i386         VA-API plugins for GStreamer
ii  gstreamer1.0-x:i386                   1.4.4-2                              i386         GStreamer plugins for X11 and Pango
ii  libgstreamer-plugins-bad0.10-0:i386   0.10.23-7.4                          i386         GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-bad1.0-0:i386    1.4.4-2.1+b1                         i386         GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base0.10-0:i386  0.10.36-2                            i386         GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base1.0-0:i386   1.4.4-2                              i386         GStreamer libraries from the "base" set

**Comment by phaoost** [comment]
Ok I have the issue resolved by removing gstreamer 1.0 and adding 0.10 instead. It plays sounds now.
Thanks!
