### ISSUE TITLE
Nagios: list index out of range

### ISSUE THREAD

**Issue by Machieeen** [HenriWahl/Nagstamon#264]
First of all, thank you very much for this lovely application.

We want to show the critical hosts and services on a big screen, so we can immediately see what the problems are. But for some reason I can't make it work. Perhaps the reason is that I use "Naemon" instead of Nagios, but the basis should be the same.

Whatever I try, I always get the message: list index out of range in the application and also in the debug file. I created a new user in Nagios and also tried different Monitor links (FQDN, IP-address etc) but still no luck.

Is it possible to tell me what causes the problem? (Not compatible, etc...)
xxxxxx = FQDN

Here you can find some output from
![nagstamon](https://cloud.githubusercontent.com/assets/19813887/15887748/3925ab54-2d64-11e6-8bd6-174be66c0bfd.JPG)
 the debug file:
DEBUG: 2016-06-08 10:12:01.149749 Middleware Applications Start rechecking all
DEBUG: 2016-06-08 10:13:00.973749 Middleware Applications FetchURL: http://xxxxxx/naemon/#cgi-bin/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
ERROR: 2016-06-08 10:13:01.084749 Middleware Applications Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Generic.py", line 546, in _get_status
IndexError: list index out of range

DEBUG: 2016-06-08 10:14:01.085749 Middleware Applications FetchURL: http://xxxxxx/naemon/#cgi-bin/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
ERROR: 2016-06-08 10:14:01.204749 Middleware Applications Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Generic.py", line 546, in _get_status
IndexError: list index out of range

DEBUG: 2016-06-08 10:14:16.830749 Middleware Applications Created server.
DEBUG: 2016-06-08 10:14:16.833749 Middleware Applications FetchURL: http://xxxxxx/naemon/#cgi-bin/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
ERROR: 2016-06-08 10:14:16.938749 Middleware Applications Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Generic.py", line 546, in _get_status
IndexError: list index out of range

DEBUG: 2016-06-08 10:14:21.789749 Middleware Applications Start rechecking all
DEBUG: 2016-06-08 10:14:23.101749 Middleware Applications Refreshing all hosts and services
DEBUG: 2016-06-08 10:14:23.938749 Middleware Applications FetchURL: http://xxxxxx/naemon/#cgi-bin/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
ERROR: 2016-06-08 10:14:24.043749 Middleware Applications Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Generic.py", line 546, in _get_status
IndexError: list index out of range

Thanks in advance!!

**Comment by HenriWahl** [comment]
Yes, I think using Naemon is the cause of the problem here. If there are some differences at login page or on page structure at all this might fail.

**Comment by Machieeen** [comment]
Unfortunate I'm not able to make changes, so I guess I will have to find another way to display all the hosts and services. Or if anyone knows a solution... :)

Thanks for your fast reply and explanation ;)
