### ISSUE TITLE
Wrong host IP

### ISSUE THREAD

**Issue by vgaudin** [HenriWahl/Nagstamon#267]
Working on centreon 2.7.4 with nagstamon 2.0 (beta 20160601)

When using action on a  host (like rdp or ssh) The action work correclty but using a bad ip ?

**Comment by HenriWahl** [comment]
Can you explain in detail? What IP is known in your monitoring system?

**Comment by vgaudin** [comment]
Hello Henri, 

Yes it seems it is an other host listed in centreon but not the right one. 

vincent 

----- Mail original -----

De: "Henri Wahl" <notifications@github.com> 
À: "HenriWahl/Nagstamon" <Nagstamon@noreply.github.com> 
Cc: "vgaudin" <vincent.gaudin@cprpsncf.fr>, "Author" <author@noreply.github.com> 
Envoyé: Lundi 27 Juin 2016 16:15:18 
Objet: Re: [HenriWahl/Nagstamon] Wrong host IP (#267) 


Can you explain in detail? What IP is known in your monitoring system? 
— 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or mute the thread . 




Ce message est protégé par les règles relatives au secret des correspondances. Il est donc établi à destination exclusive de son destinataire. Celui-ci peut donc contenir des informations confidentielles. 
La divulgation de ces informations est à ce titre rigoureusement interdite. 
Si vous avez reçu ce message par erreur, merci de le renvoyer à l'expéditeur dont l'adresse e-mail figure ci-dessus et de détruire le message ainsi que toute pièce jointe.


Ce message est protégé par les règles relatives au secret des correspondances. Il est donc établi à destination exclusive de son destinataire. Celui-ci peut donc contenir des informations confidentielles. 
La divulgation de ces informations est à ce titre rigoureusement interdite. 
Si vous avez reçu ce message par erreur, merci de le renvoyer à l'expéditeur dont l'adresse e-mail figure ci-dessus et de détruire le message ainsi que toute pièce jointe.

**Comment by HenriWahl** [comment]
So this issue can be closed?

**Comment by vgaudin** [comment]
it is simply not the correct host that is opened . 

always the same . I don't have any idea why. 

----- Mail original -----

De: "Henri Wahl" <notifications@github.com> 
À: "HenriWahl/Nagstamon" <Nagstamon@noreply.github.com> 
Cc: "vgaudin" <vincent.gaudin@cprpsncf.fr>, "Author" <author@noreply.github.com> 
Envoyé: Lundi 27 Juin 2016 16:32:16 
Objet: Re: [HenriWahl/Nagstamon] Wrong host IP (#267) 


So this issue can be closed? 
— 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or mute the thread . 




Ce message est protégé par les règles relatives au secret des correspondances. Il est donc établi à destination exclusive de son destinataire. Celui-ci peut donc contenir des informations confidentielles. 
La divulgation de ces informations est à ce titre rigoureusement interdite. 
Si vous avez reçu ce message par erreur, merci de le renvoyer à l'expéditeur dont l'adresse e-mail figure ci-dessus et de détruire le message ainsi que toute pièce jointe.


Ce message est protégé par les règles relatives au secret des correspondances. Il est donc établi à destination exclusive de son destinataire. Celui-ci peut donc contenir des informations confidentielles. 
La divulgation de ces informations est à ce titre rigoureusement interdite. 
Si vous avez reçu ce message par erreur, merci de le renvoyer à l'expéditeur dont l'adresse e-mail figure ci-dessus et de détruire le message ainsi que toute pièce jointe.

**Comment by BenoitPoulet** [comment]
I successfully reproduce the bug.

SSH command defined as : C:\HARs\kitty.exe -l root $ADDRESS$

under «Settings > Action > Connection method» 
- if «Hostname» is selected, everything is fine
- if «IP» is selected, the same IP address is used for all host

I will try to help on this bug

**Comment by HenriWahl** [comment]
Fixed by @BenoitPoulet
