### ISSUE TITLE
Status Window - Follows the mouse on refresh

### ISSUE THREAD

**Issue by jwhipp** [HenriWahl/Nagstamon#268]
If the status Window is open, it will center itself on the mouse pointer on refresh rather than staying put near it's tray/indicator icon area.    In Nagstamon 1.0.1, the window stayed by the tray or indicator area.  

Ubuntu 16.04 LTS, Unity, Nagstamon running as an app indicator, version 2.0-beta-20160601.

**Comment by HenriWahl** [comment]
I can confirm this... do you know of a version wher this did not happen?

**Comment by HenriWahl** [comment]
Expect in being fixed in the next binaries available.

**Comment by jwhipp** [comment]
Just to answer your question, only version when I know it didn't happen was 1.0.1.  It's just taken me a while to file a bug.
