### ISSUE TITLE
Zabbix Login Issue

### ISSUE THREAD

**Issue by mdiorio** [HenriWahl/Nagstamon#269]
After upgrading to Zabbix 3.0.3 I am no longer able to connect.

Nagstamon.thirdparty.zabbix_api.ZabbixAPIException: ('Error -32602: Invalid params., Not authorised. while sending {"jsonrpc": "2.0", "params": {"filter": {}, "output": ["host","ip","status","available","error","errors_from"]}, "auth": null, "method": "host.get", "id": 5}', -32602)

Thanks!

**Comment by HenriWahl** [comment]
Which version worked before?

**Comment by mdiorio** [comment]
It was working fine on Zabbix 3.0.1

**Comment by HenriWahl** [comment]
Any changes known where 3.0.1 and 3.0.3 differ?

**Comment by mdiorio** [comment]
No changes differ from my end.  It was a straight upgrade.

Here are the API changes made in the versions since 3.0.1
[API Changes](https://www.zabbix.com/documentation/3.0/manual/api/changes_3.0)

**Comment by HenriWahl** [comment]
@oN0 being the author of https://github.com/HenriWahl/Nagstamon/pull/200 - can you check this issue?

**Comment by mdiorio** [comment]
Crap - you can close this.  Turns out we forgot to update our LDAP settings in Zabbix and it was trying to authenticate against an old domain - not sure how I was able to log into it all this time though.  Sorry about that.

**Comment by HenriWahl** [comment]
Hoorraay! Great it was nothing broken.
