### ISSUE TITLE
Fedora 24 issues with  nagstamon-2.0b20160601-1.noarch.rpm package

### ISSUE THREAD

**Issue by treenerd** [HenriWahl/Nagstamon#270]
The nagstamon-2.0b20160601-1.noarch.rpm has broken dependencies for Fedora24

The problem is the dependency to the python(abi) 3.4 version.
With Fedora 24 the python version has changed to 3.5.

`➜  Downloads sudo dnf install nagstamon-2.0b20160601-1.noarch.rpm       
Letzte Prüfung auf abgelaufene Metadaten: vor 0:34:45 am Thu Jul  7 09:27:22 2016.
Fehler: nothing provides python(abi) = 3.4 needed by nagstamon-2.0b20160601-1.noarch`

With a build from today it was no problem, but please add a new build to the download website.
https://nagstamon.ifw-dresden.de/download

Not sure if this is the right place to add the issue.
Best regards
Gerhard

**Comment by HenriWahl** [comment]
Yes, my packaging script is not very sophisticated so this effect occurs. I will provide a new package as soon as possible,
In the meantime you could build it yourself with the build.py script provided in the Github repo - if all dependencies are met as described on the homepage of Nagstamon.

**Comment by treenerd** [comment]
Hi @HenriWahl ,
Thank you for the fast answer.
The build script worked for me.

**Comment by HenriWahl** [comment]
Fedora 23 & 24 RPMs are now online.
