### ISSUE TITLE
ValueError after update to beta 20160727

### ISSUE THREAD

**Issue by Finkregh** [HenriWahl/Nagstamon#275]
![image](https://cloud.githubusercontent.com/assets/518090/17209166/f5738dd4-54bb-11e6-95b6-74125cb68296.png)

Windows 8 x64, just updated to the latest beta and cant connect to our icingaweb2 :-(

**Comment by HenriWahl** [comment]
Sorry this is a bug. Please check in server settings to disable no-cookie-auth in extra options,

**Comment by HenriWahl** [comment]
Fixed with commit https://github.com/HenriWahl/Nagstamon/commit/7c0761a3d51570b90043bdef354b9edd74616bdc
