### ISSUE TITLE
Heavy usage of tempfiles created and removed

### ISSUE THREAD

**Issue by varac** [HenriWahl/Nagstamon#276]
`sudo iotop -o` shows constant IO usage of nagstamon (nagstamon_2.0-beta-20160727_all.deb but also with 2.0-beta-20160707, using ubuntu 16.04), at least when there are new nagios alerts the nagstamon notifies with a flashing "N" symbol.

`watch -n 0.1 'ls -la /tmp/qt-trayicon*' ` shows that temp files get created and removed quite frequently, and `mkdir /tmp/nagstamon; cp /tmp/qt-trayicon* /tmp/nagstamon` shows 2 png files with the nagstamon "N" symbol.

**Comment by HenriWahl** [comment]
What the hell... Nagstamon does not knowingly create these files! Should Qt use temporary files for the systray icon? Did you use it on older versions of your OS with older Qt too? Might be an interesting questions to the Qt developers.

**Comment by varac** [comment]
I'm using ubuntu 16.04, with the gnome-shell and i3 desktop.

**Comment by HenriWahl** [comment]
So these seems to be the perfect conditions to achive the effect noticed by you. Not much I can do here. I am not in the mood to build a workaround for the workaround of the Qt people - I doubt it will be possible a all.

**Comment by varac** [comment]
sure, fair enough. I'll create an issue at https://bugreports.qt.io

**Comment by varac** [comment]
for the record, here's the QT upstream issue: https://bugreports.qt.io/browse/QTBUG-55021

**Comment by mprenditore** [comment]
I can confirm that on Qt 5.7 is solved... Cheers!

**Comment by varac** [comment]
> I can confirm that on Qt 5.7 is solved... Cheers!

not for me, see https://github.com/HenriWahl/Nagstamon/issues/355#issuecomment-274756392 for more details.
