### ISSUE TITLE
IcingaWeb2 not working anymore

### ISSUE THREAD

**Issue by janvonde** [HenriWahl/Nagstamon#277]
Since 20160727 IcingaWeb2 is not working anymore. It was not fixed in 20160729 for me. The last working version is 20160601. I am always getting the following error:
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Please tell me how I can assist you with debugging.

**Comment by HenriWahl** [comment]
Please check extra IcingaWeb2 settings in server settings dialog and unset the no-cookie-option.

**Comment by HenriWahl** [comment]
Assumed to be working now: https://twitter.com/fink_/status/758605886021566464

**Comment by janvonde** [comment]
Check. Thanks for your help.
