### ISSUE TITLE
Clarify "Connection method" for "Actions"

### ISSUE THREAD

**Issue by BenoitPoulet** [HenriWahl/Nagstamon#280]
Hello,

I think it would be nice to clarify Connection method" for "Actions".
In particular "DNS name" which is "Do a reverse DNS on IP address in order to use the answer"
I don't say to put this long sentence but something more clear on what this option does.

![capture](https://cloud.githubusercontent.com/assets/2464712/17404666/d975d44c-5a5c-11e6-88d6-1b823b8d11df.PNG)

Regards.

**Comment by HenriWahl** [comment]
Good idea, will be done as soon as possible.

**Comment by HenriWahl** [comment]
Done in https://github.com/HenriWahl/Nagstamon/commit/284d04d63dd04652b5839971fe2922b1fa981058
