### ISSUE TITLE
nagstamon64 crashes / many failures

### ISSUE THREAD

**Issue by winter1967** [HenriWahl/Nagstamon#281]
Hi, 
i installed the last Version of Nagstamon:

Nagstamon-2.0-beta-20160729-win64_setup.exe

After the start, i have to configure the Server Connection, i try icingaweb2 with adress and the credentials. After it nastamon crashs.
Taking a look in ".nagstamon" i see my Server configuration file, restarting nagstamon, it says there is no configuration file. Trying to create a new one, the same, nagstamon crashes.
Sometimes Nagstamon said, there are no configured Servers yet, Create new Server let him Crash, after a ignore i can open nagstamon, then Settings and create a new Server, after creating nagstamon crashes.
I started nagstamon with processmonitor running, it's the file i attached.. May be it helps.

[nagstamon.txt](https://github.com/HenriWahl/Nagstamon/files/403440/nagstamon.txt)

**Comment by HenriWahl** [comment]
Any special authentication configuration in your IcingaWeb2 or is this just plain standard cookie-based?

**Comment by HenriWahl** [comment]
Can you enable debug mode in Nagstamon and see if there is any useful output?
The best debugging help would be running it from source on console...

**Comment by winter1967** [comment]
I haven’t no debug output, after i have enabled it; nagstamon crashed without output.

But I’ve found a solution (in monitoring-portal.org)

When I use the FQDN for our servername

https://icingaweb2server.verwaltung.stadtkoeln.de/icingaweb

and

make “Do not use cookie authentificion” true

it works.







Von: Henri Wahl [mailto:notifications@github.com]
Gesendet: Freitag, 5. August 2016 11:33
An: HenriWahl/Nagstamon
Cc: Winter, Wolfgang; Author
Betreff: Re: [HenriWahl/Nagstamon] nagstamon64 crashes / many failures (#281)


Can you enable debug mode in Nagstamon and see if there is any useful output?
The best debugging help would be running it from source on console...
