### ISSUE TITLE
Can not log into Zabbix 3.0.4 - ZabbixAPIException: Could not open URL

### ISSUE THREAD

**Issue by ghost** [HenriWahl/Nagstamon#282]
I got that kind of error, while trying to log into Zabbix 3.0.4, both in Nagstamon 1.01 on Centos 7 and Nagstamon 2.0b on Windows 8:

`ZabbixAPIException: Could not open URL`

The URL is 100% good, since it's working in some kind of Zabbix plugins to Google Chrome. The problem may be with the fact, that on that URL, there is .htaccess authentication first (Authentication Required" window, if you open the URL in browser) and then you can log into Zabbix. It may be the issue? But as I said, it doesn't stop Google Chrome Zabbix addons from working. Also, the URL is HTTPS.

I would also like to mention that changing authentication in Nagstamon 2.0b from default to "digest" is not helping.

Thanks for any replies, suggestions etc. I will provide more data if needed.

**Comment by HenriWahl** [comment]
@oN0 Do you think authorization via plain basic auth is possible somehow?

**Comment by dkorzhevin** [comment]
Got same for Zabbix 3.2.1, plain http, Nagstamon 2.0

**Comment by mprenditore** [comment]
from other bug reports seams there are issues to get  Nagstamon to login to zabbix 3.x...
If i'll hove some spare time to create a vm with windows I'll test it and try to solve

**Comment by HenriWahl** [comment]
@mprenditore :+1: 
In the meantime I merged your latest pull request - still seems to work! :-)

**Comment by mprenditore** [comment]
@HenriWahl Thanks :)
Sorry for the dependant import removed -_-'

**Comment by HenriWahl** [comment]
Well, I could also had commented it before... :-)

**Comment by alexandrefrp** [comment]
Hi, I'm having the same problem logging in to Zabbix 3.0.3, I suspect the certificate problem because my URL is https://localhost:8000/zabbix and in the browser it is necessary to add exception to work page.
![nastmon_zabbix](https://cloud.githubusercontent.com/assets/10060574/20080687/35a034ea-a532-11e6-80d9-5525b5f21218.jpg)
