### ISSUE TITLE
Nagstamon and centreon Centreon 2.7.4 Windows 10 64 bits

### ISSUE THREAD

**Issue by jordan85** [HenriWahl/Nagstamon#283]
Hi 

I have same error that : https://github.com/HenriWahl/Nagstamon/issues/271

I have installed 
- Nagstamon-2.0-beta-20160729-win32_setup.exe
- Nagstamon-2.0-beta-20160729-win32_setup.exe 
- Nagstamon-2.0-beta-20160801-win32_setup.exe 

You have an issue for this error?

Regards

**Comment by HenriWahl** [comment]
Did you try 64 bit?
Maybe your Centreon has to be updated to 2.7.6 as it seems to work according to https://github.com/HenriWahl/Nagstamon/issues/271#issuecomment-237491703.

**Comment by jordan85** [comment]
Ok I've update my Centreon to 2.7.6 but with which version Nagstamon is ok ? 20160729 ? 20160801 ? Or other ? 

Thanks

**Comment by HenriWahl** [comment]
The newer the better... latest binaries are not yet published but available here:

32 Bit Zip: https://seafile.ifw-dresden.de/f/560a490063/?raw=1
32 Bit Setup.exe: https://seafile.ifw-dresden.de/f/ebf5628b38/?raw=1
64 Bit Zip: https://seafile.ifw-dresden.de/f/1eb6d15c27/?raw=1
64 Bit Setup.exe: https://seafile.ifw-dresden.de/f/d801a9b146/?raw=1

Coming from https://github.com/HenriWahl/Nagstamon/issues/271#issuecomment-238540730

**Comment by HenriWahl** [comment]
Please see https://github.com/HenriWahl/Nagstamon/issues/271#issuecomment-239331642 - an Centreon update did the trick.
