### ISSUE TITLE
Nagstamon 2.0 beta crashes on server events

### ISSUE THREAD

**Issue by mattmarich** [HenriWahl/Nagstamon#284]
Been having issues with every Nagstamon 2.0 install on Mac when it comes to server events. Whenever I do a 'Recheck All' or 'Recheck', the app crashes. Whenever I do a 'Acknowledge', 'Submit Check Results', or 'Downtime' the app does not crash but the expected action does not happen server side. 

I'm running 10.11.5. Do you want the Apple crash report?

**Comment by HenriWahl** [comment]
Did you find a reason? Which version of Nagstamon was involved?
