### ISSUE TITLE
Problem with sorting.

### ISSUE THREAD

**Issue by warik-zp** [HenriWahl/Nagstamon#285]
Hello,

I have problem with sorting. If I click "Duration", after "Status" and again "Status" I have this problem:
![screenshot at 10 08 16_01-18-47](https://cloud.githubusercontent.com/assets/11426085/17535623/6b9a34b4-5e98-11e6-81ec-7f054079e093.png)
The program thinks that the 108 and 155 is less than 47, 89 and 97.

**Comment by warik-zp** [comment]
But if I once click "Duration" all good:
![screenshot at 10 08 16_01-21-11](https://cloud.githubusercontent.com/assets/11426085/17535688/c76a6d40-5e98-11e6-8df1-089d2ac25530.png)

**Comment by HenriWahl** [comment]
Which monitor server type do you connect to?

**Comment by warik-zp** [comment]
I use Nagios server.

**Comment by HenriWahl** [comment]
I am not sure about the order you press the headers. I understand as:
1. Duration
2. Status
3. Status
Is this right?

**Comment by warik-zp** [comment]
Yes. I click 
1. Duration
2. Status
3. Status
And I have this sorting: 
![screenshot at 10 08 16_08-21-22](https://cloud.githubusercontent.com/assets/11426085/17542664/79535b9a-5ed3-11e6-935c-700cefa05a4a.png)

**Comment by HenriWahl** [comment]
So there is no real sorting by duration to be expected. As far as I remember the last sorting before the current one is recognized and evaluated, but the whole sorting history is not.

**Comment by warik-zp** [comment]
Please look this screenshot. On 0.9.8 sorting works fine.
![bcwocwe](https://cloud.githubusercontent.com/assets/11426085/17649544/b74b34de-6240-11e6-8c51-9c546295ea4b.png)
On this screenshot I open program and click:
1. Duration
2. Status
3. Status

**Comment by HenriWahl** [comment]
OK now I was able to reproduce - and also applied a fix. Should I provide you some binaries to test? If so, for which platform?

**Comment by warik-zp** [comment]
Hello.
Yes. You can. I use Ubuntu 16.04 x64 with KDE 5.

**Comment by HenriWahl** [comment]
Here you go: https://seafile.ifw-dresden.de/f/5f44c9fc66/?raw=1

**Comment by warik-zp** [comment]
All good. Thanks!
![so83uof](https://cloud.githubusercontent.com/assets/11426085/17693627/7f3e78c6-63a8-11e6-9666-e602e716b786.png)
