### ISSUE TITLE
Add support for Librenms

### ISSUE THREAD

**Issue by nerdalertdk** [HenriWahl/Nagstamon#286]
Hi

It would be awesome if you could add support for librenms.org, they have en API to extract most infomation about alerts

http://docs.librenms.org/API/API-Docs/#alerts-top

**Comment by HenriWahl** [comment]
I cannot promise anything but let this issue stay on the todo list

**Comment by nerdalertdk** [comment]
Sounds good :+1:

**Comment by nerdalertdk** [comment]
Any news/progress on this :)

**Comment by HenriWahl** [comment]
Not really... some contribution would be great.

**Comment by HenriWahl** [comment]
Finally... merged some seconds ago: https://github.com/HenriWahl/Nagstamon/pull/1152
