### ISSUE TITLE
[v2.0-beta-20160729] No reauth after Standby

### ISSUE THREAD

**Issue by mkrsn** [HenriWahl/Nagstamon#287]
Hello Henri,

I've got a "Problem" with Nagstamon after waking the Windows-Machine from Standby (Suspend to Ram over the night). In This situation Nagstamon is unable to reauth to the icinga2 Server. This Problem only appears when the Windows-Machine is "longer" in standby. It doesn't  appear on "short" Standby's.

It complains about "ValueError: Expecting value: line 1 column 1 (char 0)". If the Problem appears i have to end Nagstamon and start it again to fix this behavior.

![2016-08-11 08_08_26-](https://cloud.githubusercontent.com/assets/10330231/17580231/55be44c2-5f9d-11e6-82ca-b97ce9538972.png)

Best Regards Matthias

p.s.: Danke für dieses klasse Tool :) Ist eine enorme Erleichterung des Arbeitsalltags!

**Comment by HenriWahl** [comment]
I assume Nagstamon has a problem with the sleeping and awaking network connection but this is so deep inside the OS... I fear there is nothing I do here.

Just one chance to find out anything here might be activating debug mode in settings, maybe there will be some useful output.

**Comment by HenriWahl** [comment]
On the other hand... which monitor type do you use? Maybe just the auth cookie is obsolete after longer standby and now Nagstamon fails to reauth?

**Comment by mkrsn** [comment]
I'm using the cookie (Basic-Auth).

I'll try the Debug-Log today evening and report it tomorrow.

**Comment by HenriWahl** [comment]
And what is your monitor server type? Nagios? Icinga? ...?

**Comment by mkrsn** [comment]
Sry - IcingaWeb2

**Comment by HenriWahl** [comment]
So there is the question: do you use cookies OR basic auth?

**Comment by mkrsn** [comment]
hmm... The Setting seems to use both HTTP-Basic Auth AND Cookie-Auth (?!)

![2016-08-11 12_42_42-nagstamon 2 0-beta-20160729](https://cloud.githubusercontent.com/assets/10330231/17586381/b5f76d7c-5fc1-11e6-9b58-42f90153a116.png)

**Comment by HenriWahl** [comment]
No... this might be misleading... as you do not  not-use-cookie-auth you do use cookie auth... without any basic whatever auth.
Quite possibly the auth retrieving mechanism is not re-auth-capable so this should be inspected again.
@minibbjd any interest/time/mood to check this? :-)

**Comment by mkrsn** [comment]
Good Morning.

`DEBUG: 2016-08-12 08:07:13.183000 XXX - XXXXXX FetchURL: https://foo.bar.tld/icingaweb2/monitoring/list/hosts?host_state>0&host_state<=2&host_state_type=1&addColumns=host_last_check&format=json CGI Data: None
ERROR: 2016-08-12 08:07:15.030000 XXX - XXXXXX Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\IcingaWeb2.py", line 156, in _get_status_JSON
  File "c:\Python34\lib\json\__init__.py", line 318, in loads
  File "c:\Python34\lib\json\decoder.py", line 343, in decode
  File "c:\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)`

BG Matthias

**Comment by HenriWahl** [comment]
I kind of found something to improve. Which kind of binary can you use to test if this changes will help? 32 or 64 bit?

**Comment by mkrsn** [comment]
Wonderful. 64bit

**Comment by HenriWahl** [comment]
Setup.exe: https://seafile.ifw-dresden.de/f/0690d9dcfd/?raw=1
Standalone zip: https://seafile.ifw-dresden.de/f/854edce0f2/?raw=1

**Comment by mkrsn** [comment]
Good Morning.

Thanks Henri, your Fix solved the Problem.

Notebook awakes, nagstamon runs in a Timeout and throws an error. After that it's refreshing and reauth is done!

**Comment by HenriWahl** [comment]
Good news! 
Thanks for reporting anyway - the reauth feature was missing completely until now.
