### ISSUE TITLE
Issue with Nagios Acknowledgment 

### ISSUE THREAD

**Issue by Muntasir123** [HenriWahl/Nagstamon#288]
There seems to be an issue with acknowledging service requests on Nagastamon 2.0 beta. Its showing a bunch of test alarms I created but I'm having to manually go on the Nagios website website  to acknowledge them and simply doing 

![image](https://cloud.githubusercontent.com/assets/18218625/17666342/d848bb24-62cd-11e6-8bd1-cf8ce2caf0fc.png)

Anyone else facing similar issues?

**Comment by HenriWahl** [comment]
Which version of the beta and which version of Nagios?

**Comment by Muntasir123** [comment]
Fixed. Turns out there was a problem with RegExp, and it was adding spaces in between substrings for no reason. Fixed this by manually taking out spaces. Thanks
