### ISSUE TITLE
Use display name as service name not working with icinga2

### ISSUE THREAD

**Issue by mgresser** [HenriWahl/Nagstamon#289]
Despite checking the "use display name as service name" I am seeing the service name instead of the display name for icinga2 services. I'm running the latest beta.

**Comment by HenriWahl** [comment]
Which version of Nagstamon do you refer to?

**Comment by HenriWahl** [comment]
Fixed in https://github.com/HenriWahl/Nagstamon/commit/15e572a5dba3fafd1045c9ee9ff0e3e714ba891c

**Comment by mgresser** [comment]
Just for completeness, this was:
Icinga2 2.3.4
Nagstamon 2.0-beta-20160729

Thanks for the fix and for a great application!
