### ISSUE TITLE
[Nagstamon-2.0-beta-20160729] icinga vs nagios monitortype-setting

### ISSUE THREAD

**Issue by hknet** [HenriWahl/Nagstamon#290]
Hi
the current release on win10 x64 has on one hand the issue that the status window is not displayed when the tray icon is clicked upon in fact it shows the context menu. (popup and close when clicking statusbar is selected)

on the other hand the monitortype has to be set to nagios when using an icinga v1.x interface.

thanks for the good work,
hk

**Comment by HenriWahl** [comment]
The first problem might occur if you have no problems ("green N") - thus no need to show a popup. Is this the case?

Which Icinga version exactly do you run? Since 1.6 or something like this they went they own way away from Nagios so the Incinga monitor type has to be used.

**Comment by hknet** [comment]
Hi
the first "green N" is indeed the case, it's odd though that left mouse-click gives me a context-menu :)

regarding icinga, it's v1.7.1 - in nagstamon v1 we use the type icinga and all is well.

regards,
hk

**Comment by HenriWahl** [comment]
1. Well, consider it as a service... it would make no sense to show you an empty popup. The most imaginable reason you might have to click at the green N is changing some settings or quit the program - so why not also show it on left click?

2. Even Icinga 1.7 is pretty old... might even be that this one still is fully Nagios compatible. If it works for you then just use it as "Nagios". Maybe you have there any special configuration, regarding auth or so?
 I think (and hope) the userbase of this Icinga version will shrink anyway so I see no need for action.
