### ISSUE TITLE
bugs in v 2.0-beta-20160729 on Win 7 Pro

### ISSUE THREAD

**Issue by sebfun** [HenriWahl/Nagstamon#291]
Hi

I found some bugs in this beta version.

First : when choosing hovering mode in settings, it does not work when mouse hovers the icon in systray. I need to left click for it works and left click again for it closes.

Secondly I create an action option in Action menu. This action is designed to browse the RRD graph used in pnp4nagios. So I did exactly the same action as you said in your documentation website.
When I right click on a host or service problem and then I choose my action, it opens the Windows Explorer

Thirdly, When activating debug mode with setting a debug file. It does not create the debug file until app restarts.

Tested on Windows 7 Pro SP1 in 32 bits
Firefox 48 as the default browser
Using Nagios 4.0.7 in a Hyper-V's VM with Centos 6.8

**Comment by HenriWahl** [comment]
Systray icon does not react in general to hovering - at no platform.

Can you post your complete action string and type here?

**Comment by sebfun** [comment]
Hi Henri
I found my problem for the action string. I made a mistake in the url so it was considerating acting as windows ' shortlink
I tested my modification and it was working like a charm :)
So the 2nd issue is ok now.

and thanks for the job, this is very useful. Previously I used the mozilla addon but as you said, you always need to have Firefox opens for it works.

**Comment by HenriWahl** [comment]
:-)

**Comment by HenriWahl** [comment]
Sorry I missed the 3rd bug. I consider this a minor problem but will have a look at it.

**Comment by HenriWahl** [comment]
Debug bug fixed now in https://github.com/HenriWahl/Nagstamon/commit/8cbfecd6b31c7c4b9dd78bca1724d55adeda2d19
