### ISSUE TITLE
Icinga2 reauth issue

### ISSUE THREAD

**Issue by mostafahussein** [HenriWahl/Nagstamon#292]
I couldn't find a thread for this so i can add a new comment so i opened this as a new issue. I am aware that you are working on a solution. I have installed the latest version `2.0-beta-20160729` then i added a new server (Icinga2web) the monitor url is: `http://localhost/icingaweb2`. and i got this error:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/Nagstamon/Servers/IcingaWeb2.py", line 159, in _get_status_JSON
    hosts = json.loads(jsonraw)
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```
Then i tried to debug it in order to solve it so i can submit a pull request in here. I printed the value of `jsonraw` and the result was an HTML of Icinga2Web login page. then i came here to see if there is an existing issue or maybe a commit and i found a commit already.

then i have repacled `IcingaWeb2.py` and `Generic.py` then restarting nagstamon but i got another error this time which is:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/Nagstamon/Servers/Generic.py", line 1254, in FetchURL
    response = self.session.get(url, timeout=self.timeout)
AttributeError: 'NoneType' object has no attribute 'get'
```

- Should i change the url ? 
- Am I missing some other files that needs to be replaced ?
- Is there something i could do in order to help you solving this issue ?

**Comment by mostafahussein** [comment]
Update: I restored the original files again and then added my web credentials instead of basic auth api credentials. and it worked correctly. I will close this for now.

- Can't we use the api itself instead of using the web interface?

**Comment by HenriWahl** [comment]
As far as I know the API needs autohrization via web interface - if there is any way to avoid this let me know.
