### ISSUE TITLE
Bug with Action RDP

### ISSUE THREAD

**Issue by lorrainezo** [HenriWahl/Nagstamon#293]
Hello,

I found that since version 1.01, action to do a RDP connection have bad configuration.
It's put by default :
C:\windows\system32\mstsc.exe $ADDRESS$
Instead of :
C:\windows\system32\mstsc.exe /v:$ADDRESS$

Is-it possible to correct this in next beta version ?

Thanks

**Comment by HenriWahl** [comment]
You are right, fixed in https://github.com/HenriWahl/Nagstamon/commit/efa1339e6f1ae984130a6123206c3c6b7b88139f.
This will only affect new installations - your once wrong action will stay as it is.
