### ISSUE TITLE
Links in status info not rendered

### ISSUE THREAD

**Issue by mgresser** [HenriWahl/Nagstamon#294]
In the status information column if an HTML link is included in that text the HTML tags are show instead of a clickable link. If you hover over it a version with a clickable link is displayed but you can't move your mouse into that hover box to click the link. It would be awesome if HTML tags could be converted to clickable links when they appear in the status info.

Nagstamon: 2.0 BETA-20160825
Icinga2: v2.3.4

**Comment by HenriWahl** [comment]
As far as I remeber the table cells only contain pure text which HTML tags will not be evaluated - as you see there are link tags instead of links. To avoid confusion the maximum we can reach here is to clean out HTML tags.

**Comment by mgresser** [comment]
From my perspective it would be totally sufficient if the tags were simply cleaned up and not displayed.

**Comment by HenriWahl** [comment]
Tried to fix with last commit https://github.com/HenriWahl/Nagstamon/commit/733e7b4f64b00810052cd7f5613fa332ee087182.
Do you need binaries to test it or can you run it from source? If you need binaries - which ones?

**Comment by mgresser** [comment]
A binary would be helpful. I'm running nagstamon on OSx.

**Comment by HenriWahl** [comment]
Please check https://seafile.ifw-dresden.de/f/0f6d1e608f/?raw=1

**Comment by mgresser** [comment]
Thank you. Looks good to me!
