### ISSUE TITLE
[Nagstamon-2.0] Connection errors 

### ISSUE THREAD

**Issue by torstenbunde** [HenriWahl/Nagstamon#295]
First let me thank you for the good work!

I just updated my old nagstamon version to the new version 2.0 (Windows 7, 64 bit; monitoring one Nagios and one Check_MK system) which means I uninstalled the old one before installing the new one.

The old version worked fine, using the new version I regularly get the message "Error" 
![20160830_nagstamon0](https://cloud.githubusercontent.com/assets/9153422/18079807/df71b146-6e92-11e6-95c9-c066ad7510a1.png)
and "Connection error"
![20160830_nagstamon1](https://cloud.githubusercontent.com/assets/9153422/18079820/ea50d6c8-6e92-11e6-9980-4f90159aeb79.png)

The message disappears a minute later (next check?!) but then comes back again. It also disappears if I do a manual recheck/refresh.

I even set the timeout option to 30 seconds and the update interval to 180 seconds but it still happens regulary. Do other users have the same problems or is it maybe only some kind of network problem here?

Regards
- Torsten

**Comment by HenriWahl** [comment]
Did not hear this form somebody else but obviously this is real. :-) So can you enable debugging in settings to see if we get some usable info?

**Comment by torstenbunde** [comment]
Yes of course. I enabled debugging and it looked like problems with Python and/or the remote host. There are of course messages like 'An existing connection was closed by the remote host' (in German: 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen').

[nagstamon_20160830.txt](https://github.com/HenriWahl/Nagstamon/files/445023/nagstamon_20160830.txt)

I even updated to the newest Python version (3.5.2): Same problem. And I installed Nagstamon as binary release and not from source.

**Comment by HenriWahl** [comment]
Hallo Torsten,

ich switche mal auf german um :-)

Am 30.08.2016 um 16:03 schrieb Torsten Bunde:
> Yes of course. I enabled debugging and it looked like problems with
> Python and/or the remote host. There are of course messages like 'An
> existing connection was closed by the remote host' (in German: 'Eine
> vorhandene Verbindung wurde vom Remotehost geschlossen').
>
Was hat das zu bedeuten... keine Ahnung. Knallt es bei einem speziellen
Server oder ist die Reihenfolge der Aktivierung egal und es knallt immer
sobald es 3 sind?

> nagstamon_20160830.txt
> <https://github.com/HenriWahl/Nagstamon/files/445023/nagstamon_20160830.txt>
> 
> I even updated to the newest Python version (3.5.2): Same problem. And I
> installed Nagstamon as binary release and not from source.
> 
Wenn Du die Binärvariante von Nagstamon installiert hast, spielen alle
extra Pythons keine Rolle dafür - diese Version kommt all inclusive.

Grüße
Henri


-- 
Henri Wahl

IT Department
Leibniz-Institut fuer Festkoerper- u.
Werkstoffforschung Dresden

tel: +49 (3 51) 46 59 - 797
email: h.wahl@ifw-dresden.de
https://www.ifw-dresden.de

Nagios status monitor Nagstamon: https://nagstamon.ifw-dresden.de

DHCPv6 server dhcpy6d: https://dhcpy6d.ifw-dresden.de

S/MIME: https://nagstamon.ifw-dresden.de/pubkeys/smime.pem
PGP: https://nagstamon.ifw-dresden.de/pubkeys/pgp.asc

IFW Dresden e.V., Helmholtzstrasse 20, D-01069 Dresden
VR Dresden Nr. 1369
Vorstand: Prof. Dr. Burkard Hillebrands, Dr. Doreen Kirmse

**Comment by HenriWahl** [comment]
Sorry last post was belonging to another thread... well, not much to get out of the debugging info. Python comes with Nagstamon binaries so if you install anything extra it has no influence. What platform runs your remote server on?

**Comment by HenriWahl** [comment]
Reading http://stackoverflow.com/questions/27333671/how-to-solve-the-10054-error I remember I had a similar problem with a "BadStatusLine" error which I simply decided to work around by actively ignoring it - see https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/Servers/Generic.py#L821. Might not be the best way but it is one way at all... so I propose to do you in your case too and add this error to the list of ignored errors.

**Comment by HenriWahl** [comment]
A more clean approach might be to check the webserver and find out why it closes the connection.

**Comment by torstenbunde** [comment]
Just to answer your first question: We've got two remote servers here. One running SUSE Linux Enterprise Server 11 and one running Ubuntu 14.04 LTS. Both using Apache2.

So maybe it's the easiest way to ignore the error because a colleague of mine installed the new version too and doesn't have these problems. So it's maybe a problem of my workstation. The web logs only have information about status code 200 so everything seems to be ok (on both servers).

So I think you can close this ticket?!

**Comment by HenriWahl** [comment]
OK. Maybe the most pragmatical way.
I would leave the ticket open as a reminder to include the ignore-the-error-code for me.

**Comment by HenriWahl** [comment]
Can you please test the latest 2.0.1 testing versions (zip and exe):

https://seafile.ifw-dresden.de/f/d9c32b78df/
https://seafile.ifw-dresden.de/f/d9b277b12a/

**Comment by torstenbunde** [comment]
I tested it today and it worked without any error messages the whole day.
