### ISSUE TITLE
nagstamon 2.0 Win10 x64 - no status window shown

### ISSUE THREAD

**Issue by hknet** [HenriWahl/Nagstamon#297]
Hi
since the update to the final release selecting "show status window" results in no status window displayed.

Regards
hk

**Comment by HenriWahl** [comment]
What monitor type do you connect to? Did you use other beta versions before or upgraded from 1.0.1 to 2.0? Is there any old config?

**Comment by HenriWahl** [comment]
No more info - assumed to be OK now.
