### ISSUE TITLE
[Nagstamon-2.0] Font size issue, floating statusbar

### ISSUE THREAD

**Issue by peterny** [HenriWahl/Nagstamon#300]
Looks like Nagstamon-2.0 (on Windows) uses the _same_ font size for the floating statusbar overview (one line) and details (mouseover). 
For me this means either the one line overview is too small (e.g. the default font size 8) or the details too big (e.g. if I use font size 10).

In version 1.\* I think the one line overview had a bigger font than the details, which is exactly what I want.

Any suggestions?

**Comment by HenriWahl** [comment]
Try font size 9?

**Comment by peterny** [comment]
Font size 9 is a reasonable compromise, but still: 
What I would really like is having a larger font size (e.g. 10) for the one line statusbar overview, and a smaller font size (e.g. 8) for the statusbar details (shown on mouseover). 
I believe  Nagstamon-1.* worked like this by default (font sizes could not be chosen).

**Comment by HenriWahl** [comment]
You are right, 1.0 had different font sizes. The then used GTK seems to use different sizes for labels and tables. The now used Qt apparently doesn't.
Let's see it as advantage that you can change font and size at all - even if it the same for all widgets.

**Comment by peterny** [comment]
Sure, being able to select font size is good, and Nagstamon is still a beauty!
An enhancement request perhaps (to enable different sizes for labels and tables)?
