### ISSUE TITLE
Win 7 x64 doesn't start

### ISSUE THREAD

**Issue by MarcusCaepio** [HenriWahl/Nagstamon#301]
Hi Henry,
Deinstalled the beta version, also removed whole folder and got the 2.0 x64 for win 7.
Nothing appears when I start nagstamon.exe

regards

Marcus

**Comment by HenriWahl** [comment]
can you rename or delete the .nagstamon-folder in your home directory? Just to make sure it does not have a problem with the config.

**Comment by MarcusCaepio** [comment]
remove .nagstamon fixed it.
Maybe the should be include in 00uninst.exe?

**Comment by HenriWahl** [comment]
I know not enough about the installer creation and for many people the update simply works. If their settings will be deleted automatically they won't be happy neither... :-(
