### ISSUE TITLE
Invalid SSL certificates accepted without warning

### ISSUE THREAD

**Issue by sircompo** [HenriWahl/Nagstamon#302]
I've noticed on the IcingaWeb2 monitor, it ignores SSL certificate problems (checked with an expired certificate).
This may also apply to the other types or monitor (I haven't checked).

This is a handy feature, but would be nice if there was a checkbox to skip SSL validation, rather than it being skipped default.

Great job on v2 by the way guys.

**Comment by HenriWahl** [comment]
The SSL/TLS-ignorance was a progress compared to Nagstamon 1 and the problems Python 2.7.9 introduced (see https://github.com/HenriWahl/Nagstamon/issues/126). To check the certificate or deal in general with valid or invalid certificates will be part of a next version, probable THE next one.

**Comment by moschlar** [comment]
For the record, there is also a native Debian bug report about this:
https://bugs.debian.org/861152

**Comment by HenriWahl** [comment]
As far as I know and see the certificate store Python uses is very limited so I assume that almost every connection will be claimed unsecure.
The next version will include a dialog or something like that to inform the user and if the uses Requests library allows it the possibility to add a certificate.

**Comment by moschlar** [comment]
I would already be satisfied by a trust-on-first-use kind of mechanism - then you just had to store the certificate hash within Nagstamon. (Assuming of course, that a user will be able to handle it when some time later the server gets a new certificate and he will be prompted again - which I think is a valid assumption for Nagstamon users). Let's Encrypt users will see that more often, of course, but I think that's ok.

Anyways, I think it would be nice to be able to skip SSL validation per server - not just for the whole application.

**Comment by debfx** [comment]
Python Requests uses its own CA store: http://docs.python-requests.org/en/master/user/advanced/#ca-certificates
It's a copy of the Mozilla CA bundle so it should be fine.
Most Linux distributions likely patch it to use the system store.

**Comment by HenriWahl** [comment]
@debfx this sounds OK - thanks!

**Comment by HenriWahl** [comment]
Last commit brings TLS security by default plus the option to either ignore it or add a custom CA cert. Testers welcome!
