### ISSUE TITLE
Mac version does not quit with open update alert panel

### ISSUE THREAD

**Issue by pierswalter** [HenriWahl/Nagstamon#303]
A very minor nuisance:

Nagstamon 2.0b20160825 displayed an alert panel with information about the 2.0 final release being available. The panel contained a link which I clicked, so the download page opened in my web browser. I then dowloaded and opened the disk image file. Before replacing the beta app with the release app I wanted to quit Nagstamon.

So I tried to use the dock menu item to quit Nagstamon. But **this did not work**. It did not seem to have any effect.

It took me quite a while to figure out what was going on: I was just about to force quit Nagstamon when I finally realized that the update alert panel was still open on one of my monitors.

I assume that this panel is opened as a modal panel which needs to be dismissed before the application can be terminated. 

It may make sense to open this panel in a non-modal way.

**Comment by HenriWahl** [comment]
Your idea makes sense, but looks like especially on MacOS this dialog cannot be made nonmodal. I tried several variants without any of them being of any effect. I fear this will stay as it is. :-(

**Comment by HenriWahl** [comment]
Latest commit contains another attempt to solve this.

**Comment by HenriWahl** [comment]
Either works or is not fixable.
