### ISSUE TITLE
[2.0] does not work on ubuntu 16.04

### ISSUE THREAD

**Issue by MarcusCaepio** [HenriWahl/Nagstamon#304]
Hi Henri,

we have a problem to get Nagsta 2.0 to work.
We have uninstalled the beta package. Also we have deleted the .nagsta folder.
After the installation, the following errors appear:

[Errno 2] No such file or directory: '/home/XXXX/.nagstamon/nagstamon.pid'
Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 53, in <module>
    from Nagstamon.QUI import (APP,
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 32, in <module>
    from PyQt5.QtWidgets import *
ImportError: No module named 'PyQt5'

After creating the folder manually: 

Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 53, in <module>
    from Nagstamon.QUI import (APP,
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 32, in <module>
    from PyQt5.QtWidgets import *
ImportError: No module named 'PyQt5'

OS: Ubuntu Gnome 16.04 

Regards,

Marcus

**Comment by idl0r** [comment]
You'll have to install PyQt5 as well as all other dependencies. I'm not sure how the packages are called there but you need e.g.:
dev-python/PyQt5 with gui, multimedia, svg, widgets
beautifulsoup
dbus-python
keyring (optional)
requests
psutil
setuptools

**Comment by HenriWahl** [comment]
@idl0r is right. Strange the Nagstamon .deb package did not ask for its dependencies - how did you install it?

**Comment by MarcusCaepio** [comment]
Hi all,

we installed with dpkg -i <package>

**Comment by idl0r** [comment]
dpkg will not install any dependencies but it should actually warn/abort if some dependencies are not met. Did you force install it by chance?

**Comment by MarcusCaepio** [comment]
Yep, that fixed it.
