### ISSUE TITLE
[Nagstamon 2.0] Partial host alert

### ISSUE THREAD

**Issue by DeadPixhell** [HenriWahl/Nagstamon#305]
Hi everyone,

I have an issue with Nagstamon 2.0 and Centreon 2.7.4.
Nagstamon see few alerts than Centreon.
Nagstamon see:
![image](https://cloud.githubusercontent.com/assets/12892834/18342963/96924cee-75b1-11e6-8999-ea987164dcc1.png)
Centreon see: 
![image](https://cloud.githubusercontent.com/assets/12892834/18343004/bead90b2-75b1-11e6-98ae-467172721403.png)

Nagstamon Configuration: 
![image](https://cloud.githubusercontent.com/assets/12892834/18343129/5f0ee146-75b2-11e6-833c-a8435d6aafc8.png)
![image](https://cloud.githubusercontent.com/assets/12892834/18343581/3e55e7c2-75b4-11e6-88a2-9e627dd634d9.png)

When i installed Nagstamon i removed all old install.
I don't know why i have partial data. Nagstamon connect well on centreon and get some data.
Debug log:
```
DEBUG: 2016-09-08 08:20:53.421261 Centreon Created server.
DEBUG: Initializing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003B920D8> for state "OK"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003B92048> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003B92168> for state "WARNING"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003B921F8> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003B92288> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003B92318> for state "DOWN"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x0000000003B923A8> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt5.QtGui.QIcon object at 0x0000000003B92438>
DEBUG: 2016-09-08 08:20:54.744337 Centreon FetchURL: http://yyy.xxx.net/centreon/index.php CGI Data: None
DEBUG: 2016-09-08 08:20:55.126359 Centreon Centreon version detected : 2.7
DEBUG: 2016-09-08 08:20:55.126359 Centreon FetchURL: http://yyy.xxx.net/centreon/index.php CGI Data: None
DEBUG: 2016-09-08 08:20:55.272367 Centreon FetchURL: http://yyy.xxx.net/centreon/index.php CGI Data: {'submitLogin': 'Connect', 'password': '[REDACTED]', 'centreon_token': '49ecb17e0a556e5f8dc2f132ea47c677', 'useralias': '[REDACTED]'}
DEBUG: 2016-09-08 08:20:56.027410 Centreon FetchURL: https://nagstamon.ifw-dresden.de/version/stable CGI Data: None
DEBUG: 2016-09-08 08:20:56.437434 Centreon Password login : [REDACTED] : [REDACTED]
DEBUG: 2016-09-08 08:20:56.437434 Centreon SID : 5o6paa7ulj11rgkvlkgct1pd95
DEBUG: 2016-09-08 08:20:56.437434 Centreon FetchURL: http://yyy.xxx.net/centreon/include/monitoring/status/Hosts/xml/broker/hostXML.php?sort_type=status&num=0&sid=5o6paa7ulj11rgkvlkgct1pd95&limit=999&o=hpb CGI Data: None
ERROR: 2016-09-08 08:21:06.237473 Centreon Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.py", line 91, in create_connection
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.py", line 81, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 578, in urlopen
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 351, in _make_request
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 814, in _validate_conn
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 254, in connect
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 147, in _new_conn
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003AEF400>, 'Connection to nagstamon.ifw-dresden.de timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 403, in send
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 623, in urlopen
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\retry.py", line 281, in increment
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nagstamon.ifw-dresden.de', port=443): Max retries exceeded with url: /version/stable (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003AEF400>, 'Connection to nagstamon.ifw-dresden.de timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Generic.py", line 1282, in FetchURL
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 487, in get
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 475, in request
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 585, in send
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 459, in send
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='nagstamon.ifw-dresden.de', port=443): Max retries exceeded with url: /version/stable (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003AEF400>, 'Connection to nagstamon.ifw-dresden.de timed out. (connect timeout=10)'))

DEBUG: 2016-09-08 08:21:06.654723 Centreon FetchURL: http://yyy.xxx.net/centreon/include/monitoring/status/Services/xml/serviceXML.php?sort_type=status&num=0&sid=5o6paa7ulj11rgkvlkgct1pd95&limit=999&o=svcpb CGI Data: None
DEBUG: 2016-09-08 08:21:13.598887 Centreon FetchURL: http://yyy.xxx.net/centreon/include/monitoring/status/Meta/xml/broker/metaServiceXML.php?sort_type=status&num=0&sid=5o6paa7ulj11rgkvlkgct1pd95&limit=999&o=meta CGI Data: None
DEBUG: 2016-09-08 08:22:24.312290 Centreon FetchURL: http://yyy.xxx.net/centreon/include/monitoring/status/Hosts/xml/broker/hostXML.php?sort_type=status&num=0&sid=5o6paa7ulj11rgkvlkgct1pd95&limit=999&o=hpb CGI Data: None
DEBUG: 2016-09-08 08:22:29.779568 Centreon FetchURL: http://yyy.xxx.net/centreon/include/monitoring/status/Services/xml/serviceXML.php?sort_type=status&num=0&sid=5o6paa7ulj11rgkvlkgct1pd95&limit=999&o=svcpb CGI Data: None
DEBUG: 2016-09-08 08:22:35.052730 Centreon FetchURL: http://yyy.xxx.net/centreon/include/monitoring/status/Meta/xml/broker/metaServiceXML.php?sort_type=status&num=0&sid=5o6paa7ulj11rgkvlkgct1pd95&limit=999&o=meta CGI Data: None
DEBUG: 2016-09-08 08:23:41.389508 Centreon FetchURL: http://yyy.xxx.net/centreon/include/monitoring/status/Hosts/xml/broker/hostXML.php?sort_type=status&num=0&sid=5o6paa7ulj11rgkvlkgct1pd95&limit=999&o=hpb CGI Data: None
DEBUG: 2016-09-08 08:23:47.021886 Centreon FetchURL: http://yyy.xxx.net/centreon/include/monitoring/status/Services/xml/serviceXML.php?sort_type=status&num=0&sid=5o6paa7ulj11rgkvlkgct1pd95&limit=999&o=svcpb CGI Data: None
DEBUG: 2016-09-08 08:23:52.993466 Centreon FetchURL: http://yyy.xxx.net/centreon/include/monitoring/status/Meta/xml/broker/metaServiceXML.php?sort_type=status&num=0&sid=5o6paa7ulj11rgkvlkgct1pd95&limit=999&o=meta CGI Data: None
```

Thanks for your help
DeadPixHell

**Comment by HenriWahl** [comment]
Please see https://github.com/HenriWahl/Nagstamon/issues/271#issuecomment-239331642 - there seems to be a problem with Centron < 2.7.6,

**Comment by loic45** [comment]
Hi,

It's my first post in this project, I use Nagstamon 1.0.1 with Centreon 2.6 : all was fine.

Now, i confirm the same problem with Centreon 2.7.6 and nagstamon 2.0 with seven.

If I could help you by posting traces, just tell me as I can do it because my trace file does not indicate debug ...

Thanks for your work ...

**Comment by HenriWahl** [comment]
Is this the latest STABLE Nagstamon 2.0 and no testing preview?

**Comment by loic45** [comment]
No it's the latest stable nagstamon 2.0 dowloaded this monday on official site ...

**Comment by HenriWahl** [comment]
OK. Just to make sure.

**Comment by loic45** [comment]
To be complete :  rpm -qa | grep centreon

centreon-plugins-base-1.16-1.el6.noarch
centreon-engine-1.5.1-3.el6.x86_64
centreon-broker-cbmod-2.11.5-2.el6.x86_64
centreon-widget-service-monitoring-1.4.2-1.el6.noarch
centreon-engine-daemon-1.5.1-3.el6.x86_64
centreon-broker-2.11.5-2.el6.x86_64
centreon-web-2.7.6-4.el6.noarch
centreon-connector-ssh-1.1.2-1.el6.x86_64
centreon-clib-1.4.2-1.el6.x86_64
centreon-plugins-2.7.6-4.el6.noarch
centreon-2.7.6-4.el6.noarch
centreon-bam-server-3.4.2-2.el6.noarch
centreon-widget-host-monitoring-1.4.2-1.el6.noarch
centreon-backup-2.2.0-1.el6.noarch
centreon-connector-perl-1.1.2-1.el6.x86_64
centreon-connector-1.1.2-1.el6.x86_64
centreon-perl-libs-2.7.6-4.el6.noarch
centreon-broker-core-2.11.5-2.el6.x86_64
centreon-trap-2.7.6-4.el6.noarch
centreon-plugin-meta-2.7.6-4.el6.noarch
centreon-widget-hostgroup-monitoring-1.3.0-4.el6.noarch
centreon-widget-graph-monitoring-1.3.0-3.el6.noarch
centreon-common-2.7.6-4.el6.noarch
centreon-engine-extcommands-1.5.1-3.el6.x86_64
centreon-broker-storage-2.11.5-2.el6.x86_64
centreon-base-config-centreon-engine-2.7.6-4.el6.noarch
centreon-widget-servicegroup-monitoring-1.3.1-1.el6.noarch
centreon-broker-cbd-2.11.5-2.el6.x86_64
centreon-lang-fr_FR-2.7-3.el6.noarch

**Comment by DeadPixhell** [comment]
I think I found the origne the problem , when I use the following URL http://x.x.x.x/centreon/include/monitoring/status/Services/xml/serviceXML.php?o=svcpb&limit=999&num=0&sort_type=status copied from the debug file, the returned XML file also contains the services that the state are OK and not sorted, its the same for hostXML.php

Henri i have sent to you my resulting XML file in case you need it.

**Comment by HenriWahl** [comment]
I feared something like this. This trace looks promising!

**Comment by HenriWahl** [comment]
I can confirm that ALL hosts/services are downloaded - I am not sure if it has been always like this. Seems like the server behaviour changed? Sad that the only references regarding the URL of Centreon in this context I found on Google are from Nagstamon...

**Comment by Dodofox** [comment]
Hi everybody
Exactly the same problem here....

![centreon alert](https://cloud.githubusercontent.com/assets/17407992/18465228/f8261d04-7995-11e6-8f14-00c11080f508.PNG)
![nagstamon alert](https://cloud.githubusercontent.com/assets/17407992/18465229/f82c71f4-7995-11e6-84be-514ae5d583cc.PNG)

**Comment by HenriWahl** [comment]
Can you check latest commit https://github.com/HenriWahl/Nagstamon/commit/ca3c8152d1320c604bda72f07d6eac633aa44917 from master source here? Works for me at least.

**Comment by Dodofox** [comment]
Hi,


I would like to try this commit, but it would be easier to have the exe version. ( I don't know how to compile and i'm not admin on my client computer)...


Thanks,


Dorian


________________________________
De : Henri Wahl <notifications@github.com>
Envoyé : lundi 26 septembre 2016 21:53
À : HenriWahl/Nagstamon
Cc : Dodofox; Manual
Objet : Re: [HenriWahl/Nagstamon] [Nagstamon 2.0] Partial host alert (#305)


Can you check latest commit ca3c815<https://github.com/HenriWahl/Nagstamon/commit/ca3c8152d1320c604bda72f07d6eac633aa44917> from master source here? Works for me at least.

-

**Comment by HenriWahl** [comment]
Are 64 bit sufficient?

**Comment by DeadPixhell** [comment]
it's sufficient for me

Thanks

**Comment by HenriWahl** [comment]
Please check https://seafile.ifw-dresden.de/f/7b79c7a210/?raw=1 - it's a ZIP file for standalone use.

**Comment by DeadPixhell** [comment]
Downloaded, tested, And it's work fine !

![image](https://cloud.githubusercontent.com/assets/12892834/18869460/babc9412-84ac-11e6-8af3-52a94ff49773.png)

![image](https://cloud.githubusercontent.com/assets/12892834/18869467/c8d36ab2-84ac-11e6-9846-22dfa86aa5d1.png)

Thanks Henri

**Comment by Dodofox** [comment]
Yes that works for me  !!! thanks a lots :)

**Comment by HenriWahl** [comment]
I forward your thanks to @BenoitPoulet and @julienmathis :-)

**Comment by loic45** [comment]
Hello ! It 's OK for me !!! Thanks a lot

**Comment by sideneif** [comment]
Hello guys
Can someone pass me this file?
Link is broken.
_"Please check https://seafile.ifw-dresden.de/f/7b79c7a210/?raw=1 - it's a ZIP file for standalone use."_

I am having the same problem reported above.
Thank you.
