### ISSUE TITLE
Program crashes after click to "Recheck All" 

### ISSUE THREAD

**Issue by Widmo** [HenriWahl/Nagstamon#307]
No any special error in debug.

http://pastebin.com/raw/dahE0272

**Comment by HenriWahl** [comment]
Looks you use several monitor servers - can you find out which one is involved when crashing? All or one special one=

**Comment by Widmo** [comment]
Found one, if disabled, buttor recheck all works. 

Bugmaker: Latest Nagios XI

**Comment by HenriWahl** [comment]
OK Thanks. I try to find more out with bugfix release 2.0.1.

**Comment by HenriWahl** [comment]
Could not reproduce with http://nagiosxi.demos.nagios.com/. Can you run it in a console window from source to get some extra crash output?

**Comment by Widmo** [comment]
Use it on Windows, running from console did't show any log or backtrace (would be nice to run nagstamon.exe /debug to get log's) 

Filetext log's shows nothing.

**Comment by HenriWahl** [comment]
What is you Nagios XI version?

**Comment by Widmo** [comment]
Nagios XI 5.2.9

**Comment by HenriWahl** [comment]
5? - well, I have no chance to test it.
The most useful would be some console output anyway. At https://nagstamon.ifw-dresden.de/docs/requirements/ there are some notes what you need for this - maybe you get it running?

**Comment by pudding90** [comment]
i got the same issue and i fixed it by editing the cgi url

from
https://xxxx.xx/nagios/cgi-bin/status.cgi
to
https://xxxx.xx/nagios/cgi-bin/

hope i could help.

**Comment by Widmo** [comment]
I have https://xxxx.xx/nagios/cgi-bin/ from the beginning :(

**Comment by avnlevent** [comment]
The problem is if you use the normal nagios user.
When I use the Nagiosadmin user, it works.

**Comment by HenriWahl** [comment]
What is the difference?

**Comment by avnlevent** [comment]
I mean that if you input the Nagiosadmin user, then the "Recheck All" will work perfectly otherwise it will exit when you click the "Recheck All".

**Comment by HenriWahl** [comment]
Yes, but what is the difference between the users? Do they have different rights?

**Comment by avnlevent** [comment]
The normal user don't have the rights to make a schedule check.
Below is the message when I tried to do schedule check by normal user on Nagios 4.x

_"It appears as though you do not have permission to submit the command you requested...
If you believe this is an error, check the HTTP server authentication requirements for accessing this CGI
and check the authorization options in your CGI configuration file."_

**Comment by HenriWahl** [comment]
As silly as is sounds but the recheck crashed the whole application if the URL for CGI was wrong... maybe there should be only one URL and the CGI-URL should be derived from that...
