### ISSUE TITLE
Custom notification actions

### ISSUE THREAD

**Issue by xelite** [HenriWahl/Nagstamon#308]
I would like to use custom notification actions only for CRITICAL events eg.

/path/to/script $HOST$ "$SERVICE$"

...but placeholder variables are empty. Could you add placeholder variables from Actions menu to Notifications?

**Comment by HenriWahl** [comment]
Quite probably you found a bug. Was at least intented to work like you expected... goes into 2.0.1 bugfix release.

**Comment by HenriWahl** [comment]
I found this would need larger rework so I would consider it for a 2.x release. Maybe the $EVENTS$ variable might help you out here?

**Comment by xelite** [comment]
Yes. I'll parse it as arguments of external script.

**Comment by littlejo** [comment]
Hello,

i try:
~/nagstamon.sh "$EVENTS$"

but it doesn't work.

**Comment by xevilstar** [comment]
bump please I need it to work

**Comment by HenriWahl** [comment]
Please check latest unstable where I fixed these custom notifications.

**Comment by remoteitguy** [comment]
Doesn't seem to work still with version 3.1-20171030.
The following works with a custom notification action:

echo "$EVENTS$" | espeak -s 95  -p 10 -v en+f9

However I only get the interrruption alerts, not the recoveries. 

When I put the same in the notification actions, I get nothing at all.

**Comment by cerberus10** [comment]
I think $EVENT$ WORKS BUT $EVENTS$  doesnt.

**Comment by HenriWahl** [comment]
@remoteitguy Nagstamon ever knew only about the problems, not the recoveries. Your monitoring server schould tell you about recoveries.
@cerberus10 I will check this again. Did you use it with single action for every event action or the one which needs a seperator?

**Comment by remoteitguy** [comment]
Even for the notification actions? There is a section for OK's. And an alert when I use the 'Enable Sound" feature. Basically what I'm trying to do is use espeak to say the alert notifications. So looking at nagstamon or nagios isn't required.

**Comment by cerberus10** [comment]
Yes I am using single event  action with $EVENT$ and it works that way.

**Comment by remoteitguy** [comment]
@cerberus10  Would you mind sharing how you're  piping hte placeholder?

**Comment by billyjack669** [comment]
My Nagstamon doesn't perform actions on OK status.  According to the Nagstamon features for actions, "The first allows to define some command to be run if one of the states WARNING, CRITICAL, DOWN or **OK** appears. "  
I've run through the log and don't see any notification actions when Nagstamon reports OK.
