### ISSUE TITLE
nagstamon-2.0 on one screen

### ISSUE THREAD

**Issue by wiqert** [HenriWahl/Nagstamon#309]
Before upgrading to 2.0 nagstamon shosw 'floating statusbar' on all of virtual desktops (linux). Now it's only on one desktop.

**Comment by HenriWahl** [comment]
Which distro do you use?

**Comment by wiqert** [comment]
Ubuntu 14.04.4 LTS with gnome3.

Now I see that statusbar jump into current screen after refresh with crit/warns

**Comment by HenriWahl** [comment]
GNOME3 should work... but this is a complicated field in general. Different environments treat some poor little window wishing to stay on every desktop differently. Ubuntu Unity is the worst in this respect...
In your case I guess the Qt5 coming with Ubuntu 14.04 is quite outdated - did you consider an upgrade to latest 16.04 LTS?

**Comment by wiqert** [comment]
I try to upgrade in a few days, not easy at desktop in work. Thanks for answer
