### ISSUE TITLE
server monitor name can't contain slashes

### ISSUE THREAD

**Issue by rutsky** [HenriWahl/Nagstamon#310]
When I try to set monitoring name to something like: "server/path", nagstamon crashes with `FileNotFoundError` in `SaveMultipleConfig()`: `[Errno 2] No such file or directory: '/home/user/.nagstamon/servers/server_server/path.conf'.

**Comment by HenriWahl** [comment]
Yes, the servername is used in server config filename... well, is it possible to use some non-slash-containing server name?

**Comment by HenriWahl** [comment]
Might be worth a look to abstract file name from real server name to be able to fix problems like in https://github.com/HenriWahl/Nagstamon/issues/306 too.

**Comment by rutsky** [comment]
@HenriWahl, thanks for the response. Yes, I workarounded this issue by removing slashes from the monitoring name, so this is not a critical bug for me.

But in general this is very unexpected behavior. Either it shouldn't be possible to specify such name in the GUI, or such name should work.

**Comment by HenriWahl** [comment]
Quite probably fixed in latest commit https://github.com/HenriWahl/Nagstamon/commit/c8446e54ae76edfa5bb71cd952e1b2319e37d8da
