### ISSUE TITLE
Mac app does not correctly handle notification actions

### ISSUE THREAD

**Issue by mightyoj** [HenriWahl/Nagstamon#311]
When launched through the .app wrapper, none of the notification actions are used. Sporadically, you can hear the notification sounds. 

When launched through the file located at /Applications/Nagstamon-2.0.app/Contents/MacOS/nagstamon, the notification actions usually work, though this does have a high degree of failure on the OK action. 

I have a blink(1) LED device that a shell script controls via parameterized conditions (blink red for crit, yellow for warn, etc). The script is called via the notification actions and none of that works or is logged even with debug logging on the release version.

I am on OS X El Capitan, 10.11.6 using the latest release version of Nagstamon with a Nagios 4.1.1 system.

**Comment by HenriWahl** [comment]
How do your notification actions look like?

**Comment by mightyoj** [comment]
they go to a script that i have based on the wrapper found at https://1337.tips/using-blink1-mk2-with-nagiosnagstamon/

**Comment by mightyoj** [comment]
I am now using the windows application and the same issue is present here. This time I am not using any custom notification script here but just the custom actions that are already built into the GUI. The warning and critical actions work, however, the OK action is never fired. This occurs in 2.0 as well as 2.1. 

I will fork 2.1 and see if I can offer a patch.

**Comment by HenriWahl** [comment]
Unclear state - reopen if any news.
