### ISSUE TITLE
Process does not terminate on "quit" (Ubuntu 16.04, Nagstamon 2.0)

### ISSUE THREAD

**Issue by XnS** [HenriWahl/Nagstamon#314]
Hi,

OS: Ubuntu 16.04.1 LTS
Nagstamon 2.0
- If I rightclick on nagstamon in the Ubuntu launcher and hit "quit", the overlay closes but the process does not exit/terminate.
- If I start nagstamon within a terminal session and hit ctrl+c it does not even close the overlay and keeps running.
  Terminal output:

> ^CTraceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/Nagstamon/QUI/**init**.py", line 2249, in reset
>     @pyqtSlot()
> KeyboardInterrupt
- If I click on the burger menu in the nagstamon overlay and choose "exit", everything works fine.

Old (1.x) config was removed before starting 2.0 for the first time.

Regards,
XnS

**Comment by HenriWahl** [comment]
Do you use Unity?

**Comment by XnS** [comment]
Oh sorry, forgot that part. Yes, unity 7.4.0

**Comment by HenriWahl** [comment]
By Ubuntu launcher you mean the dock on the left side of the screen?

**Comment by HenriWahl** [comment]
I tried and found the same effect. I do not know ift Nagstamon gets a killing signal from Unity but at least Unity kills the windows. Looks almost like Nagstamon has no clue of its non-existence...

**Comment by HenriWahl** [comment]
Let's hope the next versions of Ubuntu without Unity finally will solve this issue...
