### ISSUE TITLE
Feature Request: Different views for the same nagios instance

### ISSUE THREAD

**Issue by kasimon** [HenriWahl/Nagstamon#316]
It would be quite helpful to be able to define different views for one nagios instance and be able to easily switch between them because, depending on what I'm working on, I'm interested in different subsets of the current nagios alarms. For example if you monitor available package updates and a commonly used package enters the repository, it would be nice to define a view without the update service so I can still see what's important without the list being cluttered with hundreds of update warnings.

**Comment by HenriWahl** [comment]
Do you mean monitor specific filters?

**Comment by kasimon** [comment]
I'm not sure it's exactly that. Maybe a better analogy would be to add the ability to configure multiple dashboards that provide different views on the data provided by nagios, and easily switch between them. Each dashboard could have different settings regarding host and service filters, criticality states to be displayed, sort order and so on - all the settings that currently can only be set globally for the whole application.

**Comment by HenriWahl** [comment]
In the meantime you could just run several instances of Nagstamon which is possible by running it with different configurations as argument.
