### ISSUE TITLE
nagstamon 2.0 crashes with dbus exception

### ISSUE THREAD

**Issue by magenbrot** [HenriWahl/Nagstamon#320]
nagstamon 2.0 crashes after a few minutes running. this is what I get if I start it via my terminal:

```
$ nagstamon 
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 1836, in desktop_notification
    dbus_connection.show(AppInfo.NAME, message)
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 6112, in show
    self.timeout)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.370 was not provided by any .service files
Aborted
```

this happens on Linux Mint 18 MATE Edition

```
$ inxi -Fxz
System:    Host: noname Kernel: 4.7.4-040704-generic x86_64 (64 bit gcc: 6.2.0)
           Desktop: MATE 1.14.1 (Gtk 3.18.9-1ubuntu3.1) Distro: Linux Mint 18 Sarah
Machine:   Mobo: Motherboard by ZOTAC model: ZBOX- EN979 v: Rev.00
           Bios: American Megatrends v: B286Z009 date: 06/28/2016
CPU:       Quad core Intel Core i5-6400T (-MCP-) cache: 6144 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 17663
           clock speeds: max: 2800 MHz 1: 800 MHz 2: 800 MHz 3: 800 MHz 4: 799 MHz
Graphics:  Card: NVIDIA GM204M [GeForce GTX 970M] bus-ID: 01:00.0
           Display Server: X.Org 1.18.3 drivers: nvidia (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
           GLX Renderer: GeForce GTX 960/PCIe/SSE2 GLX Version: 4.5.0 NVIDIA 367.44 Direct Rendering: Yes
Audio:     Card-1 NVIDIA GM204 High Definition Audio Controller driver: snd_hda_intel bus-ID: 01:00.1
           Card-2 Intel Sunrise Point-H HD Audio driver: snd_hda_intel bus-ID: 00:1f.3
           Card-3 Logitech Webcam C200 driver: USB Audio usb-ID: 001-004
           Sound: Advanced Linux Sound Architecture v: k4.7.4-040704-generic
Network:   Card-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: d000 bus-ID: 02:00.0
           IF: enp2s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
           Card-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: c000 bus-ID: 03:00.0
           IF: enp3s0 state: down mac: <filter>
           Card-3: Intel Wireless 3165 driver: iwlwifi bus-ID: 04:00.0
           IF: wlp4s0 state: down mac: <filter>
Drives:    HDD Total Size: 480.1GB (15.5% used) ID-1: /dev/sda model: SAMSUNG_MZ7LM480 size: 480.1GB temp: 0C
Partition: ID-1: / size: 424G used: 55G (14%) fs: ext4 dev: /dev/dm-1
           ID-2: /boot size: 473M used: 193M (43%) fs: ext2 dev: /dev/sda2
           ID-3: swap-1 size: 17.14GB used: 0.00GB (0%) fs: swap dev: /dev/dm-2
Sensors:   System Temperatures: cpu: 29.8C mobo: 27.8C gpu: 0.0:47C
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 300 Uptime: 1 day Memory: 5100.2/16013.4MB Init: systemd runlevel: 5 Gcc sys: 5.4.0
           Client: Shell (bash 4.3.421) inxi: 2.2.35 
```

**Comment by HenriWahl** [comment]
Which mode do you use? Systray, floating statusbar or fullscreen?

**Comment by magenbrot** [comment]
I use the systray mode

**Comment by HenriWahl** [comment]
Do you have desktop notifications enabled?

**Comment by magenbrot** [comment]
yes, I do

**Comment by HenriWahl** [comment]
Can you try without desktop notification? Just for fun...

**Comment by magenbrot** [comment]
sure, I'll report back on friday

**Comment by magenbrot** [comment]
Hey, sorry for the late response.

Since I've disabled the notifications nagstamon didn't crash anymore.

**Comment by HenriWahl** [comment]
Ok so DBus is the problem. Did desktop notifications show up or did the crash happen before?
The error message about a missing .service file seems pretty cryptic anyway.

**Comment by magenbrot** [comment]
immediately after start it shows the notification of current services/hosts with problems. I can also click the button to show the status window. It seems to crash sometime later.

it seems that the error with those service files changes on every crash:
`dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.79 was not provided by any .service files`

**Comment by HenriWahl** [comment]
Hm, sounds rather esoteric. I might try to reproduce soon.

**Comment by HenriWahl** [comment]
On Fedora there is a package mate-notification-daemon which seems to provide a .service file in /usr/share/dbus-1/services which cares about notifications. Is there anything like this in Mint?

**Comment by magenbrot** [comment]
yes, it's installed and the service-file is in place: 
```$ cat /usr/share/dbus-1/services/org.freedesktop.mate.Notifications.service

[D-BUS Service]
Name=org.freedesktop.Notifications
Exec=/usr/lib/mate-notification-daemon/mate-notification-daemon
```

**Comment by HenriWahl** [comment]
Strange, strange... in the latest commit there is at least a workaround - if DBus cannot be initialized it will be simply ignored.
But another idea... to initialize notificiations Nagstamon tries in line 6116 of QUI/__init__.py to access path /org/freedesktop/Notifications which clearly corresponds to /usr/share/dbus-1/services/org.freedesktop.Notifications.service. In case of MATE this seems to be org.freedesktop.mate.Notifications.servise. Can you simply add a symlink named org.freedesktop.Notifications.service pointing to your org.freedesktop.mate.Notifications.service? Just to see if it would work?

**Comment by magenbrot** [comment]
ok, did that. Let's see if it helps.

```
/usr/share/dbus-1/services# ll org.freedesktop.*Notification*
-rw-r--r-- 1 root root 115 Sep 21 18:06 org.freedesktop.mate.Notifications.service
lrwxrwxrwx 1 root root  42 Oct 18 09:33 org.freedesktop.Notifications.service -> org.freedesktop.mate.Notifications.service
```

**Comment by HenriWahl** [comment]
I tried meanwhile and it didn't. But the latest commits should just work around DBus.

**Comment by magenbrot** [comment]
yeah, I noticed the same. It didn't work.
´´´
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.63 was not provided by any .service files
´´´

Do you have an idea where the number after "name: " is coming from? Is this internal variable or maybe performance data of one of the icinga checks?

**Comment by HenriWahl** [comment]
Really no idea, sorry. 
Did you try with the latest 20161017 beta?

**Comment by magenbrot** [comment]
yep, but it just crashed with the same error message as the release version.

**Comment by HenriWahl** [comment]
Can you please post the error message here again?

**Comment by magenbrot** [comment]
sure :)
```
$ nagstamon
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 1837, in desktop_notification
    dbus_connection.show(AppInfo.NAME, message)
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 6145, in show
    self.timeout)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.123 was not provided by any .service files
Aborted
```

**Comment by HenriWahl** [comment]
However they manage to produce that crash there at Mint... needs more investigations - I fear I need to set up a Mint VM. Which Mint release do you use exactly? Mint 18 MATE?

**Comment by magenbrot** [comment]
exactly. You can find the relevant information in the first post (inxi). The only non-standard thing is the running kernel (I'm on 4.8.1 right now, 4.4.0(.21) is delivered with mint currently).

**Comment by HenriWahl** [comment]
Set up a Mint VM. Running Nagstamon from source as 2.0 and latest 2.0.1 simply works. Same with 2.0.1-20161017 .deb. :-(
![nagstamon_mint_dbus](https://cloud.githubusercontent.com/assets/2835065/19511906/a78be606-95e9-11e6-9fb8-ee1d855b7971.png)

**Comment by HenriWahl** [comment]
Out of nowhere it crashed now....

henri@mint18mate ~/Nagstamon $ nagstamon 

    QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout

    QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout

    QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout

    /usr/lib/python3/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: 
    https://urllib3.readthedocs.org/en/latest/security.html

      InsecureRequestWarning)

    Traceback (most recent call last):
  
    File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 1837, in desktop_notification
    dbus_connection.show(AppInfo.NAME, message)
  
    File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 6145, in show
    self.timeout)

      File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)

      File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)

    dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.94 was not provided by any .service files

    Aborted

**Comment by HenriWahl** [comment]
Added workaround in https://github.com/HenriWahl/Nagstamon/commit/8ff98b4afd92cf62b6325b589e73cd557ae476ee - can you check this from source?

**Comment by magenbrot** [comment]
sure, I'll give it a try :)

**Comment by magenbrot** [comment]
seems to be fine now. It doesn't crash any more, just skips the error and goes on ;)

**Comment by HenriWahl** [comment]
Does it display notifications or not?

**Comment by HenriWahl** [comment]
Latest commit version as .deb file: https://seafile.ifw-dresden.de/f/aa7d77382f/

**Comment by magenbrot** [comment]
I've installed the deb and tried again. nagstamon doesn't show notifications anymore

**Comment by HenriWahl** [comment]
So this is no real solution but a workaround for a mysterious problem. It is hard to find out for Nagstamon that DBus actually does NOT work even if it claims so at start - time for fuzzy logic?

**Comment by lolorc** [comment]
looks like ubuntu zesty has the workaround patch and it still does crash with notification disabled and notification-daemon not running, yuk
