### ISSUE TITLE
Crash with Thruk on StartUp-Login - Referencing session too early

### ISSUE THREAD

**Issue by ToMoritz** [HenriWahl/Nagstamon#321]
Version: 2.0 Final.
Platform: Windows X64.
Server-Type: Thruk

When starting Nagstamon, a login-prompt is generated.
When the users fills in the correct credentials, Nagstamon exits immediatly.
When the user clicks Cancel, Nagstamon starts normally. If credentials are entered in settings after startup, Login is successfull and everything is fine. So only the login during startup is buggy.

Because debug logging seems to be broken currently (at least this version on this platform), I reproduced the issue based on python source code instead of the binaries.
This is the error message before the applications exits:

`Traceback (most recent call last):`
`  File "C:\Daten\install\Nagstamon\src\Nagstamon\Nagstamon\QUI\__init__.py", line 5785, in ok`
`    self.server.reset_HTTP()`
`  File "C:\Daten\install\Nagstamon\src\Nagstamon\Nagstamon\Servers\Thruk.py", line 75, in reset_HTTP`
`    if len(self.session.cookies) > 1:`
`AttributeError: 'NoneType' object has no attribute 'cookies'`

It seems that during that initial cookie check, a sessions is not existing.
I've put an exception handler about this problematic code, the issue is fixed.

**Old code:**

    def reset_HTTP(self):
    """
        brute force reset by GenericServer disturbs logging in into Thruk
    """
        # only reset session if Thruks 2 cookies are there
        if len(self.session.cookies) > 1:
            self.session = None

**New code:**

    def reset_HTTP(self):
        """
            brute force reset by GenericServer disturbs logging in into Thruk
        """
        try:
            # only reset session if Thruks 2 cookies are there
            if len(self.session.cookies) > 1:
                self.session = None
        except:
            self.Error(sys.exc_info())

Can someone please verify this?
Thank you :)

**Comment by HenriWahl** [comment]
Interesting find. Can you make a pull request of this?

**Comment by HenriWahl** [comment]
Included fix in commit https://github.com/HenriWahl/Nagstamon/commit/ae7459a840cda249b767ac517c1517f4bf528f72
