### ISSUE TITLE
leave status bar after clicking/opening

### ISSUE THREAD

**Issue by rysic** [HenriWahl/Nagstamon#322]
As I remember, in Nagstamon 1.X when I was clicking on it (to open detailed view) the statusbar was still displayed. Then I was able to click it again and Nagstamon detailed view was closing. In Nagstamon 2.0 when I  expand it, I'm not able to click again and close it. Is it possible to add option in Settings to close Nagstamon detailed view when clicking on first top bar (this with title "nagstamon 2.0")? Or option to leave statusbar after opening Nagstamon detailed view?

It can be very usefull especially for people with small screens and many warnings. There will be no need for searching X for window closing and it can even speedup work for other people.

**Comment by HenriWahl** [comment]
If you selected close on click just click somewhere in the top area - should close the status window too.

**Comment by HenriWahl** [comment]
At least it was intended to work like this...

**Comment by rysic** [comment]
It is working! :-) ...but what if I want to have both options?
Close when outside window and when clicking? :-)

**Comment by rysic** [comment]
Anyway, is it possible to make first bar thinner? This with Filter, Refresh, Settings options? This way we will be able to see one more service on screen :-D Or maky it option in settings :-)

**Comment by HenriWahl** [comment]
Good ideas, might take them into the next stable release.

**Comment by rysic** [comment]
Thanks for help!
Anyway, really nice soft!!! A lot of good coding! :-D

**Comment by HenriWahl** [comment]
Done in latest commit c534254a3aa17ab64bf59f83f5285dd57af36900 - now a toparea click closes the statuswindow. Expect binaries flagged "20170724" soon.
