### ISSUE TITLE
Does it work with zabbix 3.2?

### ISSUE THREAD

**Issue by mykolq** [HenriWahl/Nagstamon#323]
Does it work with zabbix 3.2?

**Comment by HenriWahl** [comment]
I honestly do not know - but just try it.

**Comment by mykolq** [comment]
Doesn't  =(

**Comment by mprenditore** [comment]
It works.. I use it without any problem. What problem do you have?

**Comment by mykolq** [comment]
Hello, @mprenditore 
![nagstamonerror](https://cloud.githubusercontent.com/assets/935567/19521871/f878431e-961d-11e6-9841-8683992f5636.png)
![nagstamosettings](https://cloud.githubusercontent.com/assets/935567/19521879/fd27f382-961d-11e6-9a43-8e329f7d7806.png)
