### ISSUE TITLE
Nagstamon VS Centreon Limit 5000

### ISSUE THREAD

**Issue by Thiefoumongars** [HenriWahl/Nagstamon#325]
Good day,

Is there any possibility to set the Limit of result in the Console "setting" interface instaed of Hardcoded on the soft ?
I have more than 5000 service and my nagstamon don't show me some service.
Thanks,

**Comment by HenriWahl** [comment]
Which version do you refer to?

**Comment by Thiefoumongars** [comment]
Version 2.0

**Comment by HenriWahl** [comment]
Please use the latest beta of 2.0.1 which addresses Centreon.

**Comment by Thiefoumongars** [comment]
Testing it, will open another case if the issue is still there, i don't want to create issue for test :)Thanks a lot for your fast answer

**Comment by HenriWahl** [comment]
Sounds like https://github.com/HenriWahl/Nagstamon/issues/305.

**Comment by BenoitPoulet** [comment]
This issue can be close, this pb has been resolved at least in the last build from october.

**Comment by HenriWahl** [comment]
So it shall be too...
