### ISSUE TITLE
Nagstamon crashes after re-install

### ISSUE THREAD

**Issue by scrubby** [HenriWahl/Nagstamon#327]
After installing the latest version, Nagstamon keep crashing as soon as I start it. When I run is from the console, I get the following output.

Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 128, in <module>
    output = GUI.GUI(conf=conf, servers=servers, Resources=Resources, debug_queue=debug_queue, GUILock=GUILock)
  File "/usr/share/nagstamon/Nagstamon/GUI.py", line 249, in **init**
    self.startup_sort_field = self.COLUMNS_IDS_MAP[self.conf.default_sort_field]
KeyError: 'status'

**Comment by HenriWahl** [comment]
Looks like Nagstamon 1.x - the 2.x has no GUI.py.

**Comment by HenriWahl** [comment]
Please install a recent release.
