### ISSUE TITLE
Hide Mac App from Dock

### ISSUE THREAD

**Issue by n3r0-ch** [HenriWahl/Nagstamon#333]
I think the Nagstamon App should not be visible in the dock on Mac. This would be possible by editing the `Info.plist` and add the following line:

```
<key>LSUIElement</key>
<true/>
```

Further information: https://www.cnet.com/news/prevent-an-applications-dock-icons-from-showing-in-os-x/

**Comment by HenriWahl** [comment]
Sounds good - thanks for the Info.plist hint, will check this out when again in front of a Mac.

**Comment by HenriWahl** [comment]
@n3r0-ch @soxwellfb As showing Nagstamon on all spaces/virtual desktops seems more important than not showing its icon in the doc I would prefer https://github.com/HenriWahl/Nagstamon/issues/334 which allows even this. As this information goes into the Info.plist file it can't be an option in Nagstamon settings.

**Comment by soxwellfb** [comment]
My obvious preference is that the dock icon stays, but that's what suits my use case. Annoying that it

It looks like it might be possible programatically via setActivationPolicy:NSApplicationActivationPolicyProhibited 

See:http://stackoverflow.com/questions/6796028/start-a-gui-process-in-mac-os-x-without-dock-icon

**Comment by HenriWahl** [comment]
@n3r0-ch @soxwellfb please try latest release https://github.com/HenriWahl/Nagstamon/releases/download/latest/Nagstamon.3.11-20230227.dmg which improved the no-icon-on-dock-behavior by allowing keyboard focus in dialogs when hidden.
