### ISSUE TITLE
Windows tray mode doesn't collapse all the way

### ISSUE THREAD

**Issue by jwhipp** [HenriWahl/Nagstamon#336]
I have 2.0.1 in tray mode, when I click the icon, it opens as expected.  When I leave or click the x (or leave in hover mode), I am left with a portion of the nagstamon screen running:

![nagleftover](https://cloud.githubusercontent.com/assets/556332/20225978/5dc627c6-a803-11e6-9267-65d1ca9a15c8.PNG)

All the visible buttons are clickable so one can simply click the close box (again).   The expected behavior is one close (or leave if in hover mode) show fully collapse the screen to the tray icon.

**Comment by HenriWahl** [comment]
Does this always happen? Only on Windows 10?

**Comment by HenriWahl** [comment]
I can't reproduce this behaviour neither in click or hover mode. Any special conditions over there? What monitor type do you use?

**Comment by jwhipp** [comment]
I've seen it on both my laptop and my desktop, only on Windows 10, it's the only Windows I am running.

I do have uxstyle installed, and a different theme for windows.  I can reset to stock and test again later tonight.

**Comment by jwhipp** [comment]
I can't get it to happen now, must have something to do with interaction or when a certain amount of stuff is on the screen.  If I can find a reliable way to replicate it, I'll re-open the issue.
