### ISSUE TITLE
Nagstamon segfaults on exit on Fedora

### ISSUE THREAD

**Issue by MedicMomcilo** [HenriWahl/Nagstamon#338]
Nagstamon 2.0.1 works flawlessly on Fedora with exception of segfaulting on exit.
Please let me know how can I gather 'verbose' output or any debug info for this.

At the moment it just says:
$ nagstamon 
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
Segmentation fault (core dumped)

I'll be happy to provide more info.

**Comment by HenriWahl** [comment]
Yes, this nags me since months but I did not found a reason or even a solution. I assume something Qt-related but really have no idea how to debug this. :-(

**Comment by mprenditore** [comment]
I'm searching a solution on this bug too without any success for now. I'm on Fedora too and the problem still remain even on Fedora 25 that use Wayland.
I don't know if it's related to Qt because the error up there aren't blocking...
I'll keep to search about it and keep updated.

**Comment by HenriWahl** [comment]
I have not seen this on Windows or MacOS. Only Fedora cries about these errors. Even never seen on Debian or Ubuntu.

**Comment by mprenditore** [comment]
I didn't tested it on other Linux distro but I'll try.

**Comment by mprenditore** [comment]
After a deep search, I found out why it goes in segmentation fault on Fedora (don't know if also on other distro). It's a bug on QT5 version 5.5+ (on Fedora 25 there is version 5.7)... Here the bug reference: https://bugreports.qt.io/browse/QTBUG-49594

On Debian 8 it works because QT5 are at version 5.3.

I searched out for a solution but did't find it...

**Comment by HenriWahl** [comment]
Bad news but at least there is some reason...

**Comment by HenriWahl** [comment]
We can't fix this, just hope Qt5 will work correctly one day.

**Comment by HenriWahl** [comment]
BTW, did not see the error in Fedora26 anymore...

**Comment by MedicMomcilo** [comment]
Hey Henri,

Indeed this is no longer the case for Wayland (even tested on Rawhide).
However, I did need to "touch ~/.Xauthority" to be able to start it, but that's minor issue.

Kind regards,
Momo.
