### ISSUE TITLE
nagstamon not even open. 

### ISSUE THREAD

**Issue by cafranjul** [HenriWahl/Nagstamon#340]
Hey, 

I have a problem with a fresh install of nagstamon. the software doesn't even open, no error, no nothing... I can't event see the process in the taskmanager.  

nagstamon version: 2.0.1

my computer:
Dell OptiFlex 5040
Ram: 8gb 
processor: Intel i5-6500 CPU @ 3.20GHz (4 CPUs)
os: win10 ent

thoughts?

**Comment by HenriWahl** [comment]
Strange... any special conditions/programs installed?

**Comment by HenriWahl** [comment]
Any old .nagstamon config file in your profile?

**Comment by cafranjul** [comment]
*** Sophos Antivirus, no warnings, no threat detections, 

I've unistalled and install again the software and nothing seems to work. can you give me the path should I need to look for old profiles?

**Comment by HenriWahl** [comment]
In you home directory C:/Users/cafranjul there should be a folder .nagstamon (yes, with dot - Unix-style...).

**Comment by cafranjul** [comment]
Thank you Henri,  that did the trick, I remove the  .nagstamon directory then the app re-create a new one, the application now opens just fine.  I guess I had a hell of a config files there ....

**Comment by HenriWahl** [comment]
:-)
