### ISSUE TITLE
Icingaweb2 -> Nagstamon just ends

### ISSUE THREAD

**Issue by ponchofiesta** [HenriWahl/Nagstamon#341]
I tried to set up our Icingaweb2 interface in Nagstamon but the process simply ends without any message. I do very shortly see the icon with green "OK".

I tried Nagstamon 2.0-win64 and 2.1-20161129-win64.

I'm using Windows 7 64bit, Icinga 2.5.4 with Icingaweb2 2.3.4.

I also enabled debug mode to file but the log file stays empty.

EDIT:
I enabled "Do not use cookie authentication" and now it works. But the "crash" should be fixed.

**Comment by HenriWahl** [comment]
Yes indeed. Thanks for reporting.

**Comment by HenriWahl** [comment]
Should be fixed.

**Comment by ponchofiesta** [comment]
Thanks. I'm not working for several months. So I can not check if it is working now. And even if I would, before I went I changed the authentication mode on the server to not use http auth. Nevertheless thank you.
