### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by micah** [HenriWahl/Nagstamon#346]
Hi,

I am running the unstable debian packaged version, and I am getting this error for one of the nagios instances I monitor:

```
ERROR: 2017-01-10 13:46:55.792586 foo Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Generic.py", line 544, in _get_status
    table = htobj('table', {'class': 'status'})[0]
IndexError: list index out of range
```

I'm happy to provide any more info if needed!

**Comment by micah** [comment]
Stefano Stella <notifications@github.com> writes:

> Can you check if the url for Nagios is correct? because seems that it fails to get informations.
> If it's right, enable debug and debug to file, close and opena again Nagstamon till it crash and post here the debug...

It seems that the URL for Nagios was correct, but the CGI URL was
producing a Nagios error because the configuration had a syntax
error.

It took me some time to realize that was the problem! Perhaps nagstamon
could catch that exception and provide a useful error message?

A couple other notes:

 . I enabled debug and had it go to a file, but it wasn't writing to the
 file. I was able to get the debug output to the screen
 though. Mysteriously, some debug output did end up in the file when I
 exited though.

 . When I exited, I would get a segfault.

**Comment by mprenditore** [comment]
@micah What was the syntax error? Was it bad generated by Nagstamon?
Indeed it can be useful to print out the error... I'm working on that code so I'll try to add it as soon as I'll finished my implementations.

Usually all the debug informations should go to the file, not just some of them... can you share the debug file?

Which OS are you using? And which version of QT5 you have installed?

**Comment by HenriWahl** [comment]
No further information...
