### ISSUE TITLE
Empty "Acknowledge service" window remains and can't be closed

### ISSUE THREAD

**Issue by cverbiest** [HenriWahl/Nagstamon#347]
Occasionally I see an empty Acknowledge window like this
![image](https://cloud.githubusercontent.com/assets/1312691/21846406/45a3adb6-d7f7-11e6-9cda-81766335f344.png)
this cannot be closed by clicking the [X]. You need to restart nagstamon to get rid of it.

* Nagstamon 2.0.1 
* windows 10

**Comment by HenriWahl** [comment]
Does it appear automatically or did you trigger an acknowledge action before?

**Comment by cverbiest** [comment]
I'm not sure how this appears. I'll try to get more details if, or when, I see it again.

It could be that I opened the acknowledge screen and left it overnight. I only log out on my laptop if windows updates force me. Most of the time I just lock my session and re-logon.

I tried to reproduce but so far I have not been able to.

**Comment by cverbiest** [comment]
Extra info. ***Failed to reproduce*** with following steps
* Left acknowledge screen open overnight
* logged out in the evening
* logged in in the morning
* the acknowledge screen was perfectly OK, the issue for which the acknowledgement was opened had already been resolved by then.

Probably not very helpful but this was one of the scenarios I thought that could provoke the issue.

Maybe we can close this issue and re-open if new info becomes available ?

**Comment by HenriWahl** [comment]
Do as you like. :-)
If I once get it compiled with a newer version of Qt5 (current is 5.4, latest is 5.7) it even might go automatically as this looks pretty much like some toolkit but.
