### ISSUE TITLE
config file fucked up

### ISSUE THREAD

**Issue by davidak** [HenriWahl/Nagstamon#348]
Nagstamon don't start anymore.

```
davidak@unibook:~$ nagstamon 
Gtk-Message: Failed to load module "pantheon-filechooser-module"

(nagstamon:21219): Gtk-WARNING **: Im Modulpfad »pixmap« konnte keine Themen-Engine gefunden werden,

(nagstamon:21219): Gtk-WARNING **: Im Modulpfad »pixmap« konnte keine Themen-Engine gefunden werden,

(nagstamon:21219): Gtk-WARNING **: Im Modulpfad »pixmap« konnte keine Themen-Engine gefunden werden,

(nagstamon:21219): Gtk-WARNING **: Im Modulpfad »pixmap« konnte keine Themen-Engine gefunden werden,
Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 46, in <module>
    conf = Config()
  File "/usr/share/nagstamon/Nagstamon/Config.py", line 212, in __init__
    config.read(self.configfile)
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /home/davidak/.nagstamon/nagstamon.conf, line: 1
"S\x08\x95QpS\xe4\xd3\tb\r\x94\x8c\x08\xe1e\xcep\x0bQ\xde}\x96H\x9bD\xef\xd57\x02/P\xbf&n\xa5U\x0f\xb7\x08\x01\xec5\xabe\xa8ee\xc0\x17\x0c\xf0.\xd2\x1c,nj\x16]z\xc0\xe80G\xd1K\x14#O\xbc\x95S\xe8\xd2\xeeG1\xf6\x18\x7f\xd5\xe3\xd8\xec\x048=A(\xcb\xbc\xeaq\x95\xc4\x05\xf3Y\xc54\xb6\x05\xdb\xaa\x02z\xe89^\xe3\r\xa2\x8c(\x9f\xeb\xbfx\xbf\x18\x96\xed\x18\xbe\x19\xb7\xda-\x02!\xa9\x9e\x87\x86\xb3\x85\x99\r\xdc\x9dKwm\x88\x14\x08t'\x80<\t\xc9t\x91\x9f\x100Q\xeag\x0f\xa0\xdb\xd8~\xd8\xf9\x96\xbc\xa2\xf4\xdd.Ph \x92m\xb6\x80\xdc\x01V\x1fEN\x90\x18:\xd3\xd3\x97BP\xc4\xa0\x8a\x89\xed\xe6RA\xa04\xad\xf4\x9a(\x80\xa3n\xbaQ?\xad^\xa0\x97=\x89W\xab\x91@\xf1K\xe7Fr\x8fJp\x19\xb5[\n"
```

I think `/home/davidak/.nagstamon/nagstamon.conf` should contain plain text, but it's just some binary.

Starts with: `<95>QpS<E4><D3> b^M<94><8C>^H<E1>e`

How can i fix it?
How can i prevent this happening again?

---

Version 1.0.1-1
elementary OS 0.4 Loki (based on Ubuntu 16.04 LTS)

**Comment by mprenditore** [comment]
you can remove the conf file and the next time that you'll start Nagstamon will generate it again.
But I advice you to move on 2.0.1 ;)

**Comment by davidak** [comment]
@mprenditore of course i can do that but that doesn't solve the problem. it could happen again and it's not fun to configure it every time again.

Is that a known problem that is fixed in 2.x?

Do you have a PPA for Ubuntu? Else i'm bound to what my Distribution provides. If this is fixed in 2.x, i can create a bugrport in Ubuntu and advice them to update the package.

**Comment by mprenditore** [comment]
@davidak I don't think is a common error, I used v1.0.1 for over a year and never broke my config and v2.x neither.
Let's see if @HenriWahl have some info about that.

Here you can find the latest stable .deb package compiled... It would be good if Ubuntu will start to use it or at least package it as "nagstamon2" as already is done with other packages that have various major versions

**Comment by davidak** [comment]
I asked the Ubuntu package maintainer: https://bugs.launchpad.net/ubuntu/+source/nagstamon/+bug/1655706

**Comment by davidak** [comment]
I had a backup of my previous OS X install with a working Nagstamon config. Also i configured Backups for elementary OS. This shows again how important they are!

![33c3_claim_small](https://cloud.githubusercontent.com/assets/91113/21861624/edec8d2e-d835-11e6-92e4-fcdeb1e652ef.png)

**Comment by mprenditore** [comment]
Perfect, now we need to understand why it was corrupted... Have you modified something lately?

**Comment by davidak** [comment]
@mprenditore not on the nagstamon config.

Some days ago i had a problem that the system freezes and i had to reboot it hard.

https://bugs.launchpad.net/ubuntu/+source/gajim/+bug/1654338

But i think i have the nagstamon problem longer. Not sure for how long, maybe end of december 2016.

I'm really not sure what has to happen that a text file turns into a file with garbage. Maybe when an encrypted home folder is not properly closed when i had to do a hard reset?

Might be a more general problem, but only nagstamon stopped working.

**Comment by mprenditore** [comment]
So you have an encrypted home folder and you had to hard reboot the OS?
Well in that case could be that it was corrupted... maybe some pieces of the file were lost with the fsck and that's what caused your problem...

**Comment by HenriWahl** [comment]
Seem to has been happening only once without any known reason... most probably nothing to fix here.
