### ISSUE TITLE
Time of service state change differes from icingaweb2

### ISSUE THREAD

**Issue by ghost** [HenriWahl/Nagstamon#349]
Hi,

I noticed that while icinga2 shows a service state change 42m ago, Nagstamon says it was -1d 23h 16m. Timezone in php5 config is set to Berlin and matches the timezone of the machine nagstamon is running on. ALso the system date of the client machine as well as the server running icinga2 and icingaweb2 is correct.

- Julian

**Comment by HenriWahl** [comment]
Sorry for the late answer... does the problem still exist? If so, what exactly do you mean with service state change? Which of the columns in the status window is affected?
