### ISSUE TITLE
Nagstamon segfault with libQt5Core.so.5.6.1

### ISSUE THREAD

**Issue by agutierrezdapda** [HenriWahl/Nagstamon#351]
- Ubuntu: 16.10
- Qt: 5.6.1

Only work first time init. After configure and exit, nagstamon not start anymore.

Same problem with nagstamon 2.0.1 and 2.1.

Options configured:

- Nagios server
- Filter "Hosts and services with disabled notifications" checked.
- Icon in systray

```
nagstamon[15849]: segfault at 7ffba67e9900 ip 00007ffb9ed6ec87 sp 00007fff272ddba0 error 7 in libQt5Core.so.5.6.1[7ffb9eae1000+4c6000]
```

debug log empty

**Comment by mprenditore** [comment]
We know there are issues with Qt 5.5+ that cause segfault when closing Nagstamon, but this seems different... I'm using it with 5.7.x on fedora and I have no problem, I'll try it on Ubuntu 16.10 and qt 5.6.1 to see if I can spot the problem

**Comment by HenriWahl** [comment]
Maybe works in newer Ubuntu?
