### ISSUE TITLE
Feature request: Display "All Ok" image/page in fullscreen when no alerts are shown

### ISSUE THREAD

**Issue by cverbiest** [HenriWahl/Nagstamon#352]
It would be nice if we could configure something to be shown in the full screen when there are no alerts to be shown.

This could be an image, or maybe an html page.

The idea is to display a happy face or something similar when there are no issues.

**Comment by HenriWahl** [comment]
Good idea.

**Comment by HenriWahl** [comment]
Well, this would cause pretty deep changes so I will not go into this deeper. If there would be any pull request I would consider it but right now I will close this issue.

**Comment by HenriWahl** [comment]
Finally found a simple solution for this so it is included now - a large OK. Find it in latest commit 11f0fa0ca5bd9aefca5fbdc0fe55b1d670702b6a.
