### ISSUE TITLE
Nagstamon doesn't work properly with sm-box

### ISSUE THREAD

**Issue by xf0e** [HenriWahl/Nagstamon#365]
Hello, 
we are using sm-box(http://systemmonitoring.de/) to monitor our infrastrukture. 
Nagstamon is only able to fetch results from sm-box with the user "admin" with no group restriction. If i select the user with a limited number of visible Servers, Nagstamon is not able to connect. 

Thank you!

[log]
DEBUG: 2017-02-21 16:10:17.172325 Monitor server Created server.
DEBUG: 2017-02-21 16:10:17.172325 mon Created server.
DEBUG: Initializing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000000042D45E8> for state "OK"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000000042D4558> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000000042D4678> for state "WARNING"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000000042D4708> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000000042D4798> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000000042D4828> for state "DOWN"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x00000000042D48B8> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt5.QtGui.QIcon object at 0x00000000042D44C8>
DEBUG: 2017-02-21 16:10:17.319325 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:10:17.331666 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:10:17.613196 Monitor server FetchURL: https://nagstamon.ifw-dresden.de/version/unstable CGI Data: None
DEBUG: 2017-02-21 16:10:18.472203 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:10:18.486867 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
ERROR: 2017-02-21 16:10:27.667137 Monitor server Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.py", line 91, in create_connection
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.py", line 81, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 578, in urlopen
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 351, in _make_request
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 814, in _validate_conn
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 254, in connect
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 147, in _new_conn
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000000000558E668>, 'Connection to nagstamon.ifw-dresden.de timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 403, in send
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 623, in urlopen
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\retry.py", line 281, in increment
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nagstamon.ifw-dresden.de', port=443): Max retries exceeded with url: /version/unstable (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000000000558E668>, 'Connection to nagstamon.ifw-dresden.de timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Generic.py", line 1288, in FetchURL
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 487, in get
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 475, in request
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 585, in send
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 459, in send
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='nagstamon.ifw-dresden.de', port=443): Max retries exceeded with url: /version/unstable (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000000000558E668>, 'Connection to nagstamon.ifw-dresden.de timed out. (connect timeout=10)'))

DEBUG: 2017-02-21 16:10:27.667137 mon FetchURL: https://nagstamon.ifw-dresden.de/version/unstable CGI Data: None
DEBUG: 2017-02-21 16:10:28.568241 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:10:28.582898 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:10:28.619220 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:10:28.666828 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
ERROR: 2017-02-21 16:10:37.671953 mon Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.py", line 91, in create_connection
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.py", line 81, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 578, in urlopen
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 351, in _make_request
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 814, in _validate_conn
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 254, in connect
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 147, in _new_conn
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000005DD9DD8>, 'Connection to nagstamon.ifw-dresden.de timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 403, in send
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 623, in urlopen
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\retry.py", line 281, in increment
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nagstamon.ifw-dresden.de', port=443): Max retries exceeded with url: /version/unstable (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000005DD9DD8>, 'Connection to nagstamon.ifw-dresden.de timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Generic.py", line 1288, in FetchURL
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 487, in get
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 475, in request
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 585, in send
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 459, in send
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='nagstamon.ifw-dresden.de', port=443): Max retries exceeded with url: /version/unstable (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000005DD9DD8>, 'Connection to nagstamon.ifw-dresden.de timed out. (connect timeout=10)'))

DEBUG: 2017-02-21 16:10:38.699290 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:10:38.732687 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:10:38.735702 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:10:38.839834 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:10:48.791624 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:10:48.825147 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:10:48.888231 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:10:48.916069 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:10:58.881063 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:10:58.926337 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:10:58.976377 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:10:59.066128 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:08.980024 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:09.022795 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:09.136942 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:09.181385 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:19.098662 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:19.136884 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:19.235775 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:19.338449 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:29.196924 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:29.237809 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:29.399409 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:29.483031 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:39.289934 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:39.333722 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:39.546245 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:39.586432 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:49.423912 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:49.470761 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:49.642620 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:49.687160 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:59.533630 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:59.574311 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:59.748904 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:11:59.792620 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:09.617149 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:09.844304 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:09.858963 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:09.870695 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:19.908964 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:19.947597 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:19.958383 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:20.001512 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:30.017970 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:30.061152 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:30.079137 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:30.159430 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:40.118590 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:40.165053 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:40.227238 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:40.270925 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:50.223828 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:50.310237 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:50.352902 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:12:50.375076 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:00.363784 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:00.417564 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:00.419519 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:00.447251 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:10.506781 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:10.533486 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:10.544239 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:10.562815 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:20.636680 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:20.655937 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:20.690319 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:20.704982 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:30.742336 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:30.756951 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:30.792862 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:30.804593 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:40.880926 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:40.892935 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:40.930780 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:40.995005 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:50.988865 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:51.032289 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:51.053598 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:13:51.119614 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:14:01.113684 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:14:01.148453 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:14:01.181128 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:14:01.200678 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:14:11.185779 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:14:11.222929 mon FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:14:11.232787 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-02-21 16:14:11.286957 Monitor server FetchURL: https://10.30.0.2/cgi-bin/nagios3/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None

**Comment by HenriWahl** [comment]
Looks like this thing is Nagios-3-based - pretty old I think. Maybe contact the developers to ask how they customized it. As this is not very widespread and kind of closed there is not much we can do here I fear.
