### ISSUE TITLE
feature request: sound notifications only in specified time period

### ISSUE THREAD

**Issue by gizu** [HenriWahl/Nagstamon#366]
It would be nice to configure when sound notifications are played (workhours)  or choose silence mode (23:00-6:00)

**Comment by mprenditore** [comment]
I think that as discussed per feature request #364, this should be handled on monitor side and not on Nagstamon.

**Comment by HenriWahl** [comment]
I am with @mprenditore - makes things more complicated instead of having a clean monitoring.

**Comment by gizu** [comment]
i don't want to filter anything on nagstamon side instead server side - i think that only blinking alert,
or open dialog alert is enough in night time.

i remember similar setting on firefox plugin - nagios checker (it was named "plugin working hours"). 

reason is simple - when i turn on my laptop late in night, alerts from nagstamon can be very 
annoying for my roommates...

**Comment by mprenditore** [comment]
Just disable audio in your laptop... It think that is the better idea, I do the same on my own laptop because it annoying me too,  especially as soon as I woke up in the middle of the night

**Comment by gizu** [comment]
http://www.netmonitoring.org/wp-content/uploads/2008/03/behaviour.PNG
