### ISSUE TITLE
[nagios] Startup - don't blink or alert when something is acked

### ISSUE THREAD

**Issue by jwhipp** [HenriWahl/Nagstamon#367]
Whenever Nagstamon starts and there is something (warn, crit, unknown and down) in the list, the icon will blink and alert sounds will happen even when everything in the list is acked.  Nagstamon should remain quiet on startup unless something unacked or not in scheduled downtime is in the list.

**Comment by HenriWahl** [comment]
You could simply filter acknowledged problems out in filters settings.
