### ISSUE TITLE
Add an option to display summary in tray

### ISSUE THREAD

**Issue by renard** [HenriWahl/Nagstamon#368]
Is there a simple way to add a summary aside of the tray icon?

The floating bar mode displays a nice summary of problems:
<img width="50" alt="screen shot 2017-03-05 at 02 14 56" src="https://cloud.githubusercontent.com/assets/383821/23583613/946882c0-0149-11e7-816a-a8bee619cd75.png">

But when displayed in the tray bar (I am using MacOS, but I guess this is similar with other OS) there is no summary of problems.
<img width="33" alt="screen shot 2017-03-05 at 02 16 20" src="https://cloud.githubusercontent.com/assets/383821/23583621/ec8d5502-0149-11e7-89f1-c7588f898b45.png">

[NagBarApp](https://sites.google.com/site/nagbarapp/) Has this nice feature (with flashing colors):
<img width="130" alt="screen shot 2017-03-05 at 02 18 29" src="https://cloud.githubusercontent.com/assets/383821/23583628/29c9a01a-014a-11e7-9253-429783745c8d.png">
<img width="154" alt="screen shot 2017-03-05 at 02 21 35" src="https://cloud.githubusercontent.com/assets/383821/23583635/7df21604-014a-11e7-8195-60cda271cca8.png">

IFAIK the tray can only display icons but according this [post](http://stackoverflow.com/a/25078611)  a dynamic image can be created with some text in it.

I would be great to have such a feature. 

Thanks

**Comment by HenriWahl** [comment]
Actulally Nagstamon started this way back in the old days on Linux and GTK2, where this was possible by the GUI toolkit. But on GTK and now on Qt this feature does not exist anymore. Quite possibly it is possible for NagBar by some macOS-only-GUI-feature but apparently out of reach for Nagstamon. :-(

**Comment by renard** [comment]
So if I understand correctly:

* It is not possible to dynamically generate an image that would summarise nagios status
* It is not possible to change a tray icon

Am I right?

**Comment by HenriWahl** [comment]
Exactly. The used Qt5 toolkit (and most desktop environments at all) does not support generated images outside the plain little icon format.
If there is a way in macOS to achieve this by what-ever-toolkit-NagBar-is-made-of in bigger dimensions than an icon this won't apply to Qt5 too.
The only dynamic changes Nagstamon can do are the background color changes of the icon according to worst state but this still can only happen in the icon boundaries.
Putting text into the little icon will be pretty useless I guess a it will hardly be readable.
