### ISSUE TITLE
Unstable build, more often ?

### ISSUE THREAD

**Issue by BenoitPoulet** [HenriWahl/Nagstamon#369]
Hello,

Can we have unstable build more regularly ? Sometime we fix important bugs but there is no build to give to users.

Regards.

**Comment by HenriWahl** [comment]
Yes, sorry, I had a lot of other stuff to do at work the last months so I lost focus on builds. But well, I will create some as soon as possible,

**Comment by HenriWahl** [comment]
I created some build mechanism which allows to build unstable releases more often.
First results are available at https://nagstamon.ifw-dresden.de/download/.
Only the macOS version is missing which I hope to get done tomorrow.

**Comment by BenoitPoulet** [comment]
Thank you Henri !

**Comment by HenriWahl** [comment]
Just one bad news: cx_Freeze 5.0.1 (used for packaging) seems to be even more broken on macOS than on Windows so a new macOS binary might get some delay until I get it fixed or pyinstaller working.
