### ISSUE TITLE
Url on Custom notification actions 

### ISSUE THREAD

**Issue by nykroy** [HenriWahl/Nagstamon#370]
I'm trying to run url with gets parameters for send email an Telegram with php. I put the url in Action string on Custom notificacion action but nothing was happened. 

When i put the same url on a new Action, on the action tab i have'nt got any problem to run the url. ¿what could it happend?

The url is like that: http://URL/filel.php?host=$HOST$&servicio=$SERVICE$&statusinfo=$STATUS-INFO$&imonitor=$MONITOR$

**Comment by nykroy** [comment]
I am sorry if this is'nt que place for questions.  I am noob and this is my first question on Github. 

I use nagstamon on windows 10.

**Comment by mprenditore** [comment]
Hi,
Can you enable the debug log, execute the custom notification action and share the log?
Another question: Which version of Nagstamon are you using?

**Comment by nykroy** [comment]
I'm using Nagstamon 2.0.1 on one Computer (The Stable version) and 2.1 20170323 on another computer. I am enabling teh debug log now, tomorrow morning  i'm sharing the log. 

Thank you for your great Job

**Comment by nykroy** [comment]
[nagstamon.zip](https://github.com/HenriWahl/Nagstamon/files/872656/nagstamon.zip)

**Comment by almirf** [comment]
Dear Friends

1 * - is it possible to do an action in nagstamon so that it automatically comments by selecting the button create by action  ?

2 * - Is it possible for nagios to add comment automatically after host down ?

Thanks
Almir
