### ISSUE TITLE
Recheck action causes error on Check_MK passive checks

### ISSUE THREAD

**Issue by Ian2020** [HenriWahl/Nagstamon#373]
Running the "recheck" action on Check_MK passive service results in this error on the service:

> ERROR - you did an active check on this service - please disable active checks

Is it possible to change the recheck action to issue a Check_MK-style refresh on Check_MK servers?

**Comment by HenriWahl** [comment]
Sorry for the late answer but as far as I see this Nagstamon dies not know about the type of the check on the server.
