### ISSUE TITLE
SOLVED [Icinga] Quoting/escaping special characters in $status-info$ (email/url) - merged in #486

### ISSUE THREAD

**Issue by e1ze** [HenriWahl/Nagstamon#374]
Hi,

is it possible to quote the $status-info$ for usage in url actions such like email? I have a problem if there is a special character like % in the status information of icinga, it cannot be displayed in an email with the url command.

Example -> ? should be a %:
Service: sys_cpu_remote_usage_average 
Status Information: **CRITICAL: 1: average load 99? warning, 5: average load 99? critical, 15: average load 99? critical** 
Another Example:
Status Information: **DISK WARNING - free space: /mnt/xxx 79298 MB (5?node=99?** 
This should be: **(5% inode=99%):**

Also if you have quotes (**""**) in your status information, the url command is not working and then you will get the error message that the command line argument is invalid.

Example -> quoted databse in pgsql WAL File Check from check_postgres:
Status information: **POSTGRES_WAL_FILES WARNING: DB "db" (host:10.x.x.x) WAL files found:** 

We have a lot of different checks and plugins and it's not possible for me to change every plugin or escape every output.

Thanks 

Greetings René

**Comment by HenriWahl** [comment]
Sorry for the late answer but always much other stuff to do... what happens if you quote the $STAUTS_INFO$ variable in your action string?

**Comment by e1ze** [comment]
Ah... Shit, I totally forgot this issue but better late than never I just tested it.
If i use quotes for "$STATUS-INFO$" i get an invalid response (wrong command line argument).
Thanks

**Comment by e1ze** [comment]
Issue was solved: [Pull Request #486 ](https://github.com/HenriWahl/Nagstamon/pull/486)
