### ISSUE TITLE
[centreon] meta services checking error

### ISSUE THREAD

**Issue by vince68** [HenriWahl/Nagstamon#376]
version 2.1 and 2.1-20170323
I just added a meta service, I dont' have one, it's the first meta service I added. And now I get this error message in nagstamon : AttributeError : 'NoneType' Object has no attribute 'text'.

![image](https://cloud.githubusercontent.com/assets/2109682/24788893/518380ae-1b70-11e7-81a8-bd38e328f096.png)

**Comment by BenoitPoulet** [comment]
Hello,

Can you tell us which Centreon version , and which Centreon language are you using ?

**Comment by vince68** [comment]
I use centreon 2.4 with french language. I planned to upgrade this version if this version causes this bug, you dont have to fix it only for me.

**Comment by BenoitPoulet** [comment]
It's a very old release, i don't have the possibility to test on it anymore. 
I think the XML format was not the same in this version.

If you can upgrade, if think it's the best option.

**Comment by vince68** [comment]
Ok, nevermind, I already planned to update this old centreon release. Thank you for your time. Nagstamon is a very good tool and help me all days.

**Comment by BenoitPoulet** [comment]
Hi,
 This ticket can be closed.
