### ISSUE TITLE
Column "Duration" is fails on Ubuntu 17.04

### ISSUE THREAD

**Issue by ilgizar** [HenriWahl/Nagstamon#377]
After upgrade Ubuntu to 17.04 the column "duration" ceased to work: shown interger instead time, not sorting. [Screenshot](https://www.dropbox.com/s/oza45irx61zvhob/Nagstamon.png)

**Comment by HenriWahl** [comment]
Strange... this wasn't the case with former Ubuntu version and the same Nagstamon version?

**Comment by ilgizar** [comment]
For many years everything was fine. After detecting this bug, I upgrade to 2.1beta, but did not help.

**Comment by HenriWahl** [comment]
Which kind of monitoring server do you use?

**Comment by ilgizar** [comment]
Opsview 3.13.1

**Comment by HenriWahl** [comment]
Oh heaven... isn't this a pretty old version? Regardless of it should be working as before but anyway this sounds pretty antique.
I am not even able to test it as I have no acces (anymore) to an Opsview server.
Can you produce some debug output by enabling debugging in Nagstamon?

**Comment by ilgizar** [comment]
Yes, I can. [link](https://www.dropbox.com/s/5lxleky08ozzrmc/nagstamon.log?dl=0) I leave only one host.

**Comment by HenriWahl** [comment]
OK... in the JSON I find the duration 217565 - what is this supposed to be in reality? That amount of seconds?

**Comment by ilgizar** [comment]
Yes, this duration like to 2,5 days on a Web for it.

2017-04-18 18:18 GMT+05:00 Henri Wahl <notifications@github.com>:

**Comment by HenriWahl** [comment]
Does this still apply?

**Comment by ilgizar** [comment]
Not relevant.
