### ISSUE TITLE
[Feature request] Alarm only on HARD state

### ISSUE THREAD

**Issue by ponchofiesta** [HenriWahl/Nagstamon#380]
Currently Nagstamon notifies the user instantly when a status is not OK. In Icinga I have configured 3 tries to go from the SOFT state to the HARD state. And only then the user gets a email notification. This is to prevent false positives.

It would be great if Nagstamon also could check if it is a HARD state (after 3 tries) before alarming.

**Comment by HenriWahl** [comment]
You can set this in filters.

**Comment by ponchofiesta** [comment]
You're right. Too many settings :)

If someone else searches for it:
open Settings->tab Filters->watch down right for "Hosts in soft state" and "Services in soft state"

**Comment by HenriWahl** [comment]
Yes... historically grown featureset...
