### ISSUE TITLE
Nagstamon 2.1-20170323 don't lunch

### ISSUE THREAD

**Issue by blanchouins** [HenriWahl/Nagstamon#381]
Hi, 

I'm testing Centreon 2.8.5, and I see that I need to install the lastest unstable nagstamon.

I've done it, but I have no access to Nagstamon, immediatly after lunch, nagstamon crashed.

No log in nagstamon.log, and no log in eventviewer.

OS : Windows 10 x64

Tell me if you want another information.

Regards,

**Comment by dervitti** [comment]
Hi,
i have the same behavior and not only 2.1-20170323 but 2.1-stable, also. Windows 10.1607. Nagstamon installed without any errors. Starting it shows the process in Task Manager for a second, then it terminates without any apparent reason. There is no log File and no entry in Windows Event Logs.
regards

**Comment by blanchouins** [comment]
Hi,
Exactly the same behavior ! For the moment, I don't have the solution...

regards

**Comment by BenoitPoulet** [comment]
Hello,

If you are ok with tech tools, you can install the development requirements listed here : https://nagstamon.ifw-dresden.de/docs/requirements/

And run Nagstamon from the command line (use "nagstamon.py").
I think you will got an error message to report here.

**Comment by blanchouins** [comment]
Sorry, but I'm not very friendly with python

**Comment by blanchouins** [comment]
I did the following : 

- install python 3.6 at c:\python36 
- execute the line **C:\python36\scripts\pip install PyQt5 requests requests-kerberos beautifulsoup4 keyring psutil** from elevated prompt
- launch nagstamon.py

All is OK !

So, I remove old version, I install 2.1 from executable since last time, and, all is OK !

Why it does not work the first time ? A problem with a dependency ?

**Comment by blanchouins** [comment]
I think the problem is caused by Kaspersky. When I shut kaspersky, I don't have any problem !

I will add an exception in the rules.

**Comment by HenriWahl** [comment]
What crime does Kaspersky blame poor Nagstamon to commit?

**Comment by blanchouins** [comment]
TCP socket open maybe, after adding exception on executable, it's OK

**Comment by yasa1987** [comment]
I got the same problem after compiling the executable and Symantec Endpoint Protection detected a threat named [SONAR.Heuristic.159](http://securityresponse.symantec.com/security_response/writeup.jsp?docid=2017-010520-1048-99)

**Comment by HenriWahl** [comment]
Phew... even if you compiled yourself? This I would call a false positive...

**Comment by HenriWahl** [comment]
This can only be solved locally I fear.
