### ISSUE TITLE
Windows Uninstall Info: Wrong Link in HKLM\MS\WIN\CV\Uninstall\...\DisplayIcon

### ISSUE THREAD

**Issue by dervitti** [HenriWahl/Nagstamon#384]
Hi,
found with 2.1-stable: 
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{***GUID***}_is1\DisplayIcon links to C:\Nagstamon\build\Nagstamon-2.0.1-win64\recources\nagstamon.ico but should link to %Program files%\Nagstamon\recources\nagstamon.ico

regards

**Comment by HenriWahl** [comment]
Funny... comes from used packager solution InnoSetup I guess.
