### ISSUE TITLE
Nagstamon @ windows 7 64 bit crashing

### ISSUE THREAD

**Issue by romeor** [HenriWahl/Nagstamon#386]
Hi,

we've got an issue with nagstamon on fresh windows 7 installation running on intel nuc.

Periodically we receive this kind of an error:

Faulting application name: nagstamon.exe, version: 0.0.0.0, time stamp: 0x549debc7
Faulting module name: MF.dll, version: 12.0.7601.23471, time stamp: 0x57603c0f
Exception code: 0xc0000005
Fault offset: 0x00000000000fac1f
Faulting process id: 0x97c
Faulting application start time: 0x01d2c30e9301b9c0
Faulting application path: C:\Program Files\Nagstamon\nagstamon.exe
Faulting module path: C:\Windows\system32\MF.dll
Report Id: a6135cd0-3005-11e7-af54-f44d30665027

Faulting application name: nagstamon.exe, version: 0.0.0.0, time stamp: 0x549debc7
Faulting module name: MF.dll, version: 12.0.7601.23471, time stamp: 0x57603c0f
Exception code: 0xc0000005
Fault offset: 0x00000000000fac1f
Faulting process id: 0x96c
Faulting application start time: 0x01d2bf268a4f0a8c
Faulting application path: C:\Program Files\Nagstamon\nagstamon.exe
Faulting module path: C:\Windows\system32\MF.dll
Report Id: 209d7cbc-2c19-11e7-9967-f44d30665027

Faulting application name: nagstamon.exe, version: 0.0.0.0, time stamp: 0x549debc7
Faulting module name: Qt5Widgets.dll, version: 5.5.1.0, time stamp: 0x562412f6
Exception code: 0xc0000005
Fault offset: 0x0000000000067323
Faulting process id: 0xa40
Faulting application start time: 0x01d2bf232688f4a9
Faulting application path: C:\Program Files\Nagstamon\nagstamon.exe
Faulting module path: C:\Program Files\Nagstamon\Qt5Widgets.dll
Report Id: f32dbf99-2b16-11e7-b88b-f44d30665027

**Comment by HenriWahl** [comment]
Please try latest devel release which is based on newer Qt5.

**Comment by romeor** [comment]
We will give it a try.

**Comment by romeor** [comment]
Hi,

just for a note, it seems like we had no issues with latest devel release. Thanks.
