### ISSUE TITLE
Specify quiet hours where nagstamon does not poll servers

### ISSUE THREAD

**Issue by robpumphrey** [HenriWahl/Nagstamon#387]
We would like to be able to specify a quiet period (18:00 to 09:00) and quiet days (Sat and Sun) so that nagstamon is not polling servers during these periods.

The primary reason for this is to reduce the traffic between the desktop and the server.

Alternatively, it would be useful if nagstamon could be quiet if the desktop screensaver is on, or the desktop is locked.

**Comment by mkrsn** [comment]
Cronjobs would solve your needs.

**Comment by robpumphrey** [comment]
Thanks for the comment, although I am not quite sure what you mean. Are you suggesting that we could use cron to start the app in the morning, then kill it in the evening? Or perhaps send the app sigstop/sigcont signals?

**Comment by mkrsn** [comment]
Excatly that - whether signals or not is your choice :)

Signals would the best Option because you don't have to save the password on Disk.

**Comment by robpumphrey** [comment]
Thanks. We will see if we can get that to work for us.
