### ISSUE TITLE
[2.1-20170323] Kerberos  - authentication request pop ups

### ISSUE THREAD

**Issue by gerdesj** [HenriWahl/Nagstamon#389]
I have a Kerberised Icinga instance.  Nagstamon works fine with it but the username/password dialogue pops up when the server is configured and on start up.  If I simply ignore the request Nagstamon works fine - ie I leave the u/p fields blank and Kerberos takes over and Nagstamon connects fine.

(Windows 7 64 bit with the amd64 version of Nagstamon)

**Comment by HenriWahl** [comment]
Nice to hear Kerberos works. Apparently the used requests-kerberos manages even on Windows to acces the credentials.
Kerberos support is pretty raw yet and an upcoming version of Nagstamon will suppress the unneeded dialog with Kerberos enabled. See https://github.com/HenriWahl/Nagstamon/pull/339 for reference.

**Comment by gerdesj** [comment]
It's working flawlessly on Windows for me and I'm just about to test on Linux - my weapon of choice 8)  I'm in the process of Kerberising everything I can get my hands on to get rid of hard coded passwords in odd places.  As I am unable to create Arch packages yet I'll install manually and test against master.  I'll do the same on my Gentoo laptop.

**Comment by gerdesj** [comment]
... on the other hand someone ("ghostbuster") has kindly put nagstamon-beta into the AUR, saving me from going off piste.

Works nicely, with the same caveat that it pops up the auth dialogue which is no problem.

I've noticed that it no longer displays the full username when using Kerberos.  It currently looks like "@<servername>" but should look like user@REALM.CO.UK or perhaps user@REALM.CO.UK@servername !  Pretty minor stuff.

**Comment by HenriWahl** [comment]
Can you send me screenshot with the incorrect username displayed?

**Comment by HenriWahl** [comment]
The authentication dialog issue is fixed by commit 4807db9a9bafa8b71deca645659ade37a41676e7.

**Comment by HenriWahl** [comment]
Now I understand... as there is no username given via Kerberos... Interesting though as the servername still exists... too sad I am not able to test this.

**Comment by gerdesj** [comment]
The servername is from the configuration.  For example I created a server configuration called "BLL" which then causes the large bold text for the monitor to display as @BLL.  As I said - this is pretty minor.  Having the functionality is great. 

Hopefully I'll have time to spin up a VM on my PC at work to test the latest code.  I can't do it on my PC - I need nagstamon working at all times for the day job!

**Comment by HenriWahl** [comment]
OK.. as for now I think there is no way to fix this as the username keeps hidden for Nagstamon as the Kerberos mechanism cares about authentification.

**Comment by HenriWahl** [comment]
Just an idea - in theory the locally logged in user which runs Nagstamon would be the one having the Kerberos session too, right? So it would simply be enough to set that username in front of the '@'?

**Comment by gerdesj** [comment]
I don't think anyone is going to complain if you simply use the locally logged in username as their identity displayed in Nagstamon.  You can have a local ID and use another for Kerberos but that is going to be pretty rare. Good idea.
