### ISSUE TITLE
2.1-20170323 - Zabbix - Trigger description shown as service name

### ISSUE THREAD

**Issue by Metrax** [HenriWahl/Nagstamon#391]
Hi,

not sure if this is a bug or a feature ;-)

Nagstamon 2.1-20170323 is showing the description of the trigger as service name when it is set.
For trigger without description it show the application name if the item. For me the application name makes the most sense here.

![grafik](https://user-images.githubusercontent.com/1061866/27378954-ccec1992-5679-11e7-8c49-7870416a0982.png)

![grafik](https://user-images.githubusercontent.com/1061866/27379037-14000794-567a-11e7-9ed3-aee92c3c85b5.png)

Regards,

Robert

**Comment by mprenditore** [comment]
Hi,
It was meant to be a feature to have more detailed information about the alarm.
I would like to add a setting to let user to choose it but I'm a little bit busy ATM...
In case that annoy you, you can change the following code and recompile it.

**_Nagstamon/Servers/Zabbix.py:256_**
overwrite:
```
                    if len(service['comments']) == 0:
                        srvc = service['application']
                    else:
                        srvc = self.nagiosify_service(service['comments'])`
```
with:
```
#                 if len(service['comments']) == 0:
#                        srvc = service['application']
#                 else:
#                        srvc = self.nagiosify_service(service['comments'])
                    srvc = service['application']
```

then recompile it or reinstall it vie the setup.
I hope that will help.

**Comment by mprenditore** [comment]
I'm not sure if it will be easy to implement... 
ATM I'm working on fixing the ACK on Zabbix, after I'll pass to add the setting for the description/application and after I'll look about the over popup :)

Thanks for the suggestions,

Stefano

**Comment by HenriWahl** [comment]
Is this fixed with latest stable version from https://nagstamon.ifw-dresden.de/download/#stable?

**Comment by mprenditore** [comment]
Not yet, I hope to finish it soon

**Comment by mprenditore** [comment]
Now should be fixed! Keep me updated please
