### ISSUE TITLE
Started only with admin permission (Windows 10)

### ISSUE THREAD

**Issue by de1m** [HenriWahl/Nagstamon#392]
Hi, I do use the latest stable version (Nagstamon-2.0.1-win64.zip).
The nagstamon will not started, if I started this as a normal user.

But I can start nagstamon.exe with admin permissions. 

It's normal behaviour?

**Comment by HenriWahl** [comment]
This is not intended - but I can reproduce this. :-( Strange nobody noticed before.
At the moment there is no time to dig deeper here - maybe use in the meantime the setup.exe-version?

**Comment by de1m** [comment]
I've the save issue with installation version, but it working(setup version) after I've delete the configuration folder in user profile (C:\users\USER\.nagstamon)

**Comment by HenriWahl** [comment]
Does the zip-version run when previously deleting the config folder?

**Comment by HenriWahl** [comment]
Please check latest unstable.

**Comment by HenriWahl** [comment]
Latest unstable has no problems with nagstamon.exe started by normal user.
