### ISSUE TITLE
Acknowledgement on Icinga1 w Thruk not working

### ISSUE THREAD

**Issue by Lord-of-Kerry** [HenriWahl/Nagstamon#398]
Hi there,
we are using Nagstamon together with Thruk on Icinga1.
Unfortunately setting a acknowledgement in nagstamon has no effect at all. Thruk-webgui does the job.

Nagstamon debugfile with obscured servernames:
```
DEBUG: 2017-07-10 08:47:09.297833 Icinga Filter: SOFT STATE Server123;ServiceXYZ
DEBUG: 2017-07-10 08:47:09.297833 Icinga Filter: DOWNTIME Server234;ServiceYZA
DEBUG: 2017-07-10 08:47:14.527833 Icinga FetchURL: https://icinga.example.com/thruk/cgi-bin/cmd.cgi CGI Data: OrderedDict([('cmd_typ', '34'), ('cmd_mod', '2'), ('host', 'Server-with-problem'), ('service', 'Blade Server Status'), ('com_author', 'icingauser'), ('com_data', 'acknowledged'), ('btnSubmit', 'Commit'), ('send_notification', 'on'), ('persistent', 'on'), ('sticky_ack', 'on')])

```

**Comment by HenriWahl** [comment]
Seems related to https://github.com/HenriWahl/Nagstamon/issues/194. Thruk changed something in the web interface which Nagstamon does not know about yet. Maybe just use the Icinga webinterface for Nagstamon?
