### ISSUE TITLE
IcingaWeb2 acknowledged services are displayed when filtered

### ISSUE THREAD

**Issue by yasa1987** [HenriWahl/Nagstamon#399]
Hello,
in Nagstamon 2.1-20170323 I checked the box to filter "Ackknoledged hosts and services". It works for Icinga1.x but for IcingaWeb2 acknowledged services (at least) are displayed.

I analyzed the source code and I found out why.
In Generic.py line 969, **acknowledged** is checked against **True** (boolean value):
` if service.acknowledged is True and conf.filter_acknowledged_hosts_services is True:`
The same is done at line 884 for hosts:
`if host.acknowledged is True and conf.filter_acknowledged_hosts_services is True:`

In IcingaWeb2.py those values are set as **Integers** and will therefore **never be True**
Line 277:
`self.new_hosts[host_name].services[service_name].acknowledged = int(s['service_acknowledged'])`
Line 190:
`self.new_hosts[host_name].acknowledged = int(h['host_acknowledged'])`

I modified those line in order to have *bool* value and it works:
Line 277:
`self.new_hosts[host_name].services[service_name].acknowledged = bool(int(s['service_acknowledged']))`
Line 190:
`self.new_hosts[host_name].acknowledged = bool(int(h['host_acknowledged']))`
Same issue is present for the other flags.

The **s** dictionary in Icinga.py contains **Booleans**
`{'host': 'iptv-srv-portal-2', 'service': 'iptv-srv-portal-3 responsivness', 'status': 'CRITICAL', 'last_check': '2017-
07-21 10:48:57', 'duration': '784d  2h  0m 34s', 'attempts': '3/3', 'is_flapping': False, 'in_scheduled_downtime': False
, 'active_checks_enabled': True, 'passive_checks_enabled': True, 'notifications_enabled': True, 'has_been_acknowledged':
 True, 'host_display_name': 'iptv-srv-portal-2', 'service_display_name': 'iptv-srv-portal-3 responsivness', 'status_info
rmation': 'CRITICAL - portal_vario_prd3 malfunction'}`

The **s** dictionary in IcingaWeb2.py contains **number in a String**
`{'host_name': 'dhcp', 'host_display_name': 'DHCP Services Primary', 'host_state': '0', 'service_descr
iption': 'dhcpd_sharednet', 'service_display_name': 'DHCP shared networks', 'service_state': '1', 'service_in_downtime':
 '0', 'service_acknowledged': '1', 'service_handled': '1', 'service_output': 'WARNING: Shared nets - crit: 0 warn: 1 ok:
 44: ', 'service_perfdata': '...', 'service_attempt': '1/3', 'service_las
t_state_change': '1500257199', 'service_icon_image': '', 'service_icon_image_alt': '', 'service_is_flapping': '0', 'serv
ice_state_type': '1', 'service_severity': '544', 'service_notifications_enabled': '1', 'service_active_checks_enabled':
'1', 'service_passive_checks_enabled': '1', 'service_last_check': '1500626580'}`

**Comment by HenriWahl** [comment]
Thanks - added your fixes and applied them to the other states flapping and scheduled downtime too. Pushed in latest commit.
