### ISSUE TITLE
IcingaWeb2 service display name

### ISSUE THREAD

**Issue by yasa1987** [HenriWahl/Nagstamon#400]
Hello,
for IcingaWeb2 the displayed name for the service is the *internal* configuration name and is taken from *service_description* field. 
The service display name is in the key *service_display_name* and this one should be displayed.
In IcingaWeb2.py, lines 256 to 262 this name is chosen accordingly to *legacy icinga adjustement* that normaly could be removed as they entirely rewrote Icinga code.
`if self.use_display_name_host == False:`
`    # legacy Icinga adjustments`
`    if 'service_description' in s: service_name = s['service_description']`
`    elif 'description' in s: service_name = s['description']`
`    elif 'service' in s: service_name = s['service']`
`else:`
`    service_name = s['service_display_name']`

By replacing previous lines with only the following one, the right name is displayed:
`service_name = s['service_display_name']`

**Comment by HenriWahl** [comment]
So there is no difference in IcingaWeb2 between display name and real name?

**Comment by yasa1987** [comment]
In Icinga2 a service is configured like that 
`apply Service "dhcpd_sharednet" {`
` ...`
`    display_name = "DHCP shared networks"`
`...`
}
`
Here is the data in dictionary **s** in IcingaWeb2.py  :

`{'host_name': 'dhcp', 'host_display_name': 'DHCP Services Primary', 'host_state': '0', 'service_descr
iption': 'dhcpd_sharednet', 'service_display_name': 'DHCP shared networks', 'service_state': '1', 'service_in_downtime':
 '0', 'service_acknowledged': '1', 'service_handled': '1', 'service_output': 'WARNING: Shared nets - crit: 0 warn: 1 ok:
 44: ', 'service_perfdata': '...', 'service_attempt': '1/3', 'service_las
t_state_change': '1500257199', 'service_icon_image': '', 'service_icon_image_alt': '', 'service_is_flapping': '0', 'serv
ice_state_type': '1', 'service_severity': '544', 'service_notifications_enabled': '1', 'service_active_checks_enabled':
'1', 'service_passive_checks_enabled': '1', 'service_last_check': '1500626580'}`

As you can see :
-  *dhcp_sharednet* is the internal name of the service and is in key *service_description*
- *"DHCP shared networks* is the display name and is in key *service_display_name*

With the modification mentionned above, I did in sort to have the *display_name* displayed in Nagstamon

**Comment by HenriWahl** [comment]
And the internal name is not used anywhere in the web interface? So the flag self.use_display_name_host is of no use anymore?

**Comment by HenriWahl** [comment]
Maybe the author of IcingaWeb2.py, @minibbjd, does know anything about it?

**Comment by yasa1987** [comment]
The internal name is used in the service URL  :
`https://SERVER/icingaweb2/dashboard#!/icingaweb2/monitoring/service/show?host=HOSTNAME&service=dhcpd_sharednet`

And is displayed once in the detail page next to the display name:
`Service: DHCP shared networks (dhcpd_sharednet)`

I could acknowledge an alarm so I presume there are no side-effects. I will do some more tests to be sure.

**Comment by HenriWahl** [comment]
So the internal name might be needed for actions like acknowledgement?

**Comment by yasa1987** [comment]
Yes it is but there is a *real_name* attribute containing the internal name on service (on host too) and it's used for all actions like acknowledgement.
`    def _set_acknowledge(self, host, service, author, comment, sticky, notify, persistent, all_services=[]):`
`        # First retrieve the info page for this host/service`
`        if service == '':`
`            # url = self.monitor_cgi_url + '/monitoring/host/acknowledge-problem?host=' + host`
`            url = '{0}/monitoring/host/acknowledge-problem?host={1}'.format(self.monitor_cgi_url,`
`                                                                            self.hosts[host].real_name)`
`        else:`
`            # url = self.monitor_cgi_url + '/monitoring/service/acknowledge-problem?host=' + host + '&service=' + service`
`            url = '{0}/monitoring/service/acknowledge-problem?host={1}&service={2}'.format(self.monitor_cgi_url,`
`                                                                                           self.hosts[host].real_name,`
`                                                                                           self.hosts[host].services[service].real_name)`
`        result = self.FetchURL(url, giveback='raw')`

The internal name is set in *real_name* at line 278 for the service
`self.new_hosts[host_name].services[service_name].real_name = s['service_description']`
And at line 254 for the host
`self.new_hosts[host_name].real_name = s['host_name']`

I looked into Generic.py and IcingaWeb2.py and the *name* attribute is only used for display or debug.
My guess is that it's safe to replace it as proposed above.

**Comment by HenriWahl** [comment]
Does this apply to hosts and services? Can you test if actions still work? If so, can you create a pull request?

**Comment by yasa1987** [comment]
I commited the modifications in my fork. Actually almost all the job was already done in #192 
I tested "Recheck", "Acknowledge", "Downtime" and "Submit check result" for host and service. Everything worked fine in my setup. I'll create the pull request and job will be done :-)

**Comment by HenriWahl** [comment]
Does the same apply to host_name in lines 167 to 176 too? I guess yes... can you test this?

**Comment by yasa1987** [comment]
Yes the same applies to host_name

**Comment by HenriWahl** [comment]
Would you mind to test this and make a pull request? 🥇

**Comment by yasa1987** [comment]
It's already in the pull request I made.
For service_name  :
`self.use_display_name_service = True`
And for *host_name* too:
`self.use_display_name_host = True`

**Comment by HenriWahl** [comment]
Yes of course... I just cannot test this so if you have the opportunity to do so I would just ask you to do it.

**Comment by HenriWahl** [comment]
Ah, sorry, I thought there is some host_description like service_description but apparently there isn't.
