### ISSUE TITLE
Centreon broken in master

### ISSUE THREAD

**Issue by HenriWahl** [HenriWahl/Nagstamon#402]
@BenoitPoulet @mprenditore apparently the latest Centreon.py is somewhat broken in current master. When starting, I get

      File "/home/henri/Nagstamon/Nagstamon/QUI/__init__.py", line 3489, in get_status
        status = self.server.GetStatus()
      File "/home/henri/Nagstamon/Nagstamon/Servers/Generic.py", line 803, in GetStatus
        status = self._get_status()
      File "/home/henri/Nagstamon/Nagstamon/Servers/Centreon.py", line 497, in _get_status
        nagcgiurl_services = self.urls_centreon['xml_services'] + '?' + urllib.parse.urlencode({'num':0, 'limit':999, 'o':'svcpb', 'p':20201, 'nc':0, 'criticality':0, 'statusService':'svcpb', 'sSetOrderInMemory':1, 'sid':self.SID})
    AttributeError: 'CentreonServer' object has no attribute 'urls_centreon'

And true, there is no definition of urls_centreon which has been there some commits before. Can you please check this as I am not sure if I would create an even bigger confusion?

**Comment by HenriWahl** [comment]
Hm... i found the urls_centreon definition but the problem is another one... I just set a server to type 'Centreon' but it is just another type - so apparently the urls_centreon never gets set. Just should be set earlier.

**Comment by BenoitPoulet** [comment]
Hello,
I just saw this bug and yes something has been broken, i will investigate.

**Comment by HenriWahl** [comment]
I kind of fixed it by setting the URLs earlier in init_config() as seen in https://github.com/HenriWahl/Nagstamon/commit/3e9892c4099f5c0c8e05480f70add13880d80375

**Comment by BenoitPoulet** [comment]
But i had another bug : 
  File "C:\Users\benoit.poulet\Documents\Dépots\GitHub\Nagstamon\Nagstamon\Servers\Centreon.py", line 372, in _define_url
    'xml_services': self.monitor_cgi_url + '/include/monitoring/status/Services/' + self.XML_PATH + '/serviceXML.php',
AttributeError: 'CentreonServer' object has no attribute 'XML_PATH'

I just did a fix, i will send you a push request

**Comment by BenoitPoulet** [comment]
OMG, i see my fix is exactly what you removed :|
So i'm upset, and i dont know what to do

**Comment by BenoitPoulet** [comment]
This is what i did to get my checkout of this morning, working :
![capture](https://user-images.githubusercontent.com/2464712/28560457-05d286d6-711b-11e7-8576-7d9be6368c4f.PNG)

With this i can run Nagstamon with a pre existing config, and from a clean start.

I'm still with the Python requirement from the beginning of this year (Python 3.4) , something had changed ?

**Comment by HenriWahl** [comment]
The movement of self._define_url() was my part. The removed time-stuff... no idea.

**Comment by HenriWahl** [comment]
I use Python 3.6 now but things shouldn't have changed that much.

**Comment by BenoitPoulet** [comment]
time stuff was just cleaning theses lines was commented.

**Comment by HenriWahl** [comment]
Ah.. yes. :-)

**Comment by BenoitPoulet** [comment]
i don't know how to reproduce your original bug.
Can you give me more information ? (Centreon version, Pass auth or Token, new config, ....)

**Comment by HenriWahl** [comment]
No, it was caused by plain stupidity... I used a Nagios server, but switched its type to Centreon... thus login failed and so the former definition of URLs never happend. That's why I moved the definition into init_config().
