### ISSUE TITLE
Nagstamon not compatible with python3.6?

### ISSUE THREAD

**Issue by mattLLVW** [HenriWahl/Nagstamon#403]
Hello,
I recently switched to Fedora26 which use python3.6 as default python3.
When i try to install manually Nagstamon 2.0.1:
```
conflicting requests
  - nothing provides python(abi) = 3.5 needed by nagstamon-2.0.1-1.noarch
```
So far i tried to compile python3.5 from sources, skip dependances when installing (using rpm)

When i skip dependances:
```
Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 36, in <module>
    from Nagstamon.Config import (conf,
ModuleNotFoundError: No module named 'Nagstamon'
```

**Comment by HenriWahl** [comment]
Help is underway... just wait some, there will be a Fedora 26 RPM soon.
For some reason the dependency of a Python version gets always hardcoded to the one the RPM is built on. I am no packager so if there anybody can be of any help to avoid this let me know...

**Comment by mattLLVW** [comment]
Great!
I manage to install it "the dirty way":
- copied Nagstamon dir in /usr/bin
- installed all dependances manually.

i should have waited... Thank you!

**Comment by HenriWahl** [comment]
Please check the RPM available at https://nagstamon.ifw-dresden.de/download/#unstable.
