### ISSUE TITLE
Ubuntu 16.04 python3-keyring dependency missing

### ISSUE THREAD

**Issue by madaxel** [HenriWahl/Nagstamon#404]
at startup I get 
`Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 39, in <module>
    from Nagstamon.Config import conf
  File "/usr/lib/python3/dist-packages/Nagstamon/Config.py", line 29, in <module>
    import keyring
ImportError: No module named 'keyring'
`
in version 20170725.

after a 
`apt install python3-keyring`
it worked again.
Thanks again for this nice tool

**Comment by HenriWahl** [comment]
Thanks! Fixed in commit edd327d4c80707fb9ce58d583aaf33a23150dff2.
