### ISSUE TITLE
Nagstamon crashes when sorting by time

### ISSUE THREAD

**Issue by FeatherBoy** [HenriWahl/Nagstamon#405]
I am using nagstamon on Windows 10 x64 machine. I have nagstamon 2.1.0 version installed, but issue is also reproducible at nagstamon 2.0.1.

Nagstamon crashes when I change default settings of Statusbar details popup:
Default sort filed: Status
Default sofr order: Descending

to

Default sort filed: Duration
Default sofr order: Ascending 

Nagstamon runs for aproximately 45 minutes and then it crashes. Please let me know if I can provide more info (logs, dumps, etc.) and where to find this info.

**Comment by HenriWahl** [comment]
It doesn'nt crash if you use the default sort order?

**Comment by HenriWahl** [comment]
Do you run it in systray or as floating statusbar or fullscreen?

**Comment by FeatherBoy** [comment]
I run it as floating bar. It seems that it is OK when I use defaults like at my first post. My scenario was:

1) I used it month at defaults and it works ok.
2) I change settings to sort by Duration -> Ascending
3) It starts crashing on regular basis (without error message so I dindt know that it crashed)
4) I have changed it back to defaults today and it seems to hold for now.

I saw a "crashreport" in different bugreports so if I can retrieve similar crashreport, tell me how and I will provide more information.

**Comment by HenriWahl** [comment]
The best way to get something is running it as pure Python script in a console window, but maybe you can get already something interesting when enabling debugging in the first settings tab and let it store in a debug log file there.

**Comment by FeatherBoy** [comment]
Sent log to mail

**Comment by HenriWahl** [comment]
Thanks - this lead to a crash?

**Comment by FeatherBoy** [comment]
It is debug log right after the crash has happen. I didnt work it at that
time.

2017-07-26 15:18 GMT+02:00 Henri Wahl <notifications@github.com>:

**Comment by HenriWahl** [comment]
well.. nothing to see here. The Python-in-a-shell way might be the last resort here.
https://nagstamon.ifw-dresden.de/docs/requirements/ has a list of requirements - all free and working so far. At the end you would have an installed Python with all the other dependencies for GUI and can run nagstamon.py in its source folder in a terminal window. There you get the direct output if anything happened.

BTW I have a Nagstamon running with the same default order settings like you but it runs and runs... only difference is the monitor server, which here is a Check_MK one.

**Comment by HenriWahl** [comment]
I let a Nagstamon run with Nagios demo server directly from Nagios with your sort order and there is no crash.
:-(

**Comment by nykroy** [comment]
I have the asme problem. If i order by duration nagstamon crash with the last update 20170727 :(

**Comment by HenriWahl** [comment]
@nykroy what monitor server do you use?

**Comment by nykroy** [comment]
Check mk

_Sent from my Lge LG-H870 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by HenriWahl** [comment]
Which version of Check_MK? Can you send me a screenshot with the duration column?

**Comment by nykroy** [comment]
1.4.0p8.

[image: image.png]

**Comment by nykroy** [comment]
1.4.0p8

![image](https://user-images.githubusercontent.com/7745881/28746972-1a96429c-7495-11e7-8de7-e6e7236827e1.png)

**Comment by HenriWahl** [comment]
Should get better with latest commit or binaries in https://nagstamon.ifw-dresden.de/files/incoming/ which should arrive there soon.

**Comment by nykroy** [comment]
Thank you !! :)

_Sent from my Lge LG-H870 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by FeatherBoy** [comment]
I am getting the error with new version. I am not able to view any status. I ve sent the logs to email.

For now, I am using workaround with Restart On Crash application B-)

**Comment by HenriWahl** [comment]
Version is from incoming URL as above?

**Comment by HenriWahl** [comment]
@FeatherBoy no email yet...

**Comment by FeatherBoy** [comment]
Yes, specifically this one: https://nagstamon.ifw-dresden.de/files/incoming/Nagstamon-2.1-20170730-win64_setup.exe

**Comment by HenriWahl** [comment]
@FeatherBoy  Check_MK changed its time format since version 1.4.0. Apparently I did not get all new differences. Thus a screenshot of your monitor's website would help me.

**Comment by HenriWahl** [comment]
@FeatherBoy does it work now?

**Comment by FeatherBoy** [comment]
Sorry I was very busy today... What screen do you want? Nagios XI screen?
Which one?

Dne 1. 8. 2017 15:48 napsal uživatel "Henri Wahl" <notifications@github.com

**Comment by HenriWahl** [comment]
@FeatherBoy ah OK you do not use Check_MK? This one has changes in date format. Any Nagios problem seems new so a screenshot might help.

**Comment by HenriWahl** [comment]
I test now with nagiosxi.demos.nagios.com and the default sort order with ascending duration and everything works fine so far. All this with latest commit https://github.com/HenriWahl/Nagstamon/commit/52cc75d61c6a47f2f6f0967fcf843c55fe42e779.
Please don't forget to ignore certificate or provide the certificate of your CA.

**Comment by HenriWahl** [comment]
I found out that nagiosxi.demos.nagios.com is in reality a Nagios Core... so if you could send me some html or screenshot of a status overview page which contains durations I might get more what happens here.

**Comment by HenriWahl** [comment]
After looking for the real NagiosXI demo at Nagios I wonder how you managed at all to login there as it looks pretty PHP-based in contrast to former Nagios.

**Comment by FeatherBoy** [comment]
I ve just you the html page from Last alers page at Nagios XI. Thanks.

**Comment by HenriWahl** [comment]
The timestamps there look normal and will be parsed as always.
What would be of most help would be some real console output when running the pure Python nagstamon.py in a terminal/command line session from source. Do you think you could run it following the directions on https://nagstamon.ifw-dresden.de/docs/requirements/ ?

**Comment by FeatherBoy** [comment]
Sorry for the silence, I ve been busy. Today I installed python and start running it with dobug console via nagstamon.py

I will let you know during tomorrow about result. So far it holds.

**Comment by FeatherBoy** [comment]
Just crashed. I have sent you email with details.

**Comment by HenriWahl** [comment]
This seems to be the problem:
`ValueError: invalid literal for int() with base 10: '??'`
Any chance to find out why some time value is ?? instead of an integer? Does it already appear in the web interface like this?

**Comment by HenriWahl** [comment]
BTW, this error appears in your setup in line 299, but current master has this call in line 229 https://github.com/HenriWahl/Nagstamon/blob/ed60ce019c8fbd917da885f42b56314596eed3ce/Nagstamon/Helpers.py#L229. Are you sure you have the latest code of master there?

**Comment by FeatherBoy** [comment]
I am sending you the realpages at web interface at the time of crash...

**Comment by HenriWahl** [comment]
Please check the binaries of https://nagstamon.ifw-dresden.de/files/incoming/.

**Comment by HenriWahl** [comment]
Any news?

**Comment by FeatherBoy** [comment]
So far I didnt register any crash, so I think it is OK now :-)

**Comment by HenriWahl** [comment]
OK so I will close one of the last showstoppers.
