### ISSUE TITLE
[Master] Have to add a username and password

### ISSUE THREAD

**Issue by gerdesj** [HenriWahl/Nagstamon#407]
I am trying out the Kerberos support including the fix for auth pop ups.

I created a new server and ticked use Kerberos and did not fill in the username or password fields.  This caused a crash with this output:

`Traceback (most recent call last):
  File "/usr/src/Nagstamon/Nagstamon/QUI/__init__.py", line 5263, in ok
    statuswindow.servers_vbox.addLayout(statuswindow.create_ServerVBox(servers[self.server_conf.name]))
  File "/usr/src/Nagstamon/Nagstamon/QUI/__init__.py", line 1210, in create_ServerVBox
    not conf.authentication == 'kerberos':
AttributeError: 'Config' object has no attribute 'authentication'
Aborted (core dumped)`

I recreated it using Basic auth and filled in the username and password and that worked fine.  I then switched it to Kerberos - all OK.  I switched back to Basic and emptied the user/pass fields - same crash as above.  Finally I put dummy values into the user/pass fields and that works OK - Kerberos is working correctly.

I think that the server creation process requires the username and password to be filled in to finish.  This doesn't make sense for Kerberos and should simply cause a login pop up when in use for other authentication schemes.

**Comment by HenriWahl** [comment]
If you tried master directly please try again, otherwise it takes some time for binaries.

**Comment by gerdesj** [comment]
That works fine.  I have both the username and password fields cleared out and Kerberos works OK.  Tested on Arch Linux only.

Thanks

**Comment by HenriWahl** [comment]
Was some stupidly forgotten snippet. Expected to work everywhere.
If you also use Kerberos - what do you think of https://github.com/HenriWahl/Nagstamon/issues/389#issuecomment-318055584 ?

**Comment by gerdesj** [comment]
As I put on #389 I think that is a great idea (use the username from the logged in session).  I've also tested the latest Windows unstable binary install - that works fine provided a username/pass is entered so I guess it was built just before the commit that fixed this bug.

You are on fire mate 8)  Great stuff.
