### ISSUE TITLE
Dark Theme not respected

### ISSUE THREAD

**Issue by presianbg** [HenriWahl/Nagstamon#411]
Dear Henri,

First of all - thanks for the hard work and the wonderful  app you are developing.

I have a headache with nagstamon-2.1.20170727-1 and brand new Arch Linux installation - the dark gtk theme is not respected by nagstamon.

My setup:
Cinnamon
Arc-Dark theme
qt5 - Dark Breeze

Would you be so kind to guide me how to debug and resolve this issue?

Best Regards,
Presian

**Comment by presianbg** [comment]
Just to illustrate what I'm talking about:
![image](https://user-images.githubusercontent.com/2163486/28752086-04f29478-7520-11e7-936d-c4e72be7a2a9.png)

**Comment by HenriWahl** [comment]
Which version of Qt5 is there used? Would mostly depend on it I guess.

**Comment by HenriWahl** [comment]
I kicked out the extra-ignorance-of-any-platform-theme because it caused some UI-trouble before. Either use latest commit code or wait until all binaries arrived in https://nagstamon.ifw-dresden.de/files/incoming/ - a wait, Arch won't use either DEB or RPM, right? So even a tar.gz will arrive there soon or just pull from Github to see if it helped.

**Comment by presianbg** [comment]
This is the QT5 version in use:
```
extra/qt5-base 5.9.1-3 (qt qt5) [installed]
    A cross-platform application and UI framework
```
Also tried with the latest version from AUR:

https://aur.archlinux.org/packages/nagstamon-beta/

No difference.

**Comment by HenriWahl** [comment]
Did you try latest commit on Github, 834f06b8120855ed48fd8f086aded92e15e61165?

**Comment by presianbg** [comment]
Yep dark themes are applied, but:
```
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)
```

I'm using self-signed certs for my nagios setup.

**Comment by HenriWahl** [comment]
No, you could set in the server settings extra options to ignore this problem or provide your CA's certificate.

**Comment by presianbg** [comment]
@HenriWahl  somehow I missed that awesome option!

Many thanks, you are great. Keep it up !

**Comment by HenriWahl** [comment]
This feature came in freshly.
