### ISSUE TITLE
Nagstamon window doesn't hide properly

### ISSUE THREAD

**Issue by unknown321** [HenriWahl/Nagstamon#412]
Window manager: awesome 3.5.
Nagstamon version: 2.1-20170727
I am having issues after hiding nagstamon window - it creates 1x1 window, which closes after a while. It messes up with my WM layouts, because that window joins list of active windows. Is there a particular reason for hiding window instead of just closing it?

Suggested fix:
Call self.close() after hiding the window here: https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/QUI/__init__.py#L1528

**Comment by HenriWahl** [comment]
In which mode does Nagstamon run there?

**Comment by unknown321** [comment]
Tray icon, floating statusbar works fine.

**Comment by HenriWahl** [comment]
According to https://stackoverflow.com/questions/39407564/difference-between-hide-close-and-show-in-qt close() won't make any difference as being the same as hide() as long as the widget should not be deleted. And it should not be deleted because it is used again as soon as the tray icon is clicked next time.

**Comment by unknown321** [comment]
I see, thanks. 
Adding self.close() fixes my issue, but it seems there is no need to add it to master. Guess I'll stick with local patches.

**Comment by HenriWahl** [comment]
Really? Please make a pull request or send a patch so I can see your exact changes.

**Comment by HenriWahl** [comment]
Please check commit 52cc75d61c6a47f2f6f0967fcf843c55fe42e779

**Comment by HenriWahl** [comment]
The idea to use close() by the way helped to solve another issue with systray icon on macOS. :-)

**Comment by unknown321** [comment]
Unfortunately nagstamon is broken now. Floating statusbar works fine, but systray icon doesn't.
After switching display option icon doesn't appears, monitor window is nowhere to be seen. Process is still alive, but there is no way to bring up the window.
Tested on clean profile.

https://gist.github.com/unknown321/8ae86453bfbb6e780d6d78b7ccc70826 - diff of my fix and 2.1-20170727 version of __init__.py, basically calling self.close() at the end of hide_window() function after hiding the window.

**Comment by HenriWahl** [comment]
Switching sometimes makes trouble - did you kill the process and started it again as systray icon?

**Comment by HenriWahl** [comment]
Latest commits should contain a second show() command so please try it.

**Comment by unknown321** [comment]
Yea, I killed the process and started it again.
Issue persists even with latest commit - no tray icon, no monitor window in icon mode.

Debug log:
https://gist.github.com/unknown321/45e0ec8453a9a3a9accff4c76dbcbe40

**Comment by HenriWahl** [comment]
Makes no sense to me... well I try to run awesomewm in a VM. Any hint for a preconfigured distro?

**Comment by HenriWahl** [comment]
Finally managed to run awesome in Debian 8 - runs fine in systray, closes after click - all this with latest commit which is 91ee761de9ee8f427b23b9a3a6741271bdeec381.

**Comment by unknown321** [comment]
I am using ubuntu 16.04. I will try to reproduce the issue on clean vms, but it will take me some time.

**Comment by unknown321** [comment]
Tried to replicate the issue on Ubuntu 16.04.3 LTS, fresh install.

awesome v3.5.6 (For Those About To Rock)
 • Build: Sep  1 2015 11:28:53 for x86_64 by gcc version 5.2.1 (buildd@lgw01-18)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔

Nagstamon was cloned from repo, commit https://github.com/HenriWahl/Nagstamon/commit/dcd04b704dcfbcf1f158d17c287d4997b1109fa3.

Nagstamon always starts as a 1x1 window after entering server connection settings - no tray icon (see pic, window is on the left). After killing the process credentials are not saved.

![screenshot_ubuntu_2017-08-04_13 22 47](https://user-images.githubusercontent.com/1469658/28965218-abfb5dd0-7918-11e7-9c23-74e1ebde13ed.png)

Issue is not present on debian 9, awesome 4 - everything works fine.

**Comment by HenriWahl** [comment]
Strange thing is that there are no real differences between your fix and my implementation using close() - I just had to add some little more to the first.

**Comment by unknown321** [comment]
Just tried to run it in default Unity session. Works fine, so it is definitely awesome's 3.5 issue (not ubuntu-specific versions of python/qt-libs, just wm itself).
