### ISSUE TITLE
2.1-20170802 - Bug - Colums too short

### ISSUE THREAD

**Issue by BenoitPoulet** [HenriWahl/Nagstamon#413]
Hello,

Since a few time (1 or 2 month of commits) the "Status information" column is too short.
We can't read the message anymore
![capture](https://user-images.githubusercontent.com/2464712/28876735-743a394a-779a-11e7-95b1-65c19d2e7172.PNG)

And there is not settings to set the size of the columns.

Regards.

**Comment by HenriWahl** [comment]
Yes... i fiddled around with it to make it not to LARGE... do you have there several monitors (aka servers) connected or just one? Which OS is this?

**Comment by HenriWahl** [comment]
Do you run from source or binary?

**Comment by BenoitPoulet** [comment]
Hello,

- I'm running it from sources.
- Floating statusbar
- Several monitors (servers), but ONLY ONE enabled.
- Windows 10, dual screen (same resolution)
- QT 5.5.1 for Python 3.4
- No, sometimes the display is OK. But when it begin to "bug" it stay in this state.

**Comment by HenriWahl** [comment]
Kind of voodoo.... but are you able to use Python 3.6 and Qt5 5.8.0 (not the latest 5.9, it had some other problem)? Just lets see what happens.

**Comment by HenriWahl** [comment]
Please check the latest commit, also already available as binary at https://nagstamon.ifw-dresden.de/download/#unstable. I changed some at the column handling.

**Comment by BenoitPoulet** [comment]
I have updated all my Python stack to the version you gave.

The problem seems to be gone. Thanks.
