### ISSUE TITLE
Zabbix with Self-Signed SSL cert

### ISSUE THREAD

**Issue by aspel** [HenriWahl/Nagstamon#414]
Hello,
I have an issue with a  Self-Signed SSL cert at Zabbix server.
Nagstamon receive an error
![iss1](https://user-images.githubusercontent.com/1587659/28934966-872ca33e-788b-11e7-8fa4-814e3ca2453b.PNG)

And I have already enabled option "Ignore SSL/TLS certificate"
![iss2](https://user-images.githubusercontent.com/1587659/28935003-abb9b278-788b-11e7-987e-23a17f3c21cb.PNG)

Zabbix version: 3.0.10
Nagstamon: 2.1-20170803

**Comment by HenriWahl** [comment]
Did it work with any version before?
