### ISSUE TITLE
2.0.1 not showing Zabbix severity 'High' 

### ISSUE THREAD

**Issue by zetheroo** [HenriWahl/Nagstamon#417]
Basically that's it - I know there are High alerts as I can see them in Zabbix frontend and in the Chrome Zabbix Notifier plugin, but they never show on Nagstamon. 

I am running Ubuntu 16.04 btw.

**Comment by HenriWahl** [comment]
Did you try latest devel version from https://nagstamon.ifw-dresden.de/download/#unstable yet?

**Comment by zetheroo** [comment]
I just tried it now. Still not showing 'High' severity problems for Zabbix. Could this be because those problems were acknowledged? 
It does show the acknowledged Critical issues from the Icinga monitoring though.

**Comment by zetheroo** [comment]
I can confirm that if the alert is acknowledged it no longer shows up on Nagstamon.

**Comment by HenriWahl** [comment]
What are your filtering settings?

**Comment by zetheroo** [comment]
Nothing. I have nothing in the Filters settings tab ticked.

**Comment by zetheroo** [comment]
Something I should be filtering? Or another setting I have wrong perhaps? I left everything default.

**Comment by mprenditore** [comment]
Hello @zetheroo , I checked and I cannot reproduce the problem.
Here a screenshot: https://imgur.com/a/8oH4f

Please check if in the "Notifications" tab do you have every security level setup as shown here: https://imgur.com/a/tlOOq

I hope that helps. If it doesn't work please enable Debug mode and share the log file.
