### ISSUE TITLE
How im can add auto comment in naggios ???

### ISSUE THREAD

**Issue by almirf** [HenriWahl/Nagstamon#418]
Dear Friends

Is it possible for nagios to add comment automatically after host down ?

Or if it is not possible the above item I can do an action in nagstamon for it to comment by right clicking on the host ????

Thanks
Almir

**Comment by HenriWahl** [comment]
If you are able to achieve the comment by a command line call you could use the notification actions in settings dialog. Which variables to use there is at the moment only visible in the actions editing dialog but next release will show this info in place here too.
