### ISSUE TITLE
Option to override view for check_mk

### ISSUE THREAD

**Issue by syshackmin** [HenriWahl/Nagstamon#42]
It would be nice to be able to change the view that nagstamon uses when polling check_mk. This way you can create views with different filters to only show the information you want.

Currently you can change the nagstamon view and add a single set of settings. You can also add a regexp filter on the nagstamon side. If you could change the view multiple servers pointing to the same server could be setup with smaller sets of data. Then the dropdown in the list can be used to show what you need to see.

This cannot be done with your regexp filters as those apply to all servers. The check_mk views allow a higher degree of control.

**Comment by HenriWahl** [comment]
Please check latest testing version from https://nagstamon.ifw-dresden.de/download/#testing.
