### ISSUE TITLE
Nagstamon crashes due to trigger

### ISSUE THREAD

**Issue by igorehan** [HenriWahl/Nagstamon#421]
Nagstamon 2.1-20170811
Zabbix 3.0.4
With certain triggers the Nagstamon craches. I did not find a dependency on what the application crashes in the triggers. In the trigger due to which it cracks, the name does not differ from other triggers and does not contain non-standard characters, as well as the description. The name of the node is also not unusual. If the trigger still exists, after running the application it instantly crashes.

   Signature of the problem:
   The name of the problem event: APPCRASH
   Application name: Nagstamon.exe
   Application version: 0.0.0.0
   Application timestamp: 00000000
   Module name with error: ucrtbase.DLL
   Module version with error: 10.0.10586.788
   Module time stamp with error: 5879ab76
   Exception code: 40000015
   Offset exception: 000000000006990f
   OS version: 6.1.7601.2.1.0.256.48
   The language code: 1049
   Additional information 1: cf7f
   Additional information 2: cf7f580d60247ead1eadaa1302600c88
   Additional Information 3: 9c12
   Additional Information 4: 9c122266c64cdf173da125927a696981

**Comment by mprenditore** [comment]
Thanks for sharing.
I've just made a pull request (https://github.com/HenriWahl/Nagstamon/pull/440) that should fix it.
Let me know if everything is ok ;)
