### ISSUE TITLE
nagios - downtime and recheck doesn't work

### ISSUE THREAD

**Issue by danilo1984** [HenriWahl/Nagstamon#424]
Hello,

I use nagstamon for nagios monitoring. Downtime and recheck doesn't work, this is a debug.
I use version 2.0.1 on fedora.

- downtime error, I set "flexible" and 2 hours and "n/a" in start/end time

ERROR: 2017-08-17 16:03:07.818077 ANZ3 Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/Nagstamon/Servers/Generic.py", line 476, in get_start_end
    start_time = dict(result.result.find(attrs={'name': 'start_time'}).attrs)['value']
AttributeError: 'NoneType' object has no attribute 'attrs'

- downtime. I set "fixed" and in start "2017-08-17 16:10:27" in end "2017-08-17 17:10:27"

DEBUG: 2017-08-17 16:10:01.963714 ANZ3 FetchURL: https://nagios3.MYHOST.com/nagios/cgi-bin/status.cgi/cmd.cgi CGI Data: OrderedDict([('cmd_typ', '56'), ('cmd_mod', '2'), ('trigger', '0'), ('host', '38_caper.MYSERVER.com'), ('service', 'TempAmbient'), ('com_author', 'nagiosadmin'), ('com_data', 'downtime'), ('fixed', 1), ('start_time', '2017-08-17 16:10:27'), ('end_time', '2017-08-17 17:10:27'), ('hours', 2), ('minutes', 0), ('btnSubmit', 'Commit')])

there is no error but doesn't work.

- With debug I can't see error with recheck. I see only:

DEBUG: 2017-08-17 16:07:52.252904 BWind Rechecking service check wait e load on host onapp-cp1-node-l8

but it doesn't work

**Comment by HenriWahl** [comment]
Please check latest development release from https://nagstamon.ifw-dresden.de/download/#unstable first.

**Comment by danilo1984** [comment]
I have install version "2.1-20170815" but doesn't work. For recheck I have create this script and works.

Actions:

`/usr/bin/xfce4-terminal -x bash /home/danilo/Documenti/script/nagios/reschedule-post.sh "$HOST$" "$SERVICE$" "$MONITOR$/cgi-bin/cmd.cgi" "$USERNAME$" "$PASSWORD$"`


Script reschedule-post.sh

```
#!/bin/bash
#created by danilo1984
#rev 1.0 2017-08-17

function die {
  echo $1;
  exit 1;
}

HOST=$1
SERVICE1=$2
NAGURL=$3
USER=$4
PASS=$5

#trasformo eventuali spazi in "+" per il servizio
SERVICE="$(echo $SERVICE1 | tr " " +)"

SECONDS=1

DATE=`date "+%Y-%m-%d+%H%%3A%M%%3A%S" -d "$SECONDS sec"`

echo "cmd_typ=7&cmd_mod=2&host=$HOST&service=$SERVICE&start_time=$DATE&force_check=on&btnSubmit=Commit" | lynx -post_data $NAGURL -auth=$USER:$PASS
```

**Comment by HenriWahl** [comment]
Start/end time should not be "n/a". It should be retrieved automatically from Nagios page. Apparently this does not work. :-(
What version is your Nagios?

**Comment by danilo1984** [comment]
Version 4.2.4

**Comment by HenriWahl** [comment]
Because of the date format on the Nagios server Nagstamon retrieves it from the server and replaces "n/a" by something like "08-22-2017 02:07:37". I tested with http://nagiosxi.demos.nagios.com/nagios/ which is also version 4.2.4 and there it works.
Can you please enable debugging and send me the output file?

**Comment by danilo1984** [comment]
Hello,

this is the log of debug when I click on "dowtime" and set:

Start time: n/a
End time: n/a

FLEXIBLE
Duration: 2 houts, 0 minutes


LOG:


```
DEBUG: 2017-08-22 09:22:48.862104 ANZ3 FetchURL: https://nagios3.XXXXXXXXXXX.com/nagios/cgi-bin/status.cgi/cmd.cgi?host=38_caper.XXXXXXXXX.com&cmd_typ=55 CGI Data: None

ERROR: 2017-08-22 09:22:49.425705 ANZ3 Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/Nagstamon/Servers/Generic.py", line 486, in get_start_end
    start_time = dict(result.result.find(attrs={'name': 'start_time'}).attrs)['value']
AttributeError: 'NoneType' object has no attribute 'attrs'

DEBUG: 2017-08-22 09:22:53.254193 ANZ3 FetchURL: https://nagios3.XXXXXXXXX.com/nagios/cgi-bin/status.cgi/cmd.cgi CGI Data: OrderedDict([('cmd_typ', '56'), ('cmd_mod', '2'), ('trigger', '0'), ('host', '38_caper.XXXXXXXXX.com'), ('service', 'TempAmbient'), ('com_author', 'nagiosadmin'), ('com_data', 'downtime'), ('fixed', 0), ('start_time', 'n/a'), ('end_time', 'n/a'), ('hours', 2), ('minutes', 0), ('btnSubmit', 'Commit')])
```

**Comment by HenriWahl** [comment]
Yes, this is the crash after using the useless "n/a"-times. Can you show the some lines before where Nagstamon tries to fetch the time via FetchURL?

**Comment by HenriWahl** [comment]
Do you have the rights to set downtime on the monitoring server?

**Comment by danilo1984** [comment]
I have grep "ANZ3 FetchURL" (ANZ3 it's name of server):

```
DEBUG: 2017-08-22 09:31:08.429008 ANZ3 FetchURL: https://nagios3.XXXXXXXX.com/nagios/cgi-bin/status.cgi/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=524288&limit=0 CGI Data: None
DEBUG: 2017-08-22 10:19:15.549697 ANZ3 FetchURL: https://nagios3.XXXXXXXX.com/nagios/cgi-bin/status.cgi/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-08-22 10:19:16.048497 ANZ3 FetchURL: https://nagios3.XXXXXXXX.com/nagios/cgi-bin/status.cgi/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=524288&limit=0 CGI Data: None
DEBUG: 2017-08-22 10:19:16.385628 ANZ3 FetchURL: https://nagios3.XXXXXXXX.com/nagios/cgi-bin/status.cgi/status.cgi?host=all&servicestatustypes=253&serviceprops=262144&limit=0 CGI Data: None
DEBUG: 2017-08-22 10:19:16.779255 ANZ3 FetchURL: https://nagios3.XXXXXXXX.com/nagios/cgi-bin/status.cgi/status.cgi?host=all&servicestatustypes=253&serviceprops=524288&limit=0 CGI Data: None
DEBUG: 2017-08-22 10:19:26.148746 ANZ3 FetchURL: https://nagios3.XXXXXXXX.com/nagios/cgi-bin/status.cgi/cmd.cgi?host=38_caper.XXXXXXXX.com&cmd_typ=55 CGI Data: None
DEBUG: 2017-08-22 10:19:27.655148 ANZ3 FetchURL: https://nagios3.XXXXXXXX.com/nagios/cgi-bin/status.cgi/cmd.cgi CGI Data: OrderedDict([('cmd_typ', '56'), ('cmd_mod', '2'), ('trigger', '0'), ('host', '38_caper.XXXXXXXX.com'), ('service', 'TempAmbient'), ('com_author', 'nagiosadmin'), ('com_data', 'downtime'), ('fixed', 0), ('start_time', 'n/a'), ('end_time', 'n/a'), ('hours', 2), ('minutes', 0), ('btnSubmit', 'Commit')])
DEBUG: 2017-08-22 10:19:48.065120 ANZ3 FetchURL: https://nagios3.XXXXXXXX.com/nagios/cgi-bin/status.cgi/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-08-22 10:19:48.613929 ANZ3 FetchURL: https://nagios3.XXXXXXXX.com/nagios/cgi-bin/status.cgi/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=524288&limit=0 CGI Data: None
DEBUG: 2017-08-22 10:19:48.987566 ANZ3 FetchURL: https://nagios3.XXXXXXXX.com/nagios/cgi-bin/status.cgi/status.cgi?host=all&servicestatustypes=253&serviceprops=262144&limit=0 CGI Data: None
DEBUG: 2017-08-22 10:19:49.397495 ANZ3 FetchURL: https://nagios3.XXXXXXXX.com/nagios/cgi-bin/status.cgi/status.cgi?host=all&servicestatustypes=253&serviceprops=524288&limit=0 CGI Data: None
DEBUG: 2017-08-22 10:20:19.810115 ANZ3 FetchURL: https://nagios3.XXXXXXXX.com/nagios/cgi-bin/status.cgi/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
DEBUG: 2017-08-22 10:20:20.411202 ANZ3 FetchURL: https://nagios3.XXXXXXXX.com/nagios/cgi-bin/status.cgi/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=524288&limit=0 CGI Data: None
DEBUG: 2017-08-22 10:20:20.822140 ANZ3 FetchURL: https://nagios3.XXXXXXXX.com/nagios/cgi-bin/status.cgi/status.cgi?host=all&servicestatustypes=253&serviceprops=262144&limit=0 CGI Data: None
DEBUG: 2017-08-22 10:20:21.247998 ANZ3 FetchURL: https://nagios3.XXXXXXXX.com/nagios/cgi-bin/status.cgi/status.cgi?host=all&servicestatustypes=253&serviceprops=524288&limit=0 CGI Data: None
```


> Do you have the rights to set downtime on the monitoring server?
Yes, I'm admin and I downtime with no problem using my script.

**Comment by HenriWahl** [comment]
Nagstamon tries to get the current host time by calling https://nagios3.XXXXXXXX.com/nagios/cgi-bin/status.cgi/cmd.cgi?host=38_caper.XXXXXXXX.com&cmd_typ=55 - what do you see if you open this page?

**Comment by danilo1984** [comment]
I see the "Service Status Details For Host '38_caper.XXXXXXX.com'" (with list of all checked service) and the "Current Network Status":

Current Network Status
Last Updated: Tue Aug 22 10:43:40 CEST 2017
Updated every 90 seconds
Nagios® Core™ 4.2.4 - www.nagios.org
Logged in as nagiosadmin

**Comment by HenriWahl** [comment]
Can you send me the HTML via email?

**Comment by danilo1984** [comment]
you have it in h.wahl@ifw-dresden.de

**Comment by HenriWahl** [comment]
Do you want to downtime a host or a service?

**Comment by danilo1984** [comment]
in this case, when I click in downtime, I want to downtime a service

**Comment by HenriWahl** [comment]
You should see something like http://nagiosxi.demos.nagios.com/nagios/cgi-bin/cmd.cgi?cmd_typ=55&host=www.nagios.com (login via 'nagiosadmin', password 'nagiosadmin').

I fear I sent you the wrong URL, should be https://nagios3.XXXXXXXX.com/nagios/cgi-bin/cmd.cgi?host=38_caper.XXXXXXXX.com&cmd_typ=55 like in this Nagios URL. There you should have start and end time fields filled with some times.

Looking at your CGI URLs I think it is too long - https://nagios3.XXXXXXXX.com/nagios/cgi-bin/status.cgi has an innecessary /status.cgi at the end!

**Comment by danilo1984** [comment]
in URL  https://nagios3.XXXXXXXX.com/nagios/cgi-bin/cmd.cgi?host=38_caper.XXXXXXXX.com&cmd_typ=55 I can see:

Start Time: 2017-08-22 11:22:49
End Time: 2017-08-22 13:22:49

https://nagios3.XXXXXXXX.com/nagios/cgi-bin/status.cgi it's correct. https://nagios3.XXXXXXXX.com/nagios/cgi-bin/ doesn't show anythink

**Comment by HenriWahl** [comment]
You should set the CGI URL in Nagstamon without the status.cgi.

**Comment by danilo1984** [comment]
Thanks!! now it's works!!!

P.S.: you can remove it if it's present :) :) :) :)

**Comment by HenriWahl** [comment]
Well, maybe the extra URL ever was useless but could be calculated from Nagios URL as with all the other monitor servers...
