### ISSUE TITLE
Error while configuring Nagstamon with zabbix 3.2

### ISSUE THREAD

**Issue by BernaldoPenasAntelo** [HenriWahl/Nagstamon#425]
Hi:

I'm triying to configure Nagstamon with zabbix 3.2 and i'm getting:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 3538, in get_status
    status = self.server.GetStatus()
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Generic.py", line 801, in GetStatus
    status = self._get_status()
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Zabbix.py", line 210, in _get_status
    trigger['application'] = this_item[0]['applications'][last_app]['name']
IndexError: list index out of range
Abortado

My config file is:

[server_Monitor server]
monitor_url = http://192.168.0.32/zabbix
use_display_name_host = False
enabled = True
use_autologin = False
timeout = 10
authentication = basic
password =
username = eJwFwd0KgyAYANAH6kJX29CLXciHstKvH0rodkgIRUizGPr0O+fFiEpRCRUkP/aPMw+B6UC4nhYbSabbfdA/4oFa48LmR51rHkswlxfQezg7WNvOVm2qoqu/OveFzDFIXbJhQnwzWgRO7Xzm1Cx/VaEiuQ==
monitor_cgi_url = http://192.168.0.32/zabbix
show_options = False
use_proxy = False
no_cookie_auth = False
autologin_key = eJyztS1P9LfI8HMMTQ82KEosLC139PUyMfD2T3IJ9gvXtzAK8SgqyC5PNnBzCan0y7L0Dw2oKg41T/EJMU4xDstzqUyJqKqq9EoFAFgKGBw=
proxy_username = eJwFwcEOgiAAANAP8qBLZOvQwXSaRJgIatyqIROmpEuZfX3vnQAvGPxd2nBX9jAG9FzU7+/nunm4GrZ8TVFK6pZmZM41tj6kD4oStgJPYOUvAQpMlAhYSjdPJTBsi3oOw25E8q7dcASS9ZaSXdWZaNxkb70rXkvDuqeOSczjtCoNd5lD8g/cJy1Q
proxy_address = http://proxyserver:port/
use_display_name_service = False
type = Zabbix
proxy_password = eJwFwbESgiAYAOAHaogzKxkaPMgTEPw7dHBVtHRIBTyTp+/7Hk3LOpal2YzwigSGSdJwdOY3PemlBVzeSbGJwe6DrbY38b6vEpBeLwQmdR2xfVG5R3vi4sNsDRh1koVPoVhuNeVfXR0fYVEUK1+f6doMBC2zingunRtFycBwlmsWnA6B93/f0C8W
save_password = False
name = Monitor server
use_proxy_from_os = False
force_authuser = False

**Comment by BernaldoPenasAntelo** [comment]
Also say that the zabbix server it's a debian 8 and Nagstamon it's installed in a debian 9, same network with connection between both ... etc

**Comment by mprenditore** [comment]
Hi, which kind of "Problems" do you have on your Zabbix? can you show me the Items and trigger that are in "Problem" state in Zabbix while you're trying to launch Nagstamon?
Thanks
Stefano

**Comment by mprenditore** [comment]
I've just made a pull request (https://github.com/HenriWahl/Nagstamon/pull/440) that fix it. Let me know if everything is ok ;)

**Comment by BernaldoPenasAntelo** [comment]
As you could see the error hapens when no items or triggers configured, while i have a moment i would check the fix, thanks a lot for your time

**Comment by mprenditore** [comment]
Is that crash fixed?

**Comment by mprenditore** [comment]
@BernaldoPenasAntelo Perfect!
@HenriWahl you can close :)

**Comment by HenriWahl** [comment]
Thanks for feedback.
