### ISSUE TITLE
Need help for Centreon class

### ISSUE THREAD

**Issue by BenoitPoulet** [HenriWahl/Nagstamon#429]
Hello,

I try to enhanced the Centreon class. 
I would like to handle the case where someone use an HTTPS url, with a bad SSL certificate, without the «Ignore SSL/TLS certificate» option set.

But i do not success to trap the SSL error with exept, so the app crash.

I tried to look into the IcingaWeb2 class, who is handling the PB very well, i can't figure what is the point.

Anyone can help me with the code on this PB ?

Regards.

**Comment by BenoitPoulet** [comment]
One more question. 
Is it possible to do sanity check in init_config() or init_HTTP() and send an error in the UI ?

I would like to validate the autologin key (the key cannot be empty if the user select it as auth method)

**Comment by HenriWahl** [comment]
Not really at the moment. You just might set a not yet existing flag ore something like that which might be evaluated somewhere after https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/QUI/__init__.py#L3662 in get_status() - just an idea.

**Comment by HenriWahl** [comment]
Where exactly it crashes?

**Comment by HenriWahl** [comment]
I would guess it happens in _get_sid()?

**Comment by HenriWahl** [comment]
Like with failed authentication now there is a tls_error flag as property of GenericServer and thus of CentreonServer. My fault apparently is that this flag is set in GetStatus() which is way to late if we think of authentication and failed TLS. So I assume the tls_error flag has to be set already in FetchURL. Good task for tomorrow...

**Comment by HenriWahl** [comment]
I see what you mean when trying to use https://54.154.84.86/centreon instead if https://demo.centreon.com/centreon.

**Comment by HenriWahl** [comment]
Please check latest commit https://github.com/HenriWahl/Nagstamon/commit/d7525d5e51249cf7e9d4a12e4562e234c82ea071 which addresses your problem. BTW other monitors should have had this problem too when login is not possible due to TLS trouble.

**Comment by BenoitPoulet** [comment]
Henri you rocks !
This commit is fixing the crash and now we have a nice error and the convenient fix button. 👍 

I will try to do something about the empty key i was talking about.

Thanks for the fix :)
