### ISSUE TITLE
Create URL Action

### ISSUE THREAD

**Issue by zetheroo** [HenriWahl/Nagstamon#430]
Our triggers (alerts) in Zabbix have URL's configure in the URL settings in the trigger. I see in the Nagstamon (2.1) settings there is the possibility to create a new action. 
Is there a way to create an action which would open the URL set in the trigger settings? If so how?

**Comment by mprenditore** [comment]
Hello, sorry for the late but I'm working on something similar to fix the ACK on Zabbix and as soon as I'll be able to fix it I'll try to find out if there's a way to implement the URL too.
