### ISSUE TITLE
v2.1 ubuntu 14.4 unresolved package

### ISSUE THREAD

**Issue by frank-github** [HenriWahl/Nagstamon#432]
Vorbereitung zum Entpacken von .../nagstamon_2.1-20170829_all.deb ...
Entpacken von nagstamon (2.1-20170829) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von nagstamon:
 nagstamon hängt ab von **python3-requests-kerberos**; aber:
  Paket python3-requests-kerberos ist nicht installiert.

apt-get -f install can not resolve this dependency 
how to fix this for ubuntu 14.4?

go back to 2.0.1 meanwhile, which could be installed without problems

**Comment by HenriWahl** [comment]
Upgrade to Ubuntu 16.04...

**Comment by frank-github** [comment]
hmm, no support for 14.4 anymore  :-(
can't upgrade at the moment....

**Comment by HenriWahl** [comment]
Sorry but new features have new dependencies. You are free to build your own package with custom dependencies or simply run as plain Python script.
