### ISSUE TITLE
Nagstamon with a https only server

### ISSUE THREAD

**Issue by eager-2-learn** [HenriWahl/Nagstamon#433]
Hi,

Nagstamon works correct with my Nagios system.
Nagstamon opened http://<system-name.domein-name>/nagios
For security reasons http (port 80) had to be closed and https (port 443) is opened.
So only https://<system-name.domein-name>/nagios works any more.
But Nagstamon does not work with https.
It it possible to configure Nagstamon for https usage?

Kind regards.

**Comment by HenriWahl** [comment]
Which version do you use? Anyway https works for years. Latest devel versions are more strict regarding selfsigned certificates but allow to ignore them..

**Comment by eager-2-learn** [comment]
Hi Henri Wahl,

The Nagstamon version is 2.0.1. (the latest stable version.)
Nagstamon now connect to the URL http://<system-name.domain-name>/nagios<http://%3csystem-name.domain-name%3e/nagios>
How can I configure Nagstamon on such a way that it connect to https://<system-name.domein-name>/nagios?

Kind regards,

Hans van Leeuwen
System manager

[Logo MailStreet Deventer]<http://www.mailstreet.nl/>
T

|

(088) 67 67 747

<http://emailgfx.mailstreet.nl/emailgfx/VCF_2015_MailStreet_vanLeeuwen_Hans.vcf>[Hans van Leeuwen]<http://emailgfx.mailstreet.nl/emailgfx/VCF_2015_MailStreet_vanLeeuwen_Hans.vcf><http://emailgfx.mailstreet.nl/emailgfx/VCF_2015_MailStreet_vanLeeuwen_Hans.vcf>

E

|

hansvanleeuwen@mailstreet.nl<mailto:hansvanleeuwen@mailstreet.nl>

I

|

www.mailstreet.nl<http://www.mailstreet.nl>

A

|

Lübeckstraat 7, 7418 EK Deventer




De informatie opgenomen in dit bericht kan vertrouwelijk zijn en is uitsluitend bestemd voor de geadresseerde. Verstrekking aan en gebruik door derden is niet toegestaan. Indien u dit bericht onterecht ontvangt, wordt u verzocht de inhoud niet te gebruiken en de afzender direct te informeren door het bericht te retourneren. MailStreet sluit iedere aansprakelijkheid uit die voortvloeit uit elektronische verzending.

The information contained in this message may be confidential and is intended to be exclusively for the addressee. Should you receive this message unintentionally, please do not use the contents herein and notify the sender immediately by return e-mail. MailStreet rules out any and every liability resulting from any electronic transmission.

**Comment by HenriWahl** [comment]
Simply use the https-URL instead of http. No more settings required. Waht result do you get there? How does it not work?

**Comment by eager-2-learn** [comment]
Hi Henri Wahl,

Ok, I found in the settings the place where I can change the URL.
Nagstamon works now correct with https.
Thanks.

Met vriendelijke groet,

Hans van Leeuwen
Systeembeheerder

[Logo MailStreet Deventer]<http://www.mailstreet.nl/>
T

|

(088) 67 67 747

<http://emailgfx.mailstreet.nl/emailgfx/VCF_2015_MailStreet_vanLeeuwen_Hans.vcf>[Hans van Leeuwen]<http://emailgfx.mailstreet.nl/emailgfx/VCF_2015_MailStreet_vanLeeuwen_Hans.vcf><http://emailgfx.mailstreet.nl/emailgfx/VCF_2015_MailStreet_vanLeeuwen_Hans.vcf>

E

|

hansvanleeuwen@mailstreet.nl<mailto:hansvanleeuwen@mailstreet.nl>

I

|

www.mailstreet.nl<http://www.mailstreet.nl>

A

|

Lübeckstraat 7, 7418 EK Deventer




De informatie opgenomen in dit bericht kan vertrouwelijk zijn en is uitsluitend bestemd voor de geadresseerde. Verstrekking aan en gebruik door derden is niet toegestaan. Indien u dit bericht onterecht ontvangt, wordt u verzocht de inhoud niet te gebruiken en de afzender direct te informeren door het bericht te retourneren. MailStreet sluit iedere aansprakelijkheid uit die voortvloeit uit elektronische verzending.

The information contained in this message may be confidential and is intended to be exclusively for the addressee. Should you receive this message unintentionally, please do not use the contents herein and notify the sender immediately by return e-mail. MailStreet rules out any and every liability resulting from any electronic transmission.
