### ISSUE TITLE
Autentication Problem

### ISSUE THREAD

**Issue by nykroy** [HenriWahl/Nagstamon#434]
I have autentication Problems since the 2.1 20170831 version. I ignore the tsl/ssl certificate and i use a basic autentication. 

I attached you a debug of nagstamon without my credencials and the url of check_MK . 

Could you give us the 20170828 that is the last worked for me please? 

Thank you for your great work. Nagstamon is amazing.

**Comment by nykroy** [comment]
Nagstamon 2.1 20170904 have the same problem for me.

**Comment by HenriWahl** [comment]
This is interesting as the 20170904 addressed authentication problems with Check_MK. Can you send me the debug output to my mail address? Or even better - are you able to run Nagstamon from source in a Terminal (probably best on Linux)?

**Comment by HenriWahl** [comment]
Do you use cookie authentication or plain webserver authentication dialog?

**Comment by HenriWahl** [comment]
Do yuse valid or self-signed certificates?

**Comment by nykroy** [comment]
I use cookie autentication and use self-signed certificate. This night send
you a log od 20170904.

Thank you very much!!!

**Comment by nykroy** [comment]
i havent linux so for send you the terminal output but i can send you the nagstamon debug log in Windows OS

**Comment by HenriWahl** [comment]
What error do you see exactly? "Authentication" or "SSL/TLS problem"?

**Comment by nykroy** [comment]
authentication. i use nagstamon 20170828 and when i install 20170831 or 20170904 i have that problem. i return to 20170727 that is the last .exe that i have and i havent any problem

**Comment by HenriWahl** [comment]
I did not receive any mail regarding this problem yet.

**Comment by HenriWahl** [comment]
I think I found something. Expect binaries for various platforms in https://nagstamon.ifw-dresden.de/files/incoming/ in the next minutes.

**Comment by HenriWahl** [comment]
Any success?

**Comment by nykroy** [comment]
Perfect!!! The Issue is solved!!! thank you very much!!

**Comment by HenriWahl** [comment]
Thanks for reporting. :-)
