### ISSUE TITLE
Nagstamon 2.0.1 Always on Visual Workspace

### ISSUE THREAD

**Issue by eager-2-learn** [HenriWahl/Nagstamon#435]
First I use Nagstamon 0.9.8 on Ubuntu 14.04.3 kernel 3.13.0.129-generic
I saw Nagstamon always in the visual workspace.
Now I use Nagstamon 2.0.1 on Ubuntu 14.04.3 kernel 3.13.0.129-generic
I see Nagstamon only in the "first" workspace.
How can I configure that Nagstamon 2.0.1 is always visual in the current workspace?

**Comment by HenriWahl** [comment]
What desktop do you use? Ubuntu default desktop Unity causes major troubles which never were resolved for Nagstamon 2.0.

**Comment by HenriWahl** [comment]
Next version of Ubuntu will help you as it is based on GNOME again.

**Comment by eager-2-learn** [comment]
Dear Henri,

Sorry that I did not send a response.
Nagstamon is a only program (so far I found) that doesn’t have the possibility to change the workspace parameters.

Met vriendelijke groet,

Hans van Leeuwen
Systeembeheerder

[Logo MailStreet Deventer]<http://www.mailstreet.nl/>
T

|

(088) 67 67 747

<http://emailgfx.mailstreet.nl/emailgfx/VCF_2015_MailStreet_vanLeeuwen_Hans.vcf>[Hans van Leeuwen]<http://emailgfx.mailstreet.nl/emailgfx/VCF_2015_MailStreet_vanLeeuwen_Hans.vcf><http://emailgfx.mailstreet.nl/emailgfx/VCF_2015_MailStreet_vanLeeuwen_Hans.vcf>

E

|

hansvanleeuwen@mailstreet.nl<mailto:hansvanleeuwen@mailstreet.nl>

I

|

www.mailstreet.nl<http://www.mailstreet.nl>

A

|

Lübeckstraat 7, 7418 EK Deventer




De informatie opgenomen in dit bericht kan vertrouwelijk zijn en is uitsluitend bestemd voor de geadresseerde. Verstrekking aan en gebruik door derden is niet toegestaan. Indien u dit bericht onterecht ontvangt, wordt u verzocht de inhoud niet te gebruiken en de afzender direct te informeren door het bericht te retourneren. MailStreet sluit iedere aansprakelijkheid uit die voortvloeit uit elektronische verzending.

The information contained in this message may be confidential and is intended to be exclusively for the addressee. Should you receive this message unintentionally, please do not use the contents herein and notify the sender immediately by return e-mail. MailStreet rules out any and every liability resulting from any electronic transmission.
