### ISSUE TITLE
2.1-20170905 does not work on lmde 2 

### ISSUE THREAD

**Issue by Fabrice35** [HenriWahl/Nagstamon#436]
Hi,

I have a problem whith the last unstable version.
I want to install this version for use with sensu.

"
~ $ nagstamon
[Errno 2] No such file or directory: '/home/xxxxxx/.nagstamon/nagstamon.pid'
Traceback (most recent call last):
   File "/ usr / bin / nagstamon", line 47, in <module>
     from Nagstamon.QUI import (APP,
   File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 57, in <module>
     from Nagstamon.Servers import (SERVER_TYPES,
   File "/usr/lib/python3/dist-packages/Nagstamon/Servers/__init__.py", line 42, in <module>
     from Nagstamon.Servers.Sensu import SensuServer
   File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Sensu.py", line 22, in <module>
     from typing import Dict
ImportError: No module named 'typing'
"
I deleted the .nagstamon directory before and the 2.0.1 version work well.

My OS version:
Distributor ID: LinuxMint
Description: LMDE 2 Betsy
Release: 2
Codename: betsy

based on:
~ # more / etc / debian_version
8.9

Regards,

Fabrice

**Comment by HenriWahl** [comment]
Debian 8 has Python 3.4 which does not have the typing library included... :-( maybe https://github.com/vtsingaras finds a way without using it.

**Comment by vtsingaras** [comment]
@HenriWahl will do, it's entirely optional as it provides just type hinting.

**Comment by HenriWahl** [comment]
Please try again with the package provided in https://nagstamon.ifw-dresden.de/files/incoming/

**Comment by Fabrice35** [comment]
It's perfect :-)
Thanks a lot.
