### ISSUE TITLE
Nagstamon 3.0.0 crashes after start

### ISSUE THREAD

**Issue by bunnu** [HenriWahl/Nagstamon#438]
Today I upgraded Nagstamon to version 3.0.0. Nagstamon shows a green icon after start and crashes immediately. Windows eventlog shows following information:
```
Name der fehlerhaften Anwendung: Nagstamon.exe, Version: 0.0.0.0, Zeitstempel: 0x00000000
Name des fehlerhaften Moduls: ucrtbase.dll, Version: 10.0.15063.413, Zeitstempel: 0x5ba8b66e
Ausnahmecode: 0xc0000409
Fehleroffset: 0x00000000000734be
ID des fehlerhaften Prozesses: 0x28e8
Startzeit der fehlerhaften Anwendung: 0x01d32d20bdbe8bf9
Pfad der fehlerhaften Anwendung: C:\Program Files\Nagstamon\Nagstamon.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\ucrtbase.dll
Berichtskennung: e83cdefa-a0a2-42eb-b785-0b270d597a84
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

I'm using Nagstamon on Windows 10, x64 with Zabbix.

**Comment by HenriWahl** [comment]
Do you use TLS encryption?

**Comment by HenriWahl** [comment]
Are you able to run Nagstamon in a terminal following the info at https://nagstamon.ifw-dresden.de/docs/requirements/?

**Comment by bunnu** [comment]
I don't use TLS encryption.
I'm able to run Nagstamon from source without application crash.

**Comment by HenriWahl** [comment]
Can you enable debugging in Nagstamon hoping to see any output?

**Comment by bunnu** [comment]
I just realized, the problem also occures while running Nagstamon from source.
As soon there is a issue with state 'warning', Nagstamon crashes on startup as well as during normal runtime. There is no problem with issues in state 'average'.

Here are the last lines of debug output:

```
Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\QUI\__init__.py", line 3710, in get_status
    status = self.server.GetStatus()
  File "C:\Nagstamon\Nagstamon\Servers\Generic.py", line 821, in GetStatus
    status = self._get_status()
  File "C:\Nagstamon\Nagstamon\Servers\Zabbix.py", line 206, in _get_status
    last_app = len(this_item[0]['applications']) - 1  # use it to get the last application name
IndexError: list index out of range
```

**Comment by bunnu** [comment]
I should mention, the issue shown in Zabbix is a 'Web monitoring/Web-Step Check'. So it's not a _standard_ Zabbix item with trigger.

**Comment by mprenditore** [comment]
Hi @bunnu, I developed that part but I don't have webmonitoring elements in my setup so I'll try to fix it ASAP

**Comment by mprenditore** [comment]
Please @bunnu can you share me the configuration of the Web Scenario so I can replicate the error and make some test?

Thanks
Stefano

**Comment by bunnu** [comment]
Hi Stefano,

here are steps to create a web scenario which triggers the crash:

1. _Configuration_ -> _Hosts_
1. Chose any host (e.g. hostxyz) and Click on _Web_
1. Click on Button _Create web scenario_ (upper right corner)
1. Enter Name (e.g. _Test Webcheck_)
1. Click on tab _Steps_
1. Click on the text _add_ within the _Steps_-Box 
1. Enter Name (e.g. _Google_)
1. Enter Url (e.g. http://www.google.com)
1. Enter Required string (e.g. asdf) (Should be a string which dosn't exists on page)
1. Click on button _Add_
1. Click on button _Add_
1. Click on _Triggers_
1. Click on button _Create trigger_ (upper right corner)
1. Enter Name (e.g. Test Webcheck failed)
1. Choose Severity _Warning_
1. Enter following Expression: {hostxyz:web.test.fail[Test Webcheck].last(0)}>0
1. Click on Button _Add_

The Web scenario is configured and should trigger a warning. Now Nagstamon crashes.

**Comment by mprenditore** [comment]
Thanks for sharing.
I've just made a pull request (https://github.com/HenriWahl/Nagstamon/pull/440) that fix it. Let me know if everything is ok ;)

**Comment by HenriWahl** [comment]
All new binary files arrived at https://nagstamon.ifw-dresden.de/download/#testing.

**Comment by bunnu** [comment]
Version 3.0.0-20170915 works fine.
Thanks!
