### ISSUE TITLE
Acknowledged services not filtered out after update version 3

### ISSUE THREAD

**Issue by TestingUser1432** [HenriWahl/Nagstamon#441]
Updated to version 3.0 with on the serverside OP5.
In previous versions, no problems with the filtering of acknowledged services.
In the 3.0 release they don't get filtered.

**Comment by HenriWahl** [comment]
Which server version do you use exactly?

**Comment by HenriWahl** [comment]
I can at least confirm this behavior for https://demo.op5.com. Stay tuned.

**Comment by HenriWahl** [comment]
From which version did you upgrade? The op5-code did not change for 11 months.

**Comment by TestingUser1432** [comment]
Hi, don't know. I'm almost sure the most recento one.
So from the most recent beta, I guess. In the previous version I ran this
withouth any problems.

2017-09-15 10:21 GMT-04:00 Henri Wahl <notifications@github.com>:

**Comment by HenriWahl** [comment]
Strange... at least in 2.0 filters couldn't have been working anyway. I fixed it and will provide a binary for testing soon.

**Comment by TestingUser1432** [comment]
Oke, thanks. Please inform me about the binary so I can test is directly.

2017-09-15 11:02 GMT-04:00 Henri Wahl <notifications@github.com>:

**Comment by HenriWahl** [comment]
If there is already one fitting your needs check https://nagstamon.ifw-dresden.de/files/incoming/, otherwise all binaries will be available at the download location soon too.

**Comment by HenriWahl** [comment]
All files arrived at https://nagstamon.ifw-dresden.de/download/#testing.

**Comment by TestingUser1432** [comment]
Tested it, and it works fine.
Thanks for the very quick response.

2017-09-15 11:26 GMT-04:00 Henri Wahl <notifications@github.com>:
