### ISSUE TITLE
SSL/TLS problem-button doesn't disappear even when error is fixed

### ISSUE THREAD

**Issue by cstuder** [HenriWahl/Nagstamon#442]
I'm using a custom CA file for checking in on two Icinga servers. The connections work, but Nagstamon is still reporting a SSL/TLS problem:

![nagstamon_tls](https://user-images.githubusercontent.com/288493/30532592-61efd256-9c55-11e7-99d7-adbddb7bd432.png)

Unfortunate side effect: The tray icon is gray (Reporting a problem) instead of the error level status (red in this case)

Nagstamon 3.0.0 running on Windows 10

**Comment by cstuder** [comment]
Log file:

[nagstamon.log.txt](https://github.com/HenriWahl/Nagstamon/files/1309973/nagstamon.log.txt)

**Comment by HenriWahl** [comment]
In this case the CA file might be wrong somehow. How did you retrieve it? How would it be displayed in Firefox?
One test happened with a self-signed certificate, which I had to extract from Firefox certificate view.

**Comment by cstuder** [comment]
No, exporting the certificate file (*.crt) from Firefox yields the exact same file.

Oh, wait, the log file reports errors when calling https://nagstamon.ifw-dresden.de/version/stable

When I disable the update check, the SSL/TLS-error in the GUI disappears. I suspect that the version check is using the custom certificate as well and that https request fails.

**Comment by HenriWahl** [comment]
This is interesting... and apparently somehow stupid as well... thanks for the hint!

**Comment by HenriWahl** [comment]
Please check latest unstable 3.0.0-20170918 from https://nagstamon.ifw-dresden.de/download/#testing.

**Comment by HenriWahl** [comment]
Is there any improvement noticeable?

**Comment by cstuder** [comment]
Sorry, couldn't check yet. (Kids sick, deadlines looming, inappropriate time for software updates...)

I will get back to you later today or tomorrow.

**Comment by HenriWahl** [comment]
Good luck then...

**Comment by cstuder** [comment]
Success: unstable 3.0.0-20170918 on Windows 10 fixes this issue.
