### ISSUE TITLE
Nag 3.0: Not Retina / HighRes optimised 

### ISSUE THREAD

**Issue by rubenschmidtmann** [HenriWahl/Nagstamon#443]
The new interface is pixelised on my Retina / HighRes screen:

<img width="572" alt="screen shot 2017-09-18 at 15 30 01" src="https://user-images.githubusercontent.com/1044463/30544612-61245806-9c87-11e7-9f35-d76dea83163c.png">

**Comment by HenriWahl** [comment]
Does this come with 3.0 or happened with earlier version 2.0 too?

**Comment by rubenschmidtmann** [comment]
It’s a new thing (never happened with any 2.x version).

**Comment by HenriWahl** [comment]
Please check https://nagstamon.ifw-dresden.de/files/incoming/Nagstamon%203.1-20170921.dmg as it is compiled with latest Qt5, hoping it has less Retina problems.

**Comment by rubenschmidtmann** [comment]
No, still the same.

OS: macOS 10.12.6

**Comment by HenriWahl** [comment]
This bad news. I can't reproduce it due to the lack of a Retina capable device.
Maybe you can do some testing according to https://stackoverflow.com/questions/34465506/retina-support-in-qt5-on-os-x and modify the file Info.plist in the Nagstamon.app, just to see if it is of any help?

**Comment by HenriWahl** [comment]
Please use the Info.plist from https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/resources/Info.plist to see if it helps.

**Comment by HenriWahl** [comment]
Please try with https://nagstamon.ifw-dresden.de/files/incoming/Nagstamon%203.1-20170922.dmg.
For compiling Nagstamon 3.0 pyinstaller was used, but cx-freeze for 2.0. The custom Info.plist from 2.0 has been omitted so the Retina setting was missing.

**Comment by rubenschmidtmann** [comment]
Thanks! The latest version fixed the problem.

#
Ruben Schmidtmann
M +49.151.24242386
ruben@rubenschmidtmann.com

rubenschmidtmann.com
twitter.com/160grad

**Comment by HenriWahl** [comment]
Great news!

**Comment by HenriWahl** [comment]
Just out of couriosity: can you post a Retina-enabled screenshot for comparison?

**Comment by rubenschmidtmann** [comment]
Here is screenshot of the fixed version:

<img width="583" alt="screen shot 2017-09-22 at 13 47 15" src="https://user-images.githubusercontent.com/1044463/30743162-cca9baf4-9f9c-11e7-9394-8424524f9002.png">

**Comment by HenriWahl** [comment]
Looks better, indeed.

**Comment by HenriWahl** [comment]
Would you mind if I use your screenshots for a release post?

**Comment by rubenschmidtmann** [comment]
No problem. Please go ahead.
