### ISSUE TITLE
Status window closes immediately on open

### ISSUE THREAD

**Issue by johnpugh24** [HenriWahl/Nagstamon#445]
Since upgrading to version 3.0.0 the status window closes immediately when clicking on the tray icon. This doesn't seem to happen the first time it is started, but does every time after that.

Using Windows 10 64bit Pro. 

Connected to IcingaWeb2 and has been working on all the versions leading up to 3.0.0.

If I right click and click on show status window then it shows a truncated view (attached)

![image](https://user-images.githubusercontent.com/32326907/30906963-4f1162a8-a371-11e7-95c6-c275633672ab.png)

I have reinstalled, but it had no effect.

**Comment by HenriWahl** [comment]
This sounds strange... what settings do you have regarding the status window (as in settings dialog display section)?

**Comment by johnpugh24** [comment]
If I am honest I didn't try changing anything in there! 

Current settings attached. 

![image](https://user-images.githubusercontent.com/32326907/30910435-b6bb2316-a37c-11e7-8afa-59abb95881a4.png)

If I select "Close when clicking statusbar" then it seems to open properly, but switching back to "Close when hovering out of popup" breaks it again.

Even though the "Popup when hovering over statusbar" is selected it doesn't come up on a hover, I have to click. Which is a shame, but at least it works ok with "Close when clicking statusbar" now.

**Comment by HenriWahl** [comment]
Hovering only works if in floating mode - systray always has to be clicked, on every platform.
Apparently your click is considered as hovering in the same time... I'll try to reproduce this behaviour.

**Comment by johnpugh24** [comment]
Ok I didn't know that. Thanks for your help, it is working well enough as a click to close for me now.
