### ISSUE TITLE
Nagstamon 3.0.2, 3.1-20170925 crashes on startup on Ubuntu 16.04

### ISSUE THREAD

**Issue by noonedeadpunk** [HenriWahl/Nagstamon#446]
Hello,

I've upgraded nagstamon from 2.0 to 3.0.2 and nagstamon 3 even doesn't start. It crashes with segfault instantly after launch. Config files flush doesn't work.

I've launched nagstamon with strace and attached output below:
[nagstamon.log](https://github.com/HenriWahl/Nagstamon/files/1336949/nagstamon.log)

Also, on the requirements page you specified, that requests-kerberos python module is required. However, it's unable to install this module, as its' setup.py uses deprecated import, which was removed in python3 ("import commands").

**Comment by HenriWahl** [comment]
Did you run Nagstamon from supplied .deb file?

**Comment by noonedeadpunk** [comment]
Yes, sure. I've installed it with `dpkg -i nagstamon_3.0.2_all.deb` And all my colleagues have exactly the same problem.

Thanks in advance.

**Comment by HenriWahl** [comment]
Your postscriptum seems t obe a valuable hint. So this is Kubuntu?
The used keyring module should be desktop and wallet agnostic.

**Comment by HenriWahl** [comment]
Runs in plain Ubuntu 16.04, both freshly installed. So what flavor of Ubuntu are you exactly running?

**Comment by mprenditore** [comment]
Can you share the output of `dpkg - l` and `pip freeze` please?

**Comment by noonedeadpunk** [comment]
I've just tried to install nagstamon on my home laptop and got the same result (I mean crash). On all devices I actually use Kubuntu. This is output from my apt log, when I installed nagstamon:Start-Date: 2017-09-27  23:35:38 Install: python3-html5lib:amd64 (0.999-4, automatic), python3-requests-kerberos:amd64 (0.7.0-2), python3-keyring:amd64 (7.3-1ubuntu1), python3-psutil:amd64 (3.4.2-1), python3-pyqt5.qtsvg:amd64 (5.5.1+dfsg-3ubuntu5~xenialoverlay11~1), python3-kerberos:amd64 (1.1.5-2build1, automatic), python3-crypto:amd64 (2.6.1-6ubuntu0.16.04.2,automatic), python3-lxml:amd64 (3.5.0-1build1, automatic), python3-secretstorage:amd64 (2.1.3-1, automatic),python3-pyqt5.qtmultimedia:amd64 (5.5.1+dfsg-3ubuntu5~xenialoverlay11~1), python3-bs4:amd64 (4.4.1-1)End-Date: 2017-09-27  23:35:45    27.09.2017, 23:03, "Henri Wahl" <notifications@github.com>:Runs in plain Ubuntu 16.04, both freshly installed. So what flavor of Ubuntu are you exactly running?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   -- С Уважением,Дмитрий.

**Comment by HenriWahl** [comment]
Well, on a fresh Kubuntu 16.04 with Nagstamon 3.0.2 with all its dependencies added by apt -f install I get a segmentation fault when starting from terminal. Is this the same experience you share?

**Comment by noonedeadpunk** [comment]
Yes, it's exactly this experience.
And, by the way, I almost sure, that it's related to using a keyring. As it seems, that nagstamon tries to use gnome keyring by default (which is replaced by kwallet in Kubuntu). When I got gnome keyring installed on one of work PC's, I was asked for new keyring creation, and once I cancelled it - nagstamon falled to seg fault as well.
When I've removed gnome keyring, it just instantly falls to segmentation fault.

**Comment by HenriWahl** [comment]
Bad news: https://github.com/jaraco/keyring/issues/273
Looks like gnome-keyring is necessary even on KDE. :-( Looks like keyring usage would not be possible on KDE - thus I need some detection method to avoid the segmentation fault.

**Comment by HenriWahl** [comment]
Good news: https://github.com/jaraco/keyring/issues/235 - please check the hints there, looks like one has to trigger keyring locally to use the correct backend.

**Comment by HenriWahl** [comment]
I do not even get it running with gnome-keyring... can you just try with gnome-keyring and for heavens sake give it some password?

**Comment by noonedeadpunk** [comment]
Hello,

Unfortunately, installation of gnome-keyring doesn't resolve problem for me either. I'm not even asked for the password (after I cancelled it entrance at the first launch).

**Comment by HenriWahl** [comment]
There is a semi-solution. I kicked out keyring for Ubuntu 16.04 (no idea if it would work with a later Ubuntu release) and thus it works now - without storing password in system keyring, but this seems to be OK compared to not being able to run Nagstamon at all. Please check https://nagstamon.ifw-dresden.de/files/incoming/nagstamon_3.1-20170927_all.deb.

**Comment by noonedeadpunk** [comment]
Yep, it works. And it even uses monitor credentials, which were saved within nagstamon 2

**Comment by HenriWahl** [comment]
yes, when I built binaries for all other platforms I will update the version string on server so it points to the latest one then. Just some minutes...

**Comment by HenriWahl** [comment]
Bow get them all at https://nagstamon.ifw-dresden.de/download/#testing.

**Comment by Vitexus** [comment]
SIGSEGV - Debian 9 / LXQT 
[nagstamon.strace](https://github.com/HenriWahl/Nagstamon/files/1841087/nagstamon.txt)
[dpkg -l](https://github.com/HenriWahl/Nagstamon/files/1841100/dpkgL.txt)
[pip freeze ](https://github.com/HenriWahl/Nagstamon/files/1841108/pipFreeze.txt)

:(

**Comment by noonedeadpunk** [comment]
On about 10PC's with kubuntu  we've got 20170927 and it works without problems. But yes, 3.1-20180425 crashes as well... For me crashes returned starting from 3.1-20171101

**Comment by Vitexus** [comment]
In my case uninstalling gstreamer plugins solve my problem.
