### ISSUE TITLE
Nagstamon 3.0.2-Win64 - Crashes on launch

### ISSUE THREAD

**Issue by Becky79Boo** [HenriWahl/Nagstamon#447]
Hi there, I have been trying to install v3.0.2-Win64 on Windows 10 without much luck.
Every time I launch this I get the "There are no configured server yet" message and process to create new server.
Once my server details are entered and I click OK, the setup box vanishes and nothing else happens however the system process is still running.
I have uninstalled and reinstalled several times, doing full removal and reg cleans in between but nothing seems to help.
Is this a known issue, can anyone advise if there is a workaround?

**Comment by HenriWahl** [comment]
Are there any special conditions in your setup? Did you remove the C:\Users\<user>\.nagstamon folder?

**Comment by Becky79Boo** [comment]
Hi, its a fresh install on my Windows machine for testing.
Just a bog standard PC running desktop applications.

**Comment by HenriWahl** [comment]
Are you able to run it in a terminal from pure Python source after creating an environment following the guidelines at https://nagstamon.ifw-dresden.de/docs/requirements/? This way there is a chance to get the error output.

**Comment by HenriWahl** [comment]
Any news?

**Comment by christophenouvel** [comment]
Hi there,
Exactely same problem here : after install on a Win 7 64 bits, unable to create any server.
My user account is a basic user account one.

Any help?

  Thank You,

    Christophe.

**Comment by HenriWahl** [comment]
@Becky79Boo @christophenouvel what monitor server types do you use? Any HTTPS involved?

**Comment by HenriWahl** [comment]
I prepared a .zip-file which allows you to run Nagstamon form plain sources in Windows to be able to get an error message of your crash. Please download it from https://seafile.ifw-dresden.de/f/67cb7de276bd4c26908c/ and run the included nagstamon-debug.bat. A cmd window should open, clone the latest Nagstamon source and wait even if it crashes so you might be able to give me some valuable error message.

**Comment by HenriWahl** [comment]
@Becky79Boo @christophenouvel did you try the debuggin version?

**Comment by jothoma1** [comment]
Hi @HenriWahl 
i have tried your debug version (i have the same problem)
Here is the output of nagstamon-debug.bat :

> C:\Users\jothoma1\Downloads\Nagstamon_debug\Nagstamon>..\python36\python nagstamon.py
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
Traceback (most recent call last):
  File "C:\Users\jothoma1\Downloads\Nagstamon_debug\Nagstamon\Nagstamon\QUI\__in
it__.py", line 3710, in get_status
    status = self.server.GetStatus()
  File "C:\Users\jothoma1\Downloads\Nagstamon_debug\Nagstamon\Nagstamon\Servers\
Generic.py", line 1326, in GetStatus
    self.events_current[service.get_hash()] = True
  File "C:\Users\jothoma1\Downloads\Nagstamon_debug\Nagstamon\Nagstamon\Objects.
py", line 164, in get_hash
    return " ".join((self.server, self.site, self.host, self.name, self.status))
TypeError: sequence item 4: expected str instance, NoneType found

**Comment by christophenouvel** [comment]
Hi all, 

Seems to be my fault : my centreon server is http only for now, and at the server creation box I entered an https link! 
It is enough to crash nagstamon without any error or warning, at least 3.0.2 64 bits and latest unstable, also 64 bits, on Windows 7. 

All is running fine now, but such an error killed me some hours to look for... 

Thank you, 

Christophe. 

----- Mail original -----

De: "Johan THOMAS" <notifications@github.com> 
À: "HenriWahl/Nagstamon" <Nagstamon@noreply.github.com> 
Cc: "christophenouvel" <christophe.nouvel@laposte.net>, "Mention" <mention@noreply.github.com> 
Envoyé: Jeudi 19 Octobre 2017 09:55:37 
Objet: Re: [HenriWahl/Nagstamon] Nagstamon 3.0.2-Win64 - Crashes on launch (#447) 



Hi @HenriWahl 
i have tried your debug version (i have the same problem) 
Here is the output of nagstamon-debug.bat : 



C:\Users\jothoma1\Downloads\Nagstamon_debug\Nagstamon>..\python36\python nagstamon.py 
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout 
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout 
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout 
Traceback (most recent call last): 
File "C:\Users\jothoma1\Downloads\Nagstamon_debug\Nagstamon\Nagstamon\QUI_ in 
it _.py", line 3710, in get_status 
status = self.server.GetStatus() 
File "C:\Users\jothoma1\Downloads\Nagstamon_debug\Nagstamon\Nagstamon\Servers 
Generic.py", line 1326, in GetStatus 
self.events_current[service.get_hash()] = True 
File "C:\Users\jothoma1\Downloads\Nagstamon_debug\Nagstamon\Nagstamon\Objects. 
py", line 164, in get_hash 
return " ".join((self.server, self.site, self.host, self.name, self.status)) 
TypeError: sequence item 4: expected str instance, NoneType found

**Comment by gizav** [comment]
Hi all,
I have tried to install the version 3.0.2 of Nagstamon on a Windows 2012 R2 but it crash after I entered my server details and I click OK. I have Centreon as monitor type, without SSL.
So, I have tried the debug version and here is the output of nagstamon-debug.bat:

> C:\Users\Administrator\Downloads\Nagstamon_debug\Nagstamon_debug>nagstamon-debug.bat`
> fatal: destination path 'Nagstamon' already exists and is not an empty directory.
> QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
> defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
> QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
> QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
> Traceback (most recent call last):
>   File "C:\Users\Administrator\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon\Nagstamon\QUI\__init__.py", line 5518
> , in ok
>     statuswindow.servers_vbox.addLayout(statuswindow.create_ServerVBox(servers[self.server_conf.name]))
>   File "C:\Users\Administrator\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon\Nagstamon\QUI\__init__.py", line 1312
> , in create_ServerVBox
>     server_vbox = ServerVBox(server, parent=self)
>   File "C:\Users\Administrator\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon\Nagstamon\QUI\__init__.py", line 2787
> , in __init__
>     self.table = TreeView(len(HEADERS) + 1, 0, sort_column, sort_order, self.server, parent=parent)
>   File "C:\Users\Administrator\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon\Nagstamon\QUI\__init__.py", line 3171
> , in __init__
>     self.worker = self.Worker(server=server, sort_column=self.sort_column, sort_order=self.sort_order)
>   File "C:\Users\Administrator\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon\Nagstamon\QUI\__init__.py", line 3693
> , in __init__
>     self.server.init_config()
>   File "C:\Users\Administrator\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon\Nagstamon\Servers\Centreon.py", line
> 72, in init_config
>     self._define_url()
>   File "C:\Users\Administrator\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon\Nagstamon\Servers\Centreon.py", line
> 382, in _define_url
>     'xml_services': self.monitor_cgi_url + '/include/monitoring/status/Services/' + self.XML_PATH + '/serviceXML.php',
> AttributeError: 'CentreonServer' object has no attribute 'XML_PATH'
> 
> C:\Users\Administrator\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon>

Is there a workaround?

Thanks.

_// Giovanni_

**Comment by BenoitPoulet** [comment]
@gizav 
That's not the same PB, yours is Centreon related, please copy your message in another issue and delete this one.  It will be easier to help you.
