### ISSUE TITLE
Error when inserting and ejecting a DVD

### ISSUE THREAD

**Issue by jackburton79** [HenriWahl/Nagstamon#448]
When nagstamon is active, if I insert a DVD in the drive, keep it there for a while, then eject it, nagstamon will periodically open a modal window with "Cannot find disk in unit D:". Restarting nagstamon does not fix the problem. I have to restart the computer.
Happens on at least two computers here, with Windows 7 x64.
Nagstamon 3.0.2, but I think this bug is there at least since 2.0

**Comment by jackburton79** [comment]
![immagine](https://user-images.githubusercontent.com/3501519/31005240-1d31bcaa-a4f8-11e7-85d2-d12a5edfb23d.png)

**Comment by mprenditore** [comment]
Can you please try to enable Debug mode and share the log while you have the error?

**Comment by jackburton79** [comment]
I inserted the dvd, launched an executable on it (then closed the launched app), waited a bit, then ejected the dvd.
Seems there is absolutely nothing in the log:
[nagstamon.log](https://github.com/HenriWahl/Nagstamon/files/1386660/nagstamon.log)

**Comment by jackburton79** [comment]
I think this can be closed. I observed the same behaviour with another application, and I think it's caused by our antivirus (ESET Nod32)
