### ISSUE TITLE
Nagstamon 3.0.2-Win64 - Crashes on launch with Centreon 2.8.x

### ISSUE THREAD

**Issue by joschi99** [HenriWahl/Nagstamon#452]
We use nagstamon 3.0.2 with Centreon 2.8.14. The normal configuration using https with a correct certificate work fine, but if we enable "Ignore SSL/TLS certificate" or if we switch to a http url the program crashes.

**Comment by BenoitPoulet** [comment]
Strange, 
I'm currently using the latest stable version to try hunting another bug, and i'm on a install with Centreon 2.8.14, Self sign certificate.

I tried to switch in HTTP, and no crash too.

Can you try to purge you config files (C:\Users\<you login>\.nagstamon), do the config again, enable debug, and post the debug here on crash please ?

**Comment by BenoitPoulet** [comment]
Perhaps it related to #447 ?

**Comment by jothoma1** [comment]
Hi @BenoitPoulet 
Did you see the bug "Nagstamon 3.0.2-Win64 - Crashes on launch #447" ?
I think it's related and i have post a debug.
Johan

**Comment by joschi99** [comment]
I tried to reproduce the problem in lab, but it seem's working. I will try to reproduce the error on the production system this week.
