### ISSUE TITLE
Latest unstable doesnt write to conf file

### ISSUE THREAD

**Issue by cerberus10** [HenriWahl/Nagstamon#456]
Hi I just wanted to let you know that the latest nightly build doesnt update nagstamon.conf with changes. 

I have tried it in Lubuntu 16.10 and Windows 10. 

Hope it helps.

**Comment by HenriWahl** [comment]
The previous worked?

**Comment by HenriWahl** [comment]
Strange thing... I tested on Fedora 26 without any trouble. Can you run it in  a terminal to see if there is any uncovered error?

**Comment by cerberus10** [comment]
Solved in the Windows host, I just modified the permissions for the config file. 
Not sure whats up in the linux one, i just modified with vim the file manually and it works. I will try to  do a fresh install and upload  the bash output to sere of the problem remains.

**Comment by HenriWahl** [comment]
Interesting where the worng permissions came from... any thirdparty action done recently?

**Comment by cerberus10** [comment]
I dont think so It was a fresh lubuntu VM.

**Comment by HenriWahl** [comment]
How is it now on your Lubuntu VM?
