### ISSUE TITLE
3.0.2 Win64 - Empty host XML result

### ISSUE THREAD

**Issue by antier-r** [HenriWahl/Nagstamon#457]
Hi, when a computer goes out of standby mode, Nagstamon won't refresh and we have to restart it.
It seems like Nagstamon is losing connection and then can't reconnect even when manually refreshing
The log is attached. Nagstamon 3.0.2 win10 64bits
[nagstamon.log](https://github.com/HenriWahl/Nagstamon/files/1445523/nagstamon.log)

Does anyone have an idea ? Thanks

**Comment by HenriWahl** [comment]
What monitor server do you connect to?

**Comment by antier-r** [comment]
Centreon 2.8
More info: it does not happen when I put my pc on standby and I turn it back on directly.
It happens when the standby lasts more than ~30min

**Comment by BenoitPoulet** [comment]
That's because you session must be expired when you wake up you computer, but Nagstamon still have it.

The push #455 must fix the issue , if you can run Nagstamon from source , please confirm it (branch master)

**Comment by HenriWahl** [comment]
The latest unstable binaries should contain this fix already too - not entirey sure but worth a try.

**Comment by antier-r** [comment]
Yep unstable 3.1-20171101 contains the fix, it's working. Thank you :)
