### ISSUE TITLE
Check_MK 3.0.2 does nothing on click tray

### ISSUE THREAD

**Issue by grego1981** [HenriWahl/Nagstamon#459]
Hello! 

I have seen that when the tray icon is blinking and try to left click it to see the notification it doesn't come up unless you right click and select show status icon. Also most of the times the status page hides under the taskbar. (Win 7 Pro x64, Nagstamon 3.0.2)

**Comment by HenriWahl** [comment]
Please check latest testing version from https://nagstamon.ifw-dresden.de/download/#testing.
