### ISSUE TITLE
Nagstamon 3.0.2-Win64 - Crashes on launch after Centreon update...

### ISSUE THREAD

**Issue by christophenouvel** [HenriWahl/Nagstamon#460]
Hi all,

Juste updated a centreon with "yum update", and nagstamon (3.0.2 on Win7 64) crashes on launch...

Upgrade wizard on centreon solved the problem.

  Christophe.

**Comment by BenoitPoulet** [comment]
Hello,
This is because of bad handle when getting pages, so when you update the index page is redirected to the upgrade page. The code need to be reworked.
