### ISSUE TITLE
Nagstamon 3.0.2-Win 2012 64bit - Crashes after confirm my server data with Centreon as monitor type

### ISSUE THREAD

**Issue by gizav** [HenriWahl/Nagstamon#464]
Hello,
I have tried to install the Nagstamon version 3.0.2-Win64 on a Windows 2012 R2, but it crash after I entered my server details and I submited my choices.
I have Centreon as monitor type, without SSL.
So, I have tried the debug version and here is the output of nagstamon-debug.bat:

> C:\Users\Administrator\Downloads\Nagstamon_debug\Nagstamon_debug>nagstamon-debug.bat`
>     fatal: destination path 'Nagstamon' already exists and is not an empty directory.
>     QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
>     defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
>     QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
>     QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
>     Traceback (most recent call last):
>     File "C:\Users\Administrator\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon\Nagstamon\QUI_init_.py", line 5518
>     , in ok
>     statuswindow.servers_vbox.addLayout(statuswindow.create_ServerVBox(servers[self.server_conf.name]))
>     File "C:\Users\Administrator\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon\Nagstamon\QUI_init_.py", line 1312
>     , in create_ServerVBox
>     server_vbox = ServerVBox(server, parent=self)
>     File "C:\Users\Administrator\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon\Nagstamon\QUI_init_.py", line 2787
>     , in init
>     self.table = TreeView(len(HEADERS) + 1, 0, sort_column, sort_order, self.server, parent=parent)
>     File "C:\Users\Administrator\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon\Nagstamon\QUI_init_.py", line 3171
>     , in init
>     self.worker = self.Worker(server=server, sort_column=self.sort_column, sort_order=self.sort_order)
>     File "C:\Users\Administrator\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon\Nagstamon\QUI_init_.py", line 3693
>     , in init
>     self.server.init_config()
>     File "C:\Users\Administrator\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon\Nagstamon\Servers\Centreon.py", line
>     72, in init_config
>     self._define_url()
>     File "C:\Users\Administrator\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon\Nagstamon\Servers\Centreon.py", line
>     382, in _define_url
>     'xml_services': self.monitor_cgi_url + '/include/monitoring/status/Services/' + self.XML_PATH + '/serviceXML.php',
>     AttributeError: 'CentreonServer' object has no attribute 'XML_PATH'
> 
>     C:\Users\Administrator\Downloads\Nagstamon_debug\Nagstamon_debug\Nagstamon>

Is this a known issue?
Thanks. 

Regards.

// Giovanni

**Comment by BenoitPoulet** [comment]
Hello,

I need more information, can you enable the mode debug of Nagstamon ?
"Settings > Debug mode"  and paste here the log file ?
(that will be the debug of the Centreon class)

**Comment by gizav** [comment]
Hello,
I have taken time for make several tests (with the stable and debug version of nagstamon) and I'm arrived at point that I had probabily a problem with the connection with the monitoring server.
I notice that if there is a problem with the connection, when I try to add, edit or delete a server, the application closes after I confirmed my changes.
So, I belived to have an issue related with a centreon monitor type, but now is ok (now I'm tring nagstamon with a old monitoring server with nagios as engine and centreon as frontend more another centreon appliance and work fine all). I think that I can close this issue.

Below the only log that I have obtained when I changed the server's configuration and the application closes:

[nagstamon.log](https://github.com/HenriWahl/Nagstamon/files/1538685/nagstamon.log)

Regards.

**Comment by BenoitPoulet** [comment]
It looks like the PB was with you Nagios server, unable to resolve the DNS name.

@HenriWahl Perhaps some error catching must be done in the Nagios or Generic class as it's not Centreon related.

**Comment by HenriWahl** [comment]
Yes, actually a good idea.

**Comment by ytilotti** [comment]
We have the same problem. Do you have more information since?

**Comment by HenriWahl** [comment]
Any change with latest release 3.4rc2?
