### ISSUE TITLE
seg. fault when is called from crontab

### ISSUE THREAD

**Issue by apolinux** [HenriWahl/Nagstamon#465]
I tried to start nagstamon from crontab but always get a fatal error from system:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-carlos'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-carlos'
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): anubis.3dm.com.co
Segmentation fault (core dumped)

this is the line of crontab:
30 8 * * 1-5 env HOME=/home/carlos DESKTOP_SESSION=gnome DISPLAY=:0 /usr/bin/python3 /usr/bin/nagstamon > /home/carlos/runjob.log 2>&1

I'm using Ubuntu gnome 17.04 in Asus X555Q laptop.

Please help.

thanks.

**Comment by apolinux** [comment]
hi, some news about it?

**Comment by HenriWahl** [comment]
Not really.... but why do you start Nagstamon from crontab?

**Comment by apolinux** [comment]
Hi Henry

I'm using nagstamon at work and I need todo start it in work hours.

Regards.

**Comment by HenriWahl** [comment]
OK... honestly I do not have any experience with starting it from crontab. If it segfaults maybe it simply does not work this way... any trouble with DISPLAY variable?
