### ISSUE TITLE
SNI cert error

### ISSUE THREAD

**Issue by lgbff** [HenriWahl/Nagstamon#466]
Hi,

i have the following issue on a SSL Host with SNI:
`DEBUG: 2017-12-07 15:27:08.644186 lgb check_mk Refreshing all hosts and services
DEBUG: 2017-12-07 15:27:31.611370 lgb check_mk Start rechecking all
DEBUG: 2017-12-07 15:27:31.611370 lgb check_mk Rechecking all action: https://monitoring.lgb.local//lgb/check_mk/view.py?_transid=-1&_do_actions=yes&_do_confirm=Yes!&view_name=svcproblems&filled_in=actions&lang=&_resched_checks=Reschedule+active+checks
DEBUG: 2017-12-07 15:27:31.611370 lgb check_mk FetchURL: https://monitoring.lgb.local//lgb/check_mk/view.py?_transid=-1&_do_actions=yes&_do_confirm=Yes!&view_name=svcproblems&filled_in=actions&lang=&_resched_checks=Reschedule+active+checks CGI Data: None
ERROR: 2017-12-07 15:27:31.655387 lgb check_mk Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 346, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
  File "site-packages\urllib3\connection.py", line 326, in connect
  File "site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)`

This cert is i.O.
Any other Clients have no problems....

nagstamon: 3.0.2 on Windows7

Regards Karsten

**Comment by HenriWahl** [comment]
Do you need to give Nagstamon the CA cert to be able to proof the server's cert?

**Comment by lgbff** [comment]
The CA cert is on Windows IE ...
Must be give nagstamon extra this cert?
Where to?

**Comment by HenriWahl** [comment]
In case your monitor server's cert is not accepted as it is you can either tell Nagstamon to ignore the problems or give it the CA cert - see options.
I only managed to get the server's CA cert in Firefox in settings and export it.

**Comment by HenriWahl** [comment]
Happy New Year.... if this still is an issue please check https://nagstamon.ifw-dresden.de/how-to-solve-trouble-with-self-signed-certificates/.
