### ISSUE TITLE
No kerberos authentification possible when no https connection

### ISSUE THREAD

**Issue by winter1967** [HenriWahl/Nagstamon#467]
Hi,
we use kerberos authentification on our apache webserver. So icingaweb2 use the system credentials of my windows 7 machine.

At nagstamon i have the following configuration:
Monitor type: Icinga
Monitor URL: http://icinga.our.domain.de
Use proxy: false
Show more Options: true
Authentification: Kerberos
Do not use cookie authentification: true

Use system keyring for server credentials: true (i've tried false, too)
Debug mode: true

Nagstamon came up, but it shows me
"authentification problem"

Now another try with an https secured connection to our old icinga2 server:

Monitor type: Icinga
Monitor URL: https://icinga.our.domain.de/icingaweb
Use proxy: false
Show more Options: true
Authentification: Kerberos
Do not use cookie authentification: true

it works nice. Maybe we have to use an https connection?

**Comment by HenriWahl** [comment]
Happy New Year... well, are your https and http serverside settings identical? As far as I know there is no requirement to run https wile using kerberos but it is a good idea anyway to do so.
