### ISSUE TITLE
[REQUEST]Select the display on "Icon on systray" or "Window" mode

### ISSUE THREAD

**Issue by twproject** [HenriWahl/Nagstamon#469]
Hi,
  i have 2 monitor and i'm asking if is it possible to configure nagstamon in order to put notification on the second screen. I don't want to use fullscreen, where setting is present.

Is it possible to set for "Icon on systray" or "Window" mode too?

**Comment by HenriWahl** [comment]
No - an application is not free to choose a systray. In window mode you are free to put your window wherever you want so it makes no sense to configure a monitor.
To force Nagstamon notification appearing on a certain monitor just use the floating mode where you can place Nagstamon wherever you want and have its notification right there.
