### ISSUE TITLE
[Feature request]: acknowledged/downtime comment in the tooltip

### ISSUE THREAD

**Issue by bozicm** [HenriWahl/Nagstamon#471]
The suggestion would come handy when there are multiple Nagios users that can set the downtime/acknowledged comment. Currently the tooltip of a host displays the same information as *Status information* column.

It would be nice to have the tooltip display the comment on acknowledged/downtimed hosts. I'd like to see the comment directly from Nagstamon instead of switching to full Nagios web interface.

**Comment by HenriWahl** [comment]
Comments are not transmitted to Nagstamon and have to be requested one for one which makes no sense.
