### ISSUE TITLE
Status Information source data

### ISSUE THREAD

**Issue by zetheroo** [HenriWahl/Nagstamon#472]
I am using Nagstamon 3.0.2 with Icinga and Zabbix.

Is it possible to have the Status Information column get it's data from somewhere else in Zabbix - Such as the Latest Data information for that Zabbix Item?

The reason for this is that while for Icinga the Status Information shows both static and dynamically generated information (such as the output of scripts), the Zabbix Status Information merely grabs whatever the static name is of the Trigger.

TIA

**Comment by mprenditore** [comment]
Hello, sorry for the late.
In Zabbix you can use Macros in the Trigger name to show the various detailed information, like:

`Configured max number of opened files is too low on {HOST.NAME} ({ITEM.LASTVALUE})`

you can see the list of Macros from: https://www.zabbix.com/documentation/3.4/manual/appendix/macros/supported_by_location

Let me know if that is enough :)

**Comment by zetheroo** [comment]
Thanks! That seems to be working well.
One thing I will note for others who come across this ... The Macros have a 20 char limit so to see all the output I had to use: {{ITEM.LASTVALUE}.regsub("([\s\S]*)", "\1")}

**Comment by zetheroo** [comment]
A follow-up question to the above is ... Is there a way to limit the number of characters shown in Nagstamon under the Status Information column? At the moment there is a massive dump of output. Is this  something that can be controlled in Nagstamon, or has this got to be done from Zabbix?

**Comment by HenriWahl** [comment]
At the moment Nagstamon shows what it gets - so if you are able to limit this in Zabbix this is your only chance right now.

**Comment by zetheroo** [comment]
Ok, I'll try to do something on the Zabbix end then. 
One thing I noticed is that for Icinga notifications there is a 'Monitor' option when you click on the notification, but not for the Zabbix notifications - is this something that can be created/added on my end?
