### ISSUE TITLE
Nagstamon 3.1 Segfault when : The name org.freedesktop.Notifications was not provided by any .service files

### ISSUE THREAD

**Issue by dmaphy** [HenriWahl/Nagstamon#473]
For some weird reason I had no xfce4-notifyd installed on my system and thus, there was no notification service available on my system… anyway, when that happens, nagstamon segfaults:

```
% nagstamon 
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.Notifications': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/Nagstamon/QUI/__init__.py", line 6440, in __init__
    '/org/freedesktop/Notifications')
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
[1]    8968 segmentation fault (core dumped)  nagstamon
```

It's probably a great idea to catch this case and start nagstamon anyway. :-)

**Comment by HenriWahl** [comment]
In the meantime see https://github.com/HenriWahl/Nagstamon/issues/357.

**Comment by HenriWahl** [comment]
According to https://github.com/HenriWahl/Nagstamon/issues/320 this problem could not be solved as Nagstamon gets feedback first that DBus is available.

**Comment by gjedeer** [comment]
I'm affected by this after upgrading from Xubuntu 16.04 to 18.04. After reading your comments about this issue I wrote a simple [patch](https://github.com/gjedeer/Nagstamon/commit/7875183bb6828c0eb68090a541a5a3cdae81f3de) which adds a simple setting disable_dbus, which simply sets DBUS_AVAILABLE to False without checking.

It doesn't crash any more but it doesn't show the icon too. It's doing something, probably running an event loop: ran it with strace, when I click my mouse some events are coming with poll(). But no icon and no indications of connecting to my Nagios instance.

**Comment by HenriWahl** [comment]
Well, maybe you find a way to display the icon too? But anyway, this is a logical problem as DBus availability can't be checked without initializing it - at least as far as I remember and thus decided there were not much to do.

**Comment by gjedeer** [comment]
I tried to but did not succeed, I never really programmed Qt. Will try again.
