### ISSUE TITLE
v3.02 for OSX insta-crashes [Testing version works]

### ISSUE THREAD

**Issue by glamrock** [HenriWahl/Nagstamon#474]
Behavior identical to #423, but wasn't able to resolve it in the same way.  Tried reinstalling but had same behavior. 

Removed v3.02 and installed Nagstamon 3.1-macOS10.11-20171101.dmg from the testing branch and was then able to configure/run Nagstamon. Works great for what I need =)

**Comment by HenriWahl** [comment]
The stable version 3.0.2 was compiled on macOS 10.12 and sadly not able to be run at 10.11 :-(

**Comment by glamrock** [comment]
The testing version works fine, but occasionally launches the authentication prompt (greyed out since I'm already authenticated / the dashboard is already running).
