### ISSUE TITLE
Nagstamon 3.0.2 and 3.1 beta crashes on launch

### ISSUE THREAD

**Issue by MacManX** [HenriWahl/Nagstamon#477]
I am running Nagstamon 2.0.1 on MacOS X 10.10.5 which works just fine. However, updating to 3.0.2 or 3.1 does not work. The app crashes directly on launch. 
Is this because I am running an older version of MacOS X?
I have noticed that there is a separate macOS 10.11 version of Nagstamon 3.1 (which I have not tested).
Please advice!

**Comment by HenriWahl** [comment]
Exactly - for whatever reason it does not work if compiled on newer versions. Maybe just update or compile your own with the simple steps on https://nagstamon.ifw-dresden.de/docs/requirements/.
