### ISSUE TITLE
Network throughput spikes every 10 seconds

### ISSUE THREAD

**Issue by Crabbey** [HenriWahl/Nagstamon#480]
Nagstamon is causing throughput on my wifi card(s) to drop.
Tested on Killer Wireless 1535, and ASUS USB-AC53.

Best seen in this MTR between my device and 8.8.8.8:
https://puu.sh/zjYm6/9b75bae507.png
key: .:49ms 1:191 ms  2:431 ms  3:767 ms  a:1198 ms  b:1725 ms  c:2349 ms

The MTR starts with nagstamon c.losed. I open it roughly 2/5ths of the way into the trace, and begin to see the issue.

I've noticed, when the issue manifests, all responses are not processed, then all return at once.

Digging deeper, I can see Nagstamon is interrogating the registry for DHCP parameters on my network cards every ten seconds, exactly in line with these spikes:
https://puu.sh/zjYMT/62751dbc5e.png

I suspect it's one of your underlying libraries, but I'm unsure how to continue diagnosing this issue.

**Comment by corneliusroot** [comment]
I experienced the very same issue, and the network lag was every 10 seconds. Updating to 3.1 testing resolved the issue.

**Comment by HenriWahl** [comment]
Strange thing... Which platform do you run it on?
I feel pretty innocent - as well for the issue as for its solution.

**Comment by HenriWahl** [comment]
Please check with latest stable version as it contains newer Python an Qt. Get it at https://nagstamon.ifw-dresden.de/download/.
