### ISSUE TITLE
Nagstamon just giving me big OK

### ISSUE THREAD

**Issue by MoHD20** [HenriWahl/Nagstamon#481]
I've added my server on setting all I get is this OK.

- OS: MacOs sierra 10.12 
- Nagstamon version: 3.0.2
- Logs are empty

![image](https://user-images.githubusercontent.com/12420351/36344008-8fbd8482-141c-11e8-9dd1-d1a0f8f32e1c.png)
![image](https://user-images.githubusercontent.com/12420351/36344021-c4a3ba4a-141c-11e8-93d5-56402c550899.png)

**Comment by HenriWahl** [comment]
Congratulations! I wish I ever had a green OK....
Is this not the expected state?
