### ISSUE TITLE
notification icon crash

### ISSUE THREAD

**Issue by micah** [HenriWahl/Nagstamon#482]
Hi,

I want to first thank you for this great tool, it is the best and I'm very happy that it exists!

I'm using 3.0.2 of nagstamon, in i3 tiling window manager. Everything works fine, for a while... and then the notification icon disappears from the status bar. The program is still running, but I don't get any alerts or anything. The only thing I can do is to lookup the pid and kill the process, and then re-launch it again. I had the same problem with xmonad, I dont know if it is the windowmanager or not.

I've looked a bit at the nagstamon.log to try and figure out if anything was reported there, I do see a few of these:

```
ERROR: 2018-02-23 05:49:41.196330 foo Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Generic.py", line 555, in _get_status
    table = htobj('table', {'class': 'status'})[0]
IndexError: list index out of range
```

As well as a few Max retries exceeded, and connect timeout errors.

**Comment by HenriWahl** [comment]
Hi,
sorry for the late answer.
Well, your findings in the logs only have to to with information retrieval from monitor - not the output yet. 
Nagstamon is mostly tested on pretty mainstream platforms like GNOME and KDE - for testing others there are no resources, so I fear I can't really help here.

**Comment by HenriWahl** [comment]
Any progress with using release 3.4rc2?
