### ISSUE TITLE
Crash on Raspberry Pi

### ISSUE THREAD

**Issue by kallekutta** [HenriWahl/Nagstamon#483]
Hello,

I don't know if Raspberry Pi is supported but it wont start on it.

Model: Raspberry Pi 3

OS:
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.3 (stretch)
Release:	9.3
Codename:	stretch

Error:
```
pi@sam-rasp01:~ $ nagstamon
[Errno 2] No such file or directory: '/home/pi/.nagstamon/nagstamon.pid'
libEGL warning: DRI2: failed to authenticate

** (python3:1498): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.Notifications': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 6426, in __init__
    '/org/freedesktop/Notifications')
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
Segmentation fault
```

**Comment by mprenditore** [comment]
Hello,
Has stated in one of the comment here: https://github.com/HenriWahl/Nagstamon/issues/357
Can you try to install [notification-daemon](https://packages.debian.org/stretch/notification-daemon)?

**Comment by kallekutta** [comment]
Hello,

I tried your suggestion and installed notification-daemon but still get the same error.

**Comment by raffiiii** [comment]
Experiencing the same problem despite installing the notification-daemon.

**Comment by LHozzan** [comment]
Hello.
Same problem here.

Distributor ID:	Debian
Description:	Debian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch

I use LXDE as a desktop, because working on old computer with low resources.

**Comment by kallekutta** [comment]
> Hello.
> Same problem here.
> 
> Distributor ID: Debian
> Description: Debian GNU/Linux 9.9 (stretch)
> Release: 9.9
> Codename: stretch
> 
> I use LXDE as a desktop, because working on old computer with low resources.
> 
> EDIT:
> I have workaround working for me:
> 
> 1. Check, that package `notification-daemon` is installed by command `sudo apt-get install notification-daemon`. If isnt installed, install it.
> 2. Check, that `notification-daemon` is running by command `ps aux | grep notification-daemon | wc -l`, response **1** _not running_, response **2** _running_
> 3. If isnt running (my case), edit file `~/.config/lxsession/LXDE/autostart` with your favorite text editor and on end of file add line ([source](https://wiki.lxde.org/en/Autostart)):
> 
> ```
> @/usr/lib/notification-daemon/notification-daemon
> ```
> 
> After reboot (i think, relog should be enough) can nagstamon run without this problem.
> This is maybe bug in Debian / Raspbian (not sure).
> Hope that helps.

You are a hero! Your workaround works for me to, thank you for sharing!

**Comment by kallekutta** [comment]
Giving this a second thought I feel a bit stupid for not actually running notification-daemon after I installed it. I should have figured that out myself. Anyway, since there doesn't seem to be a problem with nagstamon I guess we can close this issue. Just maybe add notification-daemon as a dependency to the package?

PS. There is no need to reboot/relog, just run it from the command line like this:
`/usr/lib/notification-daemon/notification-daemon &`

**Comment by LHozzan** [comment]
Hello.
Sorry for late, I was busy.
> Giving this a second thought I feel a bit stupid for not actually running notification-daemon after I installed it. I should have figured that out myself. Anyway, since there doesn't seem to be a problem with nagstamon I guess we can close this issue. Just maybe add notification-daemon as a dependency to the package?

Dont worry, me too ;). I think, that better solution is let user side chose notification daemon. I mean `notification-daemon` working "out-of-the-box" on Gnome, but on LXDE or another light desktop environment should be "resource absorber".

I target to [Dunst](https://dunst-project.org/), which is better on slower computer with limited resources. More information about customization you can found [here](https://addy-dclxvi.github.io/post/dunst/).

In fact, I suggest add to Nagstamon only test for detect any notification daemon. If Nagstamon not found any usable notification daemon, let show error message about it.

User should be informed about missing environment component & have free hands to chose best for him.

I agreed, this isnt problem on Nagstamon side, just idea for improvement :).
