### ISSUE TITLE
RFE: RHEL 7/6 support

### ISSUE THREAD

**Issue by johsod** [HenriWahl/Nagstamon#485]
Hi,

I'd like to request support for RHEL 7 and/or 6 based distributions. Currently only community based distributions like Fedora seem to be supported.

Thanks in advance

----
rpmbuild -ba gives:
...
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd nagstamon-3.0.2.fedora26
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.I0RQxV
+ umask 022
+ cd /home/rpmbuild/rpmbuild/BUILD
+ cd nagstamon-3.0.2.fedora26
+ python3 setup.py build
/var/tmp/rpm-tmp.I0RQxV: line 29: python3: command not found
error: Bad exit status from /var/tmp/rpm-tmp.I0RQxV (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.I0RQxV (%build)

**Comment by HenriWahl** [comment]
As you correctly found I only cared about Fedora RPMs. You can try or modify the included build.py script.

**Comment by mprenditore** [comment]
Please, try to run:

`sudo yum install epel-release
sudo yum install python36
alias python3=python36`

and try to build again, if it works run:

`sudo ln -s /usr/bin/python36 /usr/bin/python3`

**Comment by HenriWahl** [comment]
@mprenditore Thanks!

**Comment by sebek72** [comment]
el7 support would be great. It is quite a hustle to manually build a working rpm for CentOS 7

**Comment by HenriWahl** [comment]
A bunch of needed packages is not available in CentOS or you have to do some strange moves.
What a bout a cleaner solution like https://flathub.org/apps/details/de.ifw_dresden.nagstamon ?

**Comment by sebek72** [comment]
Tnx, but my machines usually do not have internet access. So I need all the packages in a local repo. Have to prepare a centos7 bundle with all dependencies.

**Comment by HenriWahl** [comment]
Is https://unix.stackexchange.com/questions/404905/offline-install-of-a-flatpak-application of any help?

**Comment by sebek72** [comment]
yes, thanks. But It is too much clutter that needs to be copied over.
flatpak package = 1.3GB
rpm + dependency rpms = 144MB
