### ISSUE TITLE
No problems shown with current Check_MK Multisite 1.4.0p31

### ISSUE THREAD

**Issue by moschlar** [HenriWahl/Nagstamon#489]
While we have lots of service problems:
![screenshot from 2018-05-04 14-11-15](https://user-images.githubusercontent.com/228095/39627156-25c26bf0-4fa5-11e8-99e9-86fbd302d4df.png)
Nagstamon (latest testing version nagstamon_3.1-20180425_all.deb) doesn't think so:
![screenshot from 2018-05-04 14-11-21](https://user-images.githubusercontent.com/228095/39627170-3210b330-4fa5-11e8-80f9-d4becfd911c1.png)

The debug log just says:
```
DEBUG: 2018-05-04 14:11:18.703561 Monitor server FetchURL: https://monitor-01.zdv.uni-mainz.de/zdv/check_mk/view.py?view_name=nagstamon_hosts&output_format=python&lang=&limit=hard&is_host_acknowledged=-1&is_service_acknowledged=-1&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1&host_scheduled_downtime_depth=-1&is_in_downtime=-1 CGI Data: None
DEBUG: 2018-05-04 14:11:18.899297 Monitor server FetchURL: https://monitor-01.zdv.uni-mainz.de/zdv/check_mk/view.py?view_name=nagstamon_svc&output_format=python&lang=&limit=hard&is_host_acknowledged=-1&is_service_acknowledged=-1&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1&host_scheduled_downtime_depth=-1&is_in_downtime=-1&hst2=0 CGI Data: None
```

Is something wrong in our setup or can someone reproduce this ?

**Comment by HenriWahl** [comment]
The account in Check_MK Nagstamon is connected with is allowed to see everything? Did it work with other versions of Check_MK/Nagstamon?

**Comment by moschlar** [comment]
Yes, I tested with the administrator account.
And when I open the URL manually in the browser, I see a whole bunch of JSON data that looks good.

From the beginning of  `/check_mk/view.py?view_name=nagstamon_svc`:
```
[
['host', 'service_description', 'service_icons', 'service_state', 'svc_check_age', 'svc_state_age', 'svc_attempt', 'svc_plugin_output', 'svc_flapping', 'svc_notifications_enabled', 'svc_is_active', 'svc_in_downtime', 'svc_acknowledged', 'sitename_plain', 'host_address', 'svc_check_command'],
[u'printmonitor',u'Systemd_Status','menu ack comment','CRIT','16.0 s','2017-12-29 14:36:27','1/1',u'CRIT - SYSTEMD CRITICAL - failed units: nagios3.service','no','yes','no','no','yes','zdv',u'10.94.23.4',u'check_mk-mrpe',],[u'version-04',u'Systemd_Status','menu ack comment','CRIT','37.0 s','2018-01-18 14:43:17','1/1',u'CRIT - SYSTEMD CRITICAL - failed units: apache2.service','no','yes','no','no','yes','zdv',u'134.93.175.144',u'check_mk-mrpe',],
```

**Comment by HenriWahl** [comment]
Any filters activated?

**Comment by moschlar** [comment]
Argh, goddammit.

Yes, there were filters, and disabling them (by making a new `.nagstamon` directory) worked...

It is however weird that those filters worked for a different Nagios instance, that monitored most of the same hosts and services...

**Comment by moschlar** [comment]
Filtering "Services on unreachable Hosts" seems to effectively hide all services.
I suspect that could be "on purpose" since Check_MK doesn't do an active scan for host reachability or something like that...
