### ISSUE TITLE
FR - turn on/off added servers

### ISSUE THREAD

**Issue by FeatherBoy** [HenriWahl/Nagstamon#490]
I am using nastamon for a while. I manage 3 nagios servers but only 1 I have active in long term. As soon as something happen on the thoer 2 servers, I am forced to add server to nagstamon to see all alerts. After resolution I do not care and remove the server from nagstamon. 

It would be really nice to have option to add all servers and have the choice to enable/disable the server for checking the statuses. Something like switch where 1 one is still on and I see alerts and another 2 has switch to off so servers are added but not polled for information.

I hope I described feature request properly. If not please let me know for further details.

**Comment by HenriWahl** [comment]
You already can enable and disable a server on top of its server settings dialog. Are you looking for this feature?

**Comment by FeatherBoy** [comment]
Hi Henri, sorry I missed that option. It is exactly what I was looking for. It is pretty hidden :-) Thanks.
