### ISSUE TITLE
Crash when rechecking a 'gone alert'

### ISSUE THREAD

**Issue by Fr3dY2** [HenriWahl/Nagstamon#493]
Hi,

I'm using Nagstamon 3.1-20180523 and it just crashed when I clicked on an alert, and before clicking on 'Recheck', the alert was gone. I clicked the context menu entry anyway and program crashed.
It's not something that might happen a lot, but you could manage these scenarios (ignoring the recheck could be the easiest way).

Regards,

**Comment by HenriWahl** [comment]
Can you say if this happens only with the latest version?

**Comment by Fr3dY2** [comment]
Confirmed to crash using v20171101 as well.
Try to generate some dummy alert, then remove it, refresh (in Nagstamon) and then quickly go to the alert and right click before it disappears. Once the line is gone, click on 'Recheck' in the context menu.

**Comment by Fr3dY2** [comment]
Looks the issue has been fixed in v20180813...

**Comment by HenriWahl** [comment]
Sounds Like good news!
