### ISSUE TITLE
Distinguish multiple servers 

### ISSUE THREAD

**Issue by kostya-zpr** [HenriWahl/Nagstamon#498]
I have to monitor several servers. It seemed to me rather unhandy that all warnings merge into one common list. Running multiple instances of the nagstamon solves the problem, but they are difficult to distinguish from each other. My low-level skill in python was enough to make each instance with its own icon. Maybe someone will find this patch useful. 
Ideally, it would be nice to separate information from different servers in a floating window, for example on different lines, but I did not find a way to do it.

[Nagstamon.patch.txt](https://github.com/HenriWahl/Nagstamon/files/2112033/Nagstamon.patch.txt)

**Comment by HenriWahl** [comment]
Still easier to run separate Nagstamon instances with different colors or just multiple servers in one instance.
