### ISSUE TITLE
Check_MK 1.4.0pxx compatibility

### ISSUE THREAD

**Issue by orgitnized** [HenriWahl/Nagstamon#499]
How can I help get Nagstamon working for the Check_MK 1.4 series?  The 1.2 series works as expected, but 1.4 is the current stable, as opposed to 1.2 being the legacy stable.  So...updating sites to 1.4 renders the Nagstamon application useless.

**Comment by HenriWahl** [comment]
Which Nagstmon release do you use on which platform? Can you enable debug output?

**Comment by orgitnized** [comment]
Hi!
I use macOS High Sierra 10.13.5 and your app version is 3-1-20180523
In your app, I enable debug mode and debug to file.  I close the app and reopen it and the file gets created.  The app runs for 30 seconds and crashes and writes nothing to the log, ever.
What should I do next?
We also have the same issue on Windows 10 machines.

**Comment by HenriWahl** [comment]
I hope I will soon be able to use a productive 1.4 server so I fear we will run into the same problems but this might help to fix it!

**Comment by orgitnized** [comment]
Have you done ok on this?  I am using this on 1.5.pxx versions - figured I'd try it out for the fun of it.  I see it working so I'm wondering if you got it handled on 1.4 and 1.5 versions as far as support goes?

**Comment by HenriWahl** [comment]
No, I did not change a line of Check_MK-related code. Nice to hear it works.

**Comment by HenriWahl** [comment]
Please check latest testing version from https://nagstamon.ifw-dresden.de/download/#testing.

**Comment by orgitnized** [comment]
Works on both versions 1.4 and 1.5
Thanks!
