### ISSUE TITLE
Nagstamon Notification action on OK?

### ISSUE THREAD

**Issue by billyjack669** [HenriWahl/Nagstamon#501]
My Nagstamon doesn't perform notification actions on OK status. According to the Nagstamon features for actions, "The first allows to define some command to be run if one of the states WARNING, CRITICAL, DOWN or **OK** appears. "

I've looked through the log and don't see any notification actions performed when Nagstamon reports OK.

**Comment by billyjack669** [comment]
Checking back on this.  Maybe a little direction on how to make it work in the current stable (or testing) version?  I'm monitoring an Opsview server.  Any help will be appreciated.

**Comment by limes007** [comment]
Its broken, I made a pull request #552

**Comment by HenriWahl** [comment]
Possibly works now with latest release at https://nagstamon.ifw-dresden.de/download/#testing.

**Comment by billyjack669** [comment]
That did fix it.  It's been working in the past 2 test releases.  Thanks!
