### ISSUE TITLE
icingaweb2 $ADDRESS$

### ISSUE THREAD

**Issue by softcombiz** [HenriWahl/Nagstamon#509]
Hi. 
icingaweb2 in actions have $ADDRESS$ variable contains hostname (display name) instead of addresses.

**Comment by softcombiz** [comment]
Also the $HOST$ variable contains host_display_name instead of  host_name

**Comment by HenriWahl** [comment]
Sounds like a settings problem - can you please check them?

**Comment by HenriWahl** [comment]
![bildschirmfoto vom 2018-08-31 10-30-33](https://user-images.githubusercontent.com/2835065/44902034-3b89d600-ad09-11e8-88cd-012b41e0a552.png)
![bildschirmfoto vom 2018-08-31 10-31-37](https://user-images.githubusercontent.com/2835065/44902044-40e72080-ad09-11e8-8222-1a13233161ff.png)

**Comment by softcombiz** [comment]
https://image.ibb.co/eckPHp/2018_08_31_11_49_15.png
https://image.ibb.co/jpRaOU/2018_08_31_11_49_48.png

**Comment by softcombiz** [comment]
![server](https://image.ibb.co/eckPHp/2018_08_31_11_49_15.png)
![main](https://image.ibb.co/jpRaOU/2018_08_31_11_49_48.png)

**Comment by HenriWahl** [comment]
Yes, you use hostnames instead of IPs.

**Comment by softcombiz** [comment]
I use custom display_name in icinga, which is not has any dns record for resolve works, so if I choose any other settings I get ERROR in $HOST$ variable

**Comment by softcombiz** [comment]
as I see icingaweb2 does not provide host.adress field in monitoring/list/services?format=json, so I understand why this setting is needed.
But what about $HOST$ variable, I believe that it must contain host_name field instead of host_display_name, as you do did it with "acknowledge" action and real_name field in code

**Comment by HenriWahl** [comment]
@mmhh1910 any idea?

**Comment by softcombiz** [comment]
"Use display_name as host name" -in server settings does nothing.

**Comment by HenriWahl** [comment]
Ok. This is Icinga2Web-specific and the place where the $HOST$ is set is generic at the moment. An exception should be made there around https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/QUI/__init__.py#L4036
Are you able to make a pull request?

**Comment by HenriWahl** [comment]
Don't mind. I assumed you coded something.

**Comment by softcombiz** [comment]
Yes, Ruby and Go, Python is not known to me.
I looked at the code with the hope of understanding something and make the necessary functionality, but not luck. So I wrote the issue...

**Comment by HenriWahl** [comment]
Does it work with latest unstable from https://nagstamon.ifw-dresden.de/download/#testing?

**Comment by Massl123** [comment]
I have tested this in production since i created the pull request and had no issues.
