### ISSUE TITLE
"Services on unreachable hosts" does not work anymore on check_mk 1.5.x

### ISSUE THREAD

**Issue by vielhak** [HenriWahl/Nagstamon#510]
Hi,

since our update to CMK 1.5.0p2 the filter above does not work anymore.
I think they changed the behaviour of "/check_mk/view.py". If you add the "hst2=0" to the url, see ./Nagstamon/Servers/Multisite.py

```
        # Add filters to the url which should only be applied to the service request
        if conf.filter_services_on_unreachable_hosts == True:
            url_params += '&hst2=0'

```
the result is always an empty list, e.g.
```
[
['host', 'host_icons', 'host_check_age', 'host_state_age', 'host_attempt', 'host_state', 'host_plugin_output', 'host_in_downtime', 'host_acknowledged', 'host_address', 'host_in_downtime', 'host_acknowledged', 'sitename_plain', 'host_flapping', 'host_is_active', 'host_notifications_enabled'],

]
```

I think they changed the options to a positive filter with checkboxes so we should add
`&hst0=On&hst1=On`
instead of
`&hst2=0`

Not quite sure if this works with < 1.5.x.

Best regards
Torsten

**Comment by HenriWahl** [comment]
Does it work meanwhile with one of the latest testing versions?

**Comment by vielhak** [comment]
It's working correctly with the current 3.3-20191114. Thanks!
