### ISSUE TITLE
Feature Request: Allow multiselect in alarm list

### ISSUE THREAD

**Issue by dmaphy** [HenriWahl/Nagstamon#511]
Sometimes I want to acknowledge or downtime multiple entries at the same time. For this, it would be nice if it was possible to multiselect entries in the alarm list by pressing Ctrl, Shift or the combination of both.

**Comment by HenriWahl** [comment]
Yes I more and more wish this feature would already exist... it's on the todo list already.

**Comment by dmaphy** [comment]
Looks like I'm able to multiselect alerts under certain circumstances. The behavior is a bit unpredictable, seems it depends on where I click and the moment when I click. Bearing in mind this is a testing version, this looks quite nice to me already.

**Comment by HenriWahl** [comment]
Which version exactly do you use? Which OS do you run it on?

**Comment by dmaphy** [comment]
Oh, sorry I forgot to mention these. :-)
I'm running Fedora 29 here with Python3. The Nagstamon Version I'm currently testing is 3.3-20190130.

**Comment by HenriWahl** [comment]
Me too. I have the impression that it works a little bit strange in this constellation - did not notice such flaky behaviour in macOS or Windows.

**Comment by HenriWahl** [comment]
Fixed in latest 3.3-20190208 version.

**Comment by dmaphy** [comment]
Looks good now, thank you! :-)
