### ISSUE TITLE
Nagstamon causes intermittent high latency on WiFi on Mac

### ISSUE THREAD

**Issue by anorowitzdstillery** [HenriWahl/Nagstamon#513]
We've observed that Nagstamon causes high latency about once every 10-20 seconds on WiFi on Mac OS X. We've observed this behavior under the following conditions:

- On both High Sierra and Mojave.
- On multiple MacBook Pro models, ranging from 2013 to 2015 and 13" to 15".
- On both Nagstamon 3.0.2 and 3.1-20180829
- On multiple WiFi networks in multiple locations.
- On Nagstamon with both multiple Icinga and Nagios instances, as well as a clean configuration with no instances ($HOME/.nagstamon moved out of the way).

We've found that stopping Nagstamon causes the problems to go away.

You can see here ping results to the default gateway, both with Nagstamon running and without it. I would consider these results to be representative.

[ping_gw_with_nagstamon.txt](https://github.com/HenriWahl/Nagstamon/files/2461913/ping_gw_with_nagstamon.txt)
[ping_gw_without_nagstamon.txt](https://github.com/HenriWahl/Nagstamon/files/2461914/ping_gw_without_nagstamon.txt)

I also ran a dtruss on Nagstamon with a clean configuration with no instances. The output is mostly quiet, but gets noisy during the latency increases. I've included the output I observed during one latency increase, which seems to be representative.

[dtruss_nagstamon.txt](https://github.com/HenriWahl/Nagstamon/files/2461911/dtruss_nagstamon.txt)

I suspect that Nagstamon is doing something that's causing the Mac to scan for WiFi networks. I've observed that the following behavior, both of which cause scans for WiFi networks, causes similar increases in latency:

- Clicking the WiFi icon on the menu bar.
- Opening [NetSpot](https://www.netspotapp.com/), which runs a WiFi scan every 10 seconds that causes similar latency increases.

This looks similar to this other [bug](https://github.com/HenriWahl/Nagstamon/issues/480) on Windows 10, but upgrading to Nagstamon 3.1 testing didn't fix the problem for us.

**Comment by anorowitzdstillery** [comment]
We experience the problem on WiFi only. With Ethernet connected, the problem goes away.

**Comment by HenriWahl** [comment]
Well... at least Nagstamon does not influence your network by intention. As far as I know none of the used components Python, Qt5 and various third party modules have anything to do with wifi latency.

I see the peaks in your examples but honestly do not even know where to start debugging.

Only idea might be to build Nagstamon completely freshly with latest binaries from Homebrew hoping they might behave differently.

**Comment by HenriWahl** [comment]
Please check with latest stable version as it contains newer Python an Qt. Get it at https://nagstamon.ifw-dresden.de/download/.

**Comment by anorowitzdstillery** [comment]
The new release seems to have fixed it. Thank you!
