### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [HenriWahl/Nagstamon#515]
i've downloaded Version '3.0.2' but when selecting it in the Finder and using 'Get Info' it doesn't show any Version-number at all. i guess the **CFBundleVersion** and **CFBundleShortVersionString** entries in your **Info.plist** file are missing.
all apps on macOS are supposed to contain valid version information.

**Comment by stearz** [comment]
This pr should address this issue: https://github.com/HenriWahl/Nagstamon/pull/680
