### ISSUE TITLE
nagstamon 0.9.11 (windows 64 bit) leaks memory

### ISSUE THREAD

**Issue by djandruczyk** [HenriWahl/Nagstamon#52]
When running for long periods (weeks), nagstamon progressively uses more and more RAM.  At the last check on my (work) desktop VM it was using over 365MB of memory (windows process listing).  It monitors only two nagios hosts, each with  about 600-1000 checks each.  Closing and reopening makes it reset to about 17.4 MB of memory usage.  The linux version DOES NOT exhibit this problem.

It seems to leak memory with each GUI operation.  i.e. if I right click and select "recheck ALL" memory usage will increase,  but never decrease.  The more I do it the more ram it eats.   It'll initially eat more then free up some, but never equitably (leaking something).

**Comment by HenriWahl** [comment]
Please check latest BETA from https://nagstamon.ifw-dresden.de/nagstamon-20/
