### ISSUE TITLE
Feature request: use lighter colors for acknowledged services

### ISSUE THREAD

**Issue by kroseneg** [HenriWahl/Nagstamon#526]
For a better overview over active/new problems it would be nice to have all acknowledged problems displayed in a lighter color. I hacked this for nagstamon 1 long time ago, I used (color+white)/2 for all colors (text and background), and I really miss this since I've upgraded to nagstamon 2+.

**Comment by HenriWahl** [comment]
Did you check https://nagstamon.ifw-dresden.de/wp-content/uploads/2016/08/features-statusbar-colors.png
