### ISSUE TITLE
Malwarebytes antimalware :O

### ISSUE THREAD

**Issue by danilo1984** [HenriWahl/Nagstamon#528]
![image](https://user-images.githubusercontent.com/8511757/50155433-5427f700-02cc-11e9-89c4-fb5c25b7eaac.png)

**Comment by HenriWahl** [comment]
However this result is achieved... maybe some other malware has been built with pyinstaller and so this malware checker finds some similarities?

**Comment by HenriWahl** [comment]
Apparently this mostly hits the 32 Bit version of Windows. :-(

I tried building with UPX which lead to non-executable binaries. 
Often one finds building new bootloaders for pyinstaller which is internally used for packaging but none of the supported compilers built a new bootloader for me, so I am kind of clueless what to do here. Only hope might be that there are more 64 bit users than 32 bit ones...

**Comment by HenriWahl** [comment]
Looks really bad: https://www.virustotal.com/#/file/52e6e28afea38fbe94f0f41945948e96a41a9db64e5890dcc3d58acd0ad49f36/detection

**Comment by BenoitPoulet** [comment]
Symantec Endpoint Proctection says the same.
He talks about "WS.Reputation.1" which means he thinks the executable is suspicous. 
File : Nagstamon-3.2-win64_setup.exe 

Easy to counter as we just need to ignore the warning or in my case, taking back the file from the Symantec vault.

**Comment by HenriWahl** [comment]
I Manager to compile the bootloaders of pyinstaller dir windows myself which lead to different file hashes. Can you check again from download page? All Windows packages are replaced.

**Comment by HenriWahl** [comment]
Still the 32bit Version ist flagged as bad by many:
https://www.virustotal.com/#/file/1b2e62c9e178753270eab637df96ed8a846610b7f7920b09cbfc10ffb6cd9e0a/detection

The 64bit Version seems rather OK:
https://www.virustotal.com/#/file/823e7a1f6271aac81efa14af8f8c2e8bf22f674fafc073a5ffc2a72925d0f110/detection

**Comment by BenoitPoulet** [comment]
Same for me with Symantec E. P., alway this @%+*% WS.Reputation.1

But Symantec E. P, flag nearly all the .exe from open source software i download, with this as it's based on a reputation score. 
Explained here : https://www.symantec.com/security-center/writeup/2010-051308-1854-99?vid=4294919973

**Comment by mygithubthrowaway** [comment]
@HenriWahl 
This is a very serious security issue.

Can you state about on nagstamon site?

Thanks

**Comment by HenriWahl** [comment]
Good hint - done with https://nagstamon.ifw-dresden.de/wrong-malware-detection/
