### ISSUE TITLE
multiple selection of event

### ISSUE THREAD

**Issue by Coolgeek789** [HenriWahl/Nagstamon#529]
Hi,

I would like to be able to do action on multiple event at once. (I don't want to ack 200 alert one by one because someone messed up).

I tried to hack around but can't manage to have a reliable multiple selection on the TreeView.
I changed line 3150 on QUI/\_\_init\_\_.py from "QAbstractItemView.NoSelection" to "QAbstractItemView.ExtendedSelection". 

The selection are messed up, sometimes it works, sometimes it seems my mouse click is not working.
Do you have some clue on why it's not already inside nagstamon and why this option has a weird behavior ?

OS : archlinux
python-pyqt5 : 5.11.3
python : 3.7.1

**Comment by HenriWahl** [comment]
I wish this feature would exist but never did a closer look on how to achieve this so I am not really able to say something here.

**Comment by Coolgeek789** [comment]
see PR 529

**Comment by Coolgeek789** [comment]
see #533
