### ISSUE TITLE
No Changelog Entry für 3.2.1 

### ISSUE THREAD

**Issue by tabacha** [HenriWahl/Nagstamon#532]
I have installed 3.2 and now the client tells me, that 3.2.1 is available. But there is no Changelog for 3.2.1

I have compared the git version 3.2 and 3.2.1 and see no changes also.

**Comment by HenriWahl** [comment]
Sorry, forgot to push to GitHub. Change was only a non-crash for macOS in case of green OK icon in systray - see https://github.com/HenriWahl/Nagstamon/issues/530.

Thanks for the hint.
