### ISSUE TITLE
Scroll bars are pixellated

### ISSUE THREAD

**Issue by orgitnized** [HenriWahl/Nagstamon#536]
Working on the app in Windowed mode on a mac - the scroll bars don't show up and the window on the right-side upon scrolling is pixellated.  I can provide a video if needed.  Latest version of macOS Mojave is being used.

**Comment by HenriWahl** [comment]
Hi - yes, a video or screenshot would be helpful.

**Comment by orgitnized** [comment]
Maybe torn would be a better word.  Here you go: https://d.pr/i/b13Cdz

**Comment by HenriWahl** [comment]
Look interesting... I will try with an older version of Qt.

**Comment by HenriWahl** [comment]
I compiled a new version with a newer Qt - please check https://nagstamon.ifw-dresden.de/files/incoming/Nagstamon%203.2.2.dmg

**Comment by orgitnized** [comment]
Doesn't fix it for me.  Then when I launch it, it states a newer version is available, yet it references an older version.  20190105 is what it advertises.

**Comment by HenriWahl** [comment]
The version number is fixed - this was a preview which is now available officially as unstable.
The torn-problem... I have no idea, looks ok at my machine:
![nagstamon_macos_window](https://user-images.githubusercontent.com/2835065/51379876-be70c900-1b10-11e9-94b9-7179ce4ac350.png)

**Comment by ortizleo** [comment]
Hello, @HenriWahl 
Can you test Nagstamon with Zabbix 4.0? Inst working for me...

**Comment by orgitnized** [comment]
It’s ok. Mine certainly is a minor issue. Was just curious if it was just me.

**Comment by HenriWahl** [comment]
Would be interesting if other Qt-based software has the same problem on your machine.
