### ISSUE TITLE
Mac os - Crash on saving nagios servers

### ISSUE THREAD

**Issue by morozsm** [HenriWahl/Nagstamon#539]
nagstamon 3.2.1 and 3.3 beta - both crashed after I try to add server to list.
Application restarts with another request to add server or ignore.

Application has been upgraded, by usual MAC OS way - .app file copied from image to Applications directory.
Any ideas what can be the issue?

There is stack:
`Traceback (most recent call last):
File "Nagstamon/Config.py", line 600, in SaveMultipleConfig
File "keyring/core.py", line 64, in set_password
File "keyring/backends/fail.py", line 23, in get_password
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.`

**Comment by morozsm** [comment]
nagstamon 3.2.1 and 3.3 beta - both crashed after I try to add server to list.
Application restarts with another request to add server or ignore.

Application has been upgraded, by usual MAC OS way - .app file copied from image to Applications directory.
Any ideas what can be the issue?

**Comment by morozsm** [comment]
Tried to install:

`pip install keyrings.alt`

Didn't help.

**Comment by morozsm** [comment]
1. Yes. "Use system keyring..." checkbox checked on first tab.
2. Latest stable MacOS 10.14.2 (18C54)

**Comment by morozsm** [comment]
My question is, does Nagstamon store it's data somewhere? May be makes sense to cleanup. Possibly incorrect upgrade or something...

**Comment by HenriWahl** [comment]
I tested with macOS 10.13 and found other bugs but not this one - might it be related to 10.14? What happens without storing password in system keyring?

**Comment by HenriWahl** [comment]
I found the latest keyring module being responsible for this problem - like it was on Windows. I compiled a new unstable version - can you please test https://nagstamon.ifw-dresden.de/files/unstable/Nagstamon%203.3-20190120.dmg?

**Comment by RickS-C137** [comment]
I installed this version. It's running as long as I don't check "Use system keyring for server credentials". When checked it crashes.
But I got another problem since the update. I configured my two servers, just like before and I get the error message "AttributeError: "NoneType' object has no attribute 'get'.

**Comment by HenriWahl** [comment]
When did you get the new unstable version? To make sure it is the freshly compiled one please use https://nagstamon.ifw-dresden.de/files/incoming/Nagstamon%203.3-20190120.dmg - has the same name but newer libraries inside.

Regarding the second problem - which monitoring server do you use?

**Comment by RickS-C137** [comment]
I installed the version you posted 5 days ago. 
I'm using Icinga2 with Icinga Web 2.

**Comment by HenriWahl** [comment]
Just to make sure - can you please download the https://nagstamon.ifw-dresden.de/files/incoming/Nagstamon%203.3-20190120.dmg again and try it?

**Comment by RickS-C137** [comment]
Ok, this one is working :) 
But there's one last thing. I'm using the dark mode of MacOS and in the settings the font color is white, just like the background color. With the 3.0.2 it's ok and dark font on white background.

**Comment by HenriWahl** [comment]
Me neither... :-)

But was the AttributeError-server in a somewhat special condition?

**Comment by morozsm** [comment]
>What happens without storing password in system keyring?
Works with no issues!

**Comment by HenriWahl** [comment]
Should work now both ways.

**Comment by HenriWahl** [comment]
Can you please test the latest 3.3-20190208 with dark mode? There is a newer Qt5 included which might help there.

**Comment by RickS-C137** [comment]
Sorry for the late reply.
Looks good now! It also seems that the configuration is not breaking anymore :)
