### ISSUE TITLE
False OK if Icingaweb2's backend isn't running

### ISSUE THREAD

**Issue by Wuestengecko** [HenriWahl/Nagstamon#540]
In Nagstamon I have a monitor of type "Icingaweb2", which is (obviously) backed by an Icinga2 instance. If the Icinga instance goes down, Icingaweb after logging in shows a red bar along the bottom that the backend isn't running. Nagstamon simply shows the last reported status for monitored hosts and services, without this notice, which is ideally "everything is OK". This falsely creates the impression that the network is correctly running and monitored, when in reality it is not monitored (and potentially not running correctly either).

Please make it so that, if the Icinga instance behind the configured Icingaweb goes down, the whole monitor is shown as down in Nagstamon. This currently is only the case if Nagstamon cannot connect to the Icingaweb host.

**Comment by Massl123** [comment]
I successfully tested this today.
