### ISSUE TITLE
Alertmanager

### ISSUE THREAD

**Issue by iat00** [HenriWahl/Nagstamon#542]
Hi Henri,
do you plan to support Alertmanager (Prometheus)?
That would be great!
Best regards,
Afsin

**Comment by schneifi** [comment]
+1

**Comment by HenriWahl** [comment]
I myself do not have the resources to do so but if someone would I would not mind to integrate a Prometheus plugin.

**Comment by varac** [comment]
See also #623

**Comment by stearz** [comment]
The feature is available in the current testing release "3.5-20200527", which can be downloaded here:
https://nagstamon.ifw-dresden.de/download/#testing

**Comment by AIXruth** [comment]
oh, did I miss something?

My understanding is that right now Nagstamon still uses the the Prometheus front end http://<myprometheus>:9090, but not a central Prometheus Alertmanger on http://<myprometheus-alertmalager>:9093. (Other or same server, but different port and structure)

In our environment we send all alerts from three sources (on-premise, test-cloud, prod-cloud) to one central Prometheus-Alertmanager. Only the Alertmanager is able to silence alerts. As far as I know, only the Alertmanager evaluate the "for: 5m". Thus on Nagstamon we see a lot of temporary alerts and also alerts, which have been silenced on the Alertmanager.

If I use http://<myprometheus-alertmalager>:9093 as Monitor URL, I will get the error: "TypeError: list indeices must be integers or slices, not str" (Tested with 3.5-20200708)

**Comment by varac** [comment]
In the above use case, alertmanager integration would be great for sure.

**Comment by varac** [comment]
@HenriWahl Could you please reopen this ticket ? Alertmanager integration is indeed pretty different to the prometheus one, and should even be prioritized because of the reasons @AIXruth pointed out above.

**Comment by stearz** [comment]
First version of alertmanager support is done:
https://github.com/HenriWahl/Nagstamon/pull/679
Currently just read-only visualization of alerts but I'm trying to support acknowledgements etc. before christmas

**Comment by stearz** [comment]
Alertmanager integration now supports filtering of silenced alerts:
https://github.com/HenriWahl/Nagstamon/pull/686

Silencing directly from Nagstamon is not possible yet
