### ISSUE TITLE
Latest build does not show custom actions for Nagios checks that are showing as down

### ISSUE THREAD

**Issue by chaoscreater** [HenriWahl/Nagstamon#547]
If there's a host that is shown as down in Nagios, Nagstamon does not show any custom actions in the context menu. If you click on any other service or hosts, the custom actions will show up fine.

![image](https://user-images.githubusercontent.com/18227319/52988914-0f544400-3466-11e9-8bae-9c69ebc8fb68.png)

**Comment by HenriWahl** [comment]
Yes, I can confirm this and it is... a bug. Will check this soon.

**Comment by HenriWahl** [comment]
Please check latest available testing binaries.
