### ISSUE TITLE
No notification sounds with Zabbix

### ISSUE THREAD

**Issue by evs38** [HenriWahl/Nagstamon#549]
There is no options in Nagstamon to set cutrom notification sounds and notification actions for Zabbix-related alarms:

INFORMATION
AVERAGE
HIGH
DISASTER
UNKNOWN

So when these types alarms are happens, there is no any notification sounds.

**Comment by chatarGit** [comment]
Hi,
Same here. did you find a solution ?
Thanks

**Comment by HenriWahl** [comment]
What about release 3.4rc2?

**Comment by HenriWahl** [comment]
Well, nothing new here so closing for now.
