### ISSUE TITLE
Nagstamon crashes when selecting Downtime action on a Down HOST

### ISSUE THREAD

**Issue by cesaryelapaul** [HenriWahl/Nagstamon#558]
Nagstamon version: 3.3-20190309 (Windows 64-bits)
Nagios version: 4.0.8

I know version 3.3-20190309 is not stable, but is a great idea to select multiple lines for actions.
When I select a Down Host, and try to schedule a Downtime, the program crashes (version Windows 64 bits)

**Comment by HenriWahl** [comment]
Thanks for the hint - will be checked.

**Comment by HenriWahl** [comment]
Please check latest binaries from https://nagstamon.ifw-dresden.de/files/incoming/.

**Comment by cesaryelapaul** [comment]
Hi.
I tested, and the issue was solved for my env.
Great!!!
Thanks
