### ISSUE TITLE
How im can put auto comment ?

### ISSUE THREAD

**Issue by almirf** [HenriWahl/Nagstamon#564]
Dear Members

How im can configure auto comment in nagstmon 3.2.1 ?

This expression bellow not works :(
$MONITOR$/view.py?_transid=$TRANSID$&_do_actions=yes&_do_confirm=Yes!&output_format=python&view_name=service&host=$HOST$&_ack_comment=$COMMENT-ACK$&_acknowledge=Acknowledge&service=$SERVICE$

Help me, see image
https://i.postimg.cc/WzTkKb0X/nag-com.jpg

Att
Almir

**Comment by HenriWahl** [comment]
There is already a comment action.
