### ISSUE TITLE
please support client certificates

### ISSUE THREAD

**Issue by jandd** [HenriWahl/Nagstamon#57]
it would be nice if nagstamon would support client certificates as an alternative or in addition to username/password to authenticate agains a monitoring server.

**Comment by GuillaumeRousseau** [comment]
I need this feature too, anything new about it ? Thanks!

**Comment by HenriWahl** [comment]
The now used Requests modules supports server certificate verification and use of client certificates, but the private key of a client certificate has to be unencrypted: http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification
I am not sure if this will get it into the upcoming 2.0 release, but later this is an option.

**Comment by falck0** [comment]
hello, is there an update on this topic? We'd like to add our icingaweb2 server, which is only reachable with a specific client certificate.
Thanks!

**Comment by frankenstein91** [comment]
This function would also be a big advantage for me. Our monitoring server is only accessible via SSH and HTTPs with client certificate. I would not like to maintain each user again in the operating system. Unfortunately I cannot find the place in the source code where I would have to add the certificates. Of course, a path in the config would be nicer, but I would also be able to store a fixed path for my colleagues in the manual (a client pem in the certifi folder?).

**Comment by HenriWahl** [comment]
I assume you look for https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/Servers/Generic.py#L218 and the following - at least there the HTTP-connection is set up.

**Comment by frankenstein91** [comment]
No, I didn't suspect it there. I had searched in the product specific Python files.

**Comment by HenriWahl** [comment]
The request modules does not support client certificates.

**Comment by jandd** [comment]
What about https://docs.python-requests.org/en/master/user/advanced/#client-side-certificates ?

**Comment by HenriWahl** [comment]
The big message there:



Warning

The private key to your local certificate must be unencrypted. Currently, Requests does not support using encrypted keys.

This doesn't sound that great.
