### ISSUE TITLE
Icon disappear from tray when screen is locked and unlocked

### ISSUE THREAD

**Issue by ndias** [HenriWahl/Nagstamon#571]
I'm using gnome-shell-3.32.1-1.fc30.x86_64 (Fedora 30) with the extension topicons to show the legacy icons in the top panel.

Since I upgraded to Fedora 30 from Fedora 29, the icon disappear from the tray everytime I lock the screen and then I unlock, nagstamon is running doesn't die with the lock, I suspect this is a problem in nagstamon and not in the extension, because the other icons are still visible after I unlock the screen.

**Comment by HenriWahl** [comment]
As the thing that changed is the desktop environment I do not suspect Nagstamon to be the cause. Is the extension which provides the tray icon area updated too? Maybe contact the developer and inform about this bug? 

Aonther idea: what about the fresh flatpak version of Nagstamon? Maybe comes with newer Qt and thus maybe behaves better?

**Comment by ndias** [comment]
The reason I open the bug here was that the other icons in the tray don't disappear, and the extension has stopped the development, and suggest to switch to  libappindicator and its extension, I tested and with libappindicator extension I can't see also the icon (never, not only after the lock), there are any possible to support libappindicator?

Thanks

**Comment by HenriWahl** [comment]
Maybe there is another extension?

**Comment by HenriWahl** [comment]
In my setup this problem solved itself with a newer version of a trayicon GNOME extension. What about yours?

**Comment by ndias** [comment]
Yes, this can be closed, thanks
