### ISSUE TITLE
Crash when Non-standard HTTPS port is set

### ISSUE THREAD

**Issue by alfmannew** [HenriWahl/Nagstamon#572]
Hello,

monitor url = https://zabbix:4443

3.0.2 is ok
3.2.1 is crashing

**Comment by HenriWahl** [comment]
@vsalvador any idea?

**Comment by HenriWahl** [comment]
@alfmannew can you try with latest testing version 3.3-20191015?

**Comment by alfmannew** [comment]
It crash.

Problem signature:
  Problem Event Name:	BEX64
  Application Name:	Nagstamon.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5da570e4
  Fault Module Name:	Qt5Core.dll
  Fault Module Version:	5.13.1.0
  Fault Module Timestamp:	5d6a32dd
  Exception Offset:	0000000000022d18
  Exception Code:	c0000409
  Exception Data:	0000000000000007
  OS Version:	6.3.9600.2.0.0.256.4
  Locale ID:	1033
  Additional Information 1:	4556
  Additional Information 2:	4556dedf7036596a97d19f873d6cf593
  Additional Information 3:	81dd
  Additional Information 4:	81dd8f7a7706371d59213464226ed47a


Problem signature:
  Problem Event Name:	BEX
  Application Name:	Nagstamon.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5da57028
  Fault Module Name:	Qt5Core.dll
  Fault Module Version:	5.13.1.0
  Fault Module Timestamp:	5d6a32fb
  Exception Offset:	0001deb1
  Exception Code:	c0000409
  Exception Data:	00000007
  OS Version:	6.3.9600.2.0.0.256.4
  Locale ID:	1033
  Additional Information 1:	b89e
  Additional Information 2:	b89eb7b9210edf1df0eb60866beaf713
  Additional Information 3:	66a0
  Additional Information 4:	66a0aaae4682831abb95c108eb82c1bb

**Comment by HenriWahl** [comment]
Are you able to run it from pure Python source to get the real error?

**Comment by HenriWahl** [comment]
>  Problem Event Name: BEX64
googling BEX64 leads to Windows Update related crashes. Please check your system regarding this.
Do you know that the default port 443 works? Can you make sure that these crashes are really caused by Nagstamon?
