### ISSUE TITLE
Feature Request: Support Sensu Go

### ISSUE THREAD

**Issue by jspaleta** [HenriWahl/Nagstamon#575]
Hey!
so Sensu Go,  introduces a new api scheme and requires authentication. 

It would be great if you support Sensu Go.  I'm going to see if I can get a PR together based on your existing Sensu support as a talking point for further discussion.

**Comment by codenameck** [comment]
Hi @HenriWahl ,

Is anybody working on this feature at the moment? If not, I'm happy to work on it.

**Comment by HenriWahl** [comment]
Hi, 

no, nobody works on it, so your contribution will be welcome!

**Comment by codenameck** [comment]
Hi,

Great. Thank you. If you have any suggestion on setting up development environment, please let me know. Also, what is your preferred communication channel in case I have questions down the road?

**Comment by HenriWahl** [comment]
In theory your environment should be easily set up with the reqirements information at https://nagstamon.ifw-dresden.de/docs/requirements/.

Don't hesitate to mail me at h.wahl@ifw-dresden.de.
