### ISSUE TITLE
Feature request: Support for macOS Mojave dark mode

### ISSUE THREAD

**Issue by pgodschalk** [HenriWahl/Nagstamon#576]
Similar to #411, it'd be great if the systemwide dark mode setting for macOS Mojave was respected. This feature is available in Qt 5.12: https://bugreports.qt.io/browse/QTBUG-68891

**Comment by HenriWahl** [comment]
I built a version with Qt 5.12, available at https://nagstamon.ifw-dresden.de/files/incoming/Nagstamon%203.3-20190415.dmg.
Does it already use dark mode? If not, do you have any idea how to activate it?

**Comment by HenriWahl** [comment]
Now there is a version with Qt5 5.13.1 available at https://nagstamon.ifw-dresden.de/download/#testing which should work even better with newer macOS. In my environment Nagstamon is not getting dark but maybe it works for you?
