### ISSUE TITLE
Filter using host group for Nagios

### ISSUE THREAD

**Issue by pathade90** [HenriWahl/Nagstamon#577]
Is there a way we can set filter for host groups in Nagios instead of hostname.

**Comment by HenriWahl** [comment]
This is The Eternal Feature Request.

Sorry, not yet.

**Comment by sidharrell** [comment]
github won't let me create a 2nd pull request while I still have the first one open.
https://github.com/sidharrell/Nagstamon/commit/2bf5bc16c1b7dda9c253a3467006283de8bf46c0

I did add this in, for OP5.

**Comment by smefa** [comment]
@sidharrell Perhaps you should change the filter view text from "group" to "host group" since there is "contact groups" as well. I would love to see a contact group filter if it is an easy fix for you to add.

**Comment by sachaz** [comment]
up ?

**Comment by HenriWahl** [comment]
Well, nothing new here so will close now.
