### ISSUE TITLE
Problem with playing a .wav file

### ISSUE THREAD

**Issue by JamieVampire** [HenriWahl/Nagstamon#579]
I've tried about everything but unfortunately, I'm at the end of my wits with this one. :(

So, we use nagstamon (on Fedora 29, nagstamon version 3.3-20190415) to display two of our nagios installations on a big screen. The nagstamon and the nagios installations are all on different servers. The displaying of the notifications from both of the nagios installations works perfectly fine, just as it should.

First, I checked that in general sounds can be played - they can, no problem. Then I've added three .wav files, one for each currently supported state (warning, critical, down), made sure that they're correctly picked in "Settings" -> "Notifications" and under "Custom sounds". I've also checked that they're correctly listed in our nagstamon.conf - they are. 
Then I clicked on the play buttons in "Settings" -> "Notifications" under "Custom sounds" for each of the selected files - I found that the very first click doesn't give a sound (no matter which .wav file I choose), but all other clicks after that correctly play the custom sounds.

But when trying it with the changing states, the only sound was a very short second (maybe half a second or so) of one of the files I've used. When I tried the repeating sound option, I could hear that tiny short bit of the file over and over, but it didn't play the whole sound. 

Because of that and because the other files all start their sounds maybe two seconds into the actual record, I'd got the suspicion that maybe only the first second of a sound was played and that a longer record of a sound just wasn't what nagstamon was supposed to handle. 

That's when I copied the critical.wav, down.wav and warning.wav to my directory and thought - since they're so short - they might be played. Unfortunately, I still get absolutely no sound when states are changing, even though I've made sure that everything's in order. I've also changed the owner and group - no improvement. 

I really don't know what else to check. Do you maybe have any idea what might be the problem here?

**Comment by HenriWahl** [comment]
To be honest - I do not know. Do the default sounds work?

**Comment by JamieVampire** [comment]
No, unfortunately, the default sounds also don't work. :(

**Comment by HenriWahl** [comment]
May sound stupid, but how do you use Nagstamon? In systray or as floating statusbar?

**Comment by JamieVampire** [comment]
We actually use the fullscreen, as we're displaying nagstamon on a big TV in one of our programmers' rooms.

**Comment by HenriWahl** [comment]
Can you try the new flatpak version of Nagstamon 3.2.1? It comes bundled with its needed libraries or uses the flatpak Qt5 bundle, so we could find out if there is a problem with the Qt coming with Fedora.

**Comment by HenriWahl** [comment]
I test now with Fedora 30 and have the impression it does work *sometimes* - strange enough.

**Comment by JamieVampire** [comment]
Hey, I've unfortunately got a very busy day today but I'll test as soon as I have some free time tomorrow!

**Comment by HenriWahl** [comment]
I just let Nagstamon run with sound on my Fedora 30 installation and it honks and cries whenever there is something to claim about. Maybe some Qt-related update helped there. Can you try with a fully updated Fedora 30?

**Comment by HenriWahl** [comment]
Well... meanwhile stopped again to work.... :-1:  Same situation as before.

**Comment by JamieVampire** [comment]
Oh, phew, I was just about to update the system. Thanks for the heads-up! I'll wait with updating, then.

**Comment by HenriWahl** [comment]
An idea... maybe some other file format would be OK? Simply OGG for example...

**Comment by HenriWahl** [comment]
Guess there is nothing we could do here except hoping that it will get better in a future release of Qt or pulseaudio and the likes.
