### ISSUE TITLE
Filter doesent remove Information services with zabbix

### ISSUE THREAD

**Issue by tifennlegoff** [HenriWahl/Nagstamon#580]
Hi, we're using Nagstamon 3.3-20194015 on Windows x64 with Zabbix 4.0.9.
In Filters tab, we choosed to show only : 

- All down hosts
- All warning services
- All average services
- All critical services
- All high services 

When we modify settings to only show thats informations, we have "INFORMATIONS" status who arrived too.

![image](https://user-images.githubusercontent.com/25082085/59937952-0eebaa00-9454-11e9-80e5-b8c847a536bc.png)

![image](https://user-images.githubusercontent.com/25082085/59938249-c385cb80-9454-11e9-8ed3-8119d9d19905.png)

We can reproduce this issue with Nagstamon 3.3-20190415 on Linux Debian x64.

Can you fix that ?

Thanks a lot,
Tifenn

**Comment by mmarkgraf-tpgroup** [comment]
Hi there :-)

I have the same issue with version 3.9-20211208 : 

![image](https://user-images.githubusercontent.com/66019052/164226352-10640513-57c3-49f2-a6a1-ca2846c1798e.png)

I'm running Manjaro and installed nagstamon-git from the AUR:

![image](https://user-images.githubusercontent.com/66019052/164226815-cae02149-0b5d-4051-a034-d37e66006e76.png)

Zabbix on the Server is version 5.2

Where's a good place to start looking for the cause?

**Comment by mmarkgraf-tpgroup** [comment]
Okay, can't make sense out of this :-/

Why does it work properly when debug mode is on?

**Comment by HenriWahl** [comment]
@mmarkgraf-tpgroup strange at all - but could you try to runthe latest 3.9-20220419 version? Just to make sure.

**Comment by HenriWahl** [comment]
> Why does it work properly when debug mode is on?

At least I can confirm it works.

**Comment by HenriWahl** [comment]
I found the cause - some wrong indentation in the filter code. Please try latest release from https://github.com/HenriWahl/Nagstamon/releases/tag/latest - should work without debug now to. Was a good hint anyway :+1:!

**Comment by mmarkgraf-tpgroup** [comment]
Strangely enough `git checkout latest` leaves me with the non-working filter, but `git checkout master` works.

**Comment by HenriWahl** [comment]
`master` is latest. I referred to the binary releases.

**Comment by mmarkgraf-tpgroup** [comment]
Can't use the binary releases on Manjaro, I'm afraid.  I'll have to wait for manjaro-git to be updated by the AUR-Maintainer.
(Note to self: learn how to package...)

**Comment by mmarkgraf-tpgroup** [comment]
A colleague of mine successfully tested the release on both windows and ubuntu.  Issue can be closed, I guess?

**Comment by HenriWahl** [comment]
Yes.
