### ISSUE TITLE
Window moves to other display on each refresh

### ISSUE THREAD

**Issue by Programie** [HenriWahl/Nagstamon#581]
I'm using Nagstamon in mode "Icon in systray". Whenever I open the Nagstamon window from the tray, window moves to the other display on every refresh.

Example: If it's currently on first display, it switches to second one. If it's currently on second display, it switches to first one.

This seems to be similar to #63, but this issue has been resolved 5 years ago.

Other than in #63 this issue is not affected by the mouse location. Even if the mouse is on the second display, the window switches between the first and the second display.

Nagstamon version: 3.2.1
OS: Ubuntu 18.10
Desktop environment: KDE

**Comment by HenriWahl** [comment]
How about the latest testing release?

**Comment by Programie** [comment]
I just tested the version currently in the master branch, but it has the same issues.

**Comment by HenriWahl** [comment]
I need to find time to check with dualscreen Ubuntu. There are also issues like that in Mint. :-(

**Comment by Programie** [comment]
As Nagstamon is written in Python, I will try to fix it and open a PR.

**Comment by HenriWahl** [comment]
:+1:

**Comment by Programie** [comment]
I was able to trace down the issue to one single line:

The value for `self.icon_x` is toggled between the value returned by `QCursor.pos().x()` and `icon_x` (as the comment in the code above it already states, is always 0). This resulted in switching the X position of the window between 0 and my second screen (which has the systray and therefore also the cursor once the status window gets opened).

My fix is to only fallback to the value of `icon_x` if the value is not 0. I'm not sure whether that's the best fix. It works for me on Ubuntu 18.10 with KDE.

**Comment by HenriWahl** [comment]
Thanks - let's if there will be other complaints.
