### ISSUE TITLE
UI scaling issues on high-resolution displays and multi-monitor setup

### ISSUE THREAD

**Issue by fmonts** [HenriWahl/Nagstamon#585]
See the below image as an example.

If I open the settings, the window is so big that it's impossible to see it all, or to close it.
 
This is a secondary full hd monitor at 1x, while my main display is a 2736x1824, scaled 200%. The strange thing is that even if I go in second-screen only mode, so it's a standard 1920x1080 monitor, the result is the same, even if I close and reopen nagstamon.

![image](https://user-images.githubusercontent.com/8755314/61155657-1d306180-a4fa-11e9-913c-ba38c9c21956.png)

**Comment by HenriWahl** [comment]
Hi - looks horrible indeed.
Can you please try with the tesitng version of Nagstamon which is build with newer Qt5 and thus maybe is more compatible with high resolution?

**Comment by fmonts** [comment]
I installed the testing version and it worked (but only after restarting the computer)

Thank you!
