### ISSUE TITLE
Not working with CMK 1.6

### ISSUE THREAD

**Issue by Numblesix** [HenriWahl/Nagstamon#586]
Hi,

we upgraded to the recent version/beta of check_mk which is 1.6 but nagstamon is unable to connect to our cmk instance.

The only log output we get is failed to communicate :(

**Comment by HenriWahl** [comment]
Please tell me if the binaries in https://nagstamon.ifw-dresden.de/files/incoming/ do work now.
Thanks @UntrustedRoot

**Comment by UntrustedRoot** [comment]
I ran the 64 bit installed. It installed and connected without issue. Only issue is the new version notification asking me to downgrade :)

Thanks for including this pull.

**Comment by HenriWahl** [comment]
> I ran the 64 bit installed. It installed and connected without issue. Only issue is the new version notification asking me to downgrade :)

I KNEW I was missing something... thanks for the hint, fixed now.
