### ISSUE TITLE
Kerberos auth support breaks after 3.0.2

### ISSUE THREAD

**Issue by pbrunnen** [HenriWahl/Nagstamon#589]
I have noticed that upgrading to Nagstamon v3.2.1 and the latest test version of 3.3, Kerberos authentication no longer works and it get the 'Authentication Error' message.  I have attempted to delete and recreate the site configuration and Kerberos is selected for the authentication method.

Switching back to 3.0.2, the authentication works fine.   I'm on a Mac with macOS 10.14.6.

I'm able to do testing if needed.

Thank you.  -Cheers, Peter.

**Comment by HenriWahl** [comment]
Sounds bad. Even worse is that I can't test this feature. Apparently it works on other platforms - at least there was no report.
Kerberos support came with https://github.com/HenriWahl/Nagstamon/pull/339. @sim0nx - do you have any clue?

**Comment by HenriWahl** [comment]
I switched from requests-kerberos to requests-gssapi which is newer and maintained at all. Can you please test https://nagstamon.ifw-dresden.de/files/testing/Nagstamon%203.3-20191005.dmg if it fixes your problem?

**Comment by pbrunnen** [comment]
Hello.  I can confirm that the test build is working properly with kerberos tickets.  Thank you ever so much!

**Comment by pbrunnen** [comment]
Hello Mr. Wahl,
  I wanted to let you know that I updated from v3.5-20200113 to v3.5-20200728 on MacOS 10.14.6 and the Kerberos is not working.   Please let me know if there is anything I can do to help.

Thank you kindly, Peter.

**Comment by HenriWahl** [comment]
Please check lastest https://nagstamon.ifw-dresden.de/files/incoming/Nagstamon%203.5-20200731.dmg

**Comment by pbrunnen** [comment]
Hello Mr. Wahl,

> Please check lastest https://nagstamon.ifw-dresden.de/files/incoming/Nagstamon%203.5-20200731.dmg
Yes, the new build works.  Thank you!  👍 

With kind regards, Peter.
