### ISSUE TITLE
Feature request: Filtering which only affect status bar / tray icon

### ISSUE THREAD

**Issue by cstuder** [HenriWahl/Nagstamon#59]
When filtering out 'Acknowledged hosts & services', they disappear completely both from the status bar / tray icon indicator and the Nagstamon window.

I would love to have the option to just filter them out of the status bar / tray icon, but still show up in the list. (Just in case I acknowledge problems and then promptly forget about them.)

**Comment by HenriWahl** [comment]
Rather impossible because the used list is consistent over statusbar, systray and details.
