### ISSUE TITLE
QLayout "" to StatusWindow "", which already has a layout

### ISSUE THREAD

**Issue by mariusvw** [HenriWahl/Nagstamon#600]
Startup error:
```
$ /Applications/Nagstamon.app/Contents/MacOS/Nagstamon
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
```

Couldn't tell the impact, would be nice to see it fixed.

**Comment by mhetru** [comment]
Hello,
i got the same error with nagstamon installed from linux mint repository (3.0.2-1) or the last version .deb file (3.4.1):

> qt5ct: using qt5ct plugin
> qt5ct: D-Bus system tray: no
> QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout

Even i should create manualy a folder ".nagstamon" in my home folder because i got this error at the first launch:
> [Errno 2] No such file or directory: '/home/mhetru/.nagstamon/nagstamon.pid'

Have u an idea in order to fix the problem ?
Because with the version 3.0.2 i have no problems...

**Comment by HenriWahl** [comment]
Sorry but there is no coincidence between the harmless error message about QLayout and the folder and PID. Does it run at all?

**Comment by mhetru** [comment]
Unfortunatly, it does not work even on a recent fresh install Linux mint 19.3, even if i create the .nagstamon folder.

At this moment, i cannot use nagstamon :-(

**Comment by andydixon** [comment]
This is happening on Ubuntu 20.10:
$ nagstamon
[Errno 2] No such file or directory: '/home/andy/.nagstamon/nagstamon.pid'
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
Segmentation fault (core dumped)
$

It was previously working, and as a test I removed the .nagstamon location to effectively reset it so I could reconfigure it, but it just keeps segfaulting.

**Comment by varac** [comment]
Related to #681 and #676 ?

**Comment by shiblovich** [comment]
i have the same issue with ubuntu 20.04 any updates !?

**Comment by mhetru** [comment]
No I have not found any solution for this moment,
If you find, it can interested me,
Thanks !

**Comment by HenriWahl** [comment]
Please check https://flathub.org/apps/details/de.ifw_dresden.nagstamon - maybe not perfect solution but might be one at all.

**Comment by HenriWahl** [comment]
> i have the same issue with ubuntu 20.04 any updates !?

Please check @varac's solution: https://github.com/HenriWahl/Nagstamon/issues/681#issuecomment-814405068
