### ISSUE TITLE
Hosts Down after Upgrading Centreon to 19.10

### ISSUE THREAD

**Issue by spardhas** [HenriWahl/Nagstamon#601]
Hi,

I update my Centreon Server to 19.10 today and after that, Nagstamon give me some hosts as Down whereas this hosts only have some services in warning or critical status.

I use Nagstamon 3.2.1 in Windows 10.

**Comment by HenriWahl** [comment]
Please try latest testing version from https://nagstamon.ifw-dresden.de/download/#testing - quite possible that in the meantime it has been fixed there.

**Comment by HenriWahl** [comment]
@BenoitPoulet any idea?

**Comment by spardhas** [comment]
It's strange because sometimes they appear Down, then normal, then back Down again.

**Comment by BenoitPoulet** [comment]
Hello,

I did some check but i failed to reproduce this behavior (and i broke my 19.10 setup :| )

Can you activate the Nagstamon log and give us the output (be careful to anonymize it)

**Comment by spardhas** [comment]
[nagstamon.log](https://github.com/HenriWahl/Nagstamon/files/3742686/nagstamon.log)

Here, some logs.

**Comment by BenoitPoulet** [comment]
I tried on my 19.10 setup and on the Centreon demo website and i cannot find any pb.

@HenriWahl Perhaps my dev environment is not the same as your. I'm still under Python 3.6.2.
Which version i must use to be equal with you ?

**Comment by spardhas** [comment]
![Nagstamon down host](https://user-images.githubusercontent.com/1820067/67096048-9a353c00-f1b7-11e9-89e8-9621baad1abe.png)

Here, an exemple of a line in nagstamon wich is not in correct status.

**Comment by HenriWahl** [comment]
> @HenriWahl Perhaps my dev environment is not the same as your. I'm still under Python 3.6.2.
> Which version i must use to be equal with you ?

I develop now on 3.7.4.

**Comment by spardhas** [comment]
Centreon is in 19.10.1, not just in 19.10. Sorry for the confusion.

**Comment by BenoitPoulet** [comment]
I upgrade all my python dev env, Centreon as well in 19.10.1, cannot reproduce.

Are you sure that you host is not viewed as down my centreon as the same moment ? because the host's state is taken from directly from the XML in Centreon.

**Comment by BenoitPoulet** [comment]
Hello,

Another people who have upgraded to 19.10 has reported to have the same PB with Centreon.
It's seems to be a PB in Centreon,  as Nagstamon pull host's state from him.

**Comment by BenoitPoulet** [comment]
Confirmed, it was a bug in Centreon Engine.

@HenriWahl you can close this issue.

**Comment by HenriWahl** [comment]
👍
