### ISSUE TITLE
Fedora testing repo with download error

### ISSUE THREAD

**Issue by dmarkdvt** [HenriWahl/Nagstamon#604]
On Fedora 30 I am getting the following error when I do a `dnf update`.

`
...
nagstamon-testing                                                                                                                                                              1.5 kB/s |  33 kB     00:22    
Error: Failed to download metadata for repo 'nagstamon-testing': Yum repo downloading error: Downloading error(s): repodata/4ecd5fc0798fa45a7621f777bc4915591954cfe1ea873e78646b01abf510393e-filelists.xml.gz - Cannot download, all mirrors were already tried without success; repodata/08fc718a4497dd67e151d105c3b586ddb746304aa696281dcd8152f9d56b0fa3-primary.xml.gz - Cannot download, all mirrors were already tried without success
Ignoring repositories: nagstamon-testing
...
`

I just followed the instructions on https://nagstamon.ifw-dresden.de/download/ (#Testing):

`
wget https://nagstamon.ifw-dresden.de/repo/fedora/nagstamon-testing.repo --output-document=/etc/yum.repos.d/nagstamon-testing.repo
`

**Comment by HenriWahl** [comment]
Can you please try again? Quite probably your dnf hit a moment of updating the repo.

**Comment by dmarkdvt** [comment]
Same issue while updating the repo.

**Comment by HenriWahl** [comment]
Even after a `dnf clean all`?

**Comment by dmarkdvt** [comment]
Yes, does it work for you?

**Comment by HenriWahl** [comment]
Yes, on a fresh Fedora 30.

**Comment by dmarkdvt** [comment]
Local issue due to proxy restrictions. My bad. Have a nice day.

**Comment by HenriWahl** [comment]
:+1:
