### ISSUE TITLE
Crash when opening server settings and clicking "OK" without any changes

### ISSUE THREAD

**Issue by mbirth** [HenriWahl/Nagstamon#608]
Version: 3.3-20191114
OS: Windows 10 1903 64bit

### Steps to reproduce:

1. Open Settings
2. Select server
3. Click Edit server
4. Click OK
5. Click Edit server
6. Click OK

### Expected behaviour

Dialog closes and settings are saved. Just how it does after step 4.

### Actual behaviour

Nagstamon crashes. Debug log doesn't show anything about a crash.

**Comment by HenriWahl** [comment]
Sorry, I cannot reproduce.

**Comment by HenriWahl** [comment]
What monitor server type did you use?

**Comment by mbirth** [comment]
Check_MK. I'll try to run it from source tomorrow.

**Comment by mbirth** [comment]
This is what appears when the crash is triggered. After enabling Debug Mode, it sometimes took up to 4 tries (opening server settings, clicking "OK") until it crashed:

```
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QThread: Destroyed while thread is still running
```

Sadly, Python isn't giving any more details.

**Comment by HenriWahl** [comment]
Any change with 3.4rc2?

**Comment by mbirth** [comment]
Nope, still the same. :(

**Comment by HenriWahl** [comment]
Please check 3.5-20200105 from https://nagstamon.ifw-dresden.de/download/#testing

**Comment by mbirth** [comment]
Awesome, seems fixed. However, when clicking "OK" for the first time, the dialog closes instantly. When doing it a second (or third, fourth, etc.) time, there's a slight delay of ~1 second. That's probably where it hung/crashed before. But it's working fine now. Thank you!
