### ISSUE TITLE
Feature request: Filtering for different Nagioses

### ISSUE THREAD

**Issue by tumpech** [HenriWahl/Nagstamon#61]
Hi,

Here, we need to use Nagstamon for more than 6 Nagioses + some iCinga, and we need different filters for each one. Could you make the next version have a feature to make separate filters for each monitoring sites?

Regards,
tumpech.

**Comment by bjoernbessert** [comment]
That would help us as well. At the moment we work around that with multiple nagstamon instances and a dedicated config per instance.

**Comment by bachos** [comment]
I'd work on this feature.
@HenriWahl Would you mind giving me some guidance ?

**Comment by HenriWahl** [comment]
Of course - tell me what you need. :-)
Obviously this settings would be server related thus go into individual server settings. 
Filtering is done in GetStatus() in Generic.py - should be no big deal to switch to separate settings here.
I think of refining filtering in general, more into rule-based and not as raw as it is now - but if this ever happens this will be no big problem to combine server-based and rule-based filters.
