### ISSUE TITLE
Version 3.4RC1 loses server configuration on macOS Catalina

### ISSUE THREAD

**Issue by knaepp** [HenriWahl/Nagstamon#613]
To whom it may concern,
after updating from 3.3lastVersion to 3.4RC1 I recognized that nagstamon loses the server configuration information after each reboot.
This happend before a couple of times with older releases (eg 3.21 if I remember it correct).

Any ideas how to solve this?

Thanks in advance

Matthias

**Comment by HenriWahl** [comment]
Are there any unusual characters in the server instance name?
What is the content of ~/.nagstamon/servers?
Does it happen on a fresh installation (no ~/nagstamon folder existing) too?

**Comment by HenriWahl** [comment]
Please check https://nagstamon.ifw-dresden.de/files/incoming/Nagstamon%203.4.rc2.dmg.

**Comment by knaepp** [comment]
Hi Henri,
thank you for your answer. I checked to delete the .nagstamon folder (just by renaming it) and did a restart of the application.

It seems that it now works. After the last reboot the serverconfig was available again. I will check the second releasecandidate as well..

Many thanks!!!

Matthias

**Comment by HenriWahl** [comment]
Can you please test what will happen with the old .nagstamon folder being renamed back and the rc2 version?

**Comment by knaepp** [comment]
Hi Henri,
I checked this. RC2 works with the "old" configuration without the described issue.

Thanks a lot.

Matthias

**Comment by HenriWahl** [comment]
Great news! Thanks for reporting and I will close this issue now.
