### ISSUE TITLE
Authentication problem (check_mk-1.6.0p6)

### ISSUE THREAD

**Issue by baccenfutter** [HenriWahl/Nagstamon#614]
Installed latest `nagstamon-3.2.1` and tried to connect it to my `checkmk-raw-1.6.0p6`.

After mastering the fact that the `Monitor URL` requires a non-intuitive trailing `/check_mk/` folder, I get the error message "Authentication problem".

When I turn on debug logging, I can see:
```
[...]
DEBUG: 2019-12-13 08:40:06.178253 BIH Refreshing all hosts and services
DEBUG: 2019-12-13 08:40:06.781646 BIH FetchURL: http://172.16.120.159/bih/check_mk//login.py CGI Data: {'_login': '1', '_username': 'xxxxx', '_origtarget': '', 'filled_in': ' login', '_password': 'xxxxx'}
DEBUG: 2019-12-13 08:40:06.793877 BIH FetchURL: http://172.16.120.159/bih/check_mk/view.py?view_name=nagstamon_hosts&output_format=python&lang=&limit=hard&is_host_acknowledged=-1&is_service_acknowledged=-1&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1&host_scheduled_downtime_depth=-1&is_in_downtime=-1 CGI Data: None
```

Note, that it reports: `CGI Data: None`

When I paste the URL into my browser, I do in fact get the CGI data in the output.

**Comment by HenriWahl** [comment]
Please check with release candidate 3.4rc2 from https://nagstamon.ifw-dresden.de/download/#testing

**Comment by HenriWahl** [comment]
Any news?
