### ISSUE TITLE
Nagstamon not working after Windows 10 1909 (OS Build 18363.535) update

### ISSUE THREAD

**Issue by cfam22** [HenriWahl/Nagstamon#615]
Hello!

Nagstamon stopped working after Windows 1909 (OS Build 18363.535) update. It doesn't start and shows no error. I have tried latest stable, old stable and testing.

Confirmed working on previous 1903 (OS Build 18362.535).

**Comment by HenriWahl** [comment]
Did you try latest 3.4rc2 too?

**Comment by cfam22** [comment]
I have found the issue. Deleting C:\Users\[user]\.nagstamon folder solved the problem
