### ISSUE TITLE
scaled display results in very small fonts (Win10)

### ISSUE THREAD

**Issue by hknet** [HenriWahl/Nagstamon#618]
Hi
on Win10 with highres-displays it is quite common to have fonts and other elements scaled to 150 or even 200% to keep things readable.

nagstamon 3.4 does obviously not take this scaling into account and makes itself quite hard to read:
![image](https://user-images.githubusercontent.com/4014716/71759264-c4d78c80-2eaa-11ea-89c6-fedae5685c78.png)

**Comment by HenriWahl** [comment]
As a partly mitigation you can change don't size.

In theory the underlaying Qt should handle high res displays.

**Comment by hknet** [comment]
well, tried that :)
changed fontsize from 6 to 9 -> resulted after "ok" in a killed nagstamon process :)
restarted nagstamon and changed the fontsize again - this time it did not kill itself:

![image](https://user-images.githubusercontent.com/4014716/71764936-aa270700-2eee-11ea-91eb-804d2d8d69bf.png)

yet the result does change the fontsize only for the reported hosts and services, not for any other fonts, also this is only a very cumbersome workaround as usually multi-display-environments have different scalings on different displays and therefore this is not a real solution.
I don't know about the Qt but it obviously does not scale correctly :)

**Comment by HenriWahl** [comment]
I found some information about Qt + HiDPI and will try to implement this as soon as possible.

**Comment by HenriWahl** [comment]
Please check 3.5-20200105 from https://nagstamon.ifw-dresden.de/download/#testing

**Comment by hknet** [comment]
Hi, thank you for your quick response, I now tried 20200108 and the results are better, yet scaling probably will need to be done for any text-element:

![image](https://user-images.githubusercontent.com/4014716/72104489-d34ef980-332b-11ea-9c63-38f9b0182315.png)


on the other hand the funny effect when moving nagstamon from a HiDPI display to a "normal" DPI display it gets a bit confused there:
![image](https://user-images.githubusercontent.com/4014716/72104605-1610d180-332c-11ea-9340-9172b14e3cfc.png)
if I do a refresh after this display appears the windows gets a normal positioning as well as correct dimensions to see something :)

**Comment by HenriWahl** [comment]
Well, I guess this is Qt's part... I could not do more than activate HiDpi-awareness at all. :-(
