### ISSUE TITLE
nagstamon 3.4 on mac with icingaweb2: json.decoder.jsondecodeerror expecting value line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by simplexify** [HenriWahl/Nagstamon#619]
Nagstamon 3.4 on mac fetching data from icingaweb2 results in the following error:

json.decoder.jsondecodeerror expecting value line 1 column 1 (char 0)

Nagstamon 3.2.1 with identical configuration on the same computer does not result in this error.

**Comment by HenriWahl** [comment]
Is this error displayed in the pop-up window?

**Comment by simplexify** [comment]
Yes, see screenshot below:

![Screenshot 2020-01-05 at 18 14 29](https://user-images.githubusercontent.com/8797304/71783457-492f2a00-2fe7-11ea-9b9c-581c2764114f.png)

**Comment by HenriWahl** [comment]
Is the authentication correct? Is the system keystore used and is Nagstamon 3.4 allowed to access it for credentials?

**Comment by simplexify** [comment]
I don't find any entries for 'nagstamon' in keychain.

I tried unticking the 'save password' option and manually entering credentials when prompted: same result.

No other settings applied:

![Screenshot 2020-01-05 at 18 22 25](https://user-images.githubusercontent.com/8797304/71783540-5f89b580-2fe8-11ea-9a56-f92a5094e14d.png)

**Comment by HenriWahl** [comment]
Please enable debugging into a file on first tab of settings.

**Comment by simplexify** [comment]
Done. The file appears, but stays empty (file size 0 bytes), even after exiting and starting the application multiple times.

**Comment by simplexify** [comment]
Hmm, now it started being populated.

This is probably what you need:

```
DEBUG: 2020-01-05 21:10:27.076230 ITAF FetchURL: https://redacted.url.tld/authentication/login CGI Data: None
DEBUG: 2020-01-05 21:10:27.682490 ITAF FetchURL: https://redacted.url.tld/authentication/login CGI Data: {'redirect': '', 'formUID': 'form_login', 'CSRFToken': '***REDACTED***', 'btn_submit': 'Login', 'username': '***REDACTED***', 'password': '***************'}
DEBUG: 2020-01-05 21:10:28.172960 ITAF FetchURL: https://redacted.url.tld/monitoring/list/hosts?host_state>0&host_state<=2&host_state_type=1&addColumns=host_last_check&format=json CGI Data: None
DEBUG: 2020-01-05 21:10:28.283472 ITAF FetchURL: https://redacted.url.tld/monitoring/health/info?format=json CGI Data: None
ERROR: 2020-01-05 21:10:28.320981 ITAF Traceback (most recent call last):
  File "Nagstamon/Servers/IcingaWeb2.py", line 174, in _get_status
  File "json/__init__.py", line 348, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by simplexify** [comment]
Additional info:

that last URL https://redacted.url.tld/monitoring/health/info?format=json returns the following raw data when entering the URL in a browser:

```
<br />
<b>Fatal error</b>:  Call to undefined method Icinga\Module\Monitoring\Backend\Ido\Query\ProgramstatusQuery::getQuery() in <b>/usr/share/icingaweb2/modules/monitoring/library/Monitoring/Controller.php</b> on line <b>43</b><br />
```

**Comment by HenriWahl** [comment]
Hm... this is apparently no JSON and thus cannot be parsed by Nagstamon. Ergo the error message is correctly thrown.
The interesting question is: what is the difference between 3.2.1 and 3.4? Can you debug with 3.2.1 too to get the requested URL?

**Comment by HenriWahl** [comment]
Problems seem to start here: https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/Servers/IcingaWeb2.py#L170

Newly introduced monitoring health check seems to fail on your installation. What version of Icinga do you use?

**Comment by HenriWahl** [comment]
I added a check if health monitoring works at all - if not it will be simply disabled. Can you please test latest testing release from https://nagstamon.ifw-dresden.de/download/#testing ?

**Comment by simplexify** [comment]
the 3.5 testing version works a charm 👍 

The icingaweb instance I'm testing this against is 2.4.2, which indeed does not seem to have this monitoring health check output format feature on board.

Thanks for the fix
