### ISSUE TITLE
error after install Nagstamon-3.4-win64_setup.exe

### ISSUE THREAD

**Issue by Kornexl** [HenriWahl/Nagstamon#620]
json.decoder.JSONDecodeError: Expecting value: line1 column1 (char 0) 
when using nagstamon  with Icinga-Web2 Version 
![nagstamon](https://user-images.githubusercontent.com/5048009/71903099-a2bc6380-3163-11ea-80b5-5c444cf0e7b0.jpg)
   2.3.3

No problem with Version 3.2.1 of nagstamon

**Comment by HenriWahl** [comment]
Please check latest testing version which has a fix for this.

**Comment by Kornexl** [comment]
3.5-20200107 is OK
