### ISSUE TITLE
Feature Request: Nagstamon goes Prometheus

### ISSUE THREAD

**Issue by AIXruth** [HenriWahl/Nagstamon#623]
hi,

Nagstamon with Nagios/Icinga is a very helpful tool. In the new world of clouds many people use another cool monitoring tool called Prometheus. Alerts are sent to the Prometheus-Alertmanager. Grafana has a nice dashboard for these, but it is not the cool Nagstamon.

Would it be possible to write a Nagstamon integration/plugin for Prometheus alerts? 
Please! :)

**Comment by HenriWahl** [comment]
Nice idea. 

I will not be able to provide Prometheus integration but if someone of the community will find the time - pull requests are very welcome.

**Comment by stearz** [comment]
The feature is available in the current testing release "3.5-20200527", which can be downloded here:
https://nagstamon.ifw-dresden.de/download/#testing

**Comment by AIXruth** [comment]
Our first try said: KeyError: 'message'

**Comment by varac** [comment]
> Our first try said: KeyError: 'message'

I had the same, it happens when an alert doesn't contain any `message` key. I added a message to my custom alerts and the error was gone. However, nagstamon should handle a lacking `message` key gracefully.

**Comment by varac** [comment]
For me nagstamon is all green even when prometheus alerts are firing. i.e. using the bedug mode I see nagstamon fetching this alert:

```
DEBUG: 2020-06-07 20:00:49.805030 Prometheus varac Processing Alert: {'activeAt': '2020-06-07T12:55:10.959619345Z',
 'annotations': {'description': '84.200.69.80 of job blackbox-dns '
                                'has been down for more than 1 minutes.',
                 'message': 'Instance 84.200.69.80 down',
                 'summary': 'Instance 84.200.69.80 down'},
 'labels': {'alertname': 'service_down',
            'instance': '84.200.69.80',
            'job': 'blackbox-dns',
            'severity': 'page'},
 'state': 'firing',
 'value': '0e+00'}
```

But nagstamon doesn't show this alert. Should I create a seperate issue for this ?
Using nagstamon `3.5-20200527`

**Comment by stearz** [comment]
At the moment only severities warning and critical are supported. If you want me to support more just open a new issue as a feature request.

I wasn't aware that there could be empty or non existing message fields in alerts. That should be easy to fix. I will give it a try.

**Comment by varac** [comment]
Thanks ! Happy to test a new testing  deb package if there's any.

**Comment by varac** [comment]
So I have another issue: I have multiple prometheus alerts but Nagstamon only shows one, because it looks like the `Host` is always `unknown`. Looking at [Nagstamon/Servers/Prometheus.py](https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/Servers/Prometheus.py#L167) I see the hostname is only populated if there's a `pod_name` or `namespace` label set:

                if alert["labels"]["severity"] != "none":
                    if "pod_name" in alert["labels"]:
                        hostname = alert["labels"]["pod_name"]
                    elif "namespace" in alert["labels"]:
                        hostname = alert["labels"]["namespace"]
                    else:
                        hostname = "unknown"

All my alerts don't have these labels, they have an `instance` label .

It looks like it will be hard to do the mapping between prometheus api alert keys and Nagstamon fields right.
Looking at this kubernetes pod alert:

```
      {
        "labels": {
          "alertname": "service_down",
          "app": "promtail",
          "controller_revision_hash": "58597dbb8c",
          "instance": "10.42.0.149:80",
          "job": "kubernetes-pods",
          "kubernetes_namespace": "oas",
          "kubernetes_pod_name": "loki-stack-promtail-9sz6k",
          "pod_template_generation": "2",
          "release": "loki-stack",
          "severity": "critical"
        },
        "annotations": {
          "description": "10.42.0.149:80 of job kubernetes-pods has been down for more than 1 minutes.",
          "message": "Instance 10.42.0.149:80 down",
          "summary": "Instance 10.42.0.149:80 down"
        },
        "state": "firing",
        "activeAt": "2020-06-07T22:01:10.959619345Z",
        "value": "0e+00"
      },
```
it would be best imo to map `kubernetes_pod_name` to the `Host` and `job` to `Service`.
Maybe this mapping should be configurable in the server config dialog, as it depends largely on the prometheus setup ?
I.e. one could provide a list of comma seperated values to a `Host mapping` dialog filed with prometheus label which should ge mapped. I.e.: `kubernetes_pod_name,instance,job`. And the firs label present would get mapped ?

**Comment by varac** [comment]
@stearz I saw in !625 that you linked a prometheus server with demo alerts (http://demo.robustperception.io:9090) - do you maintain it ?
I can't connect Nagstamon to it because it fails with `KeyError: severity`, and in fact the demo alerts are lacking the `severity` label.

**Comment by stearz** [comment]
No, I don't maintain it.

**Comment by stearz** [comment]
@varac good idea. I had the idea as well but wasn't sure if it was worth the effort. I put it on my todo list

**Comment by foosinn** [comment]
I guess is somewhat would make sense to do also an Alertmanager integration, since Prometheus itself does not recognize things like acknowledgements.

What do you think @stearz

**Comment by stearz** [comment]
@foosinn It is already on my todo list. My first goal was to have insights into Prometheus alerts and to stabilize the integration. When that is done, I will start working on integrating Alertmanager for managing downtimes etc.

**Comment by stearz** [comment]
I just merged my backend changes for configurable mappings (hostname, servicename and status_information) into this PR: https://github.com/HenriWahl/Nagstamon/pull/646

**Comment by AIXruth** [comment]
Currently with version Nagstamon-3.5-20200610 I only see one of 16 alerts. After about a minute the alert is changing to another alert. Furthermore the field "Host" is always set to "unknown".

**Comment by stearz** [comment]
@AIXruth I guess that the hostname and servicename are interpreted the same for your 16 alerts. Can you please send the output of your alerts API endpoint, so I can check if that is the case. Just visit: https://your-prometheus-hostname/api/v1/alerts and send the output.

I also did some changes with the PR https://github.com/HenriWahl/Nagstamon/pull/646 so it may also be that your issue is gone in Nagstamon-3.5-20200611 as soon as the PR is merged and the new version is available.

**Comment by HenriWahl** [comment]
Please check latest binaries from https://nagstamon.ifw-dresden.de/files/incoming/

**Comment by stearz** [comment]
@varac I just opened PR https://github.com/HenriWahl/Nagstamon/pull/647 which brings the proposed behaviour. (Configure the field mappings for hostname, servicename and status_information).
It should be testable in Nagstamon-3.5-20200612 as soon as it is built.

**Comment by AIXruth** [comment]
wow, I am excited, this looks good. :) 
I am using Nagstamon-3.5-20200612.

Certainly I had to add all 3 Prometheus-Servers/Instances and cannot see severities with very custom values (false_error & info), but that's all fine. In our stage environment I have no "instance" label in one alert, so the host=default, which is also fine for me. We will fix that by an adjusted config.

Well, yes, having all alerts from our central alertmanager would be a dream, but at the moment I am very thankful for your implementation. 

Thank you all!

**Comment by varac** [comment]
What's the scope of this issue ? As nagstamon got prometheus integration now (and it works!), shouldn't we close it in favor of smaller scoped follow-up issues ? I.e. I'd like to acknowledge prometheus/alertmanager alerts via nagstamon.

**Comment by AIXruth** [comment]
In my point of view this is the wrong approach. Nagstamon must connect to the central alertmanager and not to each prometheus instance. The prometheus instance handles events, but the alertmanager the valid alerts. The prometheus instance also shows nonrelevant pending alerts. The alertmanager already has a silence function, which is also used by other applications like karma.

**Comment by stearz** [comment]
I agree. I am going to start implementation of alertmanager integration this weekend. Hopefully we will have this feature done before christmas.

**Comment by stearz** [comment]
The first version is done. It just supports read access to alert manager, the ability to silence alerts is coming next.
https://github.com/HenriWahl/Nagstamon/pull/679

**Comment by stearz** [comment]
Alertmanager integration now supports filtering of silenced alerts:
https://github.com/HenriWahl/Nagstamon/pull/686

Silencing directly from Nagstamon is not possible yet
