### ISSUE TITLE
Website and github releases differ?

### ISSUE THREAD

**Issue by devicenull** [HenriWahl/Nagstamon#624]
Why are the files different on your website versus github?

```
ae627fe5361f790f512a8e80ed1644c2  Nagstamon-3.4.1-win32.zip-github
6e4d1c228267b45fd90ecf0e0a3ddabf  Nagstamon-3.4.1-win32.zip-website
```

**Comment by HenriWahl** [comment]
You are right. I built new Windows setup binaries because the former where falsely detected as malware.
I updated the Github releases too.
