### ISSUE TITLE
Actions: Hostname by monitor not working

### ISSUE THREAD

**Issue by darkofbm** [HenriWahl/Nagstamon#626]
Hi,

After switching to 3.4.1 from 3.2.1 i have issue whit actions(SSH, Telnet etc). Option "Connection method: Hostname provided by monitor" doesn't work any more. It cuts off domain of host leaving only first part. Other two method work but they are lot slower.

**Comment by darkofbm** [comment]
I switched $ADDRESS$ to $HOST$ and it is working like before. It was working whit $ADDRESS$ before.

**Comment by HenriWahl** [comment]
Strange anyway - what kind of monitor server do you use?

**Comment by darkofbm** [comment]
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.5-1)

**Comment by darkofbm** [comment]
Also this is String that i use now that works:
"C:\Program Files\PuTTY\putty.exe" -load FBM  $HOST$

And monitoring type is configured as IcingaWeb2

**Comment by remiGauth** [comment]
oh i test this syntax and results are same and always bad

but directly thru this cmd line dos it's works fine
"C:\Program Files\PuTTY\putty.exe" -load "my profile_name_in_putty" -l "ssh_user" "real Ip address" works 

translate into action ssh nagtamon
"C:\Program Files\PuTTY\putty.exe" -load "my profile_name_in_putty" -l "ssh_user" "$ADDRESS$" 
or
"C:\Program Files\PuTTY\putty.exe" -load "my profile_name_in_putty" -l "ssh_user" "$HOST$" 

product putty 2 time => error popup window with only "centreon host field" bad address

so it's seem $ADDRESS$ and $HOST$ return same information. But aren't same in centreon field address and host

i hope ;-)
