### ISSUE TITLE
Feature Request: Adjustable display time for Tooltip hover window

### ISSUE THREAD

**Issue by elementu** [HenriWahl/Nagstamon#629]
Would it be possible to add the ability for the user to adjust/set the time in seconds that the tooltip window displays after hovering on an alert line in Nagstamon?  

We often put HTML links in our plugin output/status information - it would be really helpful if we could hover over an alert to bring up the tooltip window, and move the mouse to click on a link in the tooltip window.  At the moment the window disappears as soon as the mouse moves away from the alert line.   

![Nagstamon_tooltip_window](https://user-images.githubusercontent.com/61150952/74719017-28373700-522b-11ea-8396-cee0866326f7.png)

**Comment by HenriWahl** [comment]
This is behavior controlled by the used Qt framework. As far as I know there is no timeout to be set.

**Comment by HenriWahl** [comment]
Still no way to control timeout.
