### ISSUE TITLE
Detection of Password Changes

### ISSUE THREAD

**Issue by Phillip85** [HenriWahl/Nagstamon#631]
Hi,

looks like there is no detection of password changes in nagstamon,
We have an Icinga Server with active directory authentication.
When i change my AD password, the nagstamon app stops checking for errors and warnings.
It just run as always but does not show anything.

There is no warning that the password does not work too.

OS: MacOS 10.15.3
Nagstamon Version: 3.4.1

**Comment by glipscomb** [comment]
We have this issue as well. We have account lockout after X number of failed logins, so nagstamon locks us out of everything very quickly.  Can it fail after Y attempts at login.

**Comment by HenriWahl** [comment]
@glipscomb what monitoring server do you use?

**Comment by HenriWahl** [comment]
@Phillip85 do you use Icinga 1.x or Icinga 2.x?

**Comment by Phillip85** [comment]
@HenriWahl  its Icinga 1.x

**Comment by glipscomb** [comment]
HI Henri,

Nagios Core 4.4.5

Regards
Gary


Gary Lipscomb
Technical Officer, Systems(Infrastructure) | Infrastructure & Client Services | Division of Information Technology
Charles Sturt University
Panorama Avenue
Bathurst NSW 2795
Tel: +61 2 6338 6533
Email: glipscomb@csu.edu.au<mailto:glipscomb@csu.edu.au> |www.csu.edu.au<http://www.csu.edu.au/>

**Comment by HenriWahl** [comment]
Can you please check the version for your favorite OS from https://nagstamon.ifw-dresden.de/files/incoming/ ?

**Comment by glipscomb** [comment]
Hi Henri,


I’ve checked the version Nagstamon-3.5-20200731-win64_setup.exe<https://nagstamon.ifw-dresden.de/files/incoming/Nagstamon-3.5-20200731-win64_setup.exe> against Nagios Core 4.4.5 and openLDAP.

It now stops on first password failure, doesn’t keep on retrying so the account doesn’t get locked out.

Excellent



Regards



Gary
