### ISSUE TITLE
Requested feature: Pagerduty, AWS Cloudwatch, Solarwind Orion

### ISSUE THREAD

**Issue by edperry** [HenriWahl/Nagstamon#632]
I know wish lists should be on the person requesting it and I will start looking into how to do this with Nagstamon.   Though since I never did any development on Nagstamon. I just wanted to put a seed in peoples mind

We are already doing it with nagios but it would be nice if it interfaced with 
* Pagerduty
* AWS Cloudwatch
* Solarwind Orion

Anyway if anyone has any suggestions on getting started, or has any spare time to look at any of the above that would be great!

**Comment by HenriWahl** [comment]
Apparently not so I will close this issue for now.
