### ISSUE TITLE
Tray indicator icon H-U-G-E

### ISSUE THREAD

**Issue by ihatemicrosoft-was-already-taken** [HenriWahl/Nagstamon#633]
Hi everyone!

I'm running Ubuntu 19.10 Budgie on a HiDPI screen. When I chose Nagstamon 3.4.1 to be displayed in the system tray, the icon is really HUGE, the edge length being 4-5 times that of the other tray icons. My panel will also be displayed 5 times as high as normal.

Everything else (in terms of HiDPI etc) looks pretty normal.

Cheers

**Comment by HenriWahl** [comment]
Too bad I cannot test this - maybe use floating statusbar instead?
