### ISSUE TITLE
ERROR  Nagstamon  line 587 get_status

### ISSUE THREAD

**Issue by borgihalim90** [HenriWahl/Nagstamon#634]
ERROR: 2020-04-06 09:50:20.429848 PROD Traceback (most recent call last):
  File "Nagstamon\Servers\Generic.py", line 587, in _get_status
IndexError: list index out of range

Version of nagstamon : 
2.*
3.*

**Comment by HenriWahl** [comment]
What OS? What server type?

**Comment by HenriWahl** [comment]
Closed due to missing debug information.
