### ISSUE TITLE
Possible bug in ver 3.4.1 - Have to double click to pop-up

### ISSUE THREAD

**Issue by greatidea1** [HenriWahl/Nagstamon#639]
I'm using Windows 10 pro, build 18363 and have used previous versions of Nagstamon, absolutely love it. Kudos to your work

Upgraded to new stable version 3.4.1, gradually found that single click to popup on statusbar no longer works as usual.
I was thinking it is an issue with my touchpad clicking but later realized that single-right click opens a context menu, but single left click doesn't pop-up the full window. I checked the setting again then found that I had to click twice to open the window.

![image](https://user-images.githubusercontent.com/43351597/81634154-42d21400-9406-11ea-875a-1fea5d30dff4.png)

**Comment by HenriWahl** [comment]
@greatidea1 I tested on a Windows 10 Pro 1909 (18363.997), stable 3.4.1 as well as latest testing and both open nicely at the first left mouse click.
I fear this is a - admittedly strange - local problem. Maybe try with latest testing?
