### ISSUE TITLE
UnicodeEncodeError on password

### ISSUE THREAD

**Issue by SQLozano** [HenriWahl/Nagstamon#641]
After updating the password, nagstamon is no longer able to connect to the server, returning instead the following error:
UnicodeEncodeError: 'latin-1' codec can't encode character '\u20ac' in position 7: ordinal not in range(256)

OS: Windows 10
Nagstamon: 3.4.1

**Comment by HenriWahl** [comment]
What monitoring server do you connect to? Does the webserver in front of it speak Unicode UTF8?

**Comment by HenriWahl** [comment]
Another idea: can you please try the latest testing release from https://nagstamon.ifw-dresden.de/download/#testing ?

**Comment by SQLozano** [comment]
We have 2 different nagios servers, both speaking Unicode UTF8, and throwing the same error message.
The testing release throws the same error message too.

**Comment by HenriWahl** [comment]
Since Python 3 all strings are unicode so I am not sure where to look at. Are you able to run Nagstamon from source in a console window so the full error message could be seen?

**Comment by HenriWahl** [comment]
Still the same? Or did you meanwhile change the password? :smiley:

**Comment by HenriWahl** [comment]
Closing due to no response- might be fixed meanwhile by newer version.
