### ISSUE TITLE
Feature request for Prometheus monitoring (severity & annotations deviations)

### ISSUE THREAD

**Issue by AIXruth** [HenriWahl/Nagstamon#644]
The new Prometheus integration is great. Unfortunately at the moment it relies on hard coded configuration patterns like "message" and "severity = warning|critical".

For example we are using an alert.yml like this
```
- alert: SSL_expired
    expr: (probe_ssl_earliest_cert_expiry - time() )/ 3600 / 24 <= 1
    for: 1m
    labels: 
      severity: high
annotations:
      description: 'Certificate of {{ $labels.instance }} will expired {{ $value | printf "%.1f" }} days'
      fix: 'Update Certificate of {{ $labels.instance }} NOW'
      URL: 'https://www.google.com/search?q=ssl_expire'
      summary: 'foobar'
      info: 'do the needful'
```
as severity we are using: warning|high|critical|info|...  (certainly diverse deviations could also be common)
as most important "annotations" we are using the "description" parameter (while others might use summary or anything else)

Please make these parameters flexible/configurable in the configuration panel.

Many thanks for your fast implementation of Prometheus into Nagstamon!

**Comment by AIXruth** [comment]
With Nagstamon-3.5-20200612 most of our severities are working. "Info" and a few very custom ones do not match, but this is fine for me at the moment.

The same relates to the annotations, where we additionally use
annotations.fix (as replacement for summary)
annotations.url (to add a link with additional documentation about this alert and possible solutions)

**Comment by HenriWahl** [comment]
Available at https://nagstamon.ifw-dresden.de/files/incoming/

**Comment by AIXruth** [comment]
From my perspective this issue may be closed.
