### ISSUE TITLE
[Feature request] "use expire time" on icinga acknowledge option

### ISSUE THREAD

**Issue by kiranos** [HenriWahl/Nagstamon#651]
We use icinga heavily and also using Nagstamon, but we lack the option to set "use expire time" when we acknowledge an alarm.

this is our default behaviour on the official dashboard. 

- use expire time: "date when ack will be removed so its not forgotten"
- and uncheck sticky acknowledgement

Thanks!

**Comment by Massl123** [comment]
Are you using Icinga 1?
This feature has already been implemented for Icinga 2 and can be enabled while acknowledging.
