### ISSUE TITLE
Centreon login Error

### ISSUE THREAD

**Issue by nykroy** [HenriWahl/Nagstamon#652]
Hi i need monitorize Centreon with nagstamon (Good Job HenriWahl). I add this config: 
![imagen](https://user-images.githubusercontent.com/7745881/86462447-ed422580-bd2b-11ea-8a66-0d4618b282a7.png)
I have this result:
![imagen](https://user-images.githubusercontent.com/7745881/86462561-12369880-bd2c-11ea-8748-c832f16daf1a.png)
And the debug file show that: 

```
DEBUG: 2020-07-03 12:47:09.287543 Monitor FPS Session renewed
DEBUG: 2020-07-03 12:47:09.287947 Monitor FPS FetchURL: https://xxxxxx/boreal/include/monitoring/status/Hosts/xml/hostXML.php?num=0&limit=9999&o=hpb&sort_type=status&sid=ERROR CGI Data: None
DEBUG: 2020-07-03 12:47:09.371679 Monitor FPS Bad session ID, retrieving new one...
DEBUG: 2020-07-03 12:47:09.371801 Monitor FPS FetchURL: https://xxxxxx/boreal/index.php CGI Data: None
DEBUG: 2020-07-03 12:47:09.675157 Monitor FPS FetchURL: https://xxxxxx/boreal/index.php CGI Data: {'useralias': 'xxxxx', 'password': '***************', 'submit': 'Login'}
DEBUG: 2020-07-03 12:47:10.066212 Monitor FPS Password login : xxxxx : xxxxx
DEBUG: 2020-07-03 12:47:10.066350 Monitor FPS SID : fr5fu17ogqg3j4f4cr77aul9c7
ERROR: 2020-07-03 12:47:10.066983 Monitor FPS Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Centreon.py", line 264, in _get_sid
    self.Debug(server=self.get_name(), debug='Centreon Token : ' + self.centreon_token)
TypeError: must be str, not NoneType
```

**Comment by BenoitPoulet** [comment]
Hello,

Which Nagstamon version ?
Which Centreon vertion ?

Did you customize you Centreon installation in any way ?

**Comment by nykroy** [comment]
Nagstamon 3.4.1  The error only happens on linux (ubuntu) but on windows with the same version works perfectly
Centreon 2.5.4 Whiout Customizations

**Comment by HenriWahl** [comment]
Does it work with newer stable or testing releases?

**Comment by nykroy** [comment]
The Last stavle version

**Comment by HenriWahl** [comment]
Does it work with latest testing version?
