### ISSUE TITLE
3 character application name brakes acknowledger filter

### ISSUE THREAD

**Issue by rafaelrs** [HenriWahl/Nagstamon#654]
I've found problem with that fix. 

I have filter acknowledged problems in Nagstamon, so if i acknowledge problem it disappears from alerts.

But if such problems haves service name (application name in terms of Zabbix) with 3 characters, it's no longer filtered anymore and stays in alerts in Nagstamon and tray icon is non green.

I did debug of Nagstamon python code and found that 3 charater service name caused that behaviour and found that code the fix reason of that. 

I renamed my service name and wrong behaviour fixed.

_Originally posted by @rafaelrs in https://github.com/HenriWahl/Nagstamon/pull/502#issuecomment-656377374_

**Comment by HenriWahl** [comment]
Can you please supply information where you found the cause of that behaviour?

**Comment by rafaelrs** [comment]
It's better to explain in screenshots.

Here how it's now, tray icon of nagstamon is green, no alerts:
![image](https://user-images.githubusercontent.com/2240041/89133140-5632de00-d522-11ea-8ba7-ad6e5e927fa5.png)

Now, let's rename on that zabbix host "Application name" from "Video Recording" to "DVR". We get following:
![image](https://user-images.githubusercontent.com/2240041/89133255-27693780-d523-11ea-803d-64f88daa08e3.png)
And tray icon show alerts in spite of they are acknowledged:
![image](https://user-images.githubusercontent.com/2240041/89133361-e3c2fd80-d523-11ea-9678-0b9189cb02e8.png)

**Comment by rafaelrs** [comment]
As you can see, service.visible will be set to true, and later this will lead to enter in that if:
![image](https://user-images.githubusercontent.com/2240041/89133494-ea05a980-d524-11ea-9b9f-f6ca11b5732d.png)
....
![image](https://user-images.githubusercontent.com/2240041/89133504-03a6f100-d525-11ea-9ddf-b3b2f8bc9d52.png)

Normally, if "Application name" longer that 3 chars, service.visible is false.

**Comment by HenriWahl** [comment]
Sorry for the late answer, but the len(service.attempt) does not have to do with a service name, right?

**Comment by dizixagi** [comment]
I can confirm that setting App Name to something that is 3 or less letters breaks acknowledge filter. Nagstamon implementation of Zabbix puts in Attempt field name of Application of first item in trigger that is fired up.

![image](https://user-images.githubusercontent.com/39417483/107148116-d020a580-6951-11eb-9fb5-faa62e6a1e0d.png)
![image](https://user-images.githubusercontent.com/39417483/107148127-e464a280-6951-11eb-8aff-326edd7a96fb.png)

Filter disabled:
![image](https://user-images.githubusercontent.com/39417483/107148046-5ee0f280-6951-11eb-99fe-c997df7fc973.png)

Filder enabled:
![image](https://user-images.githubusercontent.com/39417483/107148059-6b654b00-6951-11eb-8285-629bf7f7d925.png)
