### ISSUE TITLE
Filter "Services on hosts in maintenance" doesn't work with Thruk (2.30-2)

### ISSUE THREAD

**Issue by cesaryelapaul** [HenriWahl/Nagstamon#658]
Hi.

I'm working with 3.4.1 version of Nagstamon
When a host is in a Downtime period  the filter "Services on hosts in maintenance" doesn't work for Thruk (version 2.30-2). The services with problems on this host, appear in the console.

It works ok with the Nagios Core (4.0.8)  directly.

Thank you for your great work.

**Comment by HenriWahl** [comment]
Are the services down for maintenance too?

**Comment by cesaryelapaul** [comment]
No, just the host is down for maintenance.

**Comment by HenriWahl** [comment]
So you might as well activate "Services on down hosts" filter?

**Comment by cesaryelapaul** [comment]
I'm sorry. The problem is the filter "Services on hosts in maintenance".
So the the title of the issue is wrong.

**Comment by cesaryelapaul** [comment]
Sorry for the correction of the issue. This is the correct descripcion of the problem:
When a host is in a Downtime period the filter "Services on hosts in maintenance" doesn't work for Thruk (version 2.30-2). The services with problems on this host, appear in the console.

**Comment by cesaryelapaul** [comment]
Reading de code, I think that, for Nagios Server, the detection of "host in maintenance" for a service, is made by the "downtime icon" presence.
But, in the case of Thruk, the response is obtained in a json view, so, there is no icons,  and the cgi-url doesn't include the column host_scheduled_downtime_depth. 
May be, including and evaluating this property could be a solution.
This is just a suggestion.

**Comment by cesaryelapaul** [comment]
Refesh: Now I'm working with Nagstamon 3.6.0, and this issue continues (with Thruk version 2.30-2).
When a host is "downtimed", and de Filter :"Services in hosts in mainenance" is checked, the services appears in Nagstamon.

**Comment by sni** [comment]
from looking at https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/Servers/Thruk.py#L92-L104 it fetches hosts and services separately.
I guess the reason why it fails, is the `hoststatustypes=12` filter which fetches only problem hosts. So if the host itself is up but in a scheduled downtime, it will not be fetched and the downtime information is not available for services.
I prepared a PR which improves the filtering, so nagstamon will fetch now all problem hosts along with all hosts which have either a scheduled downtime, are acknowledged, have notifications disabled or are in a soft state.

**Comment by cesaryelapaul** [comment]
I installed the new 3.8.0 version and the problem is not solved for Thruk.
When a Host is in a downtime period, the filter "Services on hosts in maintenance" doesn't work.
With Nagios Server it works fine.

**Comment by HenriWahl** [comment]
@sni any idea?

**Comment by sni** [comment]
Which Thruk version is that?
