### ISSUE TITLE
possible [FR]: hide disabled monitoring server in menus

### ISSUE THREAD

**Issue by Reiner030** [HenriWahl/Nagstamon#659]
I recognized today using NagStamon 3.4.1 that my in configuration disabled server is still shown in "Goto Montor..." menu and system menu between Refresh/Settings so a klick onto these entries tries to go to the disabled (and in my case destroyed) monitoring server.

Is this an intended behavior or can/should these entries be hidden?

**Comment by HenriWahl** [comment]
Finally... fixed with latest commit https://github.com/HenriWahl/Nagstamon/commit/fa521fc865b1c38414cd40e804d7ac0156eeb3cc

Sorry for the delay.
