### ISSUE TITLE
3.4.1: Systray + Hovering doesn't work

### ISSUE THREAD

**Issue by z1atk0** [HenriWahl/Nagstamon#663]
In 3.4.1 (which actually reports itself as 3.5-20200113 for some strange reason), setting "Appearance: Icon in systray" together with "Statusbar details popup: Popup when hovering over statusbar" doesn't work. It just doesn't, the popup won't appear no matter how long I leave the mouse pointer there. "Popup when clicking" _does_ work together with "Systray icon", as does "Floating statusbar" together with "Popup when hovering". It's _only_ the combo which I _want_ that does _not_ work. :man_shrugging: 

I only recently upgraded from `0.9.9` (yes, ancient, I know) directly to `3.4.1`, so unfortunately I have no idea where exactly it broke on the way from there over `1.x`, `2.x` and `3.[123]` to `3.4.1`.

My systray is provided by `gnome-panel-2.32.1` (yes, that's GNOME 2, as in "two" :wink:), Qt is `Qt5-1.15.1`, PyQt is `PyQt5-5.15.1`, all self-compiled on `Slackware-14.2 i686` (yes, that's i686, as in "32bit" :wink:). If you need more information just let me know.

**Comment by HenriWahl** [comment]
Where did you get the package from? The version looks pretty strange.

**Comment by z1atk0** [comment]
I just checked again - looks like what I have download as "3.4.1" back in January is actually a GIT snapshot which unpacks to a directory called "HenriWahl-Nagstamon-e8bc52e" (I have _no_ idea where I got that one from, sorry :innocent:). Still, the actual code is identical, except for the version string and the Debian changelog:
```
[zlatko@disclosure:~/usrlocal/src]$ diff -pruN Nagstamon-3.4.1 HenriWahl-Nagstamon-e8bc52e       
diff -pruN Nagstamon-3.4.1/Nagstamon/Config.py HenriWahl-Nagstamon-e8bc52e/Nagstamon/Config.py
--- Nagstamon-3.4.1/Nagstamon/Config.py	2020-01-24 16:12:12.000000000 +0100
+++ HenriWahl-Nagstamon-e8bc52e/Nagstamon/Config.py	2020-01-24 16:19:42.000000000 +0100
@@ -123,7 +123,7 @@ class AppInfo(object):
         contains app information previously located in GUI.py
     """
     NAME = 'Nagstamon'
-    VERSION = '3.4.1'
+    VERSION = '3.5-20200113'
     WEBSITE = 'https://nagstamon.ifw-dresden.de'
     COPYRIGHT = '©2008-2020 Henri Wahl et al.'
     COMMENTS = 'Nagios status monitor for your desktop'
diff -pruN Nagstamon-3.4.1/build/debian/changelog HenriWahl-Nagstamon-e8bc52e/build/debian/changelog
--- Nagstamon-3.4.1/build/debian/changelog	2020-01-24 16:12:12.000000000 +0100
+++ HenriWahl-Nagstamon-e8bc52e/build/debian/changelog	2020-01-24 16:19:42.000000000 +0100
@@ -1,3 +1,15 @@
+nagstamon (3.5-20200113) unstable; urgency=low
+  * New upstream
+   - Centreon fix for acknowledgement when using autologin key
+   - IcingaWeb2 fix support older setups
+   - fix popup in systray mode on Windows
+   - improved mode switching
+   - better support for high resolution displays
+   - build support for Python 3.8
+   - improved Windows installer
+
+ -- Henri Wahl <h.wahl@ifw-dresden.de> Wed, 8 Jan 2020 10:00:00 +0100
+
 nagstamon (3.4.1) stable; urgency=low
   * New upstream
    - Centreon fix for acknowledgement when using autologin key
[zlatko@disclosure:~/usrlocal/src]$ 
```
I could of course reinstall from [the offical source tarball](https://nagstamon.ifw-dresden.de/download/#stable_source) and see if that changes anything, but given the `.diff` above I'd be _very_ surprise if it did. :scream_cat: 

Or are you saying that "there is not much we can do here" because I used your own officially released source code instead of a distro package? :thinking: That would seem a bit strange to me, although I'd have no choice but to accept it, of course. :man_shrugging:

**Comment by HenriWahl** [comment]
No, I meant I have no experience with Slackware and especially the mixture of software used. Maybe Qt has trouble with GNOME2?

**Comment by z1atk0** [comment]
Ah, I see. Phew, that was close! :sweat_smile: But, just for kicks, I meanwhile also installed Nagstamon-3.4.1 from the offical FC32 rpm (directly from the website) on my workstation at the office, and it has _exactly_ the same problem there. This is true FC32 GNOME3, _but_ (there's always a "but", isn't there?) running the `gnome3-flashback` session, not plain vanilla GNOME3. Still, it uses the official `gnome3-panel` system tray as provided upstream by GNOME3 and packaged by Fedora, so this shouldn't be an issue.
```
thomas@wasser:~$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 32 (Thirty Two)
Release:	32
Codename:	ThirtyTwo
thomas@wasser:~$ sudo -i
[root@wasser:~]# yum install https://nagstamon.ifw-dresden.de/files/stable/nagstamon-3.4.1.fedora32-1.noarch.rpm
Last metadata expiration check: 2:26:13 ago on Do 24 Sep 2020 09:30:10.
nagstamon-3.4.1.fedora32-1.noarch.rpm                                                                                                                                           1.2 MB/s | 666 kB     00:00    
Dependencies resolved.
[...]
thomas@wasser:~$ rpm -qa | grep -iE "nags|qt5" | sort
nagstamon-3.4.1.fedora32-1.noarch
python-qt5-rpm-macros-5.14.2-3.fc32.noarch
python3-pyqt5-sip-4.19.21-1.fc32.x86_64
python3-qt5-5.14.2-3.fc32.x86_64
python3-qt5-base-5.14.2-3.fc32.x86_64
qt5-qtbase-5.14.2-5.fc32.x86_64
qt5-qtbase-common-5.14.2-5.fc32.noarch
qt5-qtbase-gui-5.14.2-5.fc32.x86_64
qt5-qtconnectivity-5.14.2-1.fc32.x86_64
qt5-qtdeclarative-5.14.2-1.fc32.x86_64
qt5-qtgraphicaleffects-5.14.2-1.fc32.x86_64
qt5-qtlocation-5.14.2-2.fc32.x86_64
qt5-qtmultimedia-5.14.2-1.fc32.x86_64
qt5-qtquickcontrols-5.14.2-1.fc32.x86_64
qt5-qtsensors-5.14.2-1.fc32.x86_64
qt5-qtserialport-5.14.2-1.fc32.x86_64
qt5-qtsvg-5.14.2-1.fc32.x86_64
qt5-qttools-common-5.14.2-1.fc32.noarch
qt5-qttools-libs-designer-5.14.2-1.fc32.x86_64
qt5-qttools-libs-help-5.14.2-1.fc32.x86_64
qt5-qtwayland-5.14.2-4.fc32.x86_64
qt5-qtwebchannel-5.14.2-1.fc32.x86_64
qt5-qtwebengine-5.14.2-2.fc32.x86_64
qt5-qtwebkit-5.212.0-0.46.alpha4.fc32.x86_64
qt5-qtwebsockets-5.14.2-1.fc32.x86_64
qt5-qtx11extras-5.14.2-1.fc32.x86_64
qt5-qtxmlpatterns-5.14.2-1.fc32.x86_64
qt5-srpm-macros-5.14.2-3.fc32.noarch
qtkeychain-qt5-0.9.1-4.fc32.x86_64
qtlockedfile-qt5-2.4-31.20150629git5a07df5.fc32.x86_64
qtsingleapplication-qt5-2.6.1-38.fc32.x86_64
```
So this _might_ be a Qt5 thing, but it's happening on both GNOME2 & GNOME3.

**Comment by HenriWahl** [comment]
Yes, looks like.

But the combo systray + statusbar hover cant't work at all, because there is no hover event for systray icons.

This really was possible with GNOME2 and < 2.0 versions of Nagstamon. Since 2.0 it is Qt based due to the better cross platform support, but the drawback is the less free handling of systray icons.

Coming from 0.9 to 3.4.1 this might look strange, but this new and less nice behaviour is there a while yet.

**Comment by z1atk0** [comment]
> [...] there is no hover event for systray icons.

Oh, okay, so there's nothing I can do about it then. Well, that's that. :man_shrugging: In that case I guess I'll either stick to Systray + Click or Floating + Hover ... let's see what feels & works better in the long run. Thanks for your time & a cool piece of software! :+1: :sunglasses:
