### ISSUE TITLE
3.4.1 + Systray icon: details popup misplaced & much too big (dual monitor setup)

### ISSUE THREAD

**Issue by z1atk0** [HenriWahl/Nagstamon#664]
When using "Appearance: Icon in systray", the details popup is misplaced and much too big. The placement _would_ be okay if monitor # 1 (left) would also be the primary display, but that's not the case. My primary display (which holds the menus, panels & taskbars, including the system tray) is monitor # 2, which is on the right. But even then, the popup is much too big vertically. It goes from the very top to the very bottom, even if it only has a few lines to display. The rest of the area is empty and grey.

When using "Appearance: Floating statusbar", the popup appears exactly as expected: located directly above the statusbar itself, and only occupying as much screen space as it actually needs.

This happens both on Slackware 14.2 with GNOME2, Qt5-5.15.1 & PyQt5-5.15.1 (self compiled & installed from source tarballs), and on FC 32 using the official Fedora & Nagstamon RPMs.

Screenshots are attached. If you need more information just let me know. :wink: 

UPDATE: while I was doing the screenshots, I noticed that (in "Systray icon" mode) when you leave the popup open until the next update interval is reached, the popup places itself on the correct horizontal position (ie. same position relative to the monitor, but on the _correct_ monitor), _and_ the empty grey part disappears. Only the vertical placement is still wrong.

Screenshot # 1 shows the popup directly after clicking the systray icon.
![Screenshot1-Systray-AfterClick](https://user-images.githubusercontent.com/12568948/94139656-48d30980-fe6a-11ea-8066-388a8a085b69.png)
Screenshot # 2 shows the very same popup after the first refresh interval, automagically repositioned & resized.
![Screenshot2-Systray-After60sRefresh](https://user-images.githubusercontent.com/12568948/94139666-4cff2700-fe6a-11ea-91b0-3a375e858ac1.png)

Screenshot # 3 shows the floating statusbar at the bottom right of monitor # 2, which is the primary display.
![Screenshot3-FloatingMon2Pri-BottomRight](https://user-images.githubusercontent.com/12568948/94139684-54becb80-fe6a-11ea-8f21-b171ad305647.png)
Screenshot # 4 shows the popup after clicking the statusbar from # 3, positioned & sized exactly as expected.
![Screenshot4-FloatingMon2Pri-BottomRight-AfterClick](https://user-images.githubusercontent.com/12568948/94139703-58eae900-fe6a-11ea-9c95-cc863e2c5157.png)

Screenshot # 5 shows the floating statusbar in the middle of monitor # 1, which is _not_ the primary display.
![Screenshot5-FloatingMon1NonPri-Middle](https://user-images.githubusercontent.com/12568948/94139712-5ee0ca00-fe6a-11ea-9407-83a457c65c2c.png)
Screenshot # 6 shows the popup after clicking the statusbar from # 5, positioned & sized exactly as expected.
![Screenshot6-FloatingMon1NonPri-Middle-AfterClick](https://user-images.githubusercontent.com/12568948/94139718-61dbba80-fe6a-11ea-9121-2405bc75a41d.png)

**Comment by HenriWahl** [comment]
I fear there is not much I can do as once again problems occur in rather esoteric circumstances... the (really nice) freedom of choice on Linux desktop environments in this case can't be fully supported as there are way too much combinations - I am sorry.

Even if Nagstamon started on GNOME2 twelve years ago I am not surprised it doesn't work on this rather ancient platforrm correctly anymore.

Thanks for the information but if not somebody else would fix it I can't and thus sorrily close this issue.
