### ISSUE TITLE
Centreon 2.5.4 - Nagstamon 3.4.1 - Mutiple sessions opened

### ISSUE THREAD

**Issue by mastepmania** [HenriWahl/Nagstamon#666]
Hello,

We are facing an issue for a long time and still have no clues how to resolve it.

Some people are using nagstamon for watching Centreon's alert and therefor a few of them are increasing the number of opened sessions really fast (up to 300+ sessions). For a single user, sessions are staying in opened state and a new session stack after an update interval.

A normal user will have usually 1/4 sessions up , but some of them more (still can't explain why); I can show you the results of a count on sessions at a peak:

![session](https://user-images.githubusercontent.com/71868444/94236727-0105be00-ff0e-11ea-8ba6-20c03fdb4277.png)

The issue is that the GUI on Centreon starts lagging with so many sessions openned and we have to kick them manually at a point...

Does someone already had this issue ? Or an idea (not involving an upgrade of Centreon) to help ?

Thanks a lot,
Pierre M.
(RE-UP for the case number !)

**Comment by BenoitPoulet** [comment]
Hello,

Centreon 2.5.4 is very very old, i don't have anything to test on this. 

This issue was fixed a long time ago but tested only with more recent version.

Sorry but, you must try to find someone in you neighborhood with Python skills to fix this.

**Comment by HenriWahl** [comment]
Only fix seems to be an update of Centreon - closing now.
