### ISSUE TITLE
GPL-2-only file from checkmk

### ISSUE THREAD

**Issue by bgermann** [HenriWahl/Nagstamon#667]
Nagstamon/Servers/Multisite.py stems from the checkmk project and is licensed under GPL-2-only.
Nagstamon's use of pyqt5 might make it a derivative work of pyqt5, which is GPL-3 licensed and thus incompatible with GPL-2-only. Please address this by checking with @tribe29 if it would be okay to relicense that file to GPL-2-or-later like the rest of the code.

**Comment by HenriWahl** [comment]
@tribe29 in case this is a real problem - would you relicense Nagstamon/Servers/Multisite.py to GPL 2 and "any later version" as desrcibed on https://opensource.org/licenses/gpl-2.0.php ?
