### ISSUE TITLE
Acknoledge prometheus alerts

### ISSUE THREAD

**Issue by varac** [HenriWahl/Nagstamon#668]
Nagstamon got prometheus integration now and it works great (see #623).
The missing piece is to acknowledge ("silence") prometheus alerts via nagstamon.

**Comment by stearz** [comment]
Acknowledgement of alerts will only be available in the alertmanager integration. I hope to deliver the feature before christmas

**Comment by stearz** [comment]
Alertmanager integration now supports filtering of silenced alerts:
https://github.com/HenriWahl/Nagstamon/pull/686

Silencing from Nagstamon is not possible yet
