### ISSUE TITLE
Expresión regular para la duración en Nagstamon

### ISSUE THREAD

**Issue by serweb** [HenriWahl/Nagstamon#673]
Hola, me podrías explicar como usar las expresiones regulares en la duración de una alerta? he buscado por la web, pero no logro encontrar ni siquiera un solo ejemplo como para comprender el uso y comenzar a aplicarlo.
O sea, en la parte de filtro, expresión regular para la duración, por ejemplo, quisiera poner que solo me muestre las alertas de eventos que duren mas de 30m
Muchas gracias.
![image](https://user-images.githubusercontent.com/3794769/96961734-abf0a400-14db-11eb-9997-d8d16f35b510.png)

**Comment by HenriWahl** [comment]
Simplemente como todos los otros filtros - expresiones regulares. Depende de tu servidor monitor y como la duración está presentada.

**Comment by serweb** [comment]
Ok muchas gracias
