### ISSUE TITLE
Icinga API?

### ISSUE THREAD

**Issue by ser** [HenriWahl/Nagstamon#674]
Any plans to support Icinga API? 

Would you accept PR for that?

**Comment by HenriWahl** [comment]
Nagstamon already supports Icinga and Icinga2. What do you mean exactly?

**Comment by ser** [comment]
https://icinga.com/docs/icinga2/latest/doc/12-icinga2-api/

**Comment by HenriWahl** [comment]
Ah OK.

Yes, of course a PR is very welcome. :-)

**Comment by sircompo** [comment]
Any possibility to add support for client certificate authentication?
I can have a look at the code for that, but it'll probably be a steep learning curve for me so was hoping someone else might add this feature.

If not, it looks like this particular issue can be closed as the API seems to now be supported and working (which it great - thanks Serge!).

**Comment by HenriWahl** [comment]
The used request library does not support client certificates with passwords - if at all - so I would just close this issue.
