### ISSUE TITLE
Nagstamon 3.4.1 dont start on Ubuntu 20.10

### ISSUE THREAD

**Issue by Huaba** [HenriWahl/Nagstamon#676]
Hi, i've updated to Ubuntu 20.10 with Gnome 3.38.1. Now Nagstamon wouldn't start.  Here is the log:

```
Oct 27 16:49:07 huabas-xps nagstamon.desktop[138238]: QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
Oct 27 16:49:07 huabas-xps nagstamon.desktop[138238]: message repeated 2 times: [ QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout]
Oct 27 16:49:07 huabas-xps gnome-shell[93891]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x6400008 specified for 0x6400006.
Oct 27 16:49:07 huabas-xps kernel: [30681.042221] nagstamon[138238]: segfault at 0 ip 00007f26dd536bc5 sp 00007ffeab895590 error 4 in iHD_drv_video.so[7f26dd41d000+348000]
Oct 27 16:49:07 huabas-xps kernel: [30681.042235] Code: 01 48 83 f8 42 75 e6 31 db 66 41 89 9f 58 0c 00 00 49 8b 5f 28 8b 83 f0 1d 00 00 85 c0 0f 84 ba 01 00 00 48 8b b3 e8 1d 00 00 <81> 3e 00 00 01 00 48 89 75 c8 0f 85 a3 01 00 00 44 8d 70 f0 4d 63
Oct 27 16:49:07 huabas-xps systemd[6754]: app-gnome-nagstamon-138238.scope: Succeeded.
Oct 27 16:49:08 huabas-xps org.gnome.Nautilus[133844]: RuntimeError: object at 0x7f5def2c53c0 of type FolderColorMenu is not initialized
```
Thanks

**Comment by HenriWahl** [comment]
Can you test with the flatpak version 3.4.1?

**Comment by HenriWahl** [comment]
Another question: are you using Wayland or Xorg?

**Comment by HenriWahl** [comment]
I run Nagstamon on Ubuntu 20.10 in Ubuntu Gnome environment without any visible trouble... inside a KVM VM via Boxen. What is your environment?

**Comment by Huaba** [comment]
Hi,
sorry for the late reaction. Today i've removed nagstamon completely. Afterwards i've done a new install and it starts and i was able to configure Nagstamon. And it works without any errors. Cool :+1: 

For your information, if anyone will have the same problem: i've updated Ubuntu from 20.04 to 20.10, Nagstam is installed over the .dep package from the original Ubuntu sources. Using Gnome with Xorg.

Kudos for your work and patience!

**Comment by HenriWahl** [comment]
> For your information, if anyone will have the same problem: i've updated Ubuntu from 20.04 to 20.10, Nagstam is installed over the .dep package from the original Ubuntu sources. Using Gnome with Xorg.

So which package caused the trouble - the one from Nagstamon website or the one coming in Ubuntu repositor?

**Comment by Huaba** [comment]
The package from the Ubuntu repository. Complete remove (with --purge) did the job.

**Comment by HenriWahl** [comment]
Please check @varac's solution: https://github.com/HenriWahl/Nagstamon/issues/681#issuecomment-814405068

**Comment by Huaba** [comment]
Linked solution works! Thanks.
