### ISSUE TITLE
Nagstamon 3.4.1 via flatpack OR a version for Fedora 33

### ISSUE THREAD

**Issue by janvonde** [HenriWahl/Nagstamon#677]
Hi,

I upgraded to the latest Fedora 33 release and it uninstalled nagstamon with the information that it is not compatible. I was able to install a version via flatpack but it is not the latest release and terminating itself after a few minutes.

It would be awesome, if you could provide a rpm file for Fedora 33 or the latest stable version via flatpack.

Thanks for your great work and stay healthy!

Jan :slightly_smiling_face:

**Comment by HenriWahl** [comment]
Thanks for the hint - it's online in the nagstamon-testing repo and stable now.

**Comment by HenriWahl** [comment]
https://flathub.org/apps/details/de.ifw_dresden.nagstamon is updated now too.
