### ISSUE TITLE
dh key too small

### ISSUE THREAD

**Issue by sHAsHiLx** [HenriWahl/Nagstamon#684]
Tried to use Ubuntu (20.10 in this case) as my main system, installed nagstamon and can't connect to one of my server, seeing in console this error

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='someurlthere.com', port=443): Max retries exceeded with url: /icinga/cgi-bin/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))

On Windows I just checked Ignore SSL/TLS certificate and all goes well but on Ubuntu can't use it. Is there any workaround or how I can understand where it search for dh key (Diffie–Hellman) and I will generate it.

**Comment by HenriWahl** [comment]
I would search on your server as I remember having to dhandle dh-files at the server side. Especially if you write 'one of my server' I assume having the root cause there.
