### ISSUE TITLE
Prometheus-Alertmanager: No seperate alert entry for different status information, if host&service is identical

### ISSUE THREAD

**Issue by AIXruth** [HenriWahl/Nagstamon#689]
I use Nagstamon with the Prometheus-Alertmanager. (Monitor type=Alertmanager)

If I there are two alerts from one host, I will only see one alert in Nagstamon instead of two.

e.g.
host= "VMa1:9100"  ;   Service="DiskSpace_Free_warn"  ; Status Information= "VMa1: **/var** is at 80%"
but the similar following alert with a different "Status Information/description" is missing:
host= "VMa1:9100"  ;   Service="DiskSpace_Free_warn"  ; Status Information= "VMa1: **/tmp** is at 80%"

**Comment by HenriWahl** [comment]
Well, this is by design - the Nagios origin and all derivatives treat the host + service combo as identifiying items. I fear this can't be fixed.
