### ISSUE TITLE
Nagstamon DOA Linux Mint 19.3

### ISSUE THREAD

**Issue by mlgoebel** [HenriWahl/Nagstamon#690]
Out of the box version 3.0.2-1. Also tried 3.4.1 with the same results. Below is full out put from install to failure to run, with OS/kernel/package version. 

[nagstamon-output.txt](https://github.com/HenriWahl/Nagstamon/files/5861206/nagstamon-output.txt)

**Comment by HenriWahl** [comment]
Maybe try the flatpak version which comes with its own Qt libraries at https://flathub.org/apps/details/de.ifw_dresden.nagstamon.

Not the best solution, but I have no idea what happened to later Ubuntu versions Qt support.

**Comment by mlgoebel** [comment]
Flatpak worked out of the box. Deeper digging reveals that I have disparate libraries for a bunch of different applications, and it looks as if flatpak or other containerization will be the norm from now on.
