### ISSUE TITLE
Nagstamon - Authentication Error

### ISSUE THREAD

**Issue by iRevenant** [HenriWahl/Nagstamon#691]
Hello,

I recently downloaded Nagstamon for CheckMK. I have all of the right login credentials, however it is still throwing an Authentication error flag when I try to login. Is there a root cause for this or is there something I can do to mitigate it?
![Screenshot_1](https://user-images.githubusercontent.com/33300386/106362738-72a5ac80-62f2-11eb-9a42-c4fe1d4886ec.png)

**Comment by toubib** [comment]
Hi,

You can try to enable debug mode in the nagstamon.conf config file in order to have more information:

```
debug_mode = True
debug_to_file = True
debug_file = /tmp/nagstamon.log
```

**Comment by GerasDraugas** [comment]
Same problem  with 3.6 and 3.7-20210408
debug mode and file enabled, but file is empty.
Nagstamon show Authentication problem.

Nagstamon 3.4.1 working fine.

I'm using:
Naemon Core 1.2.4
Thruk Monitoring Webinterface Version 2.40-2

**Comment by HenriWahl** [comment]
What Checkmk version do you use?

**Comment by GerasDraugas** [comment]
I'm not using CheckMK.

**Comment by pandvan** [comment]
I'm facing a similar issue after upgrading Checkmk to version 2.0.
By default now Checkmk set an idle timeout: https://checkmk.com/werk/12061

Once a day I've found nagstamon in "Authentication problem" state even if the credentials are correct.
In fact, if I simply click to Authenticate, it will work until the next day without further auth issues.

From debug logs I cannot see anything useful at this regard, it seems properly working (FetchURL with no errors).

**Comment by HenriWahl** [comment]
If using Checkmk please check latest build https://github.com/HenriWahl/Nagstamon/releases/tag/latest

**Comment by nikosbo** [comment]
Hi all, I have an authentication error with IcincaWeb2. If I use a user local on Icingaweb2 server, authentication works, if I use ldap user I obtain an error on Nagstamon, even if on ldap server authentication is ok and I can connect by browser with that user.
On nagstamon log I see
ERROR: 2022-07-22 13:56:14.220200 hostname_server Traceback (most recent call last):
  File "Nagstamon\Servers\IcingaWeb2.py", line 233, in _get_status
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Any idea?

**Comment by HenriWahl** [comment]
Did id work somewhen? IcingaWeb2 is the correct Icinga module to use?

**Comment by nikosbo** [comment]
Are questions for me? I can login on web interface with ldap user. I don't know what to answer to second question.

**Comment by HenriWahl** [comment]
Did it work at any time with Nagstamon?

The second question is about which of the many Icinga flavors in Nagstamon do you use?

**Comment by nikosbo** [comment]
I use Nagstamon 3.4.1, using a local user on Icinga I can login, if I use ldap user I cannot.
Monitor type in Nagstamon is Icingaweb2
many Icinga flavors : what do you mean ?

**Comment by HenriWahl** [comment]
Please use at least Nagstamon 3.8.

**Comment by nikosbo** [comment]
I confirm that with 3.8.0 I don't have the problem, thank you.
Nikos

Il 19 agosto 2022 21:07:55 CEST, Henri Wahl ***@***.***> ha scritto:
