### ISSUE TITLE
[feature request] Alertmanager / Prometheus Labels

### ISSUE THREAD

**Issue by matgn** [HenriWahl/Nagstamon#699]
We are using Nagstamon with Alertmanager : It would be awesome if we could get the Prometheus/Alertmanager labels and filter  with regular expressions. 

Version : _3.5-20201222_

Thanks

**Comment by stearz** [comment]
@matgn Can you explain what you intend to do? Do you want to use regular expressions for the detection of the host, service and status message?

**Comment by matgn** [comment]
@stearz I try to get some Prometheus custom labels first (environment for example), but it seems that Nagstamon just can't . Then, I want to filter my labels within Nagstamon. I found a solution : getting my labels in "summary". Like : summary: "[{{ $labels.environnement }}] and then filtering the summary string. 

I still have some problems with Alertmanager & Nagstamon but I know that it's quite new.
