### ISSUE TITLE
I would like to use the testing version of nagstamon from flatpak

### ISSUE THREAD

**Issue by tullis** [HenriWahl/Nagstamon#701]
Hello,

I'm a bit stuck because I'm trying to use nagstamon with Icinga2Web on Ubuntu (wayland).

I can't use the packaged versions because of the QT library incompatibility with Wayland, so I've been forced to switch to Flatpak. Unfortunately I can't use the new 3.5 RC version in testing (which includes Icingaweb2 fixes) because it hasn't been uploaded to Flatpak.

Rather than compile from source, is there any chance that you can upload the testing version to Flatpak?
I'm sure that I'm not the only one in this situation.

Many thanks for this excellent software.

**Comment by HenriWahl** [comment]
As far as I understand the flatpak process I was not able to automate the creation of new flatpak versions.
You may experiment with https://github.com/flathub/de.ifw_dresden.nagstamon/blob/master/de.ifw_dresden.nagstamon.yml to put the current latest version and its hash sum into it locally and create at least a local flatpak to see if it works.
