### ISSUE TITLE
Nagstamon not working any longer with checkmk 2.0

### ISSUE THREAD

**Issue by jmeinicke** [HenriWahl/Nagstamon#703]
I upgrade from checkmk 1.6 > 2.0 and nagstamon is not working any longer. 

Error is: 
`Monitor URL not valid`

`DEBUG: 2021-03-15 07:16:57.801686 Monitor FetchURL: https://example.com/checkmk/check_mk/index.py/view.py?view_name=nagstamon_hosts&output_format=python&lang=&limit=hard&is_host_acknowledged=-1&is_service_acknowledged=-1&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1&host_scheduled_downtime_depth=-1&is_in_downtime=-1 CGI Data: None`

Did I have to change the URL to a new Path:
Old working path is:
https://example.com/checkmk/check_mk/index.py

Any suggestions?

Thank you

**Comment by HenriWahl** [comment]
I wonder that you hate the /index.py part included - what about leaving the URL without it? Just https://example.com/checkmk/check_mk ? That's how it works with 1.6.

**Comment by sourceuser** [comment]
worked, thank you
