### ISSUE TITLE
Default URL for actions with CheckMK 2.0.0 failed

### ISSUE THREAD

**Issue by hugolyon69** [HenriWahl/Nagstamon#707]
hello,

Some Nagstamon 's features are not working well with the latest release of CheckMK : 2.0.0

Exemple : "Checkmk Edit host in WATO" action for Checkmk Multisite have false string : 

> $MONITOR$index.py?start_url=%2Fmonitor%2Fcheck_mk%2Fwato.py%3Fhost%3D$HOST$%26mode%3Dedit_host

should be replaced with : 

> $MONITOR$/wato.py?host=$HOST$&mode=edit_host

best regards
Hugo

**Comment by HenriWahl** [comment]
Thanks for the hint.

These examples are some years old - quite likely the URLs do not match anymore.

**Comment by HenriWahl** [comment]
Done in latest commit.
