### ISSUE TITLE
Unable to add Zabbix latest to nagstamon, it crashed

### ISSUE THREAD

**Issue by ftahirops** [HenriWahl/Nagstamon#708]
Every time i add latest zabbix URL to nagstamon, it crashes, there is some error in event log, 
no matter what i try, it always crash

**Comment by HenriWahl** [comment]
Can you provide some details like what OS and which version of OS, Nagstamon and Zabbix you are referring to?

**Comment by Mika56** [comment]
Hi,
I've discovered Nagstamon today. I'm having what seems to be the same issue: Nagstamon starts, says I have no server. I configure my Zabbix server, save, and Nagstamon freezes then crashes.
I've tried v3.6.0 first, then 3.4.1, but both had the same results.
I'm running on Windows 10 20H2. My Zabbix server is hosted on-premise using a custom CA (which is in the OS' certificate store). My Zabbix server uses LDAP authentication and form login against our Active Directory.

Here's what in Application log:
```
Faulting application name: Nagstamon.exe, version: 0.0.0.0, time stamp: 0x5e3034fe
Faulting module name: Qt5Core.dll, version: 5.13.2.0, time stamp: 0x5db2b3bb
Exception code: 0xc0000409
Fault offset: 0x0000000000022d28
Faulting process id: 0x7ef4
Faulting application start time: 0x01d72b81784fbaea
Faulting application path: C:\Program Files\Nagstamon\Nagstamon.exe
Faulting module path: C:\Program Files\Nagstamon\Qt5Core.dll
Report Id: f22274c1-53dd-435a-bc69-0ccd34f51cf0
Faulting package full name: 
Faulting package-relative application ID: 
```

Is there more logs somewhere? Could not find any in `%userprofile%\.nagstamon`, `%programfiles%\Nagstamon` nor `%appdata%\Temp`.

**Comment by ftahirops** [comment]
> Can you provide some details like what OS and which version of OS, Nagstamon and Zabbix you are referring to?
> 
> Edit: Did any previous version of Nagstamon work in your environment?

i tried previous versions too, tried 2-3, none work anymore now, they used to work before. 

OS: Windows 10 Pro, Ver: 1909
Nagstamon: Tried latest v3.6.0
Zabbix: 5.2

**Comment by HenriWahl** [comment]
@Mika56 

> Faulting module name: Qt5Core.dll, version: 5.13.2.0, time stamp: 0x5db2b3bb

I wonder about that Qt5 version, because it actually comes with 5.15.2. Do you have several versions installed? Or maybe a previous version has not been deleted completely? You could test with the .zip version of the downloads.

> Is there more logs somewhere? Could not find any in `%userprofile%\.nagstamon`, `%programfiles%\Nagstamon` nor `%appdata%\Temp`.

Nagstamon has a debug option but looks like it crashes before you could enable it. :-(

**Comment by ftahirops** [comment]
> @Mika56
> 
> > Faulting module name: Qt5Core.dll, version: 5.13.2.0, time stamp: 0x5db2b3bb
> 
> I wonder about that Qt5 version, because it actually comes with 5.15.2. Do you have several versions installed? Or maybe a previous version has not been deleted completely? You could test with the .zip version of the downloads.
> 
> > Is there more logs somewhere? Could not find any in `%userprofile%\.nagstamon`, `%programfiles%\Nagstamon` nor `%appdata%\Temp`.
> 
> Nagstamon has a debug option but looks like it crashes before you could enable it. :-(

Already un-instaled all versions, then tried, still same issue

Tried Zip folder version too, same issue. 

i could not enable debug option, tried a lot

**Comment by Mika56** [comment]
You can delete the server configuration in `%userprofile%\.nagstamon\servers`, then, when NAgstamon starts, select ignore. Right click on the Nagstamon "window", then settings, and enable debug mode.
I've done it but Nagstamon had nothing to log for me?

As for the Qt version, my Nagstamon install (3.4.1) shipped with 5.13.2.0:
![image](https://user-images.githubusercontent.com/600347/113835186-0466e580-978c-11eb-9fb4-e49db17eb9f2.png)

**Comment by ftahirops** [comment]
> %userprofile%\.nagstamon\

Same for me, i did enable logging, but it crashes and no logs anywhere

**Comment by HenriWahl** [comment]
> I've done it but Nagstamon had nothing to log for me?

OK, so it crashes earlier.

Did you try the new 3.6.0?

**Comment by HenriWahl** [comment]
I am going to test this in a Windows environment.

**Comment by HenriWahl** [comment]
Just one question: are there any special conditions hardware- or softwarewise?

**Comment by Mika56** [comment]
Interestingly, it doesn't crash if credentials are incorrect

**Comment by ftahirops** [comment]
> Interestingly, it doesn't crash if credentials are incorrect

yes, if credentials are nto right, it wont even open or get access to zabbix server, so obviously something only happens,when it tries to login, and after login it crashes

**Comment by HenriWahl** [comment]
@mprenditore do you maybe have an idea?

**Comment by ftahirops** [comment]
@HenriWahl so what do you think could be the reason?

**Comment by HenriWahl** [comment]
@ftahirops to me right now looks like some Zabbix login problem - that's why I ask  @mprenditore for opinion as being the main author of the Zabbix code.

**Comment by ftahirops** [comment]
> @ftahirops to me right now looks like some Zabbix login problem - that's why I ask @mprenditore for opinion as being the main author of the Zabbix code.

i want to add something
i have multiple monitoring systems added in nagstamon, nagios and zabbix
i had one nagios and 3 zabbix. all were doing fine, till last few days, even the working nagstamon is crashing (which was working perfectly fine). i was trying to add 4th Zabbix server, which used to crash it. so i did not add it. 

so now i am not able to run nagstamon, looking for better alternatives. lot of issues

**Comment by HenriWahl** [comment]
@ftahirops this sounds really strange. Have there been any other changes in your environment? Any antivirus software? OS updates?
I assume the previously working version was 3.4.1?
Just for debugging - are you able to run it on another OS; for example in a Linux VM?

**Comment by ftahirops** [comment]
> @ftahirops this sounds really strange. Have there been any other changes in your environment? Any antivirus software? OS updates?
> I assume the previously working version was 3.4.1?
> Just for debugging - are you able to run it on another OS; for example in a Linux VM?

in last few days, no OS changes, i think , may be last windows update happened, no major change beside that 

let me try it on ubuntu VM

**Comment by ftahirops** [comment]
> @ftahirops this sounds really strange. Have there been any other changes in your environment? Any antivirus software? OS updates?
> I assume the previously working version was 3.4.1?
> Just for debugging - are you able to run it on another OS; for example in a Linux VM?

here are my findings, i found the problem i think. 
on ubuntu there is same issue, but atleast it gives some erro before crashing.

![Screenshot_1](https://user-images.githubusercontent.com/16486877/114005368-54898a80-9814-11eb-933f-43be6fabc12a.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/16486877/114005370-55222100-9814-11eb-9ccb-41c8da022a05.jpg)

**Comment by HenriWahl** [comment]
Thanks! This looks at least like something to investigate in.

**Comment by ftahirops** [comment]
Not sure why Zabbix based check goes to any IPMI check. perhaps a bug

**Comment by HenriWahl** [comment]
The great Github Actions already compiled a version which might fix it - please check https://github.com/HenriWahl/Nagstamon/releases/tag/latest

**Comment by Mika56** [comment]
It crashes the same way.

There seems to be a demo instance of Zabbix available here: https://www.racom.eu/eng/products/m/ripex/demo/zabbix.html
Maybe you can use this to debug the problem?

**Comment by HenriWahl** [comment]
@ftahirops can you get the crash output via Linux again?

**Comment by HenriWahl** [comment]
@Mika56 does this demo instance crash for you?

**Comment by HenriWahl** [comment]
@Mika56 did you use **Zabbix** or **ZabbixProblemBased** server type? I just changed **Zabbix**.

**Comment by HenriWahl** [comment]
Meanwhile added ZabbixProblemBased too, so the latest builds could be tested.

**Comment by ftahirops** [comment]
Thanks man, it worked like a charm. i can add any zabbix instances without
any issues.



Regards,
Farhan

**Comment by HenriWahl** [comment]
Which one of the both Zabbix-related server types do you use?

**Comment by ftahirops** [comment]
Zabbix 4, 5.2.6 (latest) and using nagios. all are ok now, working
perfectly with new release


Regards,
Farhan

**Comment by ftahirops** [comment]
after upgrad,e , there is a problem. 
all my problems are duplicated, why is that? 

you can see same problem is being shown 2 times, why is that?

![Screenshot_1](https://user-images.githubusercontent.com/16486877/114081263-30a06600-9861-11eb-9a40-e5e3b7091eda.jpg)

**Comment by HenriWahl** [comment]
At first sight I do not know. What monitor type did you configure in Nagstamon? "Zabbix" or "ZabbixProblemBased"?

**Comment by HenriWahl** [comment]
https://github.com/HenriWahl/Nagstamon/issues/582 describes some similar experience but neither makes much sense.

**Comment by HenriWahl** [comment]
I mean which type you configured in Nagstamon? There is a dropbox with many different server types to choose from.

**Comment by HenriWahl** [comment]
Another question aside the configured monitor type: I tested with the above mentioned https://www.racom.eu/eng/products/m/ripex/demo/zabbix.html and every problem occurs just once. How does this site display in your Nagstamon?

**Comment by ftahirops** [comment]
sorry, it was problem from my side. i just ued default settings fo nagstamon, cleared all filers and now its resolved. thanks

**Comment by HenriWahl** [comment]
But strange anyway that there the issues where in double?

**Comment by ftahirops** [comment]
yes, i dont know why it showed the same with double entries. no idea how it
happened.


Regards,
Farhan
