### ISSUE TITLE
Custom action regular expression [3.6-rc2]

### ISSUE THREAD

**Issue by poldyaev** [HenriWahl/Nagstamon#710]
Tell me what regular expression should I use to remove the port from host when using alertmanager?
I've tried using a `(\ S +):` expression, but I still get host: port in the output.
![DeepinScreenshot_nagstamon_20210407154951](https://user-images.githubusercontent.com/878061/113861988-e82d6d80-97b8-11eb-8957-b6f1a737e603.png)

**Comment by matgn** [comment]
Same problem here! I tried regex groups but I think Nagstamon didn't implement it
