### ISSUE TITLE
Upgrade to 3.6.0 issue on windows7 in Italian

### ISSUE THREAD

**Issue by nikosbo** [HenriWahl/Nagstamon#713]
I tried to upgrade nagstamon on win7 Italian version, I obtain errors of missing dll, but I think problem is that software look for them in Program Files folder, but I have Programmi folder, where I find dll files, any suggestion to fix it?

**Comment by HenriWahl** [comment]
Can you provide the exact error message, for example as screenshot?

**Comment by nikosbo** [comment]
![Nagstamon_error_win7](https://user-images.githubusercontent.com/23611818/114568604-8cf5f200-9c74-11eb-9314-e81be9962d9d.jpg)
![Nagstamon_error2_win7](https://user-images.githubusercontent.com/23611818/114568607-8d8e8880-9c74-11eb-98a3-1fda063bf35f.jpg)

**Comment by HenriWahl** [comment]
According to Python website https://www.python.org/downloads/release/python-390/:

> This is the first version of Python to default to the 64-bit installer on Windows. The installer now also actively disallows installation on Windows 7. Python 3.9 is incompatible with this unsupported version of Windows.

I am sorry, but this meanwhile unsupported version of Windows plainly is too old. You either:
- just might compile your own version of Nagstamon with an older Python version
- or update your Windows, which is anyway the better and safer option

Regards
Henri
