### ISSUE TITLE
Nagstamon crash when adding server livestatus

### ISSUE THREAD

**Issue by TiDjY35** [HenriWahl/Nagstamon#717]
when i add a livestatus server, nagstamon crash

Windows 10
Nagstamon 3.6 or 3.7

Error in the event viewer.

Name of the faulty application Nagstamon.exe, version: 0.0.0.0, timestamp: 0x5ffec13d
Name of the faulty module: Qt5Core.dll, version: 5.15.2.0, timestamp: 0x5fa4dd3b
Exception code: 0xc0000409
Error offset: 0x00000000000204e8
Faulting process ID: 0x6a74
Start time of the failed application: 0x01d7329dac9cc243
Path of the faulty application: C: \ Program Files \ Nagstamon \ Nagstamon.exe
Faulty module path: C: \ Program Files \ Nagstamon \ Qt5Core.dll
Report ID: 616a5542-addb-4cc7-82d3-ecfab904b3de
Full name of the failed package:
Application ID relating to the faulty package:
![2021-04-16 11_14_30-Observateur d'événements](https://user-images.githubusercontent.com/4006867/115002350-f0fefd00-9ea4-11eb-8334-19a5ce96bfd0.png)

**Comment by HenriWahl** [comment]
Are you able to run the plain Python source to get a more informative error message?

**Comment by TiDjY35** [comment]
Hello @HenriWahl,
sorry for no response.

I still have the problem today

What is the python command to execute?

Thanks you

**Comment by TiDjY35** [comment]
![image](https://github.com/HenriWahl/Nagstamon/assets/4006867/db9455bc-6a1d-4d01-8e92-e231bfae09e6)
