### ISSUE TITLE
[Feature] API support

### ISSUE THREAD

**Issue by hugleo** [HenriWahl/Nagstamon#725]
Nagstamon is not really a server, but since Nagstamon get the status of many monitoring systems maybe a generic API would be good to support others platforms like android.

**Comment by HenriWahl** [comment]
Can you please give more details what exactly you mean?

**Comment by hugleo** [comment]
I think is out of scope of the the project. Something like a livestatus LMD API exporter, so I could use Nagstamon like a central server to feed thruk interface and use mobile apps to see alerts.

**Comment by HenriWahl** [comment]
Currently yes, out of scope. Sounds good but there are still many other unsolved issues. I gonna close this for now.
