### ISSUE TITLE
[Alertmanager] Problem with inhibition

### ISSUE THREAD

**Issue by matgn** [HenriWahl/Nagstamon#738]
It seems nagstamon don't work well with Alertmanager inhibition rules. 
For example : A host with the same alert, but with status warning and critical. 

This results to just 1 alert marked "down for maintenance" (the warning alert) and can't see critical alert... 

On Alertmanager : both alerts exist 
warning -> state suppressed 
critical -> state active

**Comment by HenriWahl** [comment]
Still being an issue?

**Comment by matgn** [comment]
> Still being an issue?

Nop, seems to be fixed 
Alertmanager 0.23.0
Nagstamn 3.7-20210914

Thanks

**Comment by matgn** [comment]
> Still being an issue?

I thought it was solved but no ... 
I have a critical alert, I can see my alert "warning" with status "suppressed" but can't see my alert "critical" with status "active"
