### ISSUE TITLE
Segmentation fault after upgrade to Ubuntu 21.04

### ISSUE THREAD

**Issue by Fjodor42** [HenriWahl/Nagstamon#740]
I have successfully used Nagstamon connecting to a Zabbix instance for a number of years, but after upgrading to Ubuntu 21.04, I get a segafult on attempting to start it.

On a different machine with the same OS, Nagstamon connecting to a Nagios instance works as expected.

Please advise on whatever else I might present in order to get this fixed.

Thanks in advance.

[nagstamon.20210603-001.strace.log](https://github.com/HenriWahl/Nagstamon/files/6593094/nagstamon.20210603-001.strace.log)

**Comment by Fjodor42** [comment]
Hi @HenriWahl,

I know this one is light on details, but it is rather inconvenient for me as well, so could you perhaps let me know if you need anything else in order to get closer to a solution for it?

Best regards,
F

**Comment by HenriWahl** [comment]
Hi @Fjodor42,
what happens on a different machine with the same OS and connection to the same Zabbix instance?
Regards

**Comment by Fjodor42** [comment]
Hi @HenriWahl,

That's quite hard to say, but I believe the problem to have had something to do with the combination of graphics drivers, Python and, possibly, Cinnamon, because I just installed a bunch of updates, including some graphics stuff, rebooted, and there came Nagstamon, when I logged in :-)

Coincidentally, this was only ~20 minutes ago, and I hadn't seen your reply until just now.

Thank you for Nagstamon, and have a nice day :-)
