### ISSUE TITLE
Floating Toolbar makes other apps not go full screen on mint20/Cinnamon

### ISSUE THREAD

**Issue by MattWright1977** [HenriWahl/Nagstamon#741]
for the longest time I thought this was an obscure issue with Cinnamon and my Laptop, and it wasn't until this past weekend, when I discovered it appears to be an issue related to Nagstamon.

normally I have Nagstamon running as a floating toolbar.  if I then load up say VLC, a game, or view a video in chrome at full screen, the Cinnamon Task bar remains at the foreground, and won't hide behind the Video.

This weekend while I was sat on a plane, I closed Nagstamon, since it couldn't actually perform any checks, and the cinnamon task bar instantly vanished, as it should 

![vlc-cinnamon-nagstamonexited](https://user-images.githubusercontent.com/56362086/121064494-853a6180-c77c-11eb-91f6-d2d711550a40.png)
![vlc_cinnamon_nagstamon](https://user-images.githubusercontent.com/56362086/121064499-85d2f800-c77c-11eb-9342-687d745504a3.png)

**Comment by HenriWahl** [comment]
Interesting... but I fear there is not much we can do there.
