### ISSUE TITLE
macOS arm64/Apple Silicon Build

### ISSUE THREAD

**Issue by dotsam** [HenriWahl/Nagstamon#743]
It looks like pyinstaller is adding support for both arm64/Apple Silicon builds for macOS, and also universal builds (although there are more caveats to get these universal2 builds working: https://pyinstaller.readthedocs.io/en/latest/feature-notes.html#macos-multi-arch-support). I just wanted to document what I did to get an arm64 build working locally in case others are looking to do the same.

To begin, I've installed python 3 and pyqt 5 from Homebrew (`brew install python@3.9 pyqt@5`).

Then I've installed pyinstaller from source, including re-compiling boot loaders, which creates x86/arm64 fat binaries: https://github.com/pyinstaller/pyinstaller/issues/5886#issuecomment-854116364

Finally, I cloned the Nagstamon git repo and made the following changes:

- Changed the version of pyqt5 in `build/requirements/macos.txt` to match the version installed by Homebrew (trying to install through pip failed, which is why I used the Homebrew package), in this case 5.15.4, which works, despite the note saying this version isn't working
- Changed the path for `pyinstaller` in `build/build.py` to be the correct one for arm64 Homebrew installations: `/opt/homebrew/bin/pyinstaller`

From there I did the normal steps to produce a macOS .app build:

- `pip3 install -r build/requirements/macos.txt`
- `cd build/ && python3 build.py`

Apple Silicon Macs require all arm64 code to be signed, but pyinstaller takes care of that by self-signing the .app bundle. For distribution, proper code signing would need to be set up, or as a worst-case, instructions given for how users could self-sign the app themselves.

Hope this is helpful to someone!

**Comment by HenriWahl** [comment]
Thanks for your investigations.

The need for signed arm64 packages sounds alarming - on the one hand a good idea for commercial distribution but on the other I am not sure how some open source project shall handle this.

**Comment by dotsam** [comment]
One other note here, RE: signing. The current build script which modifies the Info.plist after PyInstaller has run will not work with the out-of-box signing capabilities of PyInstaller, as editing the Info.plist file after signing will invalidate the signature. (This doesn't actually seem to be a problem for ad-hoc/self-signed apps, but would be for a properly signed .app for distribution).

The solution would seem to be to [generate a .spec file](https://pyinstaller.readthedocs.io/en/latest/spec-files.html#spec-file-options-for-a-mac-os-x-bundle), setting and replacing the `version=` line in there, and then generate the .app bundle from the spec file. The .spec file can also contain other Info.plist keys, eliminating the need to keep a static Info.plist file in the resources/ directory.

**Comment by HenriWahl** [comment]
Sounds sensible,

**Comment by umrashrf** [comment]
Which one is the Nagstamon git repo to be exact?

**Comment by HenriWahl** [comment]
> Which one is the Nagstamon git repo to be exact?

https://github.com/HenriWahl/Nagstamon

**Comment by HenriWahl** [comment]
> One other note here, RE: signing. The current build script which modifies the Info.plist after PyInstaller has run will not work with the out-of-box signing capabilities of PyInstaller, as editing the Info.plist file after signing will invalidate the signature. (This doesn't actually seem to be a problem for ad-hoc/self-signed apps, but would be for a properly signed .app for distribution).
> 

Looks cleaner, yes.

> The solution would seem to be to [generate a .spec file](https://pyinstaller.readthedocs.io/en/latest/spec-files.html#spec-file-options-for-a-mac-os-x-bundle), setting and replacing the `version=` line in there, and then generate the .app bundle from the spec file. The .spec file can also contain other Info.plist keys, eliminating the need to keep a static Info.plist file in the resources/ directory.

Do you think you could modify the current macOS building to make it work with your steps? I am not able at the moment due to missing hardware.

**Comment by dotsam** [comment]
Hi @HenriWahl, I've submitted PR #761 for the changes to building on macOS

**Comment by HenriWahl** [comment]
Thanks, is being built right now. Still with old unstable version number but will be fixed soon.
