### ISSUE TITLE
api-ms-win-core-path-I1-1-0.dll not found on Windows 7

### ISSUE THREAD

**Issue by choppa42** [HenriWahl/Nagstamon#744]
Nagstamon does not start on windows 7. Using the EXE Installer and also the standalone ZIP

The api-ms-win-core-path-I1-1-0.dll cannot be found both in EXE-Installer and standalone ZIP.
Subsequently the python39.dll cannot be loaded.

Should this be packaged in the distributions?

**Comment by HenriWahl** [comment]
Python since some version 3.x does not support Windows 7 anymore, which in fact is a good idea because even Microsoft doesn't since over a year. So I assume this won't be fixed.

You just can try to run it from source with a very old Python version but I won't bet much on this to work.
