### ISSUE TITLE
Servers with no alerts still take up vertical space in the popup window

### ISSUE THREAD

**Issue by svenedge** [HenriWahl/Nagstamon#745]
With many server sources configured, each one appears to take up a few pixels, even if they have no alerts. 

E.g. this is the 12th server configured, the 11 before it are taking up space:
![image](https://user-images.githubusercontent.com/82092392/122210459-94689000-ce9d-11eb-919e-8fe6ae2262b5.png)

There are 3 servers between these two alerting ones:
![image](https://user-images.githubusercontent.com/82092392/122210725-d85b9500-ce9d-11eb-931a-c7fd32598774.png)

version 3.6.0 on a mac, installed from homebrew.

**Comment by HenriWahl** [comment]
Has it been this way with previous versions too?

**Comment by HenriWahl** [comment]
This looks strange, never noticed before. Does this only happen on Mac?

**Comment by svenedge** [comment]
Just checked with a colleague on windows looking at the same nagios servers, and they don't have the same issue. I've not used a mac before this job, and never used nagstamon to look at more than 2-3 nagios servers before.

**Comment by HenriWahl** [comment]
Does it happen with latest testing release 3.9-20220605 too?

**Comment by svenedge** [comment]
Still happens, I'm afraid:
![image](https://user-images.githubusercontent.com/82092392/172679318-70292f20-e73f-4b1c-8550-07cd6cae3a68.png)
The first visible entry is server 13, the second server 14, the third server 16, the fourth server 17.

**Comment by HenriWahl** [comment]
Should be gone with latest build 3.9-30330930 from https://github.com/HenriWahl/Nagstamon/releases/tag/latest

**Comment by svenedge** [comment]
@HenriWahl yep, that's fixed it, thanks :)
