### ISSUE TITLE
No recheck action for service in Zabbix monitor

### ISSUE THREAD

**Issue by anomaliyao** [HenriWahl/Nagstamon#750]
There is no recheck action for the problem service in the Zabbix monitor, I am using Nagstagmon version 3.6.0.

**Comment by HenriWahl** [comment]
The action is not shown or does not work?

**Comment by anomaliyao** [comment]
Where the top selection menu is, it is possible to click, but this action does not apply (does not work).
And if you choose a certain service and try to recheck, there is no such action.
![image](https://user-images.githubusercontent.com/23505611/131307099-c0fbfd48-f913-4726-bbe5-2c0ecd7906cd.png)

**Comment by HenriWahl** [comment]
According to https://github.com/HenriWahl/Nagstamon/blob/f6ab7413c3313f759fdb308e8f462fc082bacae7/Nagstamon/Servers/Zabbix.py#L69 there is actually no Recheck action.
