### ISSUE TITLE
Nagstamon right click / Acknowledge sending two notification emails

### ISSUE THREAD

**Issue by paulstaf** [HenriWahl/Nagstamon#762]
When I use the Nagios web page to acknowledge a host or service problem, I only get one email notification sent.

If I acknowledge using Nagstamon, it sends two email notifications for the same acknowledgement.

I have Nagstamon running on two different Linux workstations and they both do the same thing, sending two acknowledge email notifications whenever I use Nagstamon to acknowledge a host or service problem.

Any ideas?  It is really baffling me.  

Thanks,
Paul

**Comment by HenriWahl** [comment]
As this is completely unusual - is there a chance there is something configured this way on the server side? Nagstamon just triggers the same URL as one would do in the web interface.

**Comment by paulstaf** [comment]
Oddly, it is back to normal now only sending one email.  I have no idea what fixed it and I didn't do anything.  Odd.
