### ISSUE TITLE
Icinga: When service.status_information is null we get an exception

### ISSUE THREAD

**Issue by glesys-andreas** [HenriWahl/Nagstamon#773]
When the status_information is null from an Icinga server we get an error message:
"AttributeError: 'NoneType' object har no attribute 'replace'
This causes nagstamon not to display any checks

https://github.com/HenriWahl/Nagstamon/blob/aeef908d42a3d740be9ca9d8ce9f838a11050360/Nagstamon/Servers/Icinga.py#L197
This can be solved by adding an if statement before the variable assignation:
`                        if s['status_information']:
                            self.new_hosts[host_name].services[service_name].status_information = s['status_information'].replace('\n', ' ').strip()`

**Comment by HenriWahl** [comment]
Could you provide a pull request, so this fix can be integrated faster?

**Comment by glesys-andreas** [comment]
Created the pull request #774 , please let me know if i need more changes to the PR

**Comment by HenriWahl** [comment]
Thanks. Will be available in some minutes in the latest releases.
