### ISSUE TITLE
Nagstamon icon green while "Monitor URL not valid"

### ISSUE THREAD

**Issue by varac** [HenriWahl/Nagstamon#775]
My alertmanager instance went down, and I didn't notice because the Nagstamon icon was green all the time. When I clicked on "Show status window" I saw that it complained about `Monitor URL not valid`.
Please let Nagstamon alert on these kind of connection errors, so you notice in time when an instance goes down.

![image895](https://user-images.githubusercontent.com/488213/133660399-424fa632-6201-4e9e-abaa-4fd9fb5be350.png)

**Comment by varac** [comment]
Btw, the server responded with "404 Not Found".

**Comment by varac** [comment]
I can't attach any logs because they are completely empty.

**Comment by HenriWahl** [comment]
What monitor server type do you use?

**Comment by varac** [comment]
> What monitor server type do you use?

I'm using Alertmanager v0.22.2

**Comment by HenriWahl** [comment]
Alertmanager support saw some changes recently - does this persist with latest testing release 3.9-*?
