### ISSUE TITLE
nagstamon status bar not showing up

### ISSUE THREAD

**Issue by nooralas** [HenriWahl/Nagstamon#778]
Hallo,
i installed Nagstamon on my device and it is connected to Check_MK server, it works for the rest my colleagues. when i finish the settings and close it and reopened, it appears for a second and then disappears, i activate the debug mode and debug to file, but it dose not write any log, i tried versions "3.6","3.7","3.4.1"  it didn't works, i installed Python and he still the same didn't works.
I'm using Windows 10 Ver 21H1 64bit.

Thanks in advance.

**Comment by HenriWahl** [comment]
Are you able to run Nagstamon from source as described in https://nagstamon.de/documentation#requirements ?

**Comment by nooralas** [comment]
Hi and thanks for your Replay 
i Installed it from the source code, but the same result, i can hear the notifications and it works in the background, but the status bar not showing up.
Thanks in advance.

**Comment by HenriWahl** [comment]
The output in the terminal is interesting for Fürther investigation

**Comment by nooralas** [comment]
hi,
here you find the output from the terminal for the first Time(when entering the server settings)"here it display the status bar"
`
C:\Nagstamon-3.6.0>py nagstamon.py
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
C:\Python37\lib\site-packages\urllib3\connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mk.*****.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
C:\Python37\lib\site-packages\urllib3\connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mk.*****.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
C:\Python37\lib\site-packages\urllib3\connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mk.*******.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
C:\Python37\lib\site-packages\urllib3\connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mk.****.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
C:\Python37\lib\site-packages\urllib3\connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mk.****.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
QWindowsWindow::setGeometry: Unable to set geometry 820x40+1720+40 (frame: 820x40+1720+40) on QWidgetWindow/"StatusWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 547x27+1720+40 (frame: 547x27+1720+40) margins: 0, 0, 0, 0 minimum size: 1x1 maximum size: 960x480 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=2,2 maxtrack=1920,960)
C:\Python37\lib\site-packages\urllib3\connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mk.*****.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
C:\Python37\lib\site-packages\urllib3\connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mk.*****.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,`


--------------------------------------------------------------------------------------------------------------------------------

When i quit the program and reopen it, the status bar disappears, and this is the terminal output
`C:\Nagstamon-3.6.0>py nagstamon.py
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
C:\Python37\lib\site-packages\urllib3\connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mk.*****.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
C:\Python37\lib\site-packages\urllib3\connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mk.*****.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
C:\Python37\lib\site-packages\urllib3\connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mk.*****.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
C:\Python37\lib\site-packages\urllib3\connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mk.*****.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
C:\Python37\lib\site-packages\urllib3\connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mk.*****.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,`

**Comment by neufeind** [comment]
If I assume correct you might be experiencing problems with the floating-bar mode, see #696.

**Comment by HenriWahl** [comment]
What about Nagstom 3.8?

**Comment by dsl** [comment]
I think I'm seeing the same problem on 3.8.0 (debian):

QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout

/usr/lib/python3/dist-packages/urllib3/connectionpool.py:1046: InsecureRequestWarning: Unverified HTTPS request is being made to host 'X'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:1046: InsecureRequestWarning: Unverified HTTPS request is being made to host 'X'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 4115, in get_status
    status = self.server.GetStatus()
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Generic.py", line 905, in GetStatus
    self.init_HTTP()
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/IcingaWeb2.py", line 100, in init_HTTP
    if len(self.session.cookies) == 0:
AttributeError: 'NoneType' object has no attribute 'cookies'
Aborted

Apologies if not the same, I can open a new issue if needs be?

**Comment by HenriWahl** [comment]
And what about the latest testing releases 3.9-x?

**Comment by HenriWahl** [comment]
Looks like there are now news....
