### ISSUE TITLE
Sizing problem on Windows -nagstamon 3.6.0

### ISSUE THREAD

**Issue by AV68** [HenriWahl/Nagstamon#780]
I have a laptop with external monitor (hdmi) , I keep nagstamon in system tray, when I click the icon then status bar window always start in a resized window and I cannot see immediately the notifications but have to scroll down and the windows is not resizable with the mouse. Screen resolution = 1920 x 1080.
Can you help me?

![image](https://user-images.githubusercontent.com/92156559/136540292-8c4e7372-84c7-4349-90db-6abf31326fff.png)

Many thanks, ciao

**Comment by HenriWahl** [comment]
Looks strange. Can you try the latest testing release?

**Comment by Bapf** [comment]
I have the same issue with version 3.8.0

Running on a dual screen setup with 2560x1440 (scaling 100%) on the main screen and 3456x2160 (scaling 200%) on the secondary screen.
The Taskbar (and hence the tray icon) is only on the main screen.

**Comment by HenriWahl** [comment]
Can you try the lastest testing releases which are based on Qt6? See https://github.com/HenriWahl/Nagstamon/releases/tag/latest

**Comment by AV68** [comment]
Hello Henri,
latest version seems to be OK but I'm using it since 5 minutes, I'll send feedback tomorrow.
Thanks.

**Comment by Bapf** [comment]
> Can you try the lastest testing releases which are based on Qt6? See https://github.com/HenriWahl/Nagstamon/releases/tag/latest

It's ... different.
Right after launching it doesn't show anything at all when I click on the tray icon.
If I do a manual refresh the first click shows like this (100% display height):
![2022-05-19 10_33_37-](https://user-images.githubusercontent.com/310059/169250229-d60c3f12-e0ca-4105-bde2-fa6dd41c2cb5.png)
and afterwards it begins to work correctly.

**Comment by HenriWahl** [comment]
Are you able to run it from source in a command line terminal window? Just to see any errors which might been thrown?

**Comment by HenriWahl** [comment]
Does this only happen with multiple screens? I tried with just one and none of these strange effects happens.

**Comment by Bapf** [comment]
> Does this only happen with multiple screens? I tried with just one and none of these strange effects happens.

Ok, did some testing; It happens only with a dual monitor setup and on top of that only if I use different scaling factors on those two screens. As long as the scaling is identical on both screens everything works fine.

(I'm talking about this setting:
![2022-05-20 13_56_26-Window](https://user-images.githubusercontent.com/310059/169523751-2b125349-e4ff-4124-94f5-a9fabcdf4da5.png)
)

**Comment by Bapf** [comment]
Fixed (at least for me) in 3.10.1

**Comment by HenriWahl** [comment]
👍
