### ISSUE TITLE
Can't upgrade to Fedora 35 using stable repo

### ISSUE THREAD

**Issue by gloomytrousers** [HenriWahl/Nagstamon#782]
I'm attempting to upgrade my OS to Fedora 35, with the "stable" repo (current stable version 3.6.0). Unfortunately this repo doesn't have a package for F35; it looks like (following commit f23f8b45e9b58cf5f66afeb91804f7d112df633b) this will be available for 3.7.0. Without the F35 package in the repo, `dnf system-upgrade` ([docs](https://docs.fedoraproject.org/en-US/quick-docs/dnf-system-upgrade/)) fails.

Is 3.7.0 expected to go to stable any time soon, or should I work around it by using the "latest" repo temporarily?

**Comment by HenriWahl** [comment]
Thanks for the hint - it is just missing. I'll add it ASAP.

**Comment by HenriWahl** [comment]
finally the 3.8 is out which contains a Fedora 35 repo release too.

**Comment by gloomytrousers** [comment]
Thanks @HenriWahl !
