### ISSUE TITLE
Nagstamon crash when there is a problem 

### ISSUE THREAD

**Issue by Arcocide** [HenriWahl/Nagstamon#783]
Hi,
I have some problem with Nagstamon. When a alert arrive, Nagstamon down. I have this problem with all computer who use nagstamon. I use 3.6 version on my Windows OS and Zabbix 5.4. The log file is empty after crash.
Regards,

**Comment by HenriWahl** [comment]
Should work with testing release and the upcoming stable 3.8 too.
