### ISSUE TITLE
Website inconsistency

### ISSUE THREAD

**Issue by fufroma** [HenriWahl/Nagstamon#784]
Hi !

On the url: https://nagstamon.de/download

We can see 'Get the latest stable release 3.8.0 from GitHub stable release.'

But the link is to v3.6.0 : https://github.com/HenriWahl/Nagstamon/releases/tag/v3.6.0

Maybe the link could be to https://github.com/HenriWahl/Nagstamon/releases/latest to be always up-to-date.

Regards,

**Comment by HenriWahl** [comment]
Thanks - I found this too and it is fixed now.
