### ISSUE TITLE
nagstamon 3.8.0 installation failed (due antivirus)

### ISSUE THREAD

**Issue by zyriusa** [HenriWahl/Nagstamon#785]
Hello,

bitdefender treats it as malware
 C:\Program Files\Nagstamon\is-HK8SS.tmp is malware of type Gen:Variant.Tedy.12718

**Comment by trailsnail** [comment]
Same here ...

**Comment by staabm** [comment]
Gdata the same problem

**Comment by HenriWahl** [comment]
Not again... which versions exactly? 32/64 bit? ZIP or EXE?

**Comment by trailsnail** [comment]
`Nagstamon-3.8.0-win64_setup.exe`

**Comment by HenriWahl** [comment]
I filled out the fals-positive-forms of Avast, AVG and GData. No luck with Sophos - looks rather complicated. Does anybody know how to submit there or has the opportunity as customer to flag something as false positive?

**Comment by mmurraymark** [comment]
Symantec Endpoint Protection is also showing a false positive

**Comment by zyriusa** [comment]
> Not again... which versions exactly? 32/64 bit? ZIP or EXE?
> 
> According to https://www.virustotal.com/gui/file/f24043f8618871a6ba37251436ea23768cbfb489eafac5e415cdb86d8677f29d and https://www.virustotal.com/gui/file/707d37b60c7212468d9f5d8914a2605340e71f68bdc6978f87bc8a6d37083784 Avast, Sophos and AVG are most oversensitive.

64bit exe and zip

**Comment by HenriWahl** [comment]
Avast at least promised to whitelist the installer.

**Comment by HenriWahl** [comment]
I rebuilt the PyInstaller bootloaders as they described at https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html and the result is quite THE SAME so I think the only options at the are:

- you tell your antivirus software vendors that they are wrong
- you run it locally from source
- you wait until it is whitelisted at your antivirus software vendor

Another way to package is Nuitka, but the binary crashed during a short peek at it.
So if anybody sees another option how to package Nagstamon - let us know.

**Comment by staabm** [comment]
Gdata updated signatures.. seems to work now for us.

thx for the fast fix 🙏

**Comment by Sebazzz** [comment]
To add an additional datapoint: Did also happen with Symantec Endpoint Protection.

**Comment by zyriusa** [comment]
is ok now
