### ISSUE TITLE
AttributeError: 'LooseVersion' object has no attribute 'version'

### ISSUE THREAD

**Issue by lordtaki** [HenriWahl/Nagstamon#787]
I'm using Nagstamon 3.8.0 with Windows 11 and can't get status from an Icinga 1.13 server.
Python version is 3.10.0

AttributeError: 'LooseVersion' object has no attribute 'version'

Thank you.

**Comment by HenriWahl** [comment]
Nagstamon was not tested yet with Python 3.10. Do you have the same problem with older Python?

**Comment by lordtaki** [comment]
I had the issue with Python 3.8 that's why I upgraded to 3.10.
I can give a try to a well known working python version.

**Comment by HenriWahl** [comment]
The Windows binary is compiled with Python 3.7.
AFAIK there was some issue with Python since 3.8 with distutils so it looks like this issue happens here too with https://github.com/HenriWahl/Nagstamon/blob/9ac8642e5db104fa2ed595d85fed4a76b2204db8/Nagstamon/Servers/Icinga.py#L26
Maybe the Icinga module should try to live without LooseVersion? Pull requests welcome... :-)

**Comment by lordtaki** [comment]
I've just installed Python 3.7.9 and same issue.
I enabled debug mode but the file nagstamon.log is empty.

**Comment by HenriWahl** [comment]
Could you please post the whole error output, just to have a look?

**Comment by lordtaki** [comment]
That's all I have at the top right of the window.
I tried again and this time I get:

AttributeError: 'NoneType' object has no attribute '__dict__'

**Comment by HenriWahl** [comment]
> AttributeError: 'NoneType' object has no attribute '**dict**'

Is there some line number and file stated where this happens?

**Comment by HenriWahl** [comment]
Please try latest commit https://github.com/HenriWahl/Nagstamon/commit/e670b25096e32ba88128f74d3e1e6545e5e2bd7b

**Comment by lordtaki** [comment]
I donwloaded and try:
Nagstamon-3.9-20220219-win64.zip
Nagstamon-3.9-20220219-win64_setup.exe

Nagstamon does not pop up when I launch it.
Tried also within a terminal just to be sure something is not running in the background.

**Comment by HenriWahl** [comment]
Can you try to run it from source to see more output in console?

**Comment by lordtaki** [comment]
Got it to work. It reported missing modules, some pip commands later ... :)
Thank you.

**Comment by HenriWahl** [comment]
But is there any hint why the binary did not work?

**Comment by lordtaki** [comment]
Reinstalled with: Nagstamon-3.9-20220219-win64_setup.exe

Launched within a terminal and it ends without any output within a couple of seconds:
C:\Program Files\Nagstamon\Nagstamon.exe

I didn't find any arguments to use with the command line to make it verbose (https://nagstamon.de/documentation) :(

**Comment by HenriWahl** [comment]
Would be interesting if this is Icinga specific or generally a problem.

**Comment by HenriWahl** [comment]
I could not start the binary too - seems to be a problem with the build and not only with Icinga.

**Comment by HenriWahl** [comment]
Doesn't even start for me on fresh Windows 10 with Python 3.9 and all requirements installed:
```
PS C:\Users\Henri\Desktop\Nagstamon> py.exe .\nagstamon.py
[Errno 2] No such file or directory: 'C:\\Users\\Henri\\.nagstamon\\nagstamon.pid'
Traceback (most recent call last):
  File "C:\Users\Henri\Desktop\Nagstamon\nagstamon.py", line 45, in <module>
    from Nagstamon.QUI import (APP,
  File "C:\Users\Henri\Desktop\Nagstamon\Nagstamon\QUI\__init__.py", line 61, in <module>
    from Nagstamon.Servers import (SERVER_TYPES,
  File "C:\Users\Henri\Desktop\Nagstamon\Nagstamon\Servers\__init__.py", line 36, in <module>
    from Nagstamon.Servers.Nagios import NagiosServer
  File "C:\Users\Henri\Desktop\Nagstamon\Nagstamon\Servers\Nagios.py", line 20, in <module>
    from Nagstamon.Servers.Generic import GenericServer
  File "C:\Users\Henri\Desktop\Nagstamon\Nagstamon\Servers\Generic.py", line 60, in <module>
    import gssapi.raw.cython_converters
  File "C:\Python39\lib\site-packages\gssapi\__init__.py", line 29, in <module>
    import gssapi._win_config  # noqa
  File "C:\Python39\lib\site-packages\gssapi\_win_config.py", line 89, in <module>
    configure_windows()
  File "C:\Python39\lib\site-packages\gssapi\_win_config.py", line 85, in configure_windows
    error_not_found()
  File "C:\Python39\lib\site-packages\gssapi\_win_config.py", line 49, in error_not_found
    raise OSError(
OSError: Could not find KfW installation. Please download and install the 64bit Kerberos for Windows MSI from https://web.mit.edu/KERBEROS/dist and ensure the 'bin' folder (C:\Program Files\MIT\Kerberos\bin) is in your PATH.
```

**Comment by HenriWahl** [comment]
I modified the build process so there is no gssapi anymore involved. Can you try if the latest build (with the same old name) works?

**Comment by lordtaki** [comment]
Latest build works :)

**Comment by HenriWahl** [comment]
Thanks. Whatever causes gssapi to get included. Hopefully Kerberos login will still work then.
