### ISSUE TITLE
Nagstamon 3.9 fails to launch on Win11.

### ISSUE THREAD

**Issue by scar4me** [HenriWahl/Nagstamon#788]
Nagstamon-3.6.0 x64 runs perfectly fine.
But 3.9 x64 doesn't launch, ad doesn't generate any errors.

**Comment by HenriWahl** [comment]
Are you able to run it from sources as described on https://nagstamon.de/documentation#requirements? This way some error output in a console window could help to understand.

**Comment by HenriWahl** [comment]
I can confirm that 3.9-20211116 doesn't start on Windows 11. Did you try the latet stable - 3.8? This version did run.

**Comment by scar4me** [comment]
Yes, 3.8.0 stable release does run fin on Win11.

**Comment by HenriWahl** [comment]
So might this help you for this time?

**Comment by scar4me** [comment]
Yes, I am currently using 3.8.0 release.
