### ISSUE TITLE
Feature request: change user-agent

### ISSUE THREAD

**Issue by Mika56** [HenriWahl/Nagstamon#791]
Hi,

Nagstamon uses a fixed User-Agent which is `Nagstamon/<version>/<ostype>`.
For some false reasons, our provider blocks Nagstamon and uses the User-Agent to detect it.

It would be nice to be able to either check a "Simulate real user agent" box, or a text field in which we can specify the user agent.
This option could be per server or global, depending on what seems more logical to the community.

**Comment by HenriWahl** [comment]
This looks like a very special edge case - did you contact your provider about this?
