### ISSUE TITLE
ValueError invalid literal for int() with base 10

### ISSUE THREAD

**Issue by FrankyM** [HenriWahl/Nagstamon#792]
Hi,
with version 3.8.0 i got this error on one pc:

**ValueError invalid literal for int() with base 10: b'\x00\x00\x00\x00'**

I have tried to delete the config and made a new config but with the same result.
On a second pc (both on Windows 10 20H2) it's working.

3.6.0 is working fine, 3.9-20211208 did not start without any messages.

Best regards
Frank

**Comment by HenriWahl** [comment]
Hi, can you run it from source to find out where the error occurs? See https://nagstamon.de/documentation#requirements for requirements.

**Comment by FrankyM** [comment]
Hi Henri,
thanks for reply. Sorry i can't do that on this machine. Apart from that, i'm not a developer and not familiar to python. If there is no other way to debug that, i will stay at version 3.6.0.
Frank

**Comment by HenriWahl** [comment]
What monitoring server do you use Nagstamon with?

**Comment by FrankyM** [comment]
Nagios Core Version 3.5.1

**Comment by HenriWahl** [comment]
Even harder to debug if it works on another machine... Honestly no idea.
Isn't the Nagios version pretty ancient anyway?

**Comment by FrankyM** [comment]
Hi Henry,

> Even harder to debug if it works on another machine... Honestly no idea.
Yes i know. No problem, i can stay at 3.6.0.

> Isn't the Nagios version pretty ancient anyway?
Yes it is  ;-)

Best regards
Frank
