### ISSUE TITLE
Nagstamon 3.8.0 gets killed on startup on BigSur 11.6

### ISSUE THREAD

**Issue by cjidboon94** [HenriWahl/Nagstamon#799]
System: macOS Big Sur 11.6
Nagstamon version: 3.8.0

Hi, I just downloaded Nagstamon to try it out. Tried installing it both via home-brew and via the Dmg. 
When trying to open the app, nothing appears.
Then I tried to start Nagstamon from the terminal, I just get the message `Killed : 9`.
Not sure how to proceed.

**Comment by cjidboon94** [comment]
Never mind. Just had to open it via security & privacy

**Comment by 459below** [comment]
Got this too. It is somewhat confusing. Maybe this should be in documentation.
<img width="780" alt="Screenshot 2022-08-31 at 12 56 01" src="https://user-images.githubusercontent.com/11325631/187663421-56cd4a64-1e60-4a7e-a4ee-67666e21f54b.png">

**Comment by HenriWahl** [comment]
Good idea.

Any volunteers for adding it to https://github.com/HenriWahl/nagstamon-jekyll ?
