### ISSUE TITLE
PKCS#11 authentication for Icinga

### ISSUE THREAD

**Issue by akrus** [HenriWahl/Nagstamon#8]
Hi,

Is it possible to implement PKCS#11 client certificate authentication in Icinga? We're using this to authenticate a client.

cgi.cfg has the option for this:
use_ssl_authentication=1

**Comment by wschlich** [comment]
Hi,

I would also require nagstamon to support SSL/TLS client certificate authentication, as the Icinga server I want to monitor using nagstamon requires this kind of additional transport layer authentication.

Cheers,
Wolfram

P.S.: the issue subject should be renamed to "SSL/TLS client certificate authentication", as it doesn't have anything to do with PKCS#11.

**Comment by wschlich** [comment]
P.P.S.: the aNag android app introduced client certificate authentication after I asked Damien Degois whether he could implement it: https://damien.degois.info/android/aNag/docnfaq#clientcertificateauth :)

See http://bugs.python.org/issue3466 for a possible solution for urllib2:
--8<-- snip --8<--
In 3.2, you can instantiate a HTTPSHandler with a custom SSLContext, on which you can load your client cert:
http://docs.python.org/dev/library/urllib.request.html#urllib.request.HTTPSHandler
http://docs.python.org/dev/library/ssl.html#ssl.SSLContext.load_cert_chain
--8<-- snap --8<--

**Comment by akrus** [comment]
Well, initial request was actually regarding PKCS#11 as we're using hardware security tokens (like YubiKey) to authenticate and have no access to certificate itself.

**Comment by HenriWahl** [comment]
Nagstamon 2.0 uses the famous Requests module for all HTTP(S)-stuff which according its documentation should easily be able to use cerificates. Let's see, I am still involved in the Qt5 port. After this task I will take care of feature enhancements like this.

Looks like there soon will be a beta release.
