### ISSUE TITLE
Feature Request - Icingaweb2 Dashboards

### ISSUE THREAD

**Issue by EmmaTinten** [HenriWahl/Nagstamon#800]
We would like to configure dashboards as source which are configured in Icingaweb2. Only hosts, services etc. shown on the configured dashboard should be visible in Nagstamon.

Entering the dashboard URL in the settings leads to an authentication error while using the icingaweb2-URL works.

**Comment by HenriWahl** [comment]
Any idea how? Pull requests are welcome :-)

**Comment by EmmaTinten** [comment]
Maybe import the settings of a dashboard (stored in the URL) and create filter of them? This should allow multiple host / service filters.

**Comment by HenriWahl** [comment]
Until someone tries to implement this I will close this issue as there is no solution right now.
