### ISSUE TITLE
Repo for Fedora 36, please?

### ISSUE THREAD

**Issue by Fonant** [HenriWahl/Nagstamon#810]
Just updated to Fedora 36, but there is no repo for this version.

Working: https://nagstamon.de/repo/fedora/35/repodata/repomd.xml
Not found: https://nagstamon.de/repo/fedora/36/repodata/repomd.xml

Thanks!

**Comment by HenriWahl** [comment]
It is not in repo yet but already available at https://github.com/HenriWahl/Nagstamon/releases.
