### ISSUE TITLE
Display issues on mobile

### ISSUE THREAD

**Issue by TechnologyClassroom** [HenriWahl/Nagstamon#817]
I tested Nagstamon 3.8 on the Pinephone Pro with Mobian and the Phosh desktop environment which is based on GNOME.  These are my findings.  Hopefully, these notes and screenshots will be helpful to you or others developing on Pinephone or Librem 5.

The default screen resolution is 720x1440 when vertical and 1440x720 when horizontal.

Upon first boot, I was able to easily use the wizard to setup a connection to a Nagios server.  This is not pictured.

The status window displays and I can scroll down to see a brief overview of alerts.  I cannot scroll to the right to see the `Status Information` column.  I cannot access the settings from this view.  Username, server, and domain information is redacted from screenshots.

![01-vertical-view-redacted-720x1440](https://user-images.githubusercontent.com/14501791/176343807-4860ce03-e036-408c-93b8-2064a07b9ee3.png)

If I unlock orientation, I can rotate the screen.  The view does not snap to a horizontal view automatically.  I played around with it and if I tap on the `Go to monitor...` drop down, sometimes it will fill the screen.

![02-horizontal-view-redacted-1440x720](https://user-images.githubusercontent.com/14501791/176343808-f3e04180-c704-4807-a187-5b0e329ae297.png)

Once the screen is wide, the settings menu can be accessed.  Changing the order of the first row of options by moving the sandwich menu between the version number and the `Go to monitor...` drop down would make all options available to vertical and horizontal views.

![03-horizontal-view-expanded-redacted-1440x720](https://user-images.githubusercontent.com/14501791/176343810-a17bdbe3-47c8-4f22-9051-f90ca2cd2c25.png)

The settings menus mostly display and are mostly functional.  I had to rotate back and forth between vertical and horizontal to see some of the entries.  Scrolling is unavailable so not everything is visible.  Entering filter text was the most difficult task as the on-screen keyboard would cover the text box.  You could read or type, but not both.  I ended up manually creating the `$HOME/.nagstamon/nagstamon.conf` file to initially write the filter line before I learned the trick to expand the horizontal view to access the settings menu.

The buttons at the bottom of the screen to Save or Cancel below the view of the screen.  The buttons are out of view on my laptop as well.  Closing the window does not save the settings so there is no apparent way to save to the user.  A workaround is to open the `Server` tab, tap on the `Update interval` text box, open the on-screen keyboard, and press the enter key.

![04-vertical-settings-720x1440](https://user-images.githubusercontent.com/14501791/176343812-2f088bc7-c0ec-4727-aec5-db228b9a4e45.png)
![05-horizontal-settings-1440x720](https://user-images.githubusercontent.com/14501791/176343813-77c8a278-a453-4800-8d27-03feefe95a3e.png)

Sounds play just like when using the desktop.  The sounds seem to ignore the Phosh preferences and play even when the phone is set to silent.  This is probably an upstream bug rather than nagstamon issue, but I have not traced where the issue lies yet.  I would have to stop Nagstamon or disable sound in the settings before going to bed, entering a meeting, or taking a phone call.  Rotate > Go to monitor > tap on server > tap > Settings > Uncheck `Enable sound`.

~~Desktop notifications do not interact with the notification system of Phosh so the only hint is the sound that plays.  My settings were not being saved when I thought they were.~~  Desktop notifications do display in the notifications after changing the settings, but notifications are just the count of alerts in various levels.  The custom notifications could make these useful, but currently the variables do not work.  See https://github.com/HenriWahl/Nagstamon/issues/566

Overall, not very useful at this point in time on Mobian due to sound issues, lack of notification options, and an inability to see the `Status Information` column.  In general, nagstamon does work better than many applications that I have tested.

Reproduce: If you want to try to work through these issues and do not have a Pinephone or Librem 5, Purism made a [virtual machine image](https://developer.puri.sm/Librem5/Development_Environment/Boards/qemu.html) that should be similar environment to what I showed.  Purism's PureOS is also Debian based and uses Phosh.  After configuring the system, open a terminal and run `sudo apt update && sudo apt install -y nagstamon` or open the GNOME Software app and install Nagstamon.  To close the terminal or Software app, tap or click on the `^` icon at the bottom of the screen and swipe up or click and drag up while holding onto the window that you want to close.  Scroll down to the bottom and tap on the `Show All Apps` button.  Find Nagstamon in the list to start.

Edit: Changed notes about saving settings with a workaround.

Edit: Expanded notification and sound notes.

**Comment by HenriWahl** [comment]
Hi there - nice to see it runs on mobile too but I fear becaue this is such a small niche I won't find time to look at it deeper. Maybe things will get better wit Qt6 regarding the changed display orientation.

Anyway any contribution is welcome, so if you find out how to fix things let me know.

**Comment by HenriWahl** [comment]
Nothing new here...
