### ISSUE TITLE
Nagstamon-3.9-20220626-win64 - PB with debug mode

### ISSUE THREAD

**Issue by BenoitPoulet** [HenriWahl/Nagstamon#821]
Hello,

I tried to enable debug mode and debug to file.
When a launch Nagstamon the debug file is created but never filled.

I tried to lauch Nagstamon from a terminal (Powershell and CMD.exe), and i don't have the debug in in the console.

Log file location : C:\Users\my.user\nagstamon.log

OS : Windows 10

Regards

**Comment by nona00** [comment]
I have the same issue with Nagstamon-3.9-20220707-win64

Log is empty.

And when the debug log is activated, Nagstamon freezes at exit. It has to be killed by task manager

![nagstamon_log](https://user-images.githubusercontent.com/3192606/179210863-ac83377e-0a42-4b84-adec-389332a2cf7a.PNG)

**Comment by BenoitPoulet** [comment]
PB has been fixed. Checked at the date 22 August.
