### ISSUE TITLE
nagstamon stable repository for Fedora is dead

### ISSUE THREAD

**Issue by iovcho** [HenriWahl/Nagstamon#832]
root@Vivobook ~# wget https://nagstamon.de/repo/fedora/nagstamon.repo -O /etc/yum.repos.d/nagstamon.repo
root@Vivobook ~# dnf search nagstamon
nagstamon                                                                                                                                                                                                    98 kB/s | 9.4 kB     00:00    
Errors during downloading metadata for repository 'nagstamon':
  - Status code: 404 for https://nagstamon.de/repo/fedora/36/repodata/repomd.xml (IP: 185.199.108.153)
Error: Failed to download metadata for repo 'nagstamon': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: nagstamon
Last metadata expiration check: 0:07:39 ago on 15.08.2022 (пн) 17:50:52.
No matches found.

**Comment by HenriWahl** [comment]
I see - thanks for the hint. Maybe a valid workaround is to use the latest repo?

**Comment by HenriWahl** [comment]
Please check afain - should be fixed now
