### ISSUE TITLE
Feature request: Use (Optionally) Windows Certificate store

### ISSUE THREAD

**Issue by GertjanBijl** [HenriWahl/Nagstamon#849]
Having a group of about 100 people using Nagstamon on CheckMK with a certificate signed by our own CA, we would really like to have the option to use the (centrally managed) Windows Certificate store (or built-in store in general, but we primarily have Windows Clients) instead of the certifi store. As we use the distributed binary we cannot add a certificate to the certifi store, and having to distribute our CA-certificate as a file to the clients and helping everyone to configure Nagstamon correctly is a hassle. 
It would be really, really nice if pip-system-certs was compiled into the binary for Windows, but maybe also for other OS'es to support the native OS Certificate store.

I've seen the issues created in the 'requests' project regarding CA support, but they seem to be stuck in some principle war for 6 years now, so I don't think they will solve this.

**Comment by HenriWahl** [comment]
Sounds great. Does this work in all OSs?
Could you create a pull request?

**Comment by GertjanBijl** [comment]
I've only tested it on Windows for now and that works like a charm. All it does is basically clearing the ca_certs, nothing Windows-specific is being performed:
````python

        # By default Python requests uses the ca_certs from the certifi module
        # But we want to use the certificate store instead.
        # By clearing the ca_certs variable we force it to fall back on that behaviour (handled in urllib3)
````

One issue I stumbled upon: https://gitlab.com/alelec/pip-system-certs/-/issues/11. Since PyInstaller is used by Nagstamon, this means this might be an issue, but in https://gitlab.com/alelec/pip-system-certs/-/issues/7 there seems to be a workaround. I'm not very familiar with PyInstaller (I'm a sysadmin, not a developer), so I'm not sure how to test this.

**Comment by HenriWahl** [comment]
Hi @GertjanBijl ,
I tested your last proposal and found a major problem there. I tested with a monitoring server which uses a valid LetsEncrypt certificate. As soon as I install `pip-system-certs` package I get this error when running Nagstamon:

```bash
requests.exceptions.SSLError: HTTPSConnectionPool(host='redacted.host.name', port=443): Max retries exceeded with url: /cmk/check_mk/view.py?view_name=nagstamon_hosts&output_format=python&lang=&limit=hard&is_host_acknowledged=-1&is_service_acknowledged=-1&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1&host_scheduled_downtime_depth=-1&is_in_downtime=-1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))
```

This does not happen if this module is not installed. I fear if there is no other solution I cannot use this mechanism because I am sure there are more servers out there which get LetsEncrypt certificates.

**Comment by HenriWahl** [comment]
You could test this in your setup with https://tls.test.nagstamon.de/ as server which is certified by LetsEncrypt. This is no monitoring server but it should show you the same error I got.

**Comment by GertjanBijl** [comment]
I finally had the time to test, but I can connect to the _tst.test.nagstamon.de_ server perfectly fine, without SSL errors, while I'm also able to connect to the internally signed URL's. Are you testing on Windows, Linux or some other OS?
The Root-CA in use is valid since 2015, and the Sub-CA since 2020, so either you are testing on a very old system, or there is some other difference between my computer and yours. 
Note that also [SSLLabs](https://www.ssllabs.com/ssltest/analyze.html?d=tls.test.nagstamon.de&hideResults=on) is not sure about this URL, because I get a 'Warning: Inconsistent server configuration' message when testing this page. It might have something to do with the IPv6 address, since that doesn't seem to work properly.

**Comment by HenriWahl** [comment]
@GertjanBijl sorry for the late reply. I tested on Windows 10.

**Comment by HenriWahl** [comment]
I will try on a fresh Windows again.

**Comment by HenriWahl** [comment]
Please try test release https://github.com/HenriWahl/Nagstamon/releases/download/latest/Nagstamon-3.11-20230205-win64.zip or https://github.com/HenriWahl/Nagstamon/releases/download/latest/Nagstamon-3.11-20230205-win64_setup.exe where the mentioned changes from https://pypi.org/project/pip-system-certs/ are applied.

Would be nice if you could find out if it works with custom certificate as well as with global one like from LetsEncrypt.

**Comment by HenriWahl** [comment]
@trcmd9000 @GertjanBijl I tested today and it worked surprisingly well. I think I can merge this into master branch.

**Comment by trcmd9000** [comment]
Hey @HenriWahl, thanks for integrating this. I can confirm it works. Well done :)
