### ISSUE TITLE
Latest build (03/10/2022) doesn’t start

### ISSUE THREAD

**Issue by BenoitPoulet** [HenriWahl/Nagstamon#850]
Hello

The build of today do not start successfully, the process is spawning in the Windows’s process list, and die some seconds after.

No output at all even launched in a terminal.

Regards.

**Comment by BenoitPoulet** [comment]
No error from sources, the app is starting as usual (my fork is up2date)

**Comment by HenriWahl** [comment]
At least I can confirm this new behavior. 🤯

**Comment by HenriWahl** [comment]
The automatic build grabbed the some hours ago released PyQt 6.4.0 which apparently crashes on Windows. I hardcoded PyQt 6.3.1 and now it works again.

**Comment by HenriWahl** [comment]
Please check latest build.

**Comment by BenoitPoulet** [comment]
Works perfectly. Tky.
