### ISSUE TITLE
[Feature Request] Support for Bearer Auth

### ISSUE THREAD

**Issue by ignisanulum** [HenriWahl/Nagstamon#855]
Would it be possible to add an additional authentication type "[Bearer](https://datatracker.ietf.org/doc/html/rfc6750#section-2.1)"? This would allow us accessing OAuth 2.0-protected resources by the use of a static API token.

I assume this would be fairly simple (following the [mockup ](https://github.com/HenriWahl/Nagstamon/issues/836#issuecomment-1221313398) by @hunsbea) as only the HTTP auth header would need to be changed from `Authorization: Basic $base64string` to `Authorization: Bearer $token`, compared to Basic auth.

This probably also relates to [this request](https://github.com/HenriWahl/Nagstamon/issues/807) as Prometheus (or for that purpose, any other monitoring system) is often secured by some form of token based auth if deployed on Kubernetes.

**Comment by HenriWahl** [comment]
This sounds interesting.

Right now we are preparing the latest stable release 3.10 - this feature could go into the next testing. If you provide a pull request, this might come to 3.10 already.

**Comment by HenriWahl** [comment]
Closed due to merge of #858
