### ISSUE TITLE
Update to v3.10.0 not working

### ISSUE THREAD

**Issue by Ahlen76** [HenriWahl/Nagstamon#860]
Hi
I just update from v3.8.0 to v3.10.0. When Nagstamon startup I can view the OK view during 1-2 seconds. After that the process die. We are using OP5 Monitor and I'm sorry to tell that v3.10.0 doesn't work for us.

**Comment by Ahlen76** [comment]
I used the install package Nagstamon-3.10.0-win64_setup.

**Comment by HenriWahl** [comment]
Bad news... Are you able to run Nagstamon from source in a terminal windows to get some crash output?

**Comment by Ahlen76** [comment]
Hi
I'll guess this will help. It's looks like it is the new DDL file. But if you just send me back a quick guide I'll can run in terminal... if you need more info.

Log Name:      Application
Source:        Application Error
Date:          2022-10-28 07:24:33
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      LC11020.corp.lan
Description:
Faulting application name: Nagstamon.exe, version: 0.0.0.0, time stamp: 0x635afee7
Faulting module name: Qt6Core.dll, version: 6.3.1.0, time stamp: 0x6298c2d2
Exception code: 0xc0000409
Fault offset: 0x00000000000103b8
Faulting process id: 0x46e8
Faulting application start time: 0x01d8ea8d8b97375a
Faulting application path: C:\Program Files\Nagstamon\Nagstamon.exe
Faulting module path: C:\Program Files\Nagstamon\PyQt6\Qt6\bin\Qt6Core.dll
Report Id: d0a38740-ddc8-4c90-978e-f2e8ff0121cb
Faulting package full name:
Faulting package-relative application ID:
Event Xml:
<Event xmlns=http://schemas.microsoft.com/win/2004/08/events/event>
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-10-28T05:24:33.5480015Z" />
    <EventRecordID>56231</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LC11020.corp.lan</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Nagstamon.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>635afee7</Data>
    <Data>Qt6Core.dll</Data>
    <Data>6.3.1.0</Data>
    <Data>6298c2d2</Data>
    <Data>c0000409</Data>
    <Data>00000000000103b8</Data>
    <Data>46e8</Data>
    <Data>01d8ea8d8b97375a</Data>
    <Data>C:\Program Files\Nagstamon\Nagstamon.exe</Data>
    <Data>C:\Program Files\Nagstamon\PyQt6\Qt6\bin\Qt6Core.dll</Data>
    <Data>d0a38740-ddc8-4c90-978e-f2e8ff0121cb</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by Ahlen76** [comment]
We are running OP5 Monitor v8.4.1.

**Comment by HenriWahl** [comment]
I am only able to test with op5Monitor 9.2 and there it runs flawlessly. Even on Windows.

Did you get any output with the debugging version?

**Comment by HenriWahl** [comment]
I created a new debugging version which keeps the console window open in case of crash. Please download https://github.com/HenriWahl/Nagstamon/releases/download/latest/Nagstamon-3.11-22021104-win64_debug.zip and run `nagstamon-debug.bat` to get some more output.

**Comment by HenriWahl** [comment]
@Ahlen76 according to your log you did not configure the monitoring server type correctly. It is set to Centreon which does not match your used Op5.

**Comment by Ahlen76** [comment]
@HenriWahl
You can close this ticket, thanks for your help. I have been informed that version 3.10.x works for my colleagues on OP5 v8.x. I suspect that it is a Qt package that I installed to VS Code that is causing my shady problems. I get to troubleshoot and fix my problems as it is not due to Nagstamon.
