### ISSUE TITLE
Nagstamon.exe v3.10.0 detected as Troyen by McAffee

### ISSUE THREAD

**Issue by mbl-35** [HenriWahl/Nagstamon#863]
Detection name: Artemis!A507C5F888A4
Was not the case with v3.8.0 ..
thanks :)

**Comment by HenriWahl** [comment]
Do you have a way to flag this as false positive at your AV vendor?

virustotal.com had not major problems when we tested there before.

**Comment by mbl-35** [comment]
Hello @HenriWahl ,

First I'd like to thanks you for all this behaviour .. I am using Nagstamon for years ... 

I'm not able to set any configuration to McAfee since I do not have priveleges on my compagny desktop.
I'm installing Nagstamon via scoop (portable mode) with bucket defined in my personal repo mbl-35/scoop-srsrns on github.

**Comment by HenriWahl** [comment]
Can you send the exact error message here or by mail?

**Comment by Optimaximal** [comment]
Just had the same issue...

`[USER] ran [USER]\AppData\Local\Temp\is-J7O4O.tmp\Nagstamon-3.10.0-win64_setup.tmp, which attempted to access C:\Program Files\Nagstamon\Nagstamon.exe. The Trojan named Artemis!A507C5F888A4 was detected and deleted.`

GTI, formerly Artemis, is their heuristic analysis product.

You might have to submit the false positive here - https://www.mcafee.com/support/?articleId=TS103032&page=shell&shell=article-view

**Comment by HenriWahl** [comment]
They told me they allowlisted it meanwhile.

**Comment by mbl-35** [comment]
I confirm on w11, nagstamon v3.10.1. Thanks
