### ISSUE TITLE
Centreon 22.10 - key error "Flapping"

### ISSUE THREAD

**Issue by arthur-lbchn** [HenriWahl/Nagstamon#866]
Hey guys,

I recently updated Centreon to 22.10 and getting key error "Flapping".

Nagstamon 3.10

I tried to enable Debug to file, but no records at all (maybe doing something wrong)

Could someone please assist?

**Comment by HenriWahl** [comment]
@BenoitPoulet any hint?

**Comment by HenriWahl** [comment]
@arthur-lbchn if you use Windows you could use https://github.com/HenriWahl/Nagstamon/releases/download/latest/Nagstamon-3.10.0-win64-debug.zip for more detailed debugging. On Linux just run `nagstamon` in a terminal for more output.

**Comment by arthur-lbchn** [comment]
@HenriWahl I've discovered that the error occurs if Centreon has services with UNKNOWN status. Once I resolved them and they reverted to OK, everything works as expected.

But I'm pretty sure, that I saw UNKNOWN services in Nagstamon before, so most likely Centreon changed something on their side.

**Comment by arthur-lbchn** [comment]
@HenriWahl I've debugged it a bit more and seems like the requests are coming to 22.04 link in API

https://mycentreondomain.com/centreon/api/v22.04/monitoring/resources?limit=0
https://mycentreondomain.com/centreon/api/v22.04/monitoring/resources?types=["host"]&statuses=["WARNING","DOWN","CRITICAL","UNKNOWN"]&limit=9999
https://mycentreondomain.com/centreon/api/v22.04/monitoring/resources?types=["metaservice","service"]&statuses=["WARNING","DOWN","CRITICAL","UNKNOWN"]&limit=9999

Maybe that's the reason

**Comment by arthur-lbchn** [comment]
@HenriWahl Hey, sorry for bothering you, have you had a chance to take a look into the problem? Super critical to us to have proper monitoring for our services since Nagstamon is used by big team for years ;(

**Comment by HenriWahl** [comment]
@arthur-lbchn sorry I couldn't but @BenoitPoulet might help further. I know there were changes in the API, even between 22.04 and 22.10.

**Comment by arthur-lbchn** [comment]
@HenriWahl I've finally found out the error
  File "Nagstamon\Servers\Centreon\CentreonAPI.py", line 426, in _get_status
KeyError: 'flapping'

So I forked your project and build it with the line 426 commented (Centreon doesn't have flapping enabled by default and we don't actually care)

Everything works properly for me now ;) Thanks for your help.

**Comment by HenriWahl** [comment]
@arthur-lbchn thanks this might be of interest to get into upstream again.

If flapping is not enabled by default it is still an option to be enabled?

**Comment by arthur-lbchn** [comment]
@HenriWahl yes, it's under Configuration  >  Pollers  >  Engine configuration

![image](https://user-images.githubusercontent.com/9682681/199758838-cb3993dc-6d9e-4fed-a147-afe5cdcec6b8.png)

**Comment by HenriWahl** [comment]
Please check latest build 3.11-20221103 which applies a patch based on yours.

**Comment by arthur-lbchn** [comment]
@HenriWahl thank you, everything works. appreciate all your efforts.

**Comment by BenoitPoulet** [comment]
Sorry i was very busy theses days, thanks for the fix !
