### ISSUE TITLE
Nagstamon 3.10.1 flagged as malicious file

### ISSUE THREAD

**Issue by glipscomb** [HenriWahl/Nagstamon#871]
File 'nagstamon.exe' [105D4...8F62A](https://cbacsys.csu.edu.au/file-details.php?antibody_id=602037) was identified by Carbon Black File Reputation as a malicious file.

Also by virustotal.com
https://www.virustotal.com/gui/file/105d4db17c17ae56bd8726dfd66366ef4be7f42de60dbb658403d6c89c18f62a
8 security vendors and no sandboxes flagged this file as malicious

**Comment by HenriWahl** [comment]
@glipscomb are you able to mark it as false positive in your Carbon Black File Reputation?

As long as the major vendors are fine with I consider it OK. If some user of one if the red entries on virustotal.com has a problem it still might be solved.

**Comment by glipscomb** [comment]
Hi Henri,

VMware Carbon Black have responded to our request saying that the file nagstamon.exe has been classified as not trusted  due to the Publisher not present and Certificate not present

Regards
Gary

Gary Lipscomb
Technical Officer, Systems
IT Infrastructure & Security | Division of Information Technology

**Comment by HenriWahl** [comment]
Can you find out how exactly this requirements could be fulfilled? Honestly I don't know.

**Comment by glipscomb** [comment]
Hi Henri,

Have a read here

https://codesigningstore.com/how-to-sign-executable-files-with-code-signing-certificate
https://codesigningstore.com/microsoft-authenticode-certificates
https://learn.microsoft.com/en-us/windows/win32/seccrypto/signtool

regards

Gary

Gary Lipscomb
Technical Officer, Systems
IT Infrastructure & Security | Division of Information Technology

**Comment by HenriWahl** [comment]
@glipscomb thanks for the hints.
Right now I do not own a software developers certificate and I fear the testing ones which can be created with `New-SelfSignedCertificate` won't be of any use. Without such a certificate there is no signing, of course.
The same problem exists for years on macOS where every install of Nagstamon is causing warnings.

Maybe you could run Nagstamon from source with Python to check if there would be trouble too?

**Comment by stephan-schuster** [comment]
Just for your information: Windows Defender also blocks the installation. I tried downloading the zip file and copied it into the program folder, but then starting of nagstamon is blocked

**Comment by HenriWahl** [comment]
Interesting - according to https://www.virustotal.com/gui/file/105d4db17c17ae56bd8726dfd66366ef4be7f42de60dbb658403d6c89c18f62a it isn't.

Maybe you could indicate it as false positive at https://www.microsoft.com/en-us/wdsi/filesubmission/?

**Comment by HenriWahl** [comment]
@stephan-schuster I submitted the file to Microsoft too but have no 'detection name' because it is not detected for me. So if you could report it too with all infos this might help.

**Comment by stephan-schuster** [comment]
@HenriWahl I've tried, but after I have installed nagstamon I can't reproduce the error. MS Defender doesn't complain anymore about the file and I dont see any information about the whitelisting under Virus & Threatprotection. But without the "detection name" I'm not able to submit the file. Perhaps the whitelisting during install solved the problem already...
