### ISSUE TITLE
GNOME3: GNOME-Flashback needs DESKTOP_CINNAMON workaround enabled as well

### ISSUE THREAD

**Issue by z1atk0** [HenriWahl/Nagstamon#876]
Hi,

It looks like recent versions of (Qt and/or?) GNOME3 Flashback need the `DESKTOP_CINNAMON` workaround enabled as well to display the status popup window in its proper location, at least under certain circumstances ... like, say, a slightly unusual dual-monitor setup. :slightly_smiling_face: 

In my setup the **_right_** monitor is the primary display, **_not_** the left. So all my panels, menus, notification areas etc. are on the right monitor as well. As of recently (unfortunately I don't know the exact point in time, so I don't know what exactly was updated to cause this quirk), Nagstamon started to show its status popup window at the bottom of the **_left_** monitor all of a sudden, instead of above the panel bar on the right one. As soon as I set `DESKTOP_CINNAMON = True` hardcoded in `Config.py`, the status popup window appears in its proper place again.

Note that the systray area hosting the Nagstamon icon is on the bottom right. With `DESKTOP_CINNAMON = False`:

![image](https://user-images.githubusercontent.com/12568948/202195285-2af7ed56-a5f7-4e1e-b48c-9488279fdc9a.png)

With `DESKTOP_CINNAMON = True`:

![image](https://user-images.githubusercontent.com/12568948/202195570-1a2c2e1a-ff58-4e13-b190-8b0dcb51dd9d.png)

I'm not sure whether it would make more sense to add a few more conditionals to `Config.py` (relevant environment variable candidates would be any of `DESKTOP_SESSION="gnome-flashback-metacity"`, `GDMSESSION="gnome-flashback-metacity"`, `XDG_CURRENT_DESKTOP="GNOME-Flashback:GNOME"`, `XDG_SESSION_DESKTOP="gnome-flashback-metacity"`), or simply have an additional config widget in `Settings => Display` labelled `[x] Enable GNOME/dual-screen related popup positioning fix` (similar/close to the `[x] Use offset to correct position problems` widget). The latter would probably need more effort to implement, but would be convenient to have in case more use cases pop up in the future that can be fixed this way.

System specs, if needed (if you need to know anything else just let me know): `Slackware 15.0 64bit`, `GNOME3 3.46` (Flashback session), `Python 3.9.15`, `Qt 5.15.7/6.4.0` with matching `PyQt` versions, and `Nagstamon 3.10.0/3.10.1` (any combination of the latter two components shows the same behaviour).

Thanks,
Thomas

**Comment by HenriWahl** [comment]
@z1atk0 thanks for the hint, will add it in the next days

**Comment by MatKra84** [comment]
Linux Mint 21 Cinnamon. To display popup window on the same monitor as status bar also DESKTOP_CINNAMON = False.

**Comment by HenriWahl** [comment]
@MatKra84 so in your case the fix is the opposite of the solution for @z1atk0 's problem?

**Comment by HenriWahl** [comment]
@MatKra84 do you use Wayland or Xorg?

**Comment by HenriWahl** [comment]
@z1atk0 latest testing release has you proposed option  please check if it works as expected.
