### ISSUE TITLE
Nagstamon fails to load configuration when restored by X session manager

### ISSUE THREAD

**Issue by richardschuetz** [HenriWahl/Nagstamon#878]
If Nagstamon is automatically restored by an X session manager, it fails to load an existing configuration. It incorrectly tries to interpret the command-line arguments used by Qt's session management implementation (e.g. `/usr/bin/nagstamon -session 10d6d79b61000166902480800000014900048_1669027589_391284 -name nagstamon`) as a configuration path. As a side effect, a new configuration folder named `-session` is created in the working directory. This bug occurs starting with Nagstamon 3.10.0.

**Comment by HenriWahl** [comment]
Funny consequence of kicking out never-complete nagstacli code... Well, what effect did the session storage have before?

**Comment by richardschuetz** [comment]
With earlier versions it always looked like restoring Nagstamon was never attempted, but after testing I can now confirm that it just always silently failed whenever the session arguments were passed:

```
Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 35, in <module>
    import nagstacli  # fix crash if more than 2 args are passed - mprenditore
ModuleNotFoundError: No module named 'nagstacli'
```

So the aforementioned change regarding nagstacli only made the underlying, much older bug more obvious.

**Comment by richardschuetz** [comment]
I can confirm that Nagstamon is now successfully restored at session startup.

**Comment by HenriWahl** [comment]
👍
