### ISSUE TITLE
Nagstamon self version check does not work correctly

### ISSUE THREAD

**Issue by rafi0101** [HenriWahl/Nagstamon#879]
Hi,
I think your nagstamon self version check is not working correctly as I am on the latest stable version (v3.10.1) but it shows me there is an update available. After a short look in the repository I see the "newest" version is a pre-release. 
Could you please adjust the versions check so that it only notifies when really a new version is available?

**Comment by HenriWahl** [comment]
What exactly does it show you? What OS do you use? Where does your copy of Nagstamon come from?

The version information which is requested by Nagstamon is this file: https://github.com/HenriWahl/nagstamon-jekyll/blob/main/docs/version/stable which is rendered to https://nagstamon.de/version/stable by GitHub. Currently it just consists of '3.10.1' as intended.

**Comment by rafi0101** [comment]
Okay, shame on me. For whatever reason I used version 3.11-2202-1105 and then of course I got unstable versions updates displayed. sorry for that

**Comment by HenriWahl** [comment]
@rafi0101 no problem :+1:
