### ISSUE TITLE
Nagstamon 3.10.1 doesnt work with Centreon version 21.x

### ISSUE THREAD

**Issue by Leon30071980** [HenriWahl/Nagstamon#881]
Hi all, someone solve the problem with Centreon versione 21.x ? Other versions work fine.

"Unknown Error" is given with the 21.x version as imagine:
![image](https://user-images.githubusercontent.com/119290249/204230374-ef638dbe-2fb9-4977-b65b-8223ee80239e.png)

Can someone help us?
Or if the problem is known, can you please give me the link of the thread? 
Danke

**Comment by Leon30071980** [comment]
Here is the debug log:

DEBUG: 2022-11-29 09:23:03.148315 Saving configuration to file c:\users\cdmmon\.nagstamon\nagstamon.conf
DEBUG: 2022-11-29 09:23:03.597324 Socage FetchURL: https://151.14.34.252/centreon/api/latest/platform/versions CGI Data: None
DEBUG: 2022-11-29 09:23:03.757618 [Socage] Status code 200
DEBUG: 2022-11-29 09:23:03.757618 [Socage] Loading class API, Centreon version : 21.4
DEBUG: 2022-11-29 09:23:03.757618 Socage Created server.
DEBUG: Initializing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE53F0> for state "OK"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE5360> for state "INFORMATION"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE5480> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE5510> for state "WARNING"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE55A0> for state "AVERAGE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE5630> for state "HIGH"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE56C0> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE5750> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE57E0> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE5870> for state "DOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE5900> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt6.QtGui.QIcon object at 0x000001D8D8FE51B0>
DEBUG: 2022-11-29 09:23:04.078561 Socage FetchURL: https://151.14.34.252/centreon/api/latest/platform/versions CGI Data: None
DEBUG: 2022-11-29 09:23:04.229999 [Socage] Centreon version detected : 21.4
DEBUG: 2022-11-29 09:23:04.229999 [Socage] Centreon API version used : latest
DEBUG: 2022-11-29 09:23:04.239996 [Socage] Checking session status
DEBUG: 2022-11-29 09:23:04.239996 [Socage] Check-session, the token expire if not been used for more than one hour. Current Token = None
DEBUG: 2022-11-29 09:23:04.239996 Socage FetchURL: https://151.14.34.252/centreon/api/latest/monitoring/resources?limit=0 CGI Data: None
DEBUG: 2022-11-29 09:23:04.318774 Socage FetchURL: https://nagstamon.de/version/stable CGI Data: None
DEBUG: 2022-11-29 09:23:04.394746 Socage Check-session, Fetched JSON: {'code': 500,
 'message': 'No route found for "GET '
            '/centreon/api/latest/monitoring/resources"'}
DEBUG: 2022-11-29 09:23:04.394746 Socage Check-session, Error : , Status code : 500
DEBUG: 2022-11-29 09:23:04.394746 Socage FetchURL: https://151.14.34.252/centreon/api/latest/monitoring/resources?types=["host"]&statuses=["WARNING","DOWN","CRITICAL","UNKNOWN"]&limit=9999 CGI Data: None

**Comment by Leon30071980** [comment]
Here is the debug file:

DEBUG: 2022-11-29 09:23:03.148315 Saving configuration to file c:\users\cdmmon\.nagstamon\nagstamon.conf
DEBUG: 2022-11-29 09:23:03.597324 Test FetchURL: https://xxx.xxx.xxx.xxx/centreon/api/latest/platform/versions CGI Data: None
DEBUG: 2022-11-29 09:23:03.757618 [Test] Status code 200
DEBUG: 2022-11-29 09:23:03.757618 [Test] Loading class API, Centreon version : 21.4
DEBUG: 2022-11-29 09:23:03.757618 Test Created server.
DEBUG: Initializing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE53F0> for state "OK"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE5360> for state "INFORMATION"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE5480> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE5510> for state "WARNING"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE55A0> for state "AVERAGE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE5630> for state "HIGH"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE56C0> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE5750> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE57E0> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE5870> for state "DOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x000001D8D8FE5900> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt6.QtGui.QIcon object at 0x000001D8D8FE51B0>
DEBUG: 2022-11-29 09:23:04.078561 Socage FetchURL: https://xxx.xxx.xxx.xxx/centreon/api/latest/platform/versions CGI Data: None
DEBUG: 2022-11-29 09:23:04.229999 [Test] Centreon version detected : 21.4
DEBUG: 2022-11-29 09:23:04.229999 [Test] Centreon API version used : latest
DEBUG: 2022-11-29 09:23:04.239996 [Test] Checking session status
DEBUG: 2022-11-29 09:23:04.239996 [Test] Check-session, the token expire if not been used for more than one hour. Current Token = None
DEBUG: 2022-11-29 09:23:04.239996 Test FetchURL: https://xxx.xxx.xxx.xxx/centreon/api/latest/monitoring/resources?limit=0 CGI Data: None
DEBUG: 2022-11-29 09:23:04.318774 Test FetchURL: https://nagstamon.de/version/stable CGI Data: None
DEBUG: 2022-11-29 09:23:04.394746 Test Check-session, Fetched JSON: {'code': 500,
'message': 'No route found for "GET '
            '/centreon/api/latest/monitoring/resources"'}
DEBUG: 2022-11-29 09:23:04.394746 Test Check-session, Error : , Status code : 500
DEBUG: 2022-11-29 09:23:04.394746 Test FetchURL: [https://xxx.xxx.xxx.xxx/centreon/api/latest/monitoring/resources?types=["host"]&statuses=["WARNING","DOWN","CRITICAL","UNKNOWN"]&limit=9999](https://xxx.xxx.xxx.xxx/centreon/api/latest/monitoring/resources?types=%5b%22host%22%5d&statuses=%5b%22WARNING%22,%22DOWN%22,%22CRITICAL%22,%22UNKNOWN%22%5d&limit=9999) CGI Data: None

**Comment by BenoitPoulet** [comment]
Hello,

in 21.x you need to have access to the Realtime API, and configure Nagstamon to use user/password, not the autologin key.

Like in this capture :

![image](https://user-images.githubusercontent.com/2464712/204481382-f220ca52-ce9f-4274-9006-f52c2c928f11.png)

**Comment by Leon30071980** [comment]
> Hello,
> 
> in 21.x you need to have access to the Realtime API, and configure Nagstamon to use user/password, not the autologin key.
> 
> Like in this capture :
> 
> ![image](https://user-images.githubusercontent.com/2464712/204481382-f220ca52-ce9f-4274-9006-f52c2c928f11.png)
> 
> And you need to check the Apache's VHOST configuration and apply the configuration given by Centreon, it seems that you have a pb here. ('No route found for "GET ')

Hi Benoit, thanks for responding.
I try to flag the reach API realtime, but nothing changed (i am loging as admin, and for admin all api's are already accessible..

**Comment by BenoitPoulet** [comment]
We are using this API endpoint :

https://docs-api.centreon.com/api/centreon-web/#tag/Resource/paths/~1monitoring~1resources/get

We are using «latest» as API version,  mapped by this rules from the Apache's vhost : (latest|beta|v[0-9]+|v[0-9]+\.[0-9]+)

Is it reachable on your Centreon ?

**Comment by FredNass** [comment]
Hello Benoît, 

Undoubtedly, there's an issue with v3.10.1 (and v3.11.20221216 from nagstamon-latest) and Centreon v21.x.
Same error messages repeating again and again:

DEBUG: 2023-01-19 16:54:20.952869 [Centreon UL] Checking session status
DEBUG: 2023-01-19 16:54:20.952938 [Centreon UL] Check-session, the token expire if not been used for more than one hour. Current Token = None
DEBUG: 2023-01-19 16:54:20.953021 Centreon UL FetchURL: https://centreon.infra.univ-lorraine.fr/centreon/api/latest/monitoring/resources?limit=0 CGI Data: None
DEBUG: 2023-01-19 16:54:21.210319 Centreon UL Check-session, Fetched JSON: {'code': 500, 'message': 'A Token was not found in the TokenStorage.'}
DEBUG: 2023-01-19 16:54:21.210335 Centreon UL Check-session, Error : , Status code : 500
DEBUG: 2023-01-19 16:54:21.210346 Centreon UL FetchURL: https://centreon.infra.univ-lorraine.fr/centreon/api/latest/monitoring/resources?types=["host"]&statuses=["WARNING","DOWN","CRITICAL","UNKNOWN"]&limit=9999 CGI Data: None

I have removed ~/.nagstamon/nagstamon.conf, ran Nagtamon again and created a new configuration as per below :

![Capture d’écran du 2023-01-19 16-48-04](https://user-images.githubusercontent.com/11542051/213492900-577433ae-95b2-4844-b7e2-e79a61d25740.png)

Same again. The Authentication Basic header looks good but the server replies with a "HTTP/1.1 500 Internal Server Error" and the following message: {"code":500,"message":"A Token was not found in the TokenStorage."}

I'm using user/password (and not the autologin key. Why would that not work anymore, btw?) and API Realtime is enabled on my account.

This issue is with Fedora 37, Nagstamon 3.10 (and 3.11) and Centreon 21.10. I had no troubles at all with Fedora 36, Nagstamon 3.8 and Centreon 21.10 (same version).

Let me know if you need anything.

Regards,
Frédéric.

**Comment by BenoitPoulet** [comment]
Hello,

I will try to install a 21.10 and check, without an access to this version, it’s very hard to debug.

**Comment by FredNass** [comment]
Hey Benoît, thank you for being this quick! I can confirm that your patch works brilliant.

**Comment by HenriWahl** [comment]
@FredNass @BenoitPoulet this is now available in release 3.11-20230121.
