### ISSUE TITLE
[3.10.1] Nagstamon not working with Centreon 22.10

### ISSUE THREAD

**Issue by ASLLR** [HenriWahl/Nagstamon#888]
Hi everyone, 

i've update my centreon today to 22.10 and in the same time my nagstamon to v3.10.1. 

Now, i've an error message that's work before in 22.04 and nagstamon 3.9 : 
![image](https://user-images.githubusercontent.com/37147055/206230884-2ad39864-7f5d-4a23-879b-11a5bb3d3ff2.png)

My account have the access right to call API. The anonymous debug file is join. 
[nagstamon_ko.log](https://github.com/HenriWahl/Nagstamon/files/10177777/nagstamon_ko.log)
![image](https://user-images.githubusercontent.com/37147055/206231432-f7610cbe-cdc1-4b10-82e5-145f923ebd8f.png)

Thank in advance,

**Comment by BenoitPoulet** [comment]
Hello,

Your user must have access to the API realtime :
![image](https://user-images.githubusercontent.com/2464712/206402488-90920253-3aa7-4320-a26a-d9aad28e3e44.png)

When logged on the UI, can you access to this page ?

https://(your host)/centreon/api/v22.04/monitoring/resources?limit=0

You must have a JSON like this : 
`{"result":[],"meta":{"page":1,"limit":0,"search":{},"sort_by":{},"total":85}}`

**Comment by ASLLR** [comment]
Hello @BenoitPoulet Thank you for your answer. 

My user have the correct right : 
![image](https://user-images.githubusercontent.com/37147055/206417494-1086eacd-6d96-448e-bd59-615faf0b1d42.png)

Yes, this is the result : 
![image](https://user-images.githubusercontent.com/37147055/206417368-1c742e42-326b-49ae-86e6-550200caacd1.png)

I'm on centreon 22.10.1, i will try to update to 22.10.2 but i'dont know if i can do that rapidly...

Best regards.

**Comment by BenoitPoulet** [comment]
Ok, everything is clear now

9423 entities + Centreon 20.10.1 = disaster with the API realtime.

That’s why you got this :
TimeoutError: The read operation timed out

There is no solution but update to the 20.10.2.

**Comment by ASLLR** [comment]
@BenoitPoulet but that work before my upgrade... Nothing else change. It's an issue of code of nagstamon 3.10 to be efficient on time to call API ? Or extend the timeout ? 

Best regards

**Comment by BenoitPoulet** [comment]
@ASLLR 

"Nothing else change" + "update my centreon today to 22.10"

So you did a massive change.

Centreon 22.10.0 and 22.10.1 contains the bug who fucked the API realtime. 
You can do nothing but upgrade to 22.10.2.

**Comment by ASLLR** [comment]
Hi @BenoitPoulet 

i could update my centreon to 22.10.2 this day and this resolv my issue. Thank you for your time. 

Best regards
