### ISSUE TITLE
Installed Nagstamon version missing via winget (windows platform)

### ISSUE THREAD

**Issue by thomass4t** [HenriWahl/Nagstamon#902]
Hello,
on microsoft windows (e.g. win11) you can install and update programs via winget on command line.
With Nagstamon there seems to be an issue with the installed version.
Winget can see the new version but is unable to detect the installed version.
I tested with 3.10.1-win64 and the output of "winget upgrade --include-unknown" looks like:

Name             ID                  Version Source
-------------------------------------------------------------
Nagstamon 3.10.1 HenriWahl.Nagstamon Unknown 3.10.1    winget

Maybe the installer doesn't register the version properly(?)
The current version 3.10.1 is known but the installed version column shows "unknown".
Uninstall and fresh re-install shows the same behavior.

If further information is needed, just let me know.

Thanks! Thomas

**Comment by HenriWahl** [comment]
Can you find out how to set this version information by used installer InnoSetup?

**Comment by thomass4t** [comment]
Hello,
after installing the setup, the registry keys for the versions are missing. This can be looked up at:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{44F7CFFB-4776-4DA4-9930-A07178069517}_is1

The already existing entry within the iss-file:

```
[Setup]
AppVersion={#version}
```

should do it but I am not sure, whether the placeholder {#version} works.
All the examples I found used a #define directive.
For example : [https://stackoverflow.com/questions/27985739/use-define-and-constant-in-inno-setup](https://stackoverflow.com/questions/27985739/use-define-and-constant-in-inno-setup) 

On that page it worked like that:

```
#define AppVersion GetFileVersion('C:\MyApp.exe')

[Setup]
...
AppVersion={#AppVersion}
```

Does this information help?

**Comment by HoffmannTom** [comment]
@HenriWahl 
I can also test the setup for you, if this helps.
You could also set the {#AppVersion} to a fixed string like 1.2.3 and send a compiled version to me to narrow down the issue.
Unfortunately, I can't build the sources by myself (Python 3.9 throws an error that module platform has no attribute "dist")

**Comment by HenriWahl** [comment]
@HoffmannTom how do youu try to build it?

**Comment by HoffmannTom** [comment]
@HenriWahl 
First, I installed the dependencies with 
pip install -r build/requirements/windows.txt
When running "python setup.py install" it throws an error. 
Most likely it is caused in line 46. platform.dist() is not available in current version of platform.
https://docs.python.org/3.10/library/platform.html
dist() is available in older versions.

The older version https://docs.python.org/3.7/library/platform.html states:
"Deprecated since version 3.5, will be removed in version 3.8: See alternative like the [distro](https://pypi.org/project/distro) package."

**Comment by HoffmannTom** [comment]
Short update:
I initialized the variables in setup.py but run into the next error message.
cmd was run as administrator, so permission denied might have another reason.

The output shows:
```
C:\Anaconda3\lib\site-packages\setuptools\dist.py:530: UserWarning: The version specified ('3.11.20230126.') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
running install
C:\Anaconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Anaconda3\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Anaconda3\lib\site-packages\pkg_resources\__init__.py:122: PkgResourcesDeprecationWarning: 3.11.20230126. is an invalid version and will not be supported in a future release
  warnings.warn(
running bdist_egg
running egg_info
writing Nagstamon.egg-info\PKG-INFO
writing dependency_links to Nagstamon.egg-info\dependency_links.txt
writing top-level names to Nagstamon.egg-info\top_level.txt
reading manifest file 'Nagstamon.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'Nagstamon.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
installing package data to build\bdist.win-amd64\egg
running install_data
installing scripts to build\bdist.win-amd64\egg\EGG-INFO\scripts
running install_scripts
running build_scripts
error: [Errno 13] Permission denied: 'nagstamon'

```

**Comment by HenriWahl** [comment]
You could run nagstamon.py in directory directly. Setup install is not necessary and I do not even know if it runs in Windows.

Running build/build.py should give you a nagstamon.exe.
