### ISSUE TITLE
Feature Request - Ability to change alert sounds in Nagstamon UI

### ISSUE THREAD

**Issue by MattTheQuick** [HenriWahl/Nagstamon#903]
I know the program is just looking at warning.wav, critical.wav, and down.wav files and that these can be changed to any files you like by doing some trickery in the C:\Program Files\Nagstamon\resources folder (i.e. taking your file of choice and renaming it to match a file being looked at), but it would be neat if a section of Settings > Notifications could have a portion where you can choose specific sound files to use for alerts.

**Comment by HenriWahl** [comment]
This is already possible:
![grafik](https://user-images.githubusercontent.com/2835065/216758458-41846344-53f8-474e-8a69-a9c9f9f9a7ad.png)
