### ISSUE TITLE
Enabling Debug Log not works

### ISSUE THREAD

**Issue by winter1967** [HenriWahl/Nagstamon#906]
Hello,
for fixing a problem i want to enable debug log.

I enabled it in the Nagstamon-GUI:
-Settings
-X Debug Mode
-X Debug to file: c:\temp\nagstamon-debug.txt

But there's no debug file and nagstamon stays in the status 'Authentication problem' (this is the problem, were i want to have a debug file)

The Config file of nagstamon seems to be right:
debug_mode = True
debug_to_file = True
debug_file = c:\temp\nagstamon-debug.txt

We use nagstamon in version 3.10.1,
with IcingaDBWeb as monitor type.

**Comment by HenriWahl** [comment]
Hi @winter1967 if you can't run it in a console window there now also is a debug version for Windows which shows all errors in a console: https://github.com/HenriWahl/Nagstamon/releases/download/latest/Nagstamon-3.11-20230126-win64_debug.zip. Newer releases will also come in this debugging flavor.

**Comment by winter1967** [comment]
Thank you, it works.
