### ISSUE TITLE
macos | settings dont recognise keyboard input, when Hide Dock Icon is active

### ISSUE THREAD

**Issue by christiangierschner** [HenriWahl/Nagstamon#910]
There is still or again the problem with keystrokes going into an active textfield in the background but not in the opened settings window...

maybe set icon state on settings to be recognised by keystrokes

thanks for this awesome tool :)

**Comment by HenriWahl** [comment]
Looks difficult. According to https://github.com/AvaloniaUI/Avalonia/issues/4849 this is by macOS design. Let's see...

**Comment by HenriWahl** [comment]
@christiangierschner please try latest release https://github.com/HenriWahl/Nagstamon/releases/download/latest/Nagstamon.3.11-20230227.dmg which addresses this issue.
