### ISSUE TITLE
Ubuntu 22.10, no tray icon, Zabbix

### ISSUE THREAD

**Issue by Fjodor42** [HenriWahl/Nagstamon#914]
Attempting to start Nagstamon doesn't result in anything, except the first 3 of the following lines:

```
smo@dell-smo:~$ nagstamon
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
^CTraceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 2530, in reset
    @Slot()
KeyboardInterrupt
^CTraceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 451, in reset
    @Slot()
KeyboardInterrupt
```

^C 2 times gives the next lines, then nothing further from that.

Can be killed with `killall`.

Zabbix 5.<something>
Nagstamon 3.10 (still with 3.11-20230227)
Ubuntu Linux 22.10 (worked up until the upgrade from 22.04)
Cinnamon

Please advise.

**Comment by Fjodor42** [comment]
Just upgraded my personal machine to 22.10 and face the same problem, this time with Nagios, though.

Also, Nextcloud tray icon has gone missing in a similar way, leading me to think that this might not really be a Nagstamon problem after all, but I *would* like to find a fix/solution/explanation if anyone would be so kind.

**Comment by Fjodor42** [comment]
https://github.com/linuxmint/cinnamon/issues/11541

**Comment by HenriWahl** [comment]
Is it possible that you need some kind of indicator applet like it is needed for latest GNOME? I run an Ubuntu desktop with package `gnome-shell-extension-appindicator` to see the systray of ALL apps which support it.

**Comment by Fjodor42** [comment]
Thank you for your suggestion, @HenriWahl  - just 5 minutes ago, I discovered that the icon reappeared with a Cinnamon "soft restart", making this almost certainly a Cinnamon problem after all.

Corroborating this is the fact that I haven't noticed that a few other icons were actually also missing (and were also brought back by restarting Cinnamon).

Thank you for Nagstamon, and have a great evening :-)
