### ISSUE TITLE
Nagstamon does not start on Fedora Silverblue 37 / flatpak install

### ISSUE THREAD

**Issue by a1ad** [HenriWahl/Nagstamon#916]
Just nothing... and I don't know how to debug a flatpak app?

**Comment by HenriWahl** [comment]
@a1ad the flatpak image is very outdated and I wish I would be able to update it but I once tried and failed - see https://github.com/HenriWahl/Nagstamon/issues/789.
I fear I cannot help you there - maybe a chance for you to produce a working flatpak?

**Comment by a1ad** [comment]
No not a chance
