### ISSUE TITLE
Nagstamon and EV Observe Monitor

### ISSUE THREAD

**Issue by betourneau** [HenriWahl/Nagstamon#918]
Hi Everyone,

I'm a regular user of nagstamon and we just change our Monitor solution with a new one named EV Observe from EasyVista.

But there is no connector to this. Is there a way to work on it ? Maybe I can help to develop or give you contact with the editor ?

I hope something is possible :)

Thank you.

**Comment by HenriWahl** [comment]
Hi @betourneau ,
it would be no problem to add another monitor connector. Most of the current ones are user contributions. So if you find some time to create one it can be included.
