### ISSUE TITLE
Zabbix 6.4 - nagstamon cannot log in with given credentials

### ISSUE THREAD

**Issue by moora** [HenriWahl/Nagstamon#927]
I has been working since the 6.4 upgrade.
Is there some incompatibility ?

Thank you

**Comment by HenriWahl** [comment]
Did you try the latest testing release of Nagstamon?

**Comment by HenriWahl** [comment]
> No yet…. Will do … sorry

Thi testing release addresses the Zabbix 6.4 issue.

**Comment by moora** [comment]
Thank you.
The last 64bit build works



-----End of message-----

SPOJE.NET
Michal Tomášek
Project Manager
Mobile: +420 603 11 44 88
Tel: +420 222 365 175
Fax: +420 228 880 001
Email : ***@***.******@***.***>
Web : www.spoje.net<http://www.spoje.net/>
Twitter : https://twitter.com/moora1977
Facebook : https://www.facebook.com/spoje.net
Skype : ***@***.******@***.***>
LinkedIn : https://www.linkedin.com/in/michal-tomášek-193a5b147

***@***.***



Obsah tohoto e-mailu a všechny připojené soubory jsou důvěrné a mohou být chráněny zákonem. Tento e-mail je určen výhradně jeho adresátovi a jiné osoby do něj nejsou oprávněny nahlížet či s ním jakkoliv nakládat, jinak se dopustí protiprávního jednání. V případě, že nejste adresátem tohoto e-mailu, prosíme o jeho vymazání a o podání e-mailové zprávy.

The content of this e-mail and any attached files are confidential and may be legally privileged. It is intended solely for the addressee. Access to this e-mail by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful. In this case be so kind and delete this e-mail and inform us about it.

-----End of signature-----
