### ISSUE TITLE
Login issue with zabbix 6.4.2

### ISSUE THREAD

**Issue by lhpitn** [HenriWahl/Nagstamon#932]
Hi,

i just upgraded Zabbix to 6.4.2 and afterwards nagstamon, just to be sure, and now that:

![grafik](https://user-images.githubusercontent.com/45788285/234879788-d588e44f-57d5-40ad-8be3-36004c37dda7.png)

any idea?

thanks in advance

**Comment by HenriWahl** [comment]
Please check latest Nagstamon testing release as it contains the changes necessary.
