### ISSUE TITLE
Zabbix 6.4.2 et Nagstatom 3.10.1

### ISSUE THREAD

**Issue by christophe-lechenadec** [HenriWahl/Nagstamon#934]
hi,
I updated my Zabbix server from 6.0 to 6.4.2
and everything is OK except the connection from Nagstamon.
It cannot connect to Zabbix server.

Nagstamon.thirdparty.zabbix_api.ZabbixAPIException : Not login

**Comment by HenriWahl** [comment]
Please try latest testing release of Nagstamon.

**Comment by christophe-lechenadec** [comment]
hello,
I tested the Nagstamon-3.11-20230428-win64_setup.exe version
on windows 10, and it works perfectly.

thank you,
