### ISSUE TITLE
fails on startup after updating to Python 3.11+

### ISSUE THREAD

**Issue by allddd** [HenriWahl/Nagstamon#935]
Hi,

the error message is as follows:
```
Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 32, in <module>
    from Nagstamon.Config import conf
ModuleNotFoundError: No module named 'Nagstamon'
```
As mentioned in the title, everything started right after updating to Python 3.11.3.  
I'm currently on `Arch Linux` with the last available version of `Python` (`3.11.3`) running `Nagstamon 3.10.1`.  
If you need more info, I will gladly provide it.

**Comment by HenriWahl** [comment]
Hi @allddd I am sorry but this is apparently a problem of the distro you use. Python organizes its packages dependent on the Python version, e.g. like `/usr/lib/python3.11/site-packages/Nagstamon/`. A newer Python might not have these packages in your setup and thus this error message is correct.

**Comment by allddd** [comment]
@HenriWahl 
Well, what can I say, forgive my ignorance.
I had a similar problem due to past Python changes, and now I just assumed without looking...

If anyone else finds this for whatever reason, you can just rebuild the package to get everything back in the right place.
I opted for the faster solution and simply symlinked the necessary folders from `/python3.10/site-packages/`  to `/python3.11/site-packages/` until there is an actual reason to rebuild it.
