### ISSUE TITLE
Could not start nagstamon 3.12 due to QT6 missing

### ISSUE THREAD

**Issue by rogermartensson** [HenriWahl/Nagstamon#939]
I recently upgraded to version 3.12 on my windows 11 and nagstamon wouldn't start.
It just exited without saying anything.

After I installed the debug-version I finally got an error and that was because QT was missing.

Only thing is that it wasn't missing. By comparing and doing some creative searched in the installation directory I noticed that 3.12 contains a PyQT6 directory. But my "upgrade" from earlier versions didn't delete the Qt6-files in the root install directory.

After removing those files I get a working installation again.

**Comment by HenriWahl** [comment]
How did you "upgrade"?

**Comment by HenriWahl** [comment]
@rogermartensson really strange, cannot reproduce. Maybe some kind of race condition, blocked files during reinstallation etc.?

**Comment by rogermartensson** [comment]
May be that.
An improvement would be to show an error when not using the debug build. Either as a popup or as a string when running the EXE-file.

When using the debug build I got an error to work with where are the release build just said nothing. Not even "System Error 11". (throwback to the past and an infamous error message)

**Comment by HenriWahl** [comment]
@rogermartensson because Qt6 ist a core requirement to do any GUI this ist impossible. Looks like this was a very rare exception caused by some mysterious condition so I think it's safe to keep it as it is.

**Comment by ironiq** [comment]
For me both the installable and the portable version are problematic: it starts in the taskbar, but does not show anything except the icon. I downloaded the portable 3.10.1 and works perfectly.

**Comment by HenriWahl** [comment]
Can you please try the latest testing release?

**Comment by ironiq** [comment]
I tried 3.12.0 and now it is working on Windows10.

**Comment by HenriWahl** [comment]
Anyone having this problem please try the latest testing releases.
