### ISSUE TITLE
Detection of Centreon user password change

### ISSUE THREAD

**Issue by tpouzet** [HenriWahl/Nagstamon#94]
I have a Centreon setup where user authentication is done with a freeipa server (ldap/kerberos). When a user currently running Nagstamon (being authenticated) changes his domain password, it is not detected by Nagstamon. The tool then proceeds to try a login every 10 seconds with the old and invalid password, with no limitation in time. (I got this for 1 week). 
Expected behaviour would be that Nagstamon asks for the password if it gets denied several times.

**Comment by HenriWahl** [comment]
Please check latest 2.0 betas.
