### ISSUE TITLE
Add Poller centron 

### ISSUE THREAD

**Issue by Didier97180** [HenriWahl/Nagstamon#940]
Hello,

Is it possible to add a poller Centreon ( not access web) on Nagstamon.
I can add a central but not poller.

Just for chek how to add a central Centreon sur Nagstamon

Help me please.

**Comment by BenoitPoulet** [comment]
Hello,

This is not possible as Centreon removed all the possibility to request directly centreon-engine.

If you want to to this, the simple way is to convert your Poller into a remote-central.

**Comment by Didier97180** [comment]
Hello,
What is the diferrence between Remote Server and Poller.

Is it possible of to convert a poller to Remote Server. If yes how?

Is it grave of to remplace the poller by remote Server?

Thank you

**Comment by BenoitPoulet** [comment]
Remote server is a Poller with a local database & Web UI.

I know a conversion is possible but I never did it myself, perhaps you can find information on https://docs.centreon.com/fr/ on ask on the Centreon The Watch.

But this is not related to Nagstamon.
