### ISSUE TITLE
Errors after Checkmk Upgrade to 2.2

### ISSUE THREAD

**Issue by beckjkl** [HenriWahl/Nagstamon#945]
Since we upgraded our Checkmk to Version 2.2 (2.2.0p1.cee), Nagstamon can't connect to Checkmk anymore. It says "Authentication problem", but all accounts we tested with work in the browser and the Checkmk Apache access logs don't show any refusals or errors. I have attached a carsh report generated by Checkmk after the upgrade that seems to be relevant.
[Checkmk_Crash_cmk01_76269728-0b67-11ee-b7ca-813d98558d12_2023-06-26_15-31-50.tar.gz](https://github.com/HenriWahl/Nagstamon/files/11869514/Checkmk_Crash_cmk01_76269728-0b67-11ee-b7ca-813d98558d12_2023-06-26_15-31-50.tar.gz)

**Comment by HenriWahl** [comment]
I tested with Checkmk 2.2.0p3. Auth worked but there was a server error when a host is in downtime. I already informed tribe29.

**Comment by HenriWahl** [comment]
Hi @beckjkl, according to you log this is the same error as in https://forum.checkmk.com/t/bug-with-nagstamon-after-upgrade-to-2-2-0/39382 - at least the same error message occurs: `sequence item 0: expected str instance, dict found`. Maybe you could post it there too?

**Comment by Tsunayoshi** [comment]
I have exactly the same problem. The cmkadmin works fine but my normal user get the Auth problem.

**Comment by HenriWahl** [comment]
@Tsunayoshi @beckjkl help is underway: https://checkmk.com/werk/15708

**Comment by beckjkl** [comment]
The update has fixed the issue. We also had a different small issue. Some of the username imported for Active Directory were capitalised. You are able to login to CheckMK even with the username all lowercase, but Nagstamon is case sensitive.

**Comment by HenriWahl** [comment]
Well, Nagstamon only shovels the username it was configured with into the remote server - it does not treat cases anyhow. Why don't you just use the name as it is intended/configured in the AD?

**Comment by HenriWahl** [comment]
Clsoing because it was fixed in Checkmk 2.2.0p5.
