### ISSUE TITLE
Status information not updated in case of check output changes without a status change

### ISSUE THREAD

**Issue by Tontonitch** [HenriWahl/Nagstamon#946]
We've noticed that the "Status information" are not updated in case of check output changes without a "Status" change (i.e. CRITICAL to OK).

For example, the list of auto-started services on a server:
some have started but one remains, keeping the check in the CRITICAL state:
![image](https://github.com/HenriWahl/Nagstamon/assets/600025/7656d5c1-3daf-48fe-978b-e329328484f0)

But in nagstamon, the status information still shows the list of the services / check output as it was when the check went to the CRITICAL status:
![image](https://github.com/HenriWahl/Nagstamon/assets/600025/bc34b0aa-d7dc-4172-94ae-e8ffff436492)

It is an example for windows server services, but we faced that for some other cases such as filer volumes capacity alerts.

Nagstamon 3.10.1 on windows 10, connecting to Icinga Web 2 Version 2.11.3 (icingadb 1.0.2)

**Comment by HenriWahl** [comment]
@Tontonitch I sometimes had the same effect but it always "just happened" and I could not forcibly reproduce it. Is it possible in your case to cause this in a predictable manner?

**Comment by Tontonitch** [comment]
I will try and come back to you. That should be quite simple when playing with windows services and the related check.

**Comment by Tontonitch** [comment]
@HenriWahl I confirm that it is easily reproductible. I've played with a Windows auto-start services check.
Let's say it is knows as an icinga2 service object name "Auto-start services". If the icinga2 service is in a CRITICAL but SOFT state, the plugin output is well updated on nagstamon. But as soon as it reaches the HARD state, it is not updated anymore on nagstamon. So if parts of the stopped services are back to running, but the icinga2 service is still CRITICAL, the plugin output does not change on nagstamon to reflect that there are less services stopped.

Do you need some debugs to be performed? What do you need?

**Comment by HenriWahl** [comment]
@Tontonitch this seems to be very interesting! Never considered the states because the problems mostly are in hard state. I will look at it as soon as possible.

**Comment by HenriWahl** [comment]
@Tontonitch could you please try with latest stable 3.12.0? I think the observed behavior won't be different but just in case.

**Comment by HenriWahl** [comment]
@Tontonitch please checkout latest testing release where the status information will be considered too. Maybe this has to become an option because there might be status information changes which will not be considered critical by other users but let's have a try.

**Comment by Tontonitch** [comment]
> @Tontonitch could you please try with latest stable 3.12.0? I think the observed behavior won't be different but just in case.
> 
> **Edit:** Additionally - do you use the filters 'host/service in soft state'?

Yes, usually I filter out hosts/services in soft state. For the tests I removed these filter and noticed that different behavior with the returned plugin output when filtering the soft states.

I've tested the latest release 3.12.0. The issue is still there.

![image](https://github.com/HenriWahl/Nagstamon/assets/600025/e1ca7911-2a96-468a-ab91-1a3230461cec)

Stopping another service:
![image](https://github.com/HenriWahl/Nagstamon/assets/600025/c075d586-7995-43a2-b18e-a6f184fca1b1)

Starting some services but letting 1 stopped to keep the CRITICAL state:
![image](https://github.com/HenriWahl/Nagstamon/assets/600025/b3a8e03b-ca54-492b-9341-12afde8e54f2)

No changes in the Status information in nagstamon, the info are not updated.

**Comment by Tontonitch** [comment]
Let's give you a bit of info about the "auto-started services" check, which reflect well why an up-to-date status info is important, at least for us. All your servers are monthly patched, and it happens that some services do not start correctly after the patching process, without any reason. However, the other services which are configured with a start delay will probably start correctly. When the system admin start his workstation and look at the alert, he first see a lot of services not started, but it does not reflect the reality as the status info are out of date.

There are other cases like that (storage checks,...) and in fact as soon as a "check" does not concern a single resource but multiple resources (multiple services, multiple storage volumes, multiple network interfaces,...) or if you use the check_multi or similar plugins, having up-to-date status info is important IMHO.

**Comment by Tontonitch** [comment]
@HenriWahl  I've sent another example by email.

**Comment by HenriWahl** [comment]
@Tontonitch did you try the latest testing release?

**Comment by Tontonitch** [comment]
@HenriWahl , yes, tested [Nagstamon-3.13-20230720-win64_debug.zip](https://github.com/HenriWahl/Nagstamon/releases/download/latest/Nagstamon-3.13-20230720-win64_debug.zip)
Same results.

**Comment by HenriWahl** [comment]
@Tontonitch strange, the latest testing release also considers status information changes which it did not before.

**Comment by HenriWahl** [comment]
This line https://github.com/HenriWahl/Nagstamon/blob/status_update/Nagstamon/Objects.py#L168 now also takes status information into account, so if it really changed, this change gets detected.

**Comment by HenriWahl** [comment]
@Tontonitch please check latest build 3.13-20230808.

**Comment by Tontonitch** [comment]
Hello @HenriWahl , the problem is still there with the latest build:

![image](https://github.com/HenriWahl/Nagstamon/assets/600025/4f2a88b1-92a4-407b-b5ba-4774cebc1a5c)

**Comment by Tontonitch** [comment]
I've checked the json that is retrieved by nagstamon, and it seems that this is where the outputs get stucks. It the json the reported output string is still "output":"USERS CRITICAL - 3 users currently logged in ", so does not match the reality and what is printed in the web UI! I will open a ticket on the icinga2 project.

**Comment by HenriWahl** [comment]
Sorry for the late reply.

My mitigation attempts apparently did not work as expected and if you found that there is some problem with Icinga so I will go back to the previous behaviour.

**Comment by Tontonitch** [comment]
Hello Henri. 
Indeed, it is more than probable that the problem comes from the icingadb-web module that comes with icinga2.
The fix seems merged now, but I'm still waiting for a new release to be published.
I will anyway comment here when I will get the possibility to test and validate their fix.
Regards,
