### ISSUE TITLE
Authentication problem - Failed to patch SSL settings

### ISSUE THREAD

**Issue by nona00** [HenriWahl/Nagstamon#952]
I have an issue after upgrading to check-mk 2.2.0p6.

When resuming from standby there occurs an "Authentication problem" on two different systems. I already upgraded to the debug version Nagstamon-3.13-20230720-win64_debug but this did not help, the following error is shown:

pip_system_certs\wrapt_requests.py:71: UserWarning: Failed to patch SSL settings for unverified requests (unsupported version of urllib3?)

On my screenshot there are two sites. The first one is check-mk 2.2.0p6, the second one - which works - is running 2.1.0p2
![nagstamon](https://github.com/HenriWahl/Nagstamon/assets/3192606/87931766-a92c-4035-8e00-fcd3109f32f4)

**Comment by nona00** [comment]
When I manually press "Authenticate" the connection is established again.

**Comment by HenriWahl** [comment]
@nona00 due to vacation I am not able to look at this issue right now. When being back I think we will find a solution.

**Comment by HenriWahl** [comment]
@nona00 sorry for the late reply: maybe you could run Nagstamon in terminal to get more output.
In the meantime this behaviour happened to me too so I will have a closer look to it.

**Comment by nona00** [comment]
here is the debug output of 3.13-20230720

`QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
pip_system_certs\wrapt_requests.py:71: UserWarning: Failed to patch SSL settings for unverified requests (unsupported version of urllib3?)
This may lead to errors when urllib3 tries to modify verify_mode.
Please report an issue at https://gitlab.com/alelec/pip-system-certs with your
python version included in the description

Traceback (most recent call last):
  File "Nagstamon\Servers\Multisite.py", line 238, in _get_status
  File "Nagstamon\Servers\Multisite.py", line 197, in _get_url
  File "<string>", line 1, in <module>
NameError: name 'ERROR' is not defined
Traceback (most recent call last):
  File "Nagstamon\Servers\Multisite.py", line 238, in _get_status
  File "Nagstamon\Servers\Multisite.py", line 197, in _get_url
  File "<string>", line 1, in <module>
NameError: name 'ERROR' is not defined
Traceback (most recent call last):
  File "Nagstamon\Servers\Multisite.py", line 238, in _get_status
  File "Nagstamon\Servers\Multisite.py", line 197, in _get_url
  File "<string>", line 1, in <module>
NameError: name 'ERROR' is not defined
Traceback (most recent call last):
  File "Nagstamon\Servers\Multisite.py", line 238, in _get_status
  File "Nagstamon\Servers\Multisite.py", line 197, in _get_url
  File "<string>", line 1, in <module>
NameError: name 'ERROR' is not defined
Traceback (most recent call last):
  File "Nagstamon\Servers\Multisite.py", line 238, in _get_status
  File "Nagstamon\Servers\Multisite.py", line 197, in _get_url
  File "<string>", line 1, in <module>
NameError: name 'ERROR' is not defined`

**Comment by HenriWahl** [comment]
@nona00 what are your settings regarding certificate verfication? Do you ignore certifiate validity?

**Comment by nona00** [comment]
Ignore SSL/TLS certificate is enabled. Same issue with Nagstamon-3.13-20231010-win64, Authentication problem after standby.

**Comment by HenriWahl** [comment]
@nona00 sorry for the late reply... you wrote 'Authentication problem after standby.' - does it mean this only happens after standby?

**Comment by nona00** [comment]
yes it happens after resume from standby

**Comment by nona00** [comment]
issue is still present in Nagstamon-3.13-20231208-win64. I have to manually press Authenticate to get rid of the issue. 

Would it be possible to do Authenticate automatically if the Authentifaction problem occurs?

**Comment by HenriWahl** [comment]
@nona00 sorry I somehow lost focus on this issue. Yes, will be investigated further.

**Comment by nona00** [comment]
issue still present in 3.13-20240108

![grafik](https://github.com/HenriWahl/Nagstamon/assets/3192606/9a103143-f8d2-4603-bd1e-94444ae285eb)

**Comment by HenriWahl** [comment]
Meanwhile Checkmk 2.2.0p18 is out at least - what is the version you do run Nagstamon with?

**Comment by HenriWahl** [comment]
@nona00 I am sorry but I can't reproduce this with latest Nagstamon testing and a Checkmk 2.2.0p18 instance. After waking up the sleeping Windows Nagstamon continues to work.

**Comment by nona00** [comment]
I updated to 2.2.0p21 now and can not reproduce the issue any more.
