### ISSUE TITLE
Actions for all hosts/services

### ISSUE THREAD

**Issue by sebek72** [HenriWahl/Nagstamon#955]
Is there a way to add custom actions also to OK (all) hosts or services? Now only possible for ones that have a issue.

Used case: Pre-define custom action that can be executed on all available hosts/services regardless off the status.

And FYI: https://nagstamon.de/repo is not working ATM

**Comment by sebek72** [comment]
Or
does anyone know of any alternatives for executing custom commands in icingaweb? nagstamon already has this but only for hosts/services with issues.

**Comment by HenriWahl** [comment]
You could select multiple items and start an action.

**Comment by sebek72** [comment]
I there a possibility you can add a tab (maybe configurable like filters) to show all hosts/services which would allow to configure actions for all items?

**Comment by HenriWahl** [comment]
@sebek72 do you mean ALL hosts and services, which mostly are OK anyway?

**Comment by sebek72** [comment]
Yes. The I could use actions on all hosts/services.

**Comment by HenriWahl** [comment]
@sebek72 sorry for the late reply but this is out of  Nagstamon's scope.
