### ISSUE TITLE
date string issue

### ISSUE THREAD

**Issue by sebek72** [HenriWahl/Nagstamon#962]
Having issues with the latest 20230808 build.

monitor type: icingaDBWEB
backend: 
icingaweb2.11.4+ (build from master from August)
icingadb 1.1.0
icingadb-web (master, pre 1.1.0)

`DEBUG: 2023-08-28 12:37:00.660402 NEW PROD Start rechecking all
DEBUG: 2023-08-28 12:37:02.245729 NEW PROD Refreshing all hosts and services
DEBUG: 2023-08-28 12:37:02.876868 NEW PROD FetchURL: http://10.55.32.212:8080/icingadb/hosts?host.state.is_problem=y&host.state.state_type=hard&columns=host.state.last_update&format=json CGI Data: None
ERROR: 2023-08-28 12:37:02.987765 NEW PROD Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/Nagstamon/Servers/IcingaDBWeb.py", line 211, in _get_status
    self.new_hosts[host_name].last_check = datetime.datetime.fromtimestamp(int(float(h['state']['last_update'])))
ValueError: could not convert string to float: '2023-08-25T07:02:14.894+00:00'`

P.S: older icingaweb2 (no icingadb) works ok.

**Comment by HenriWahl** [comment]
@jr-timme any idea?

**Comment by sebek72** [comment]
Hi. Thanks for the feedback. I would not know where to change that :)
I will try to install previous icinga stack versions to see if there is an instance where this works (btw my icinga is deployed via docker)

**Comment by jr-timme** [comment]
Could you check the raw json output, just to make sure that the date there is already formatted?

```bash
curl -v -l -b cookies.txt -c cookies.txt "http://10.55.32.212:8080/icingadb/hosts?host.state.is_problem=y&host.state.state_type=hard&columns=host.state.last_update&format=json" | jq
```

cookies can either be exported from a browser or generated through another curl in which you authenticate yourself

**Comment by sebek72** [comment]
This is the json output:

`"last_update":"2023-09-21T09:49:38.753+00:00","last_state_change":"1970-01-01T00:00:00.000+00:00",
"next_check":"2023-09-21T09:49:59.838+00:00",
"next_update":"2023-09-21T09:50:21.846+00:00",`

**Comment by mzac** [comment]
Just tired the update and still getting an error:

![image](https://github.com/HenriWahl/Nagstamon/assets/10270879/8df87d3c-a12c-48ec-a449-3ad67bffd2e3)

**Comment by mzac** [comment]
> Sorry.. missed the host part. Working on it!

It works now thanks!

**Comment by sebek72** [comment]
I updated and now have a new issue.
`ERROR: 2023-11-03 07:07:01.376042 NEW PROD Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/Nagstamon/Servers/IcingaDBWeb.py", line 214, in _get_status
    self.new_hosts[host_name].last_check = datetime.datetime.fromisoformat(h['state']['last_update'])
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'`

**Comment by HenriWahl** [comment]
@sebek72 well, maybe the easiest fix is an update to EL9? Even Python 3.7 is out there for a while.
 
 I saw that you can install python38, python39, python3.11 even in EL8 - maybe try it this way?

**Comment by HenriWahl** [comment]
@sebek72 how do you get it running at all? Looks like you need to do some special moves anyway?

**Comment by sebek72** [comment]
I will check how to use different python in EL8 (I took the EL8 src rpm and changed the spec file to re-create the EL8 rpm).
Now I also created a Debian docker image with embedded nagstamon to make it more portable.

`FROM debian:bullseye-slim

RUN ["bash", "-exo", "pipefail", "-c", "export DEBIAN_FRONTEND=noninteractive; apt-get update; apt-get install --no-install-{recommends,suggests} -y wget python3 python3-{pkg-resources,bs4,lxml,requests,requests-kerberos,psutil,pyqt5,keyring,ewmh,pyqt5.qtsvg,pyqt5.qtmultimedia,dbus.mainloop.pyqt5,dateutil} libqt5gui5 libqt5multimedia5-plugins sound-icons; apt-get clean; rm -vrf /var/lib/apt/lists/*; wget https://github.com/HenriWahl/Nagstamon/releases/download/latest/nagstamon_3.13-20231031_all.deb; dpkg -i nagstamon_3.13-20231031_all.deb; rm -rf nagstamon*"]`

I am able to start it on MacOS (with XQuartz: https://gist.github.com/cschiewek/246a244ba23da8b9f0e7b11a68bf3285, for audio it a bit trickier, but on linux it should be more straightforward).

**Comment by HenriWahl** [comment]
Hi  @sebek72 - there is also a native binary for macOS - just in case.
Maybe you could find a way to update the currently outdated Flatpak package of Nagstamon at https://flathub.org/apps/de.ifw_dresden.nagstamon? I tried but failed hardly.

**Comment by HenriWahl** [comment]
Hi @sebek72 - just out of curiosity: did you try with https://github.com/mviereck/x11docker already? Looks like another solution.

**Comment by magenbrot** [comment]
Hi! Thank you for the work and the fix. Is it possible to release this any time soon?

**Comment by HenriWahl** [comment]
It is available as resting release 3.13-20231117 right now.

**Comment by sebek72** [comment]
I have manage to create an el8 rpm with python3.8. But still have the date issue
`File "/usr/lib/python3.8/site-packages/Nagstamon/Servers/IcingaDBWeb.py", line 214, in _get_status
    self.new_hosts[host_name].last_check = datetime.datetime.fromisoformat(h['state']['last_update'])
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'`

**Comment by HenriWahl** [comment]
@sebek72 due to missing dependencies there was just added EL9 support.
