### ISSUE TITLE
Desktop interface shows OK although alerts are firing in alertmanager

### ISSUE THREAD

**Issue by Simoliv** [HenriWahl/Nagstamon#963]
Hi there, we use nagstamon since quite a long time already, but since a few weeks (or even month) it does not fire alerts anymore, the desktop interface is just "OK" for me. 
We use the alertmanager integration and we compared our configs from a working instance (3.11-20221121) and my actual one(s) which I tried in the meantime (currently 3.13-20230808).
When going in DEBUG mode, I can see that I receive messages from alertmanager, Warnings and also Criticals, but the interface just remains green "OK".
best regards, Oliver

**Comment by Simoliv** [comment]
By the way, I just downgraded to 3.11-20221121 and all alerts are back and the interface behaves as expected. 
best regards

**Comment by HenriWahl** [comment]
@Simoliv I was trying to fix https://github.com/HenriWahl/Nagstamon/issues/946 but apparently with no luck - that's why the 3.13-20230808 release behaved like it did.

**Comment by AIXruth** [comment]
> By the way, I just downgraded to 3.11-20221121 and all alerts are back and the interface behaves as expected. best regards
Confirm, version 3.12 shows always green.
Version 3.12 also does its job properly.

**Comment by HenriWahl** [comment]
@AIXruth what exactly do you mean.

**Comment by HenriWahl** [comment]
@aleskxyz might the change in https://github.com/HenriWahl/Nagstamon/commit/5179f2a77e559999fd667553bc475fdbc9e83fc4 might have anything to do with this issue?

@AIXruth which version of AlertManager do you use?

**Comment by aleskxyz** [comment]
> @aleskxyz might the change in [5179f2a](https://github.com/HenriWahl/Nagstamon/commit/5179f2a77e559999fd667553bc475fdbc9e83fc4) might have anything to do with this issue?
> 
> @AIXruth which version of AlertManager do you use?

I have applied my patch on v3.12.0 and it is working and I'm actually using it. So I don't think it is related to this patch.

**Comment by aleskxyz** [comment]
@HenriWahl 
I just build the package from this commit: cbde710be73d9a0b3b50f7db964339e34fb6b22c
Which is the parent commit of my patch and I confirm that the problem exists!
So definitely some other changes from v3.12.0 to cbde710be73d9a0b3b50f7db964339e34fb6b22c is the cause of this bug

**Comment by HenriWahl** [comment]
@aleskxyz I just wonder what it might be - at least the Alertmanager code saw no more changes.

**Comment by aleskxyz** [comment]
@HenriWahl 
Something is wrong in this commit:
https://github.com/HenriWahl/Nagstamon/commit/68cffad684a5103dd4889f409fb2dea6ecaccd47
Build on parent of this commit was good but build on this commit face with the problem.
