### ISSUE TITLE
Nagstamon 3.12.0 doesn't work with MacOS 14.0

### ISSUE THREAD

**Issue by ricodeschner** [HenriWahl/Nagstamon#972]
Nagstamon doesn't start after MacOS Update to 14.0.
MacOS can't search inside for malware.

![image](https://github.com/HenriWahl/Nagstamon/assets/93256962/0cbdbb1d-1746-44fd-811f-fc6e01a0c115)

**Comment by HenriWahl** [comment]
@ricodeschner just wanted to tell you that it works for me... glad you found the cause.
