### ISSUE TITLE
New SNAP package realase

### ISSUE THREAD

**Issue by res1st** [HenriWahl/Nagstamon#973]
Hi, could you also release a new SNAP or Flatpak release?
Maybe as fixed feature for every release?
That would be great.

**Comment by HenriWahl** [comment]
Hi @res1st there is an outdated Flatpak release.
I tried to update it but I don't get it how to do this. So any volunteers are heartly welcome... seriously, I would be glad if someone could find a way to do this. As far as I remember a big obstacle is the packaging of Qt6 and Python into a flatpak.

**Comment by res1st** [comment]
I also have no knowledge about it.
Maybe I can motivate me to learn it.
