### ISSUE TITLE
Nagstamon doesn't open on main screen

### ISSUE THREAD

**Issue by BDevGW** [HenriWahl/Nagstamon#976]
Hello,

I use Nagstamon in the floating statusbar mode.
When opening the overview Nagstamon opens on the screen the floating bar is except on my main display. The overview opens on the left screen or - if I move the statusbar to other screens - the last non main display the statusbar was located on.

Device: Win 11 22H2 Enterprise english
Nagstamon: 3.13-20231010

**Comment by HenriWahl** [comment]
I updated to latest Qt6 6.5.3 now  - can you please try again to download and run the latest testing release?

**Comment by BDevGW** [comment]
Thanks, works!
