### ISSUE TITLE
Installation on many clients and one config file

### ISSUE THREAD

**Issue by sadden3194** [HenriWahl/Nagstamon#977]
Hi all!

is it possible to install nagstamon on many clients and using a config file which is available on a shared network folder?

**Comment by HenriWahl** [comment]
Hi @sadden3194 - yes, if you pass the location of the config file as argument to Nagstamon's executable you can provide whatever config file you want.

**Comment by HenriWahl** [comment]
Just something like `nagstamon /some/place/where/config/is/stored/config`.

If running 'normally', Nagstamon uses a config directory in your home folder, named `.nagstamon`. The directory you want to share basically just needs to be a copy of this one.
