### ISSUE TITLE
Centreon 23.10 - KeyError: 'passive_checks'

### ISSUE THREAD

**Issue by Zelphy** [HenriWahl/Nagstamon#981]
Hi,

We've recently upgraded our Centreon server from 23.04 to 23.10 and we are facing this error when we start Nagstamon:

```
DEBUG: 2023-10-31 17:26:03.430391 Centreon FetchURL: https://centreon.REDACTED/centreon/api/v22.04/monitoring/resources?types=["metaservice","service"]&statuses=["WARNING","DOWN","CRITICAL","UNKNOWN"]&limit=9999 CGI Data: None

DEBUG: 2023-10-31 17:26:03.602707 [Centreon] Service indexed : SRV01 / Disk_W88_C93_D

ERROR: 2023-10-31 17:26:03.603704 Centreon Traceback (most recent call last):
  File "Nagstamon\Servers\Centreon\CentreonAPI.py", line 426, in _get_status
KeyError: 'passive_checks'
```

Can this issue be similar to #866?

Nagstamon is not starting at all. Here are some screenshots:

Centreon config:

<img width="270" alt="Screenshot 2023-10-31 173848" src="https://github.com/HenriWahl/Nagstamon/assets/4152786/59af6810-1145-41ab-9e73-3046edefc727">

passive_checks variable:

<img width="725" alt="Screenshot 2023-10-31 173827" src="https://github.com/HenriWahl/Nagstamon/assets/4152786/61e8c0aa-943c-4b99-8e46-cccaf28ee999">

Let me know if you need anything else. Thank you!

Regards.

**Comment by HenriWahl** [comment]
@BenoitPoulet do you have an idea?

**Comment by Zelphy** [comment]
I'll add this screen also, I think it might help, as it's linked to "SRV01 / Disk_W88_C93_D"

<img width="294" alt="Screenshot 2023-10-31 181918" src="https://github.com/HenriWahl/Nagstamon/assets/4152786/5dbe055f-ad26-4979-ac29-e668acfbafe6">

The "Disk_W88_C93_D" Service is currently in Critical state.

**Comment by Zelphy** [comment]
I've forked and built the project (master) with the problematic line commented. I was able to go one line further...
At the end, this is the code that allow Nagstamon to start without error for Centreon 23.10:

<img width="509" alt="Screenshot 2023-11-03 111904" src="https://github.com/HenriWahl/Nagstamon/assets/4152786/bde97d98-9275-4c1c-8db8-3412e8a512ed">

4 lines commented:

self.new_hosts[new_host].services[new_service].passiveonly = alerts["passive_checks"]
self.new_hosts[new_host].services[new_service].notifications_disabled = not alerts["notification_enabled"]
self.new_hosts[new_host].services[new_service].acknowledged = alerts["acknowledged"]
self.new_hosts[new_host].services[new_service].scheduled_downtime = alerts["in_downtime"]

<img width="275" alt="Screenshot 2023-11-03 111720" src="https://github.com/HenriWahl/Nagstamon/assets/4152786/92855b8b-cef4-4c83-ab7b-40452f1ce8fe">

<img width="490" alt="Screenshot 2023-11-03 111926" src="https://github.com/HenriWahl/Nagstamon/assets/4152786/025c3689-b215-45e4-a56e-15c328f6117f">

**Comment by HenriWahl** [comment]
Would be interesting what the 23.10 version actually contains and what consequences the now missing 4 lines will have.

**Comment by Zelphy** [comment]
To avoid another similar problem, I needed to comment 4 other lines:

<img width="326" alt="Screenshot 2023-11-06 101512" src="https://github.com/HenriWahl/Nagstamon/assets/4152786/64036557-e388-47c1-adae-b5a3a1726b4c">

<img width="534" alt="Screenshot 2023-11-09 095712" src="https://github.com/HenriWahl/Nagstamon/assets/4152786/6707d73e-737a-4e18-b41d-48d9fa5b0665">

**Comment by BenoitPoulet** [comment]
Hello,

That strange I already validate the code of 23.10 (beta).

If the code has not be already fixed I will have a look asap.

**Comment by polako-code** [comment]
Hello,

I had the same problem with Centreon 23.10.0
The solution proposed by @Zelphy works but some functionality is lost. For example, if a host is acknowledged in Centreon, you can no longer request that it not be displayed in Nagstamon.

**Comment by BenoitPoulet** [comment]
Hello,

I found the cause, they changed the JSON in the final release :|

The mapping must be change but only starting with 23.10

I will try to do it this evening
