### ISSUE TITLE
Error message ""KeyError:'passive_checks'"

### ISSUE THREAD

**Issue by Didier97180** [HenriWahl/Nagstamon#995]
Hello,

I updated my centreon to 23.10 and since then the nagastamon gives me the error message 

"KeyError:'passive_checks'

Thank you

**Comment by BenoitPoulet** [comment]
Hello,

Can you try with the latest build ? This version include fixes for Centreon 23.10 :

https://github.com/HenriWahl/Nagstamon/releases/tag/latest

**Comment by Didier97180** [comment]
Hello
Thank you it's work.
Is it a bêta version?
They isn't on the website?

**Comment by Didier97180** [comment]
Yes it's good?

**Comment by HenriWahl** [comment]
@Didier97180 doest it mean that it works for you?

**Comment by Didier97180** [comment]
Yes

**Comment by Didier97180** [comment]
>
