### ISSUE TITLE
IcingaDBWeb.py

### ISSUE THREAD

**Issue by Dymo-dcc** [HenriWahl/Nagstamon#996]
IcingaDB setup error, tried with 3.12 and now again with 3.13

![Screenshot 2023-12-11 154715](https://github.com/HenriWahl/Nagstamon/assets/81287207/aaad0bf2-bdc2-47c5-aea7-fc5ba8cba62b)
![Screenshot 2023-12-11 154850](https://github.com/HenriWahl/Nagstamon/assets/81287207/81e1e478-b828-47b4-9f13-8ceff19d8b0d)
![Screenshot 2023-12-11 154818](https://github.com/HenriWahl/Nagstamon/assets/81287207/93a5b7eb-d624-4784-b7c2-e60f8cdb2e79)

*********************************

DEBUG: 2023-12-11 15:43:56.487680 Saving configuration to file c:\users\xxxxxx\.nagstamon\nagstamon.conf
DEBUG: 2023-12-11 15:43:56.703236 IcingaDB Created server.
DEBUG: Initializing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000024C9D460310> for state "OK"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000024C9D4601F0> for state "INFORMATION"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000024C9D4603A0> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000024C9D460430> for state "WARNING"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000024C9D4604C0> for state "AVERAGE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000024C9D460550> for state "HIGH"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000024C9D4605E0> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000024C9D460670> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000024C9D460700> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000024C9D460790> for state "DOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x0000024C9D460820> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt6.QtGui.QIcon object at 0x0000024C9D4608B0>
DEBUG: 2023-12-11 15:43:57.008956 IcingaDB FetchURL: https://monitoring.local/icingaweb2/authentication/login CGI Data: None
DEBUG: 2023-12-11 15:43:57.896226 IcingaDB FetchURL: https://monitoring.local/icingaweb2/authentication/login CGI Data: {'redirect': '', 'formUID': 'form_login', 'CSRFToken': '++++++++++++++++++++++++++++', 'btn_submit': 'Login', 'username': '***************', 'password': '***************'}
DEBUG: 2023-12-11 15:43:58.790347 IcingaDB FetchURL: https://monitoring.local/icingaweb2/icingadb/hosts?host.state.is_problem=y&host.state.state_type=hard&columns=host.state.last_update&format=json CGI Data: None
DEBUG: 2023-12-11 15:43:58.877118 IcingaDB FetchURL: https://monitoring.local/icingaweb2/icingadb/hosts?host.state.is_problem=y&host.state.state_type=soft&columns=host.state.last_update&format=json CGI Data: None
DEBUG: 2023-12-11 15:43:58.916385 IcingaDB FetchURL: https://monitoring.local/icingaweb2/icingadb/services?service.state.is_problem=y&service.state.state_type=hard&columns=service.state.last_update,service.state.is_reachable&format=json CGI Data: None
ERROR: 2023-12-11 15:44:00.377926 IcingaDB Traceback (most recent call last):
  File "Nagstamon\Servers\IcingaDBWeb.py", line 320, in _get_status
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by HenriWahl** [comment]
@Dymo-dcc the login credentials are definitively OK?

@Tontonitch @MarcusCaepio @aleskxyz any idea what could cause this?

**Comment by Dymo-dcc** [comment]
Yes, double, triple checked the logon info. 
I cen provide the json from the link (https://monitoring.local/icingaweb2/icingadb/services?service.state.is_problem=y&service.state.state_type=hard&columns=service.state.last_update,service.state.is_reachable&format=json ) privately, would rather not post that publically, what ever response is in the services.json, seem to bewhere the issue is.

**Comment by Dymo-dcc** [comment]
Hi Short update,
We went through and began seperating out the hostgroups and testing them one at a time.  From the 40 Hostgroups, 1 is causing this issue.  We can load the other 39 without an issue and Nagstamon runs as expected.  Just this single Hostgroup causes this issue.

DEBUG: 2023-12-15 09:01:50.491806 SD FetchURL: https://monitoring.local/icingaweb2/icingadb/hosts?host.state.is_problem=y&host.state.state_type=hard&columns=host.state.last_update&format=json CGI Data: None
DEBUG: 2023-12-15 09:01:50.538351 SD FetchURL: https://monitoring.local/icingaweb2/icingadb/hosts?host.state.is_problem=y&host.state.state_type=soft&columns=host.state.last_update&format=json CGI Data: None

both return files with only [] inside, which I assume is OK

The issue seems to stem from a single service:

Here the entry:

`{"id":"08a6e1d3c057fd9d0b9517cfff57dc5b64c8aa47","environment_id":"9cd8f6286a2fac37ce1fe6a4fec59cc43a236fa7","name_checksum":"714a1073005a6d7e6ab361d0e00adea1772f3e05","properties_checksum":"86f1192a79f59beb393df80580464d80cd4f261d","host_id":"3801e2ea60f14d0b925ee322f682c0ccbe4992d5","name":"Fan \/ Power Supplies","name_ci":"Fan \/ Power Supplies","display_name":"Fan \/ Power Supplies","checkcommand_name":"check_procurve","checkcommand_id":"82ec68cd328dd15045f86731bfd5aa731a1ee75a","max_check_attempts":"3","check_timeperiod_name":"","check_timeperiod_id":null,"check_timeout":"60","check_interval":"300","check_retry_interval":"60","active_checks_enabled":"","passive_checks_enabled":"","event_handler_enabled":"1","notifications_enabled":"","flapping_enabled":"","flapping_threshold_low":"25","flapping_threshold_high":"30","perfdata_enabled":"y","eventcommand_name":"","eventcommand_id":null,"is_volatile":"","action_url_id":null,"notes_url_id":null,"notes":"","icon_image_id":"c761eea46da7d9192fbc34d2b4906dbccf313209","icon_image_alt":"","zone_name":"icinga-sat","zone_id":"de82e95c7962222fc78e5c2686a63714a41923fb","command_endpoint_name":"","command_endpoint_id":null,"state":{"service_id":"08a6e1d3c057fd9d0b9517cfff57dc5b64c8aa47","environment_id":"9cd8f6286a2fac37ce1fe6a4fec59cc43a236fa7","state_type":"hard","soft_state":"3","hard_state":"3","previous_soft_state":"99","previous_hard_state":"99","check_attempt":"1","severity":"576","output":null,"long_output":null,"performance_data":null,"normalized_performance_data":null,"is_problem":"1","is_handled":"1","is_reachable":"1","is_flapping":"","is_overdue":"","is_acknowledged":"sticky","acknowledgement_comment_id":"e5ffc8f965f2502a34b18e8548e01d4781eeb63a","last_comment_id":"e5ffc8f965f2502a34b18e8548e01d4781eeb63a","in_downtime":"","execution_time":"296","latency":"0","check_timeout":"60000","check_source":"monitoringagent.local","scheduling_source":"monitoringagent.local","last_update":"2023-11-09T07:54:35.933+00:00","last_state_change":"1970-01-01T00:00:00.000+00:00","next_check":"2023-12-15T07:51:07.849+00:00","next_update":"2023-11-09T08:04:36.526+00:00","last_comment":{"environment_id":"9cd8f6286a2fac37ce1fe6a4fec59cc43a236fa7","object_type":"service","host_id":"3801e2ea60f14d0b925ee322f682c0ccbe4992d5","service_id":"08a6e1d3c057fd9d0b9517cfff57dc5b64c8aa47","name_checksum":"61443c5c4c20222385ee11affd5d74a88c7be594","properties_checksum":"751e79a26444320895d078adc887f1e1d3cc42c6","name":"HP5406!Fan \/ Power Supplies!581997b1-dd0b-4a40-94af-c83017108ef0","author":"fakeadmin","text":"known","entry_type":"ack","entry_time":"2023-12-06T11:57:00.302+00:00","is_persistent":"1","is_sticky":"1","expire_time":null,"zone_id":"de82e95c7962222fc78e5c2686a63714a41923fb"}},"host":{"id":"3801e2ea60f14d0b925ee322f682c0ccbe4992d5","environment_id":"9cd8f6286a2fac37ce1fe6a4fec59cc43a236fa7","name_checksum":"b371b89e373d642348b046b64b0fb195a826f0f8","properties_checksum":"a2a77aeb4caac7fe12926c6242c30ef6ff359019","name":"HP5406","name_ci":"HP5406","display_name":"HP5406","address":"1.1.1.1","address6":"","address_bin":"0a661901","address6_bin":null,"checkcommand_name":"hostalive","checkcommand_id":"e4e2d6c7b7e5e4874a192151e582f80ade93da94","max_check_attempts":"4","check_timeperiod_name":"","check_timeperiod_id":null,"check_timeout":"60","check_interval":"300","check_retry_interval":"60","active_checks_enabled":"1","passive_checks_enabled":"1","event_handler_enabled":"1","notifications_enabled":"1","flapping_enabled":"1","flapping_threshold_low":"25","flapping_threshold_high":"30","perfdata_enabled":"y","eventcommand_name":"","eventcommand_id":null,"is_volatile":"","action_url_id":null,"notes_url_id":null,"notes":"","icon_image_id":"455454520d1b38985dad8d2ddb99957132a83363","icon_image_alt":"","zone_name":"icinga-sat","zone_id":"de82e95c7962222fc78e5c2686a63714a41923fb","command_endpoint_name":"","command_endpoint_id":null,"state":{"host_id":"3801e2ea60f14d0b925ee322f682c0ccbe4992d5","environment_id":"9cd8f6286a2fac37ce1fe6a4fec59cc43a236fa7","state_type":"hard","soft_state":"0","hard_state":"0","previous_soft_state":"1","previous_hard_state":"0","check_attempt":"1","severity":"0","output":"PING OK - Packet loss = 0%, RTA = 41.88 ms","long_output":null,"performance_data":"rta=41.883999ms;3000.000000;5000.000000;0.000000 pl=0%;80;100;0","normalized_performance_data":"rta=0.041884s;3;5;0 pl=0%;80;100;0","is_problem":"","is_handled":"","is_reachable":"1","is_flapping":"","is_overdue":"","is_acknowledged":"","acknowledgement_comment_id":null,"last_comment_id":null,"in_downtime":"","execution_time":"4050","latency":"0","check_timeout":"60000","check_source":"monitoringagent.local","scheduling_source":"monitoringagent.local","last_update":"2023-12-15T07:43:57.563+00:00","last_state_change":"2023-09-08T02:18:37.940+00:00","next_check":"2023-12-15T07:48:43.088+00:00","next_update":"2023-12-15T07:53:51.187+00:00"}},"icon_image":{"id":"c761eea46da7d9192fbc34d2b4906dbccf313209","icon_image":"icons-power.png","environment_id":"9cd8f6286a2fac37ce1fe6a4fec59cc43a236fa7"}},
`

Something in there triggers this event,  I disabled check now, and all 40 Hostgroup work as expected.

**Comment by DeadHunter** [comment]
The problem is, that `state.ouput` is `null`. In line 320 we expect, that `output` is a string.
https://github.com/HenriWahl/Nagstamon/blob/096e55c22a63b7f8163d5e3178f6276ba02f0397/Nagstamon/Servers/IcingaDBWeb.py#L320C109-L320C129
